### ISSUE TITLE
Oculus submission rejected for reserved interactions back button behavior

### ISSUE THREAD

**Issue by Sorduea** [Samsung/GearVRf#1009]
We recently submitted a project developed with the latest GearVRf  to Oculus and was rejected for failing the reserved interactions back button test with the following message: 

> A back button long-press (greater than 0.75 seconds) must bring the user to the Universal Menu. Long press does not bring up the Universal Menu on the Note 5.

We tested with our own Note 5 with Android 6.0 and validated it was going to the Universal Menu after a long press. We implemented patch #987 to see if that would help pass the test, but it was rejected again.

Oculus won't give us anymore information about the issue. Has anyone else had success submitting their applications to Oculus?

**Comment by liaxim** [comment]
One obvious difference is that GVRF doesn't handle this: ``If a single press of the back button is longer than 0.25 seconds but shorter than 0.75 seconds, it results in an aborted long-press and cancels the Universal Menu timer.``. Will have it fixed.

Other than that we will examine closely the VrCubeWorld_NativeActivity reference sample that Oculus points out as an example.

**Comment by thomasflynn** [comment]
Hi @Sorduea, while @liaxim looks at that, could you email me at tom.flynn@samsung.com?  I want to connect you to someone who is going to try to get better explanations out of Oculus.

**Comment by liaxim** [comment]
@Sorduea Since Oculus Mobile SDK 1.0.4 the long press is handled entirely by the Mobile SDK. We no longer do anything to bring up the Universal Menu..

I removed some leftovers from the past that may have interfered somehow. Not that I managed to reproduce anything. Also the cancellation of the long press works now.

**Comment by Sorduea** [comment]
While rebuilding from the 3.1 GearVRf release, we found that the build submitted was referencing the older Oculus Mobile SDK 1.0.3 instead of the 1.0.4 release.  Despite the older version, the reserved interaction behavior appears to be working as intended from our testing, but perhaps the Oculus Pass/Fail test refuses to acknowledge older SDK versions.  We will be moving to Oculus Mobile SDK 1.0.4 as part of the rebuild to match the GearVRf expectations, which we expect will probably resolve the issue. We will also implement #1010 to handle aborting the long-press. Thank you for your help. We can close this issue.

**Comment by Ongoza** [comment]
Is 3.1 GearVRf release on Maven repository already fixed?

**Comment by Ongoza** [comment]
I have new answer from Oculus
Fault again ;( reason is:

A “back” action is interpreted by the application dependent on its current state, but generally it will retreat one level in an interface hierarchy. The short-press should provide a custom confirmation dialog which allows the user to exit the app and return to Oculus Home.
There are 2 different interactions a user should be able to do with the back button: a short-press and a long-press.

- The back button short-press should open the "Exit to Oculus Home?" screen, and allow the user to either exit or "Cancel" and return to the app.

- Long press works fine.

**Comment by Ongoza** [comment]
How I can call brought up the exit-to-Oculus-Home prompt from my code?

**Comment by liaxim** [comment]
@Ongoza We have the GVRMain.onBackPress method. If you don't implement it a back key press will bring up the exit-to-Oculus prompt automatically. If you return true from this method you would let us know you are handling the back key inside the app. For example, the gvr-immersivepedia demo uses this method to back out to its menu scene.
