### ISSUE TITLE
Problem on GVRSceneObject.attachEyePointeeHolder(GVRMeshEyePointee eyePointee)

### ISSUE THREAD

**Issue by DanielNogueiraAndroid** [Samsung/GearVRf#102]
On gvreyepickingsample  all the objects that use method attachBoundingBoxEyePointee are not getting selected, the other objects that use method attachDefaultEyePointee the selection works fine.

**Comment by JonShemitz** [comment]
This _might_ be fixed by pull request https://github.com/Samsung/GearVRf/pull/112.

**Comment by JonShemitz** [comment]
@DanielNogueiraAndroid is this fixed?

**Comment by nathan-almeida** [comment]
Yes, it is fixed. Thank you
