### ISSUE TITLE
how to get started

### ISSUE THREAD

**Issue by grueiam** [Samsung/GearVRf#1030]
hi. not sure how to get started with gear vr framework.  i apologize if this is not the place to post, but just wondering if there's a tutorial. i've seen some powerpoint tutorials but i can't seem to find the gearvrfinstaller.exe it talks about!  i've bounced around on samsungs developers site and downloaded a ton of stuff.  but it's just not all coming together :)  i have android studio installed, ovr_sdk_mobile, downloaded a bunch of stuff including demos.  thanks.

**Comment by liaxim** [comment]
Hi.

The demos will work for you without any other prerequisites. After cloning the repo please switch to the "release_v3.1" branch. I found out that you will need to either use Gradle 3.3 or update the gradle wrapper that was checked in the repo. (This is something new that was not needed in the past. Will look into it.)

You can import the gradle project from GearVRf-Demos in AS and you should be able to build and run any of the demos. We also have some more, slightly outdated, demos under the GearVRf-Demos/old/ folder.

We have a bunch of information in these locations:
https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/070_GearVRf_Project_Tutorial
https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/060_Gear_VRf_Developer_Guide/150_Writing_a_Basic_GearVRf_Application
https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/060_Gear_VRf_Developer_Guide/160_Writing_More_Advanced_GearVRf_Applications
https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/060_Gear_VRf_Developer_Guide

The Tutorial is by far the best introduction we have. All the tutorial projects are available in GearVRf-Demos.

You shouldn't need the installer. With the 3.1 release it is easier to get up and running.

If you do want to build and use the very latest framework from the master branch then we can provide further instructions.

**Comment by grueiam** [comment]
thanks.  so when i import a project, like the gradle project, i go to File > New > Import proejct, then i just navigate to and highlight the folder, as opposed to drilling down within the folder to find some specific file/file extension.

it seems like if i do a file > new > import project and highlight the GearVRf-Demos-master folder (aka directory) it imported everything in that folder! that doesn't screw anything up does it?

thanks,

**Comment by liaxim** [comment]
Yes, just import the GearVRf-Demos folder. You will get a workspace with all the demos. Nothing screwed up.

It is very likely, at least initially, that you may find building and running the demos from the "release_v3.1" branch easier.

All the demos will need an Oculus signature you can obtain from https://developer.oculus.com/osig/. You could configure the build to include all signatures from a certain directory in the apks. In gradle.properties define a OCULUS_SIGS_DIRECTORY property and specify the full path to the directory where you put your Oculus signatures. Otherwise you will be responsible to copy the signature files to the samples assets directories.

**Comment by grueiam** [comment]
ugh.  i just started over ha!  i have the latest jdk installed, latest android studio, re-downloaded GearVRF-release_v3.1 (rather than using git i'm downloading zip files). i also downloaded a bunch of .aar files (3dcursorLibrary-debug.aar, backend..., framework-debug.aar... 9 in total).  i've downloaded the latest ovr_sdk_mobile too.  finally i have android sdk. finally i've downloaded the latest GearVRf-demos-master. all of this is unzipped into a directory on my c: drive called dev.

i'm looking at build instructions: https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/060_Gear_VRf_Developer_Guide/110_Build_Instructions 

and using the pre-built framework path and skipping the "optional" parts. do i need the libs-grvrf.zip file?

other than that, i'm assuming all i have to do again now, is launch AS and follow the instructions for building and running gearvrf applications on the very bottom of that referenced url?

thanks.  also if it's getting to be too much for discussion here, let me know.

**Comment by liaxim** [comment]
For the Demos (and your apps) you don't need to download anything to use the 3.1 release. Everything will be downloaded for you by AS as long as you have the right dependencies (see the gradle files in the Demos).

The instructions you are referring to are still at least partially true but there is a much simpler way in 3.1.

Any reference to libs-gvrf.zip is obsolete.

No problems discussing here. It may end up being alternative form of documentation for others and gives us tips how to improve the existing documentation.

--
To reiterate, this is how you build the Demos:

1. clone the demos repo
2. switch to the "release-v3.1" branch
3. New->Import the GearVRf-Demos folder in AS
4. You may be asked for gradle 3.3; supply that
5. You can build and run any of the demos.

**Comment by grueiam** [comment]
ok thanks.  

for # 1, i'm hitting clone or download, then hitting download zip.  then i unzip and drop into my c:\dev directory (c:\dev\GearVRf-Demos-master)

for #2 i did the same procedure, downloaded the zip and unzipped (c:\dev\GearVRf-release_v3.1)  and inside \GearVrf-release_v3.1 is \GVRf and \Installer, .gitignore, LICENSE, README.md 

so i might be confused about #1 & #2 in terms of the procedure?

i ended up importing the demos, selected gvr-360photo and hit build, then i got the following errors:

```
Error:(31, 9) error: method setMain in class GVRActivity cannot be applied to given types;
required: GVRMain,String
found: Minimal360PhotoMain
reason: actual and formal argument lists differ in length
```

the java file is : Minimal360PhotoActivity.java

```
> 
> package org.gearvrf.gvr360Photo;
> 
> import android.os.Bundle;
> 
> import org.gearvrf.GVRActivity;
> 
> public class Minimal360PhotoActivity extends GVRActivity
> {
>     /** Called when the activity is first created. */
>     @Override
>     public void onCreate(Bundle savedInstanceState)
>     {
>         super.onCreate(savedInstanceState);
> 
>         Minimal360PhotoMain main = new Minimal360PhotoMain();
>         setMain(main);
>     }
> }
```

**Comment by grueiam** [comment]
sorry, also saw this error:
```
Error:(27, 8) error: Minimal360PhotoMain is not abstract and does not override abstract method onStep() in GVRScript
Error:Execution failed for task ':gvr-360photo:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by liaxim** [comment]
Looks like you are using the source code from the master branch. That one needs the very latest framework which you'll have to build yourself.

To clone the 3.1 branch you can execute "git clone -b release_v3.1 git@github.com:gearvrf/GearVRf-Demos.git"

If you prefer downloading a zip then please open https://github.com/gearvrf/GearVRf-Demos/tree/release_v3.1 and then select "Download ZIP".

**Comment by grueiam** [comment]
i didn't catch on that there were v3.1 demos vs. the other one.  great, i downloaded those, imported to AS. i got the message about gradle:

```
11:29:39 AM Gradle sync failed: Minimum supported Gradle version is 3.3. Current version is 2.14.1. If using the gradle wrapper, try editing the distributionUrl in C:\Dev\GearVRf-Demos-release_v3.1\gradle\wrapper\gradle-wrapper.properties to gradle-3.3-all.zip
            Consult IDE log for more details (Help | Show Log)
```

sp o edited the gradle-wrapper.properties file as suggested.  same error, so i downloaded gradle 3.3, unzipped it and placed it in C:\Program Files\Android\Android Studio\gradle directory (along side the 2.14.1 version).

i pointed AS to this new version, it completed it's sync and all looked good until i tried to build/run on my device.  i got this error:

`11:37:06 AM Error running gvr-360photo: This version of Android Studio is incompatible with the Gradle Plugin used. Try disabling Instant Run (or updating either the IDE or the Gradle plugin to the latest version)`

i have version 2.2.3 AS.  i'm not sure disabling instant run is what i want?  isn't that what runs the apk on the phone when the phone is plugged in via usb?

**Comment by liaxim** [comment]
Hi, please try going to File->Settings->Build, Execution, Deployment->Instant Run and uncheck "Enable Instant Run to hot swap..".

**Comment by grueiam** [comment]
yep! sorry, i edited my post above as you were replying.

**Comment by liaxim** [comment]
And about what instant run is: https://developer.android.com/studio/run/index.html#instant-run. In short, it is optional.

**Comment by liaxim** [comment]
To address the Thread Priority Exception you need a signature file from Oculus. See below:

All the demos will need an Oculus signature you can obtain from https://developer.oculus.com/osig/. You could configure the build to include all signatures from a certain directory in the apks. In gradle.properties define a OCULUS_SIGS_DIRECTORY property and specify the full path to the directory where you put your Oculus signatures. Otherwise you will be responsible to copy the signature files to the samples assets directories.

**Comment by grueiam** [comment]
oh yeah, ok i have that osig file. i will move to the assets folder within the gvr-360photo.  will do this in a little while and update.

**Comment by grueiam** [comment]
dude, thanks a ton.  i got it up and running, works like a charm.

one thing i didn't realize was that once you do the build on your phone, it's basically an installed app, so i can launch it any time - for example if i build a nice demo and want to show it to others when i'm away from the computer. great.

any suggestions or comments about going through the tutorials?  maybe a gotcha or watch out for?

thanks again!

**Comment by liaxim** [comment]
Glad to hear it.

The tutorial is pretty good and straightforward. The demos can help discover features of the framework. Let us know if you encounter problems.

**Comment by liaxim** [comment]
Btw, can we close the issue?

**Comment by grueiam** [comment]
yes please close. or i'll just click that close and comment ha!

**Comment by grueiam** [comment]
darn, one more question!  so i have to point Android Studio to a location for the GearVRFramework v3.1, so when i type in "import org.gearvrf.GVRActivity;" it knows where to look correct?

i thought i found how to do that the other day, but drawing a blank today.  the demos all have it predefined so it's loading it from there and not quite helping me figure it out :)

**Comment by liaxim** [comment]
You can use GearVRf-Demos/common.gradle as a reference how to add the framework dependency to your own project. Will look into extracting the bare minimum out of that file.

**Comment by thomasflynn** [comment]
I think the bare minimum probably reduces down to adding the dependencies in the gradle file:

In AndroidStudio, Click on 'Gradle Scripts'
Click on build.gradle (app)
dependencies {
       compile fileTree(dir: 'libs', include: ['*.jar'])
       // add the following
       compile 'org.gearvrf:framework:3.1.0'
       compile 'org.gearvrf:backend_daydream:3.1.0'
       compile 'org.gearvrf:backend_oculus:3.1.0'
}

**Comment by liaxim** [comment]
These two repositories have to be added too:
```
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        maven {
            url "http://google.bintray.com/googlevr"
        }
```

Also I think the dependencies to google-vr and joml are also necessary
```
            compile 'com.google.vr:sdk-base:1.10.0'
            compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
            compile "org.joml:joml-android:${jomlVersion}"
```

Will have to double-check it is all correct in a completely new app that is not using our gradle files.

**Comment by grueiam** [comment]
yikes. ok i working on it... but might not get to it until tomorrow  am.  thaks.

**Comment by grueiam** [comment]
ok. wasn't sure where to add the maven stuff.  i added the compiles such that my build.gradle (Module: app) look like this:

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.steveg.basicgrvrf"
        minSdkVersion 23
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    // added below this line
    compile 'org.gearvrf:framework:3.1.0'
    compile 'org.gearvrf:backend_daydream:3.1.0'
    compile 'org.gearvrf:backend_oculus:3.1.0'
    compile 'com.google.vr:sdk-base:1.10.0'
    compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
    compile 'org.joml:joml-android:${jomlVersion}'
    //added above this line
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.1'

    testCompile 'junit:junit:4.12'
}
```
with the compile...joml:joml... i got an error:

```
Error:(29, 13) Failed to resolve: org.joml:joml-android:${jomlVersion}
<a href="openFile:C:/Dev/MyApps/test/basicGRvrf/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```

if i left out the compline 'org.joml:joml-android:${jomlVersion}'  then i would get error:

```
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:7:9-43
	is also present at [org.gearvrf:framework:3.1.0] AndroidManifest.xml:38:9-45 value=(@drawable/ic_launcher).
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:5:5-18:19 to override.
```

**Comment by grueiam** [comment]
update:  i looked at the "gvr-simplesample" build.gradle (Module: gvr-simplesample) file.  i looked back at my build.gradle (Module: app) file.  the two were quite different.

i combined the two in this way and the sync worked without error:

```
apply plugin: 'com.android.application'
//added below this
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.steveg.basicgrvrf"
        minSdkVersion 23
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    // added below this line

    //added above this line
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.1'

    testCompile 'junit:junit:4.12'
}

//added above this
System.setProperty("appName", "app")

if(file("../../common.gradle").exists()) {
    apply from: '../../common.gradle'
}
else if(file("../../../../GearVRf-Demos/common.gradle").exists()) {
    apply from: '../../../../GearVRf-Demos/common.gradle'
}

android {
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    sourceSets.main {
        jni.srcDirs = [] // no auto generation of Android.mk
        jniLibs.srcDir 'libs' // pre-compiled libraries
    }
}
```

not sure if that is the correct way to do it, ha, but no errors so far. maybe when i build?  but i can continue going through the tutorial of building a basic app: https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/060_Gear_VRf_Developer_Guide/150_Writing_a_Basic_GearVRf_Application

**Comment by grueiam** [comment]
darn, nope, i can't continue with that tutorial, i get these errors:

```
Error:(8, 8) error: class GalleryActivity is public, should be declared in a file named GalleryActivity.java
Error:(5, 19) error: cannot find symbol class GVRActivity
Error:(8, 38) error: cannot find symbol class GVRActivity
Error:(9, 5) error: method does not override or implement a method from a supertype
Error:(11, 9) error: cannot find symbol variable super
Error:(12, 21) error: cannot find symbol class SampleViewManager
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by liaxim** [comment]
Minimal build.gradle:

```
apply plugin: 'com.android.application'

allprojects {
    repositories {
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
        maven {
            url "http://google.bintray.com/googlevr"
        }
    }
}

android {
    // ignore the x86 and arm-v8 files from the google vr libraries
    packagingOptions {
        exclude 'lib/x86/libgvr.so'
        exclude 'lib/arm64-v8a/libgvr.so'
    }
}

ext.gearvrfVersion='3.1.1-SNAPSHOT'
project.ext.jomlVersion = "1.9.1-SNAPSHOT"

dependencies {
    compile "org.joml:joml-android:${jomlVersion}"
    compile "org.gearvrf:framework:$gearvrfVersion"
    compile "org.gearvrf:backend_daydream:$gearvrfVersion"
    compile "org.gearvrf:backend_oculus:$gearvrfVersion"
    compile 'com.google.vr:sdk-base:1.10.0'
    compile 'com.google.protobuf.nano:protobuf-javanano:3.0.0-alpha-7'
}
```

AndroidManifest.xml: add the two permissions, the meta-data and launchMode and screenOrientation attributes per:
```
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application ...>
        <meta-data android:name="com.samsung.android.vr.application.mode" android:value="vr_only"/>
        <activity ...
            android:launchMode="singleTask"
            android:screenOrientation="landscape"

```

There might be a warning about android:icon; use the AS-recommended resolution (tools:replaceIcon).

**Comment by liaxim** [comment]
We probably should create a bare-bones template project to bootstrap people.

**Comment by grueiam** [comment]
wow thanks.  i did get one heck of a lot further, at least i'm not getting the GVRActivity Symbol error, but alas still some other errors that creep up.  i'm going to take a rest for a bit for this, that's why i closed it, but will monitor for any updates. haha, especially if you build a bare-bones template project :)

hopefully i'll have a fresher look in a few days.

thanks for all the help!  i know more now than i did!

**Comment by liaxim** [comment]
Here it is - the barebones project. You just need to copy the Oculus signature to the assets folder.

[gvrfapp.zip](https://github.com/Samsung/GearVRf/files/764232/gvrfapp.zip)

**Comment by grueiam** [comment]
liaxim - thanks, download and started playing around with it. ha, have had to recreate it a couple of times!  i've been jamming on a couple of jobs that have popped up recently so only recently got to this.

so here's a question, are you or thomas developers for hire at all?  or would you know of someone i could work with to develop an app for our business?  maybe we could chat offline about it? thanks!

**Comment by jpsmith1981** [comment]
@liaxim Hello~

This maybe a stupid question but in your bootstrap application you provided where do I download the gearvr aar files too and which ones do I download.

Thank you.

**Comment by liaxim** [comment]
Hi @jpsmith1981. Please take a look at the dependencies section of https://github.com/gearvrf/GearVRf-Demos/blob/master/template/GVRFApplication/app/build.gradle. You will need these for the core framework with support for either the Oculus or Daydream backends. Gradle will take care of downloading the aar files.
