### ISSUE TITLE
Force destroy texture

### ISSUE THREAD

**Issue by aviadmini** [Samsung/GearVRf#1032]
Is there a way to destroy a texture to load another one instead?

My textures are quite large so I'm just hitting RAM limit and getting a crash.

In plain OpenGL I could simply call `glDestroyTextures` and I know there's one in GLTexture.cpp but I've not found neither low-level or high-level way to do it

Thanks ahead

**Comment by thomasflynn** [comment]
There is an update(Bitmap bitmap) method for GVRBitmapTexture if that is what you're using.  That way, you can allocate your BitmapTexture once and just reuse it.  Otherwise, releasing the java reference to the object will call glDeleteTextures() once it is garbage collected.

**Comment by aviadmini** [comment]
Thanks for the answer.

Actually I ended up using pre-compressed textures because they load blazing fast. For that I use `GVRContext.loadTexture(callback, ...)` because `loadFutureTexture` introduces a really long delay (200+ ms at a glance) before textures are actually shown :(

However sometimes when I'm doing **a lot** of texture swapping I'm getting a weird crash in native code. My semi-random guess is that I might be trying to load a resource again before it has been loaded.

**Comment by liaxim** [comment]
@aviadmini Please share with us the logcat output when the crash happens.

**Comment by aviadmini** [comment]
@liaxim I'm unable to reproduce it forcefully. Although I think the logcat output was totally meaningless: just error signal from native code and it dies (SIGEGV)

If I happen to encounter it again I'll try to grab logcat output anyway
