### ISSUE TITLE
Listview

### ISSUE THREAD

**Issue by shaishav-mtech** [Samsung/GearVRf#1036]
Is there any example that shows how to develop android like listview in gear vr?

**Comment by liaxim** [comment]
Hi. Not to my knowledge. We have integration with libgdx though - see the gvr-widgetviewer and the gvr-modelviewer2 samples which use it. See https://libgdx.badlogicgames.com/ for general libgdx information.

**Comment by thomasflynn** [comment]
Actually, take a look at gvr-events.  In there, an Android view is inflated that has buttons, checkbooks, and a list view.

**Comment by shaishav-mtech** [comment]
@thomasflynn  Thanks. I have get it working by referencing gvr-events and by making some changes to handle scroll event as I am also dealing with click events in my app. You can close it.
