### ISSUE TITLE
onInit not called on activity restart

### ISSUE THREAD

**Issue by sam16222** [Samsung/GearVRf#1044]
I am building an app that has multiple activities. When an activity (say activity B) is called first time from the main Activity(activity A), it creates the GVRMain object and initializes the scene using onInit. When I go back to the main Activity (A) and call activity B again, nothing happens. I am destroying activity B on backpress because I need a fresh new instantiation of the activity. Please let me know what needs to be done.

**Comment by liaxim** [comment]
Are both A and B deriving from GVRActivity?

**Comment by sam16222** [comment]
Yes. Both are deriving from GVRActivty. Would this be happening because of context leak? What should be the procedure to destroy a GVRActivity? Considering the corresponding GVRMain class.

**Comment by liaxim** [comment]
Having more than one GVRActivity is not something that we expect to work. So far we haven't seen a strong case that demands the support for more than one. If you do need that we can look into it but I am very curious to know why.

There are much faster and neater ways to switch between different scenes/screens in GVRF. Jumping from one activity to another is never going to be as fast and could possibly be jarring to the user.

**Comment by sam16222** [comment]
Even I am not inclined towards using multiple GVRActivites in the application, but just wanted to know as to why it won't work. I am jumping from one scene to other only as of now. Let me know if you can figure out as to why it won't work. Thank you anyway.

**Comment by liaxim** [comment]
I will open an issue to keep track of this officially.
