### ISSUE TITLE
Blur camera effect using GVRCameraSceneObject

### ISSUE THREAD

**Issue by konidk** [Samsung/GearVRf#1047]
Hi,

I'm trying to apply a blur effect on the camera preview, I tried many things but nothing is working. I know that the proper way is to work with shaders, but I really don't know how to apply a **custom shader** to the **GVRCameraSceneObject**... 
Should I work with the **GVRMaterial** instead ? If yes, how ?

I also tried to set up a **GVRViewSceneObject** and put a **TextureView** in it, then apply Camera preview to this TextureView. But this is not working, I really don't know why (even if it's working in the test app without GVRF). Using this [library](https://github.com/500px/500px-android-blur/tree/master) this could have been then easy to apply a blur effect.
Note that the camera preview only renders using the stock **OES_SHADER** :
`material = new GVRMaterial(gvrContext, GVRShaderType.OES.ID);`

Thanks, some help would be really appreciated.

EDIT : I've found [this](https://github.com/yulu/ShaderFilter) which provide a GLSL code for a blur appearance, but I can't get it to work using **addShader()**. Here is the code :

```
vec3 mosaic(vec2 position){
    vec2 p = floor(position)/10.;
    return texture2D(sTexture, p).rgb;
}

vec2 sw(vec2 p) {return vec2( floor(p.x) , floor(p.y) );}
vec2 se(vec2 p) {return vec2( ceil(p.x) , floor(p.y) );}
vec2 nw(vec2 p) {return vec2( floor(p.x) , ceil(p.y) );}
vec2 ne(vec2 p) {return vec2( ceil(p.x) , ceil(p.y) );}

vec3 blur(vec2 p) {
    vec2 inter = smoothstep(0., 1., fract(p));
    vec3 s = mix(mosaic(sw(p)), mosaic(se(p)), inter.x);
    vec3 n = mix(mosaic(nw(p)), mosaic(ne(p)), inter.x);
    return mix(s, n, inter.y);
    }

vec3 main()
{
    return blur(vTextureCoord*10.);
}
```

**Comment by NolaDonato** [comment]
The best way to do this is to make a custom shader and use it in a render pass. I will write up an example showing how to do this tonight, test it and post it here. I will also get the example added to the documentation.

In the mean time, here is a link to how to create a custom shader from the GearVRF Developers Guide: https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/060_Gear_VRf_Developer_Guide/020_GearVRf_Features/Phong_Shader_Template/GVRShaderTemplate_-Creating_Custom_Shaders

**Comment by NolaDonato** [comment]
I was wrong. You cannot do it with a render pass because OpenGL ES 3.0 won't let you read the framebuffer from a shader unless it is already in a texture. You can replace the OESShader with your blur shader though. You have to name the texture "main_texture" to match what GVRCameraSceneObject does and then call GVRRenderData.setShaderTemplate to force your custom shader into an existing material.
    public void onInit(GVRContext gvrContext)
    {
        mGVRContext = gvrContext;
        GVRScene scene = gvrContext.getMainScene();
        GVRCameraSceneObject cameraObject = null;

        //
        // Create a camera scene object.
        // This step will fail if your camera cannot be accessed.
        //
        try
        {
            cameraObject = new GVRCameraSceneObject(gvrContext, 3.6f, 2.0f);
            cameraObject.setUpCameraForVrMode(1); // set up 60 fps camera preview.
        }
        catch (GVRCameraSceneObject.GVRCameraAccessException e)
        {
            // Cannot open camera
            Log.e(TAG, "Cannot open the camera",e);
            mGVRContext.getActivity().finish();
        }
        cameraObject.getTransform().setPosition(0.0f, 0.0f, -1.0f);

        //
        // At this point the camera will be using the OESShader
        // in the material attached to its render data.
        // We replace the OESShader with a custom blur shader.
        // The blur shader and material must be explicitly connected with "bindShader"
        //
        GVRRenderData rdata = cameraObject.getRenderData();
        rdata.setShaderTemplate(BlurShader.class);
        rdata.bindShader(scene);
        scene.getMainCameraRig().addChildObject(cameraObject);
    }

**Comment by konidk** [comment]
Thank you for your answer !
I started working on the **BlurShader** class in order to use the code you've provided above. So I need to apply the shader directly inside a texture named "main_texture", and then call GVRRenderData.setShaderTemplate to apply the shader.

This is what I've done, please tell me if I'm doing it the right way (don't think so because I don't bind in the same way) :
```
                //
                // Initializing texture
                // GVRExternalTexture is the same type as the texture used by GVRCameraSceneObject
                //
                GVRTexture blurTexture = new GVRExternalTexture(gvrContext);
                //
                // Initializing material which will be used to apply the texure on
                //
                GVRMaterial blurMaterial = new GVRMaterial(gvrContext);
                //
                // Set "main_texture" as texture's name to match what GVRCameraSceneObject does and apply it to the material
                blurMaterial.setTexture("main_texture",blurTexture);
                //
                // Init GVRShaderTemplate with BlurShader
                GVRShaderTemplate customBlurShader = gvrContext.getMaterialShaderManager().retrieveShaderTemplate(BlurShader.class);
                //
                // Bind the shader & the material together
                customBlurShader.bindShader(gvrContext, blurMaterial);
                //
                //  Then applying your code
                //
                GVRRenderData rdata = cameraObject.getRenderData();
                rdata.setShaderTemplate(customBlurShader.getClass());
                rdata.bindShader(scene);
```

I used the [link](https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/060_Gear_VRf_Developer_Guide/020_GearVRf_Features/Phong_Shader_Template/GVRShaderTemplate_-_Creating_Custom_Shaders) you gave me in order to create the **BlurShader** class. I have to apply a the GLSL code from my first post, but I don't know if this fits in the fragment or vertex shader (seems to be the fragment shader though). Here is my **BlurShader** class 👍 

```
public class BlurShader extends GVRShaderTemplate
{
    private static String fragTemplate = "vec3 mosaic(vec2 position){\n" +
            "    vec2 p = floor(position)/10.;\n" +
            "    return texture2D(sTexture, p).rgb;\n" +
            "}\n" +
            "\n" +
            "vec2 sw(vec2 p) {return vec2( floor(p.x) , floor(p.y) );}\n" +
            "vec2 se(vec2 p) {return vec2( ceil(p.x) , floor(p.y) );}\n" +
            "vec2 nw(vec2 p) {return vec2( floor(p.x) , ceil(p.y) );}\n" +
            "vec2 ne(vec2 p) {return vec2( ceil(p.x) , ceil(p.y) );}\n" +
            "\n" +
            "vec3 blur(vec2 p) {\n" +
            "    vec2 inter = smoothstep(0., 1., fract(p));\n" +
            "    vec3 s = mix(mosaic(sw(p)), mosaic(se(p)), inter.x);\n" +
            "    vec3 n = mix(mosaic(nw(p)), mosaic(ne(p)), inter.x);\n" +
            "    return mix(s, n, inter.y);\n" +
            "    }\n" +
            "\n" +
            "vec3 main()\n" +
            "{\n" +
            "    return blur(vTextureCoord*10.);\n" +
            "}";

    public BlurShader(GVRContext gvrcontext)
    {
        super("float4 diffuseColor", 300);
        setSegment("fragTemplate", fragTemplate);
    }
}
```

Once again, thank you for helping me. I'm still in trouble with this piece of code, I still can't get it to work !

**Comment by NolaDonato** [comment]
The code I sent will blur the camera external texture that is already set up by the camera scene object without modification.  Isn't  that what you wanted? If so you don't have to make another texture.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by NolaDonato** [comment]
Here is the code for the blur shader which will work with the GVRCameraSceneObject directly. You can replace the OESShader with this one to get a blurred image.

public class BlurShader extends org.gearvrf.GVRShaderTemplate
{
    private static final String VERTEX_SHADER =
              "in vec3 a_position;\n"
            + "in vec2 a_texcoord;\n"
            + "out vec2 vTextureCoord;\n"
            + "uniform mat4 u_mvp;\n"
            + "void main() {\n"
            + "  vec4 pos = vec4(a_position, 1.0);\n"
            + "  vTextureCoord = a_texcoord;\n"
            + "  gl_Position = u_mvp * pos;\n"
            + "}\n";

    private static final String FRAGMENT_SHADER =
            "#extension GL_OES_EGL_image_external_essl3 : require\n"
            + "precision mediump float;\n"
            + "uniform samplerExternalOES main_texture;\n"
            + "in vec2 vTextureCoord;\n"
            + "out vec4 outColor;\n"
            + "vec3 mosaic(vec2 position) {\n"
            + "    vec2 p = floor(position) / 10.;\n"
            + "    return texture(main_texture, p).rgb;\n"
            + "}\n"
            + "vec2 sw(vec2 p) {return vec2( floor(p.x) , floor(p.y) );}\n"
            + "vec2 se(vec2 p) {return vec2( ceil(p.x) , floor(p.y) );}\n"
            + "vec2 nw(vec2 p) {return vec2( floor(p.x) , ceil(p.y) );}\n"
            + "vec2 ne(vec2 p) {return vec2( ceil(p.x) , ceil(p.y) );}\n"
            + "vec3 blur(vec2 p) {\n"
            + "vec2 inter = smoothstep(0., 1., fract(p));\n"
            + "vec3 s = mix(mosaic(sw(p)), mosaic(se(p)), inter.x);\n"
            + "vec3 n = mix(mosaic(nw(p)), mosaic(ne(p)), inter.x);\n"
            + "return mix(s, n, inter.y);\n"
            + "}\n"
            + "void main() {\n"
            + "  outColor = vec4(blur(vTextureCoord * 10.), 1.0);\n"
            + "}\n";

    public BlurShader(GVRContext gvrcontext)
    {
        super("", 300);
        setSegment("FragmentTemplate", FRAGMENT_SHADER);
        setSegment("VertexTemplate", VERTEX_SHADER);
    }
}

**Comment by konidk** [comment]
Well, everything works finally fine ! Thanks a lot.

I had to change **GL_OES_EGL_image_external_essl3** to **GL_OES_EGL_image_external** because I use a galaxy s7 with mali GPU (not adreno). I would have never done this alone, I don't know anything related to GLSL and I would have never added the line **uniform samplerExternalOES main_texture** by myself.

**Comment by NolaDonato** [comment]
I am glad you got it to work!

Adding support for multiple lights was the first project I did last year when I got to Samsung. The hokey GVRRenderData.setShaderTemplate was to avoid making the API changes which would have been necessary to get it to work properly. In a future version, we will deprecate the setShaderTemplate call and just let you pass a shader ID for a custom shader to the GVRMaterial like you do now for builtin shaders.

The  GL_OES_EGL_image_external_essl3 vs GL_OES_EGL_image_external took me totally by surprise too. GearVRF will automatically make this change for you in a future version.

**Comment by konidk** [comment]
It's great to see that this framework is still in active development, it is really useful. I think this would allow an easier comprehension by letting us passing a shader ID for custom shaders because there are a lot of functions related to shaders and it lead in so many directions... Sometimes it's hard to know where to begin with, hope this will be simplified in the future !

I've got one more question though, I want to be able to switch easily between the blurred and normal vision. What is the best way in your opinion to achieve that ? And how ?

Thanks.

**Comment by NolaDonato** [comment]
The best way to do this is to make two scene objects that both share the same texture and geometry but use different shaders. You start with a GVRCameraSceneObject as before but then make another GVRSceneObject that uses the same geometry but changes the shader to your BlurShader. You can put both of these under the same parent scene object and use a GVRSwitch component to switch between them.

Here is the code to set up the scene objects:
        //
        // Create a camera scene object.
        // This step will fail if your camera cannot be accessed.
        //
        try
        {
            cameraObject = new GVRCameraSceneObject(gvrContext, 3.6f, 2.0f);
            cameraObject.setUpCameraForVrMode(1); // set up 60 fps camera preview.
        }
        catch (GVRCameraSceneObject.GVRCameraAccessException e)
        {
            // Cannot open camera
            Log.e(TAG, "Cannot open the camera",e);
            mGVRContext.getActivity().finish();
        }
        //
        // At this point the camera will be using the OESShader
        // in the material attached to its render data.
		// We make a material based on this one using the same
        // texture but a custom blur shader instead of the OESShader.
        // The blur shader and material must be explicitly connected with "bindShader"
        //
        GVRMaterial cameraMtl = cameraObject.getRenderData().getMaterial();
		GVRSceneObject blurryCamera = new GVRSceneObject(gvrContext, gvrContext.createQuad(3.6f, 2.0f), cameraMtl.getMainTexture(), GVRMaterial.GVRShaderType.OES.ID);
        GVRRenderData rdata = blurryCamera.getRenderData();
        rdata.setShaderTemplate(BlurShader.class);
        rdata.bindShader(scene);

		//
		// Now we make a scene object to be the parent of both the normal
		// and blurry camera. Adding a switch component allows us to
		// programmatically choose which one will be displayed.
		//
		GVRSceneObject cameraRoot = new GVRSceneObject(gvrContext);
        cameraRoot.getTransform().setPosition(0.0f, 0.0f, -1.0f);
        mSwitch = new GVRSwitch(gvrContext);
		cameraRoot.attachComponent(mSwitch);
		cameraRoot.addChildObject(cameraObject);	// index 0 = normal camera
		cameraRoot.addChildObject(blurryCamera);	// index 1 = blurry camera
        scene.getMainCameraRig().addChildObject(cameraRoot);


Here is the code to toggle between them on a touch event:

    public boolean onTouchEvent(MotionEvent event)
    {
        if (event.getAction() == MotionEvent.ACTION_UP)
        {
            int i = mSwitch.getSwitchIndex();
            if (++i >= 2)
            {
                i = 0;
            }
            mSwitch.setSwitchIndex(i);
            return true;
        }
        return false;
    }

**Comment by liaxim** [comment]
@NolaDonato Would (and should it) just changing the shader type for the material work instead?

**Comment by konidk** [comment]
The switch works like a charm, switching from the Blurred Vision to the Normal One. Thanks for your solution! But there is still something that bothers me, in fact i'm adding a GVRViewSceneObject in the scene to act as an overlay to show information.

As you can see from these two screenshots, when the blur vision is disabled the GVRViewSceneObject have a fully transparent background but this feature disappear (the background becomes totally black) when enabling the blur vision. Do you know why ?
[<img src="http://imgur.com/ci3sNbf.jpeg">](http://imgur.com/ci3sNbf.jpeg)
[<img src="http://i.imgur.com/nG3mLDC.png">](http://imgur.com/ci3sNbf.jpeg)

I know I might be asking a lot of questions but I'm curious to learn about the framework.
Thanks.

**Comment by NolaDonato** [comment]
Can you show me the code you use to construct the GVRViewSceneObject? I would like to try and duplicate your issue here. It could have something to do with transparency sorting, I am not sure.

**Comment by konidk** [comment]
Here is my code,

```
           //The code you gave me to create cameraRoot
           ............................................
           cameraRoot.addChildObject(blurryCamera);	// index 1 = blurry camera
           objectList.add(cameraRoot);

            // Init GVRViewSceneObject
            quadBlur = new GVRSceneObject(gvrContext, 3.6f, 2.0f);
            InfoView = new GVRViewSceneObject(gvrContext,mActivity.getInfoView(), quadBlur.getRenderData().getMesh());
            InfoView.getTransform().setPosition(0.0f, 0.8f, -2.1f);
            objectList.add(InfoView);

           // Adding objects to the scene, making GVRSceneObject follow the user sight direction
            for (GVRSceneObject object : objectList) {
                if (object instanceof GVRSceneObject) {
                    scene.getMainCameraRig().addChildObject(object);
                } else {
                    scene.addSceneObject(object);
                }
            }
```

In order to show / hide **InfoView** I use the command,
//Hide InfoView
objectList.get(1).getRenderData().setRenderMask(0);
/// Show InfoView
objectList.get(1).getRenderData().setRenderMask(3);

**Comment by NolaDonato** [comment]
The GVRViewSceneObject uses the OES shader also. If you want it to appear transparent and and on top of everything else you need to do this:
GVRRenderData ivrd = InfoView.getRenderData();
ivrd.setAlphaBlend(true);
ivrd.setRenderingOrder(GVRRenderData.GVRRenderingOrder.TRANSPARENT);

These two lines enable alpha blending and make GearVRf render your InfoView last after rendering everything else.

**Comment by konidk** [comment]
That works perfectly ! Wow ! So happy :)
Now the last feature I need is having the possibility to vary the blur threshold when the program is running. I think I'll try to figure out how to do it by myself, I understand your time is precious. Something like adding a function to **BlurShader.java** should work.
```
       public void setFRAGMENT_SHADER(int mosaicStep) {
        String FRAGMENT_SHADER =
                "#extension GL_OES_EGL_image_external : require\n"
                        + "precision mediump float;\n"
                        + "uniform samplerExternalOES main_texture;\n"
                        + "in vec2 vTextureCoord;\n"
                        + "out vec4 outColor;\n"
                        + "vec3 mosaic(vec2 position) {\n"
                        + "    vec2 p = floor(position) / " + mosaicStep + ".;\n"
                        + "    return texture(main_texture, p).rgb;\n"
                        + "}\n"
                        + "vec2 sw(vec2 p) {return vec2( floor(p.x) , floor(p.y) );}\n"
                        + "vec2 se(vec2 p) {return vec2( ceil(p.x) , floor(p.y) );}\n"
                        + "vec2 nw(vec2 p) {return vec2( floor(p.x) , ceil(p.y) );}\n"
                        + "vec2 ne(vec2 p) {return vec2( ceil(p.x) , ceil(p.y) );}\n"
                        + "vec3 blur(vec2 p) {\n"
                        + "vec2 inter = smoothstep(0., 1., fract(p));\n"
                        + "vec3 s = mix(mosaic(sw(p)), mosaic(se(p)), inter.x);\n"
                        + "vec3 n = mix(mosaic(nw(p)), mosaic(ne(p)), inter.x);\n"
                        + "return mix(s, n, inter.y);\n"
                        + "}\n"
                        + "void main() {\n"
                        + "  outColor = vec4(blur(vTextureCoord *" + mosaicStep + ".), 1.0);\n"
                        + "}\n";
        setSegment("FragmentTemplate", FRAGMENT_SHADER);
    }
```

**But it seems like it's not working**. I don't know how can I access to the current shader applied on change  parameters programmatically
`blurryCamera.getRenderData().getGVRContext().getMaterialShaderManager().retrieveShaderTemplate(BlurShader.class).setFRAGMENT_SHADER(10);`

**Comment by NolaDonato** [comment]
Runtime parameters are passed to the shader thru the GVRMaterial. You need to tell the shader what their names are when you set it up:

public BlurShader(GVRContext gvrcontext)
{
    super("float blur_threshold", 300);
    setSegment("FragmentTemplate", FRAGMENT_SHADER);
    setSegment("VertexTemplate", VERTEX_SHADER);
}

You give it a value thru GVRMaterial:

GVRMaterial myBlurMaterial = new GVRMaterial(context);
myBlurMaterial.setFloat("blur_threshold", 0.3f);

The shader just declares it as a uniform:
String FRAGMENT_SHADER =
                "#extension GL_OES_EGL_image_external : require\n"
                  + "precision mediump float;\n"
                  + "uniform samplerExternalOES main_texture;\n"
                  + "uniform float blur_threshold;\n"
                  + "in vec2 vTextureCoord;\n"
                  + "out vec4 outColor;\n"

**Comment by konidk** [comment]
Perfect ! Thank you.
