### ISSUE TITLE
what is the replacement for getNextMainScene()?

### ISSUE THREAD

**Issue by sam16222** [Samsung/GearVRf#1048]
Hello,
The framework maven repo got recently updated due to a previous query. In that, the GVRContext.getNextMainScene function has been removed. I wanted to know what that has been replaced by. I am trying to run the camera2renderscript example from the demos repo, but it's not compiling. Let me know what is to be done. Thank you.

**Comment by konidk** [comment]
getMainScene() is the new method to call

**Comment by liaxim** [comment]
@sam16222 Please pass the ``--refresh-dependencies`` argument to gradlew if you are building from the command line. Or you can just delete the gradle cache via ``rm -rf ~/.gradle/caches/``. Unfortunately I do not think there is a better way of getting a fresh snapshot from maven.

Alternatively you could use the 3.1 branch which is stable. After cloning the demos repo switch to the release_v3.1 branch.

The master branch is under active development and subject to frequent improvements.

**Comment by sam16222** [comment]
I already have refreshed the dependencies and have the latest code for GVRF. The getNextMainScene function from the older versions has been removed, and what I wanted to know was the replacement. Also getMainScene() existed along with getNextMainScene earlier so it can't be a replacement.

**Comment by thomasflynn** [comment]
Sorry that it is confusing, but it is indeed the replacement.  The history is that getNextMainScene was introduced when we added support for having a splashscreen.  The splashscreen scene needed to be visible and executing while the application was loading assets into the 'nextMainScene'.  Adding that api wasn't elegent, but it worked out well enough for the deadline we had.  As you can see, we have been going through the api and cleaning things up and trying to make it easier for new users at the same time.  So now, you no longer need to keep track of when you need to call getNextMainScene (when you want to display a splashscreen and you're inside onInit) and when to call getMainScene (when you don't want to display a splash screen or if you call inside onStep).  Instead, you just call getMainScene and gvrf does the right thing.  One less api and a whole lot less for a user to keep track of and have explained to them.
