### ISSUE TITLE
cannot resolve method

### ISSUE THREAD

**Issue by stkim88** [Samsung/GearVRf#1049]
Hi 
I built well the GearVRf-Demos on the android studio.
and the demos worked well on the phone. 
I do not know what I'm doing wrong, but suddenly I can not build the GearVRf-Demos with the message "Cannot resolve method 'getNextMainScene()' ".  

Specifically, gvr-360photo/app/src/main/java/Minimal360PhotoMain.java  

// get a handle to the scene
        GVRScene scene = gvrContext.getNextMainScene();

I repeat all the installation process and re-download the GearVRf-Demos and GearVRf-3.1, but the error does not disappear. How should I resolve this?

**Comment by konidk** [comment]
**gvrContext.getNextMainScene()** has been replaced by **gvrContext.getMainScene()** in the last update. Demos should have been updated as well but it doesn't seem to be the case !

**Comment by liaxim** [comment]
@stkim88 @konidk Assuming you are relying on the framework we push to the maven repo and not building it yourself, you need to invalidate your gradle cache. Last week the snapshot was updated and everything builds just fine.

Pass the ``--refresh-dependencies`` argument to gradlew if you are building from the command line. Or you can just delete the gradle cache via ``rm -rf ~/.gradle/caches/``. Unfortunately I do not think there is a better way of getting a fresh snapshot from maven.

Alternatively you could use the 3.1 branch which is stable. After cloning the demos repo switch to the release_v3.1 branch.

**Comment by NolaDonato** [comment]
Try using getMainScene



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
