### ISSUE TITLE
GearVRf on Android Studio.

### ISSUE THREAD

**Issue by DanielNogueiraAndroid** [Samsung/GearVRf#105]
How to use GearVRf on Android Studio ?

**Comment by thomasflynn** [comment]
hey, jason, could you reply with your list of instructions?  thanks.

**Comment by thomasflynn** [comment]
Just as a note.  The whole Android Studio problem has been complicated by the fact that Oculus requires that you build their mobile sdk with Eclipse.  And that requirement comes from AndroidStudio's poor NDK support.  Supposedly that it doesn't support dependencies on external libs in the NDK side.  The recently announced upcoming AndroidStudio 1.3 will supposedly improve all that.  So, hopefully soon, all the bottlenecks will be removed.

**Comment by niusounds** [comment]
Hi.
I built VrLib and GearVRf with Eclipse and copy built `.so` files to my Android Studio project.
I created simple-sample example project for Android Studio.
https://github.com/ejeinc/GearVRf_simplesample

**Comment by jason2kim** [comment]
I have been recommending to use prebuilt lib for both gvrf and ovr for several reasons. This posting could align with the approach. Thanks for the posting.
However, migrating or merging similar to this one is on hold, considering impacts to the Eclipse users and some accompanying issues.
For prebuilt libraries, people should be able to download from each site respectively. Also there is an instruction page at the wiki for prebuilt gvrf.

**Comment by chenchao1407** [comment]
@niusounds Thanks for your support. Just took a quick review on your repo and have a small question here:
I see that for native side you are using so files, but for java side, you are still using source for reference. Is there any way to use jar files instead of Java source? Thanks in advance.

**Comment by lokeshguddu** [comment]
By when can we expect migration from eclipse to Android Studio?

**Comment by jason2kim** [comment]
The prebuilt library approach for Android Studio for app developers can be found at: https://github.com/Samsung/GearVRf/releases.
However, migration schedule for the framework developers are still under discussion on its priority because of aforementioned reasons.

**Comment by niusounds** [comment]
@chenchao1407 Thanks for advice.

I rebuild project for simple maintenance.
https://github.com/ejeinc/GearVRf_simplesample
now `gearvrf` module contains only .so and .jar files.

**Comment by thomasflynn** [comment]
as of Version 3.0 (released last week), we have fully moved to Android Studio
