### ISSUE TITLE
Daydream intent filter results in black screen

### ISSUE THREAD

**Issue by felislynx-silae** [Samsung/GearVRf#1059]
App is building correctly and running on Pixel phone but it's not listed in daydream app. 
To list it, I have to set <category android:name="com.google.intent.category.DAYDREAM" /> in intent filter in manifest. After that, app is listed but trying to launch it results in black screen (full screen). 
I've debugged app start and activity, scenes etc. are running like they should. There is no error, no message that could pinpoint to cause of this issue.

**Comment by liaxim** [comment]
We will have to get hold of a Pixel. It will take few days.

**Comment by rahul27** [comment]
Hi @felislynx-silae I just tried the gvr-simplesample(https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-simplesample) and it ran fine on the Pixel. I had to add the following lines to the manifest to get it to run and show up on Daydream Home:

```
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
                <category android:name="com.google.intent.category.DAYDREAM"/>
            </intent-filter>
```

Could you let me know the sample you tried at your end? Also it would be great if you could try the simplesample and let me know if you see the same issue?

Thanks.

**Comment by felislynx-silae** [comment]
I'll try this week a simplesample. I might forgot that i'm using this:
```
...
    compile 'org.gearvrf:framework:3.1.1'
    compile 'org.gearvrf:3DCursorLibrary:3.1.1'
    compile 'org.gearvrf:backend_daydream:3.1.1'
    compile 'org.gearvrf:backend_oculus:3.1.1'
...
```
instead of compiling framework by myself. So this might be an issue.

**Comment by felislynx-silae** [comment]
Ok, just builded Simplesample and it's same issue as before. Black screen with category DAYDREAM. Attaching build.gradle which i've used to build.
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "eu.lynxit.simplesample"
        minSdkVersion 19
        targetSdkVersion 19
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }

    productFlavors {
        oculus {
            dependencies {
                compile 'org.gearvrf:backend_oculus:3.1.1'
            }
        }
        daydream {
            dependencies {
                compile 'org.gearvrf:backend_oculus:3.1.1'
                compile 'org.gearvrf:backend_daydream:3.1.1'
                compile 'com.google.vr:sdk-common:1.10.0'
                compile 'com.google.vr:sdk-base:1.10.0'
            }
            packagingOptions {
                exclude 'lib/x86/libgvr.so'
                exclude 'lib/arm64-v8a/libgvr.so'
                if (!rootProject.hasProperty("ARM64")) {
                    exclude 'lib/arm64-v8a/*.so'
                }
            }
        }
    }

    dataBinding {
        enabled = true
    }

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'LICENSE.txt'
        exclude 'META-INF/spring.tooling'
        exclude 'META-INF/spring.handlers'
        exclude 'META-INF/spring.schemas'
        exclude 'META-INF/license'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/notice.txt'
        exclude 'license.txt'
        exclude 'lib/x86/libgvr.so'
        exclude 'lib/arm64-v8a/libgvr.so'
        if (!rootProject.hasProperty("ARM64")) {
            exclude 'lib/arm64-v8a/*.so'
        }
    }

    signingConfigs {
        release {
        }
    }

    buildTypes {
        release {
        }
        debug {
        }
    }

    dexOptions {
        preDexLibraries = false
        javaMaxHeapSize "4g"
    }

    lintOptions {
        abortOnError false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.gearvrf:framework:3.1.1'
    compile 'org.gearvrf:3DCursorLibrary:3.1.1'

    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:support-annotations:25.2.0'

    testCompile 'junit:junit:4.12'
}
```

**Comment by felislynx-silae** [comment]
And by the way, just checked on Moto Z, and it's the same behavior as Pixel.

**Comment by brian-faber** [comment]
I just want to chime in and say I was seeing the same issue as felislynx-silae when I tried this a few weeks back. If I specify the daydream intent I get a black screen, if I don't it runs as a cardboard app on my pixel phone.

**Comment by rahul27** [comment]
@felislynx-silae I managed to recreate the issue at my end. Thanks for the help.

The issue seems to be a conflict with the google libraries used by GVRf. v3.1.1 uses v1.0.0 of the google vr libraries (which does not recognize the intent filter for daydream). You will find the configuration for v3.1.1 here:

https://github.com/gearvrf/GearVRf-Demos/blob/release_v3.1/common.gradle

I would recommend updating your GVRf version to 3.1.2-SNAPSHOT to use v1.10.0 of the google vr libraries. This would allow you to use the intent filter as well. Here is a build.gradle that will help you migrate:

https://github.com/gearvrf/GearVRf-Demos/blob/master/template/GVRFApplication/app/build.gradle

Let me know if that works for you.

**Comment by felislynx-silae** [comment]
3.1.2-SNAPSHOT was a solution :). Is next full release going to have this solution?

**Comment by liaxim** [comment]
@felislynx-silae Absolutely
