### ISSUE TITLE
Error:Failed to resolve: org.gearvrf:backend_daydream:3.1.1-SNAPSHOT

### ISSUE THREAD

**Issue by sam16222** [Samsung/GearVRf#1066]
Getting this error while building a sample app from gvrf demos. What is the issue with this?

Error:Failed to resolve: org.gearvrf:backend_daydream:3.1.1-SNAPSHOT
Error:Failed to resolve: org.gearvrf:backend_oculus:3.1.1-SNAPSHOT
Error:Failed to resolve: org.gearvrf:framework:3.1.1-SNAPSHOT

**Comment by guiyens** [comment]
Same problem:

> Could not resolve all dependencies for configuration ':gvr-video:_debugApkCopy'.
   > Could not find org.gearvrf:framework:3.1.1-SNAPSHOT.
     Required by:
         GearVRf-Demos:gvr-video:unspecified
   > Could not find org.gearvrf:backend_daydream:3.1.1-SNAPSHOT.
     Required by:
         GearVRf-Demos:gvr-video:unspecified
   > Could not find org.gearvrf:backend_oculus:3.1.1-SNAPSHOT.
     Required by:
         GearVRf-Demos:gvr-video:unspecified

**Comment by brian-faber** [comment]
I also am getting this (just synced this morning but was fine before)

**Comment by konidk** [comment]
I also got this error.

**Comment by roshanch** [comment]
Whats your ~/.gradle/gradle.properties looks like? Does it have "useLocalDependencies=true" or "buildGvrfAndDemos=true" ?

**Comment by roshanch** [comment]
In your common.gradle of Demos, try changing line ext.gearvrfVersion='3.1.1-SNAPSHOT'" to ext.gearvrfVersion='3.1.1'

**Comment by thomasflynn** [comment]
i think something went wrong with the automated buiild.  sent a message to the build team.  will let you know.

**Comment by liaxim** [comment]
Looks like since we made a 3.1.1 release the maven repo renamed the snapshot directory. Will create a 3.1.2 snapshot and update our release procedure wiki.

**Comment by liaxim** [comment]
3.1.2 snapshot created, the framework and demos have been updated. The demos build without problems.

Updated the wiki with the steps we missed this time.

**Comment by sam16222** [comment]
Okay thanks. It is working now.
