### ISSUE TITLE
Execution failed for task '"framework:buildInfo'.

### ISSUE THREAD

**Issue by sam16222** [Samsung/GearVRf#1067]
I am trying to build the framework but end up with the error

Process 'command 'git'' finished with non-zero exit value 128

As I understand from the gradle files, the code is uploading/deleting files from the github repository. Due to company restrictions I have very limited access to github, in that I cannot clone directories. Sinse I have downloaded the zip manually, it gives the error 'not a git repository'

commandLine 'git log -n 1 --format=%H'.split()
I am assuming this line cannot be omitted. The other git functions (upload/download) have been removed

What should I change in the buildInfo task in order to make it work without git?

**Comment by thomasflynn** [comment]
yes, that can be omitted.  those lines are in there to automatically stamp the GearVRf library with the git hash of the last commit which we will output to the logcat on startup.  This allows us to help identify what was in a daily build if a problem was discovered in some random build.

you can omit any lines referencing git.

**Comment by sam16222** [comment]
Can I omit the entire buildInfo task? because that task uses the output of 'git log -n 1 --format=%H' for creating .cpp and .java files.

**Comment by thomasflynn** [comment]
i think you can.

**Comment by sam16222** [comment]
After commenting out the buildInfo tasks in both framework.gradle and backend_oculus.gradle, and commenting out the calls made to the buildInfo task, the build gives the following error

Error:(687) Android NDK: Module gvrf-oculus depends on undefined modules: systemutils    

I am not quite sure how to go about it. Can you please build once without all the git commands and let me know what all needs to be eliminated? Thank you!

**Comment by liaxim** [comment]
@sam16222 If you download the latest master, the use of the git executable has been removed. The build now tries to read the information directly from the git metainfo and if it can't, it continues on.

I will look into what happens with the version you are using.

**Comment by rahul27** [comment]
I get the same error when I try to build the framework with the latest version of the NDK : 

`Error:(686, 0) Android NDK: Module gvrf-oculus depends on undefined modules: systemutils    `

Downgrading the NDK version builds the framework correctly. We might have to fix the build for the latest version of the NDK.

**Comment by liaxim** [comment]
The systemutls error was fixed by https://github.com/Samsung/GearVRf/pull/1070

**Comment by liaxim** [comment]
@sam16222 Alternatively remove the reference to systemutils from GearVRf/GVRf/Framework/framework/src/main/jni/Android.mk if you want to keep using your snapshot.

**Comment by sam16222** [comment]
Okay it works. Thank you!
