### ISSUE TITLE
Reset orientation not working any more

### ISSUE THREAD

**Issue by Akadone** [Samsung/GearVRf#1073]
A few of weeks ago gandle was update on 3.1.1 snapshot and 
scene.getMainCameraRig().reset();
was broken. Now I am upgraded it to 3.1.2, but it`s steel not working. Not working any of scene.getMainCameraRig(). scene.getMainCameraRig().getTransform() too - I tried to use it for reset orientation.

**Comment by liaxim** [comment]
@Akadone Can you share a sample that shows how it is broken?

I just tried ``getGVRContext().getMainScene().getMainCameraRig().reset()`` and it worked as expected. To be more specific, I modified gvr-simplesample so on a touch event it would invoke the aforementioned reset. When I launch this app I am facing a quad. Then I rotate my head, tap and the quad jumps back in front in my new orientation. This is exactly what I expect of the reset method.

**Comment by Akadone** [comment]
On onInit(GVRContext gvrContext) I save the GVRContext. Then I run a thread to "speak" to server. If server send command to reset orientation, I do:
if (mServerState.nCurrentServerStatus == FSA_RESET_ORIENT) {   //Reset orientation
                            Log.e("store360", "reset ");
                            scene.getMainCameraRig().reset();
                            continue;
                        }
On ADB log this message is present.
If I do getGVRContext().getMainScene().getMainCameraRig().reset() - I have same result. May be it sacuse of another thread?

**Comment by liaxim** [comment]
Ok, attaching slightly modified gvr-simplesample. Replace the one from GearVRf-Demos with it. On tap it should reset the orientation. Does it work for you?
[gvr-simplesample.zip](https://github.com/Samsung/GearVRf/files/828595/gvr-simplesample.zip)

While we have threading issues I do not expect they would surface in this case. In my tests I reset the orientation from the Android main thread and a background thread.

**Comment by liaxim** [comment]
@Akadone Any update? Still having an issue?

**Comment by liaxim** [comment]
@Akadone Assuming it is all good. Let us know if you are still experiencing problems.
