### ISSUE TITLE
gvr-3dcursor: volume up/down keys do not bring up the volume UI

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#1074]
Also back key doesn't bring up the exit to Oculus prompt. It has something to do with the IO framework. Not caused by useAndroidWearTouchpad=true.

**Comment by rahul27** [comment]
@liaxim Will fix this one. The IO framework needs to ignore the volume keys and the back button.

**Comment by rahul27** [comment]
Should be fixed now.
