### ISSUE TITLE
Improvement: support models with vertex colors baked in.

### ISSUE THREAD

**Issue by mvasilkov** [Samsung/GearVRf#1077]
**UPD.** I've noticed that while Assimp loads vertex colors, the GearVRf adapter doesn't copy this data to the mesh. Hence changing the title of the issue. I think this would be a neat feature for authoring simple models, for prototyping and such.

**Original issue:**

Hi dear all, I'm new here, and I'm trying to render a *.ply model from file. The model has vertex colors baked in.

I'm using `GVRAssetLoader::loadModel()`, which seems to work. When I add this model to the scene, it's light gray.

I can `.setDiffuseColor()` on a material and change the color of the model wholesale, but I can't seem to make it use vertex colors from the model. This seems to be unsupported by the built-in shaders, is this correct?

Can you please advise how to proceed? (My knowledge of GLSL can be summarized by an empty string: "".)

**Comment by NolaDonato** [comment]
The built-in shaders do not currently support vertex colors. You could write your own shader that looks at vertex colors but it would not work because our asset importer might not preserve the vertex colors in import. I will look into adding support for "foreign" vertex components into the asset loader and write a sample of how to do vertex colors. I might not get to it until Weds though.

**Comment by NolaDonato** [comment]
I worked on this issue and made some progress. I got the asset loader to load a mesh with vertex colors and wrote a shader which used them. Unfortunately GearVRf crashes in the middle of creating mesh attributes inside the renderer. I will debug further later this week.

**Comment by NolaDonato** [comment]
My first crack at solving vertex colors is in PR #1085. I could only find one free PLY model with vertex colors. Assimp imports this as a 4 floats for each color. I have not tried it with other PLY models. Maybe  @mvasilkov  would like to test this pull request with other PLY models.

**Comment by liaxim** [comment]
@mvasilkov Nola added support. She even added a test case for it; see https://github.com/gearvrf/GearVRf-Tests/pull/67. Assuming it is all good if we don't hear from you.
