### ISSUE TITLE
Proguard rules

### ISSUE THREAD

**Issue by felislynx-silae** [Samsung/GearVRf#1097]
Hi, this is question rather than a bug. What are the proguard rules for minification of code? And is obfuscating supported by GearVRf? For me that ended with errors of backend not found after building minified apk.

**Comment by liaxim** [comment]
Hi. We have not experimented with it. I do know that couple of classes should not be obfuscated:
```
org.gearvrf.OvrActivityDelegate
org.gearvrf.DaydreamActivityDelegate
```

Let us know if you still have problems.

**Comment by felislynx-silae** [comment]
As far as i tested i have 2 problems with proguard.
1. XMLBeans from mozilla javascript (from framework)
2. no backend detected (proably obfuscated name)

**Comment by felislynx-silae** [comment]
Error example after obfuscating code
```
Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{pl.testapp.ui/pl.testapp.ui.activities.ApplicationActivity}: java.lang.IllegalStateException: Fatal error: no backend available
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3254)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3350)
android.app.ActivityThread.access$1100 (ActivityThread.java:222)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1795)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:158)
android.app.ActivityThread.main (ActivityThread.java:7229)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

**Comment by liaxim** [comment]
``org.gearvrf.OvrActivityDelegate`` and ``org.gearvrf.DaydreamActivityDelegate`` should preserve their names. Do you have a proguard rule to ensure that? Do you have a proguard rules files you could share with us? Thanks.

**Comment by liaxim** [comment]
Ok, had a look at this. I recommend not obfuscating GVRf. This is a proguard-rules.txt that worked for my test app:

```
-keep class com.google.** { *; }
-dontwarn com.google.**

-keep class org.mozilla.** { *; }
-dontwarn org.mozilla.**

-keep class org.joml.** { *; }
-dontwarn org.joml.**

-keep class javax.script.** { *; }
-dontwarn javax.script.**

-keep class com.naef.jnlua.** { *; }
-dontwarn com.naef.jnlua.**

-keep class org.gearvrf.** { *; }
-dontwarn org.gearvrf.**
```

**Comment by felislynx-silae** [comment]
@liaxim Yup, those rules are 100% working. I must say few of them were suprise (jnlua, joml, mozilla) :)
Maybe it's worth to put those rules into FAQ section or somewhere visible to others. 
Thank you very much for your help

**Comment by liaxim** [comment]
Awesome.

FAQ updated.
