### ISSUE TITLE
Need proper transparency sorting

### ISSUE THREAD

**Issue by thomasflynn** [Samsung/GearVRf#110]
Currently in GearVRf, objects can be assigned a 'Rendering Order' (background, geometry, transparent, and overlay. see GVRRenderingOrder in GVRRenderData.java) and objects are sorted according to that.  That's a good start.  Though, within the list of objects marked as transparent, those should be sorted by distance from the camera.  That's currently not being done.  We should fix that.

**Comment by JonShemitz** [comment]
One complication here is that `GVRRenderingOrder` is not an enum, but more a set of bucket midpoints:

        public static final int BACKGROUND = 1000;
        public static final int GEOMETRY = 2000;
        public static final int TRANSPARENT = 3000;
        public static final int OVERLAY = 4000;

That is, there really isn't such a thing as "a" transparent rendering order: `TRANSPARENT-1` draws on top of `GEOMETRY` and under `TRANSPARENT+1`. It might be necessary to calculate distance-from-camera, and do a primary/secondary key sort, where that distance only matters when the render orders match.

**Comment by thomasflynn** [comment]
TRANSPARENT-1 is a good point.  otherwise, my extremely casual, not-fully-thought-out idea was to do a sort by distance when render orders match (sounds like maybe what you're suggesting?).  Where objects marked as 3000 would be sorted together, then objects at 3001 sorted together, then objects at 3002, etc.  I hadn't considered -1.  

The way i've seen other scene graphs do this is to have separate linked lists for geometry vs transparent.  the scene graph would be traversed and culled and the remaining visible nodes would fall into one of the two lists (often called "bins").  geometry would get sorted front-to-back, and transparent would get sorted back-to-front.

the 'assign a number for rendering order' gvrf does provide a quick way to sort objects without the need for separate lists, but it overlooks the need to sort transparent objects amongst themselves.  it also provides a low-overhead way of allowing a user to put objects into their own 'bin' by simply assigning a number.  So, there are some positives to this approach, but we still need to do proper sorting within each bin.

**Comment by JonShemitz** [comment]
> sounds like maybe what you're suggesting

Yeah, pretty much. I'd imagined calculating distance-from-camera for every scene object, but the sort-comparison function would only look at the delta-distance if delta-order equals 0.
