### ISSUE TITLE
For immersivepedia example can we set a GVRSphereSceneObject instead of plain GVRSceneObject

### ISSUE THREAD

**Issue by pre2612** [Samsung/GearVRf#1108]

**Comment by liaxim** [comment]
@pre2612 What is the context? Which scene object exactly do you want changed?

**Comment by pre2612** [comment]
addSceneObject(createSkybox()); //
addSceneObject(createBlueSkybox()); //

from public class DinosaurScene extends GVRScene

Background want to change it to 360 photo like:

  // get a handle to the scene
        GVRScene scene = gvrContext.getNextMainScene();

        GVRSphereSceneObject sphereObject = null;

        // load texture
        Future<GVRTexture> texture = gvrContext.loadFutureTexture(new GVRAndroidResource(gvrContext, R.raw.photosphere));

        // create a sphere scene object with the specified texture and triangles facing inward (the 'false' argument) 
        sphereObject = new GVRSphereSceneObject(gvrContext, 72, 144, false, texture);

        // add the scene object to the scene graph
        scene.addSceneObject(sphereObject);


If I am trying to add its a black background with a sphere at bottom with image. It would be very helpful if you can add some explanation too. I was trying to look for it in developer documentation couldn't understand.

**Comment by bohuang3d** [comment]
@pre2612 I see you are following the gvr-360photo example. Do you mean you can create the sphere geometry except you see just black on it and don't see the texture?

**Comment by liaxim** [comment]
@pre2612 is it all good or do you need more help?

**Comment by liaxim** [comment]
@pre2612 Let us know if you still have problems. Closing this for now.
