### ISSUE TITLE
Developer Mode Crashes

### ISSUE THREAD

**Issue by tparisi** [Samsung/GearVRf#111]
We have a simple test app that crashes, but only when the headset is on and when Gear VR Service is in Developer Mode. This didn't used to happen but it seems to happen since upgrading the Gear VR Service after installing Lollipop. Since we can only repro it with the headset on, and we're using Note 4's, we haven't been able to locate the source of the crash.

Has anyone else seen this? Any pointers would be appreciated... including pointers to a reliable way to debug via Bluetooth or Wifi while the headset is connected.

**Comment by thomasflynn** [comment]
quick link for debugging over wifi:
http://stackoverflow.com/questions/4893953/android-run-install-debug-applications-over-wifi

without a stacktrace or sample code, it is going to be hard to debug what is going on.  fwiw, we're all on lollipop here at the moment.

**Comment by tparisi** [comment]
FYI this didn't happen after the Lollipop upgrade UNTIL we also upgraded the Gear VR Service module. So that's a clue. Let me see if I can get more info, thanks for the pointer.

**Comment by liaxim** [comment]
Planning to close this one.
