### ISSUE TITLE
GVRAndroidResource constructor didn't pass the context to its field.

### ISSUE THREAD

**Issue by codeczx** [Samsung/GearVRf#1114]
Hi,when i used constructor,
 '''public GVRAndroidResource(GVRContext context, URL url, boolean enableUrlLocalCache) {
        this.stream = null;
        this.enableUrlLocalCache = false;
        this.context = null;
        this.compressedLoader = null;
        this.isCompressedTextureSniffed = false;
        this.enableUrlLocalCache = enableUrlLocalCache;
        this.streamState = GVRAndroidResource.StreamStates.NEW;
        this.filePath = null;
        this.resourceId = 0;
        this.assetPath = null;
        this.resourceFilePath = null;
        this.url = url;
        this.resourceType = GVRAndroidResource.ResourceType.NETWORK;
    }
'''
i got an NullPointorException below:
'''
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.File android.content.Context.getCacheDir()' on a null object reference
 at org.gearvrf.GVRAssetLoader.downloadFile(GVRAssetLoader.java:1234)
 at org.gearvrf.GVRAndroidResource.openStream(GVRAndroidResource.java:353)
 at org.gearvrf.GVRAndroidResource.getStream(GVRAndroidResource.java:291)
 at org.gearvrf.GVRAssetLoader.loadTexture(GVRAssetLoader.java:604)
 at org.gearvrf.GVRContext.loadTexture(GVRContext.java:1000)
'''
Is there an error or i should call the method in other ways?

**Comment by codeczx** [comment]
I have update the latest gearvrf and still have this problem.

**Comment by bohuang3d** [comment]
Hi @codeczx 

Something good to know to help diagnose problem,

Is the context and texture you are loading valid?

Is there a complete call stack of the exception? (Assuming there is more due to the ...)

How are you using the method? Is there a complete minimal example you can send me

Also there are some examples of usage if you search for 'new GVRAndroidResource' among the source files in 
https://github.com/gearvrf/GearVRf-Demos
 
Thanks

**Comment by liaxim** [comment]
@codeczx Are you passing ``true`` as the value of the ``enableUrlLocalCache`` parameter of the ``GVRAndroidResource`` ctor?

**Comment by codeczx** [comment]
@liaxim Yes.

**Comment by liaxim** [comment]
@codeczx The fix is in https://github.com/Samsung/GearVRf/pull/1115
It will be included in our 3.2 release which is imminent. For now you should pass false for the ``enableUrlLocalCache`` as a workaround.

**Comment by liaxim** [comment]
Fix merged.

Also updated the shapshot in the maven repo in case you are getting the framework from the maven repo. To get the latest you will need to pass the ``--refresh-dependencies`` to gradle.
