### ISSUE TITLE
Dji sdk

### ISSUE THREAD

**Issue by hrmsa** [Samsung/GearVRf#1135]
Hello.. 
I want to build an vr application and to use dji sdk
Can i build this application using the gear vr framwork and the dji sdk?

**Comment by bohuang3d** [comment]
Hi @hrmsa 

DJI has an Android sdk and GearVRF is Android. So in theory yes

In practice it depends on what you hope to achieve with GearVR. Let me know what you have in mind and I can help further

**Comment by hrmsa** [comment]
i want to build an fpv and gimbal control app the gimbal will move according to the head movement

**Comment by bohuang3d** [comment]
What is fpv? First person view?

Do you mean you want to use the head orientation reported by GearVR and to control the drone? I.e., send the orientation from GearVR to DJI sdk?

Keep in mind GearVR can only reports back head rotation, not head position.

**Comment by hrmsa** [comment]
yes it is First person view..
The drone will send the video feed and i want to make it a vr video using the gearVRF...
and about the head orientation, what about using the phone sensors ( I am using the Samsung s7 edge)

**Comment by bohuang3d** [comment]
You can start with:
https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-360video

It handles head orientation. You don't need to query the phone's sensors.

The rest is to hook up features you wish to use from DJI sdk

**Comment by hrmsa** [comment]
thank you very much for your helping..
 another question.. if I use this class (GVRTexture) the texture will be in vr mode is that right??

**Comment by bohuang3d** [comment]
'vr mode' in this context I take it you mean 360 video/photo.

Any GVRTexture would be texturemapped to a GVRSphereObject. And if the virtual camera Is set up to be at the center of the sphere, you would see the texture in a spherical 360 photo fashion, provided it's in the right format and coordinate mapping

**Comment by hrmsa** [comment]
the video feed from the dji is in surfacetexture and i want to convert this to a "side by side" view so i can see it from the gear vr... in this case can i use the GVRViewSceneObject class to pass the surfacetexture

**Comment by bohuang3d** [comment]
GVRVideoSceneObject uses either Android's default MediaPlayer or the open source ExoPlayer. See makeMediaPlayer(), makeExoPlayer(), respectively in Minimal360VideoActivity.java in the sample I linked on loading a .mp4 file from disk.

You probably want to look into the latter, as

> "ExoPlayer supports features not currently provided by MediaPlayer, including Dynamic adaptive streaming over HTTP (DASH), SmoothStreaming and Common Encryption"
https://developer.android.com/guide/topics/media/exoplayer.html

and see if it supports surfacetexture.

"Side by side" you don't have to worry. As long as you can load the video somehow onto a sphere as in the above example, GVRF takes care of side by side for you

**Comment by bohuang3d** [comment]
@hrmsa Please let me know additional help you need. Will close the issue
