### ISSUE TITLE
GL_OVR_multiview2 support has regressed

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#1138]
Not talking about apps with custom shaders. Even simple things like gvr_nonglthreadupdate do not work. Usually this is the error:

```
TextureShader::render error: GL_INVALID_OPERATION
```

If we are not going to improve the support or at least enable it for all apps that should work with it, then we would be better off removing the associated code to reduce complexity.

**Comment by liaxim** [comment]
gvr-nonglthreadupdate maybe is having problems due to the use of the GVRConsole. In any case, there is a need to communicate the actual problem better. Like if the multiview is enabled and we encounter any custom shader, just abort the app with a clear error in the log.

**Comment by roshanch** [comment]
Let me look into it.

**Comment by roshanch** [comment]
GVRConsol is using posteffect and hud_consol shader which are not modified for multiview support. We need to include #defines for posteffect shaders to work with multiview.

**Comment by thomasflynn** [comment]
ok, so, you're fixing that @roshanch?

**Comment by roshanch** [comment]
yes, I am working on it.
