### ISSUE TITLE
GVRf build fails with 'com.android.tools.build:gradle:2.3.1'

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#1144]
Updating the build tools from 2.2.3 to 2.3.1 breaks the build.

**Comment by liaxim** [comment]
Should we make the change for 3.2? I was thinking we can wait until 2.4 is released which seems pretty close (AS 2.4 is at preview 5).

**Comment by rahul27** [comment]
Android Studio prompts you to bump the build tools version when you open the framework project and most users are more likely to hit yes rather than no.

I added this to 3.2 because I thought the fix would be trivial i.e. changing the path to libgvrf.so from the exploded-aar folder to the relative path inside the framework folder. I could make the change if you like. 

If you think the fix would need to be more thought out then we could remove it from 3.2.

**Comment by liaxim** [comment]
We can try it and see how our build machines likes it. Your call.

There is also NDK v15 which I don't think worked out of the box. We might have to batch up updates to ndks, gradle plugins and the like since there are so many. Even maybe skip a step or two to keep our sanity.

**Comment by rahul27** [comment]
Fixed here https://github.com/Samsung/GearVRf/pull/1148.

Taking this issue off the 3.2 release. Will merge later.
