### ISSUE TITLE
Short back button presses can no longer be used.

### ISSUE THREAD

**Issue by JoshaMunnik** [Samsung/GearVRf#1149]
I can no longer add functionality for short back button presses. 

With 3.0.1 I was using the following code:

    @Override
    public boolean onKeyUp(int aKeyCode, KeyEvent anEvent) {
      Log.d(TAG, "onKeyUp: " + aKeyCode);
      if (((anEvent.getFlags() & KeyEvent.FLAG_CANCELED_LONG_PRESS) == 0) && !this.m_paused) {
        if (aKeyCode == KeyEvent.KEYCODE_BACK) {
          // handle short back press
          return true;
        }
      }
      return super.onKeyUp(aKeyCode, anEvent);
    }

    @Override
    protected void onPause() {
      this.m_paused = true;
      super.onPause();
    }

    @Override
    protected void onResume() {
      this.m_paused = false;
      super.onResume();
    }

This no longer works with 3.1.1 (I did not test the 3.1.0). The onKeyUp code is never called. Pressing the back button will always show the Oculus UI (independent how long it is pressed).

**Comment by liaxim** [comment]
Hi. We added a method for back key handling. Please see GVRMain.onBackPress. It lets you either handle the back key in your app or delegate it to us which means we will bring up the Oculus UI. Does this work for you?

**Comment by JoshaMunnik** [comment]
I did not check GVRMain :) But I found the method and it is working.

For others reading this topic: this method is available in 3.2 (I got error in Android Studio when using v3.1.1 of the SDK).
