### ISSUE TITLE
File not found error when building with 3.2 dependencies

### ISSUE THREAD

**Issue by JoshaMunnik** [Samsung/GearVRf#1154]
I updated my gradle files as mentioned with the 3.2 release. Everything synced and build ok within Android Studio. However upon running the application I got the following error (I added some linebreaks for readability):

    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[
     DexPathList[
       [
         zip file "/data/app/com.ultraforce.gearvr.bam-1/base.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_dependencies_apk.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_0_apk.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_1_apk.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_2_apk.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_3_apk.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_4_apk.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_5_apk.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_6_apk.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_7_apk.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_8_apk.apk", 
         zip file "/data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_9_apk.apk"
       ],
       nativeLibraryDirectories=[
         /data/app/com.ultraforce.gearvr.bam-1/lib/arm64, 
         /data/app/com.ultraforce.gearvr.bam-1/base.apk!/lib/arm64-v8a,
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, 
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a, 
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a, 
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a, 
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a, 
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a, 
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a, 
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a, 
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a, 
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a, 
         /data/app/com.ultraforce.gearvr.bam-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a, 
         /system/lib64, 
         /vendor/lib64
       ]
     ]
    ] couldn't find "libgvrf.so"

I noticed it is only looking in the 64 bit folders. Upon inspecting the APK I saw that there is no _libgvrf.so_ in the 64 bit folder only in the _lib\armeabi-v7a_ folder.

Tested the above on a Samsung S7.

(for now I went back to using the .aar files which work ok)

**Comment by JoshaMunnik** [comment]
Forgot to mention, I'm testing with an Samsung S7.

**Comment by liaxim** [comment]
Hi,

This is probably because of the 64bit binaries Daydream has. Please use this gradle file as reference how to add GVRf support to your project: https://github.com/gearvrf/GearVRf-Demos/blob/release_v3.2/template/GVRFApplication/app/build.gradle.

Note the packagingOptions.

**Comment by liaxim** [comment]
@JoshaMunnik Let us know if you still have problems. Closing this for now.
