### ISSUE TITLE
3.2 Daydream controller support

### ISSUE THREAD

**Issue by felislynx-silae** [Samsung/GearVRf#1156]
Since 3.2 is released could you explain how Daydream controller is supported (i couldn't find any reference to this topic)? As far as i know, to release app to daydream we need not only controller to work but also have whole controller model in scene (like in unity/unreal apps).

**Comment by rahul27** [comment]
@felislynx-silae Here is a GearVRf daydream sample that makes use of the daydream controller:

https://github.com/rahul27/GearVRf-Demos/tree/daydream-sample/gvr-daydream

As for the controller model, you will find it here:

https://github.com/googlevr/gvr-android-sdk/tree/master/assets/controller

**Comment by felislynx-silae** [comment]
@rahul27 UX-C1 [REQ](https://developers.google.com/vr/distribute/daydream/design-requirements) is not satisfied by demo. So i assume that it's up to developers to create substitute to Unreal/Unity asset (with all behaviours)?

**Comment by niusounds** [comment]
I created a sample project for Daydream controller. It renders controller model in scene with applying arm model.
https://github.com/ejeinc/GearVRf_DaydreamController

**Comment by rahul27** [comment]
@niusounds Thanks for that. 

I just tried your sample and the GvrArmModel works great.

**Comment by felislynx-silae** [comment]
@niusounds it's awesome work! Under which licence will you publish your code?

**Comment by niusounds** [comment]
@felislynx-silae I would like to treat my code as same as a [GearVRf-Demos](https://github.com/gearvrf/GearVRf-Demos).

**Comment by felislynx-silae** [comment]
@rahul27 After i've acquired GearController and looked into gvr-controller demo. Is there any plan to add Daydream controller support like one in gvr-controller demo (to unify approach for 2 controllers and "eye pointing"). And i see that gear controller assets are also missing in framework or should we extract them from unity/unreal packages?

**Comment by liaxim** [comment]
It makes sense to provide some abstraction for the different controllers and it should happen. One day.
For the assets please use those from Unity.

**Comment by felislynx-silae** [comment]
As from my perspective this issue can be closed. But i believe that there should be created task to create the same level of abstraction for Daydream controller like for Gear controller.

**Comment by thomasflynn** [comment]
We're a bit short-staffed at the moment (but we are hiring ;-), but yes, a proper abstraction is in the plans.
