### ISSUE TITLE
Manipulating cameraRig to rotate by specified degrees

### ISSUE THREAD

**Issue by sam16222** [Samsung/GearVRf#1157]
Hello. I want to disable the camera rigs dependency on the sensor data and make the movement manual. That is I want to manually rotate the camera and make it point to a specific location. Example I want to rotate the camera 45 degrees every 5 seconds.

**Comment by liaxim** [comment]
1."freeze" the camera rig by using ``GVRCameraRig.setCameraRigType(GVRCameraRigType.Freeze.ID)``
2. get the head transform of the camera rig via ``GVRCameraRig.getHeadTransform()``
3. apply the rotation you want to the transfrom from 2.

**Comment by sam16222** [comment]
After getting the transform, I am trying to rotate using rotateByAxis(45,0,1,0) but it's not rotating. Is there something missing here? Also The camera did get frozen but there's a small stutter as the phone moves. I am using the phone in developer mode so that might be issue, but I still can't get the rig to rotate.

**Comment by liaxim** [comment]
For the stutter there is the https://github.com/Samsung/GearVRf/pull/1164 pull request.

**Comment by liaxim** [comment]
My bad about 2. Use ``GVRCameraRig.getTransform()`` and apply the rotation to this transform. The FREEZE case is special so headTransform modifications are ignored.

**Comment by sam16222** [comment]
Okay so the transform issue is resolved. When will the latest code be merged with the main branch in order to resolve the freeze issue?

**Comment by sam16222** [comment]
Okay Thank you. I have manually built the framework after making the changes.
