### ISSUE TITLE
How to render blurred overlay object?

### ISSUE THREAD

**Issue by niusounds** [Samsung/GearVRf#1158]
I would like to create an overlay dialog which has transparent background with blurring like this:
![](https://d2ujflorbtfzji.cloudfront.net/package-screenshot/26b8f251-16f3-4ee3-b257-15eb0e1020d6_scaled.jpg)
https://www.assetstore.unity3d.com/jp/#!/content/42388

Does anyone have codes or tutorials for this?

**Comment by bohuang3d** [comment]
@niusounds 

There is a blur sample to get started with
https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-blurfilter

**Comment by niusounds** [comment]
Thank you for response.

But how to get color information which come from behind of object? In above example image, transparent plane's texture will be updated when background objects are changed or camera rig is moved.

**Comment by bohuang3d** [comment]
@niusounds 

You can use the render to texture feature with classes GVRRenderTexture, GVRRenderTarget.

For example, in
https://github.com/gearvrf/GearVRf-Demos/blob/master/gvr-blurfilter/app/src/main/java/org/gearvrf/blurfilter/TestMain.java
createBlurScene()
createBlurTexture()

Except you render the scene to a render texture without blurring. Then as you draw the quad in front, the shader of this quad would have the render texture corresponding to the background scene as a member. Then you can do a blur operation on the intersected area of the render texture.

**Comment by niusounds** [comment]
@bohuang3d 

I will try it. Thank you!
