### ISSUE TITLE
Can I set byteBuffer into GVRSceneObject?

### ISSUE THREAD

**Issue by hehawjq** [Samsung/GearVRf#1168]
Hey! How can i set byteBuffer into GVRSceneObject?

**Comment by bohuang3d** [comment]
@hehawjq Can you tell me what you are trying t do. What is in the ByteBuffer

**Comment by hehawjq** [comment]
byteBuffer is video yuv data,i decode video each frame by myself and want to take byteBuffer to render in GVR.

**Comment by bohuang3d** [comment]
@hehawjq this was answered to you in https://github.com/Samsung/GearVRf/issues/1134

Let me know if need further help or will close. Thanks

**Comment by hehawjq** [comment]
@bohuang3d Thanks. It works for me.
