### ISSUE TITLE
Could not find method assembleDebug() on project ':platformsdk_support'

### ISSUE THREAD

**Issue by TimecodePete** [Samsung/GearVRf#1171]
I have been getting the following error when attempting to build the platformsdk_support library.
```
* Where:
Build file 'E:\SDKs\GearVRf\GVRf\Extensions\platformsdk_support\build.gradle' line: 83

* What went wrong:
A problem occurred evaluating project ':platformsdk_support'.
> Could not find method assembleDebug() for arguments [build_8zx34rdzldl7yc1bjhlnps51l$_run_closure4@57dd041f] on project ':platformsdk_support' of type org.gradle.api.Project.
```
I've been following the instructions described here: [https://github.com/Samsung/GearVRf/wiki/Entitlement-Check-using-GVRF](https://github.com/Samsung/GearVRf/wiki/Entitlement-Check-using-GVRF)

I'm running Windows 10 Enterprise Edition.
OVR Platform SDK 1.8.0

I have been able to build the library by removing lines 83 to 100 from platformsdk_support/build.gradle
and moving the .aar files by hand to the libs directory, so I'm guessing something in there is not particularly happy with my setup...

**Comment by liaxim** [comment]
I have a change that fixes the build. Let us know if you experience any problems with the entitlement check. The code is straightforward but setting up everything so the check works can be finicky.

**Comment by TimecodePete** [comment]
@liaxim Thanks for the fix :)
I have tested it on my end and the build seems to have run successfully!

As far as I can tell, the entitlement is working. I have successfully uploaded the app to the Alpha channel on the Oculus Store and it's not crashing when I install it on devices... I'm hoping that means it's working.

That said on the devices for which I have create osig files, when running a debug build of the App, the entitlement check does not complete. The app does run successfully though :)

I see the following error:
```
W/System.err: android.content.pm.PackageManager$NameNotFoundException: com.oculus.shimwow
W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:201)
W/System.err:     at org.gearvrf.PlatformEntitlementCheck.create(Native Method)
W/System.err:     at org.gearvrf.PlatformEntitlementCheck.start(PlatformEntitlementCheck.java:61)
W/System.err:     at com.timecodelab.syncvr.player.vr.GearVrFVideoPlayer.performEntitlementCheck(GearVrFVideoPlayer.java:121)
W/System.err:     at com.timecodelab.syncvr.player.vr.GearVrFVideoPlayer.onInit(GearVrFVideoPlayer.java:116)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
W/System.err:     at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
W/System.err:     at org.gearvrf.GVRViewManager$1$1.run(GVRViewManager.java:330)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:158)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
```

I realize this is not much to go on, but do you think it's likely to be something in my code causing that error? Should I create a new Issue?

**Comment by liaxim** [comment]
We had pretty long threads about the entitlement check in the past. This is exactly where everybody gets stuck. See https://github.com/Samsung/GearVRf/pull/818 and https://github.com/Samsung/GearVRf/issues/808.

Can you please try first going to the Oculus home and launching the app from there with developer mode off?

**Comment by liaxim** [comment]
We tried to capture the process in the wiki: https://github.com/Samsung/GearVRf/wiki/Entitlement-Check-using-GVRF

Excerpts from the threads that are most likely important:

- So I re-did the whole thing. Even though my new submission checked out according to the validator I was getting -1 too. This is how I got it to work. Run the phone not in developer mode, dock, make sure you get to the Oculus home. Launch the app then (debug build now) but still not in developer mode. Dock and check the result of the query - this is when it started working for me. Afterwards it worked in developer mode too. Some steps might be optional but this is what I did. There is nothing we can do on our side to improve this very finicky process. We will get it to work together tomorrow. I used the 1.8.0 platform sdk but based on my past experience 1.6 and 1.7 work fine too.

- https://forums.oculus.com/developer/discussion/40097/platform-sdk-1-5-0-cant-initialize-platform

- Hi, could you share the full logcat output? I have seen this exception before but it got cleared after going to Oculus home then launching the app with developer mode off from the regular android launcher.

**Comment by TimecodePete** [comment]
Thanks for the information!

Messed around with it for a bit, uninstalling then reinstalling then running from the Oculus Store and finally in developper mode 2-3 times. 4th time was the charm, now I can build and run in debug mode and I get a success on the entitlement check.

Thanks a lot for your help! Let me know if you still want the logcat output, I have it saved locally.

**Comment by liaxim** [comment]
Sure, going through the logs can never hurt. Thanks.

**Comment by TimecodePete** [comment]
Here it is :)

[logcat04252017.txt](https://github.com/Samsung/GearVRf/files/956648/logcat04252017.txt)

**Comment by thomasflynn** [comment]
Hi @TimecodePete.  Could you email me at tom.flynn@samsung.com?  I have a few questions for you.
