### ISSUE TITLE
Stencil test fails

### ISSUE THREAD

**Issue by NolaDonato** [Samsung/GearVRf#1181]
The stencil buffer test in GearVRF-Tests/framework-tests/StencilTests fails the screen shot comparison. The issue appears to be that, although the visual display honors the stencil buffer, the screen capture code appears not to.  Did this test ever work? If not then I think stencil support needs to be added to screen capture.

**Comment by liaxim** [comment]
Yes, the test used to work. Will look into it.

**Comment by liaxim** [comment]
Fix: https://github.com/Samsung/GearVRf/pull/1422
