### ISSUE TITLE
GVRExternalScene problems loading new scene

### ISSUE THREAD

**Issue by mwitchwilliams** [Samsung/GearVRf#1190]
GVRExtenalScene is not removing the previous scene despite setting the replace parameter to true, and it is crashing if I don't attach it to the root.

Below is the code being used when I receive an X3D command in the &lt;Anchor&gt; tag to go to a new X3D page.

_GVRExternalScene gvrExternalScene = new GVRExternalScene(gvrContext, url, true);
root.attachComponent( gvrExternalScene );_

If I attach gvrExternalScene to the root, I get the new scene, but the previous scene is still there.  If I don't attach gvrExternalScene, it crashes calling AssetRequest (because the first parameter is null).

**Comment by NolaDonato** [comment]
I will work on it with you this afternoon.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by mwitchwilliams** [comment]
This now works and can be closed.
There is a new issue with lights that has been documented, but the scene is loading as expected.
The resolution is that GVRExternalScene needs to be attached to a new GVRSceneObject, not root.
