### ISSUE TITLE
Programmatically Detecting Whether Oculus Service Developer Mode is On or Not

### ISSUE THREAD

**Issue by lxc-xx** [Samsung/GearVRf#1195]
Hi,

I am developing an app that disallows users to run in developer mode. I wonder if I can do it within the GearVRf. There should be a property that flags whether the developer mode is on or not.

Thanks,
L

**Comment by liaxim** [comment]
Hi. Assuming you are talking about the GearVR developer mode (https://developer3.oculus.com/documentation/mobilesdk/latest/concepts/mobile-troublesh-device-run-app-outside/). There is no public API to my knowledge. You may check whether the phone is docked or not instead. It is not the same but it may work. We expose GVRActivity.getConfigurationManager().isHmtConnected() to determine the status.

**Comment by lxc-xx** [comment]
Thanks. The isHmtConnected might work for me now. 

Is the gearvr-developer-mode API is unavailable from Oculus side or it is just not included in GVRF now?

**Comment by liaxim** [comment]
There is nothing from Oculus.

**Comment by lxc-xx** [comment]
Got it. Thanks!
