### ISSUE TITLE
Capturing Frames from GVRCameraSceneObject

### ISSUE THREAD

**Issue by lxc-xx** [Samsung/GearVRf#1198]
I am trying to capture frames from the passthrough camera. But, it seems the GVRCameraSceneObject only provides the functionality of previewing. The Camera object of the GVRCameraSceneObject is private. Did I miss anything or is there any workaround for this?

Thanks,
L

**Comment by liaxim** [comment]
@lxc-xx If you want to have access to the Camera object then you can use the ``public GVRCameraSceneObject(GVRContext gvrContext, GVRMesh mesh, Camera camera)`` constructor and pass the camera object you already have. Though it is deprecated it is still there.

**Comment by lxc-xx** [comment]
Thanks!
