### ISSUE TITLE
Loss Quality using loadFutureTexture

### ISSUE THREAD

**Issue by snti** [Samsung/GearVRf#1199]
Hello guys

I have a problem about quality when I load a lot of textures in a bucle with the method gvrContext.loadFutureTexture.
My idea is load some textures in a bucle to make the app faster.
Each texture is used as a skybox, and the user can change the skybox in real time. 
But the last textures in the list have low quality.

Any idea?

Regards!

**Comment by thomasflynn** [comment]
It sounds like you're running low on memory.  adding largeHeap="true" to your AndroidManifest.xml will increase your max heap size from 256M to 512M.  That's a short-term work-around at least.  Keep in mind, for pngs and jpegs, they get decompressed in RAM and the footprint will be Width x Height x 4 or Width x Height x 3 respectively.  Multiply that by the number of images you're loading and I wouldn't be suprised if you're taking a lot more memory than you though :)

The better thing to do, if you have the control to do so, is to compress the textures to ASTC or ETC2 and load those in.  They perform better on the GPU and don't get decompressed.

**Comment by thomasflynn** [comment]
sorry, meant to include this:  link to the AndroidManifest flags:
https://developer.android.com/guide/topics/manifest/application-element.html

**Comment by snti** [comment]
Thanks @thomasflynn finally I reduce the image size to 4000x200 like the skyboxes of gvr-modelviewer2 example and works very well.

Thanks!

**Comment by liaxim** [comment]
@thomasflynn Some time ago we added the largeHeap to the framework's manifest so all our apps by default get that. There was something about gvr-video using up too much memory.

@snti We are planning to remove loadFutureTexture in the near future.
