### ISSUE TITLE
GVRRenderData.setAlphaToCoverage() blending background over opaque objects

### ISSUE THREAD

**Issue by mwitchwilliams** [Samsung/GearVRf#1203]
GVRRenderData.setAlphaToCoverage(true) is blending the background color over opaque object.
In the X3D file, if the meshes with png texture maps with transparencies are listed before the opaque object, the background color is blended with the transparency when it is over an opaque object.

The demo contains 4 animated planes containing texture maps with transparency.  Two of the objects come before the opaque object and these seem to be wrong.  The screen shots show what happens when there is a red, green and blue background.  The two objects following the opaque object in the X3D file seems ok.

To run this demo, in X3Dobject.java, add:
 _gvrRenderData.setAlphaToCoverage(true);_
after the GVRRenderData() is constructed in the &lt;Shape&gt; node.

**Two transparent texture maps:**
![round_icon_shadow](https://cloud.githubusercontent.com/assets/18128830/26257989/9a050c62-3c77-11e7-8261-8f294645d0c5.png)
![round_half_icon_shadow](https://cloud.githubusercontent.com/assets/18128830/26257993/9cb2a2d0-3c77-11e7-9ebd-2d95a4711e8f.png)

**X3D zip file, contains the X3D file plus texture maps.**
[x3d_files.zip](https://github.com/Samsung/GearVRf/files/1014983/x3d_files.zip)

**Screen Shots with red, green and blue backgrounds.**
![screenshot_20170519-090159](https://cloud.githubusercontent.com/assets/18128830/26258483/a76c8e1e-3c79-11e7-864a-279ef1752568.png)

![screenshot_20170519-090408](https://cloud.githubusercontent.com/assets/18128830/26257976/8b7ded8a-3c77-11e7-99cd-40ba0df41a6d.png)
![screenshot_20170519-092950](https://cloud.githubusercontent.com/assets/18128830/26257979/8daa0a12-3c77-11e7-98ce-59a7ee7bfd95.png)

**Comment by mwitchwilliams** [comment]
The issue seems related to the position of the camera.  New (as yet not merged) code enables the camera to be at other positions besides (0, 0, 0).  At (0, 0, 0), it seems to work, but at (0, 0, 8) as in the demo, the problems occur.

**Comment by mwitchwilliams** [comment]
Still an active bug.
Investigating renderdata.cpp for algorithm of sorting object based on z-distance from camera versus actual distance [ sqrt(x*x + y*y + z*z) from camera ].

**Comment by mwitchwilliams** [comment]
Issue appears to be in renderer.cpp, Renderer::frustum_cull().

The order is determined by the distance from the camera to the center of each object using these two statements:
```
            glm::vec4 difference = transformed_sphere_center - position;
            float distance = glm::dot(difference, difference);
```

In this scene below, the _Back Panel_ is at (0, 0, -8.25) for a distance of **67.552**  [note that while the camera is at (0, 0, 0), the camera position value is approximately (0, 0, -0.031)
The _Upper Transparency_ is at (2, 2, -8) for a distance of **71.505**.
The _Lower Transparency_ is at (-2, -2, -7) for a distance of **56.567**.

The actual front-to-back order is: _Lower Transparency, Upper Transparency, Back Panel_.
However, GearVR's rendering order for transparencies uses distance formula.  which produces this front-to-back order: _Lower Transparency, Back Panel, Upper Transparency_.  Thus, rendering transparencies is not in the correct order.  Will continue to correct.

Test case: [Render order issue.zip](https://github.com/Samsung/GearVRf/files/1129376/Render.order.issue.zip)

![renderorder01_screenshot](https://user-images.githubusercontent.com/18128830/27934355-2c6be74e-625a-11e7-9d41-8b206744ac57.png)

**Comment by roshanch** [comment]
@mwitchwilliams We have found the issue and fix too. I will talk with @NolaDonato today

**Comment by mwitchwilliams** [comment]
I have a fix provided there is no scaling.  In renderer.cpp, I multiply the object's matrix by its inverse rotation, then compare z-values (actually, square the z value so only positive numbers for comparison).  Unfortunately, when scaling, this won't work since the upper 3x3 matrix includes scaling and rotation, so I am investigating transform.cpp and renderer.cpp to get the global translation and rotation.
Let's discuss to review what you have.

**Comment by sushantojal** [comment]
While parsing the x3d file, are separate and unique scene objects created for every object in the file, or are they all just one scene object with separate meshes?

**Comment by mwitchwilliams** [comment]
X3D creates a scene where each object is a separate and unique GVRSceneObject with its own GVRTransform, GVRMesh, etc.  For example, in the above image, there would be 3 GVRSceneObjects: the opaque mesh textured with "MarkerOne", the lower left mesh and the upper right mesh.

**Comment by liaxim** [comment]
@mwitchwilliams Are you still working on this issue on your side?

**Comment by mwitchwilliams** [comment]
I retested and the issue is much improved, though the non-transparent portions of the image (which should be identical below) blends the background color.  The rest of this issue is superseded in offline discussions so this can be closed.  Seems addressed in Pull Request  https://github.com/Samsung/GearVRf/pull/1341
**Retest results below:**
The order in the X3D file of the 3 meshes:
- Upper right partially transparent mesh at (2, 2, -1)
- Lower right partially transparent mesh at (-2, -2, 0)
- Opaque "Marker ONE" mesh at (0, 0, -1.25)

![issue1203screenshot](https://user-images.githubusercontent.com/18128830/30221669-06602564-9479-11e7-8d56-819a759768cf.png)

At least we are rendering this consist now, though not perfect:
![screenshot_20170908-094112](https://user-images.githubusercontent.com/18128830/30221985-48bcb066-947a-11e7-9ad6-25fb8e5303f6.png)

**Comment by liaxim** [comment]
@mwitchwilliams Ok then, closing this. You may want to open more specific issues for the rest.
