### ISSUE TITLE
Issue with Bitmap transparence 

### ISSUE THREAD

**Issue by snti** [Samsung/GearVRf#1204]
I have an image with a transparent backgrdound. When I try to put this image over the skybox sometimes the background turns in black.

For example:
![image](https://cloud.githubusercontent.com/assets/16910904/26271323/a3448b5a-3cda-11e7-82e6-082f7c69749d.png)

I used two methods to load the image, one is loadBitmap and the another is with Future<GVRTexture>

Any idea?

Regards!

**Comment by liaxim** [comment]
Hi. Let us know how does this work for you: ``yourSceneObject.getRenderData().setRenderingOrder(GVRRenderingOrder.TRANSPARENT);``

**Comment by snti** [comment]
Apparently works fine.

Regards!
