### ISSUE TITLE
Can not show textsence

### ISSUE THREAD

**Issue by miraclehwan** [Samsung/GearVRf#1205]
Hi, guys!
I have a little  problem.
I build 'gvr-360video'. It is demo project.
And I added textsence(GVRTextViewSceneObject) but I can not show textsence(GVRTextViewSceneObject).
If you know something, please talk to me.

**Comment by mwitchwilliams** [comment]
Greetings,
Just wanted to get some clarification, are you working with GVRTextViewSceneObject when you mention 'textscene'?  I ask because I am actively working with GVRTextViewSceneObject.
Mitch

**Comment by miraclehwan** [comment]
Dear Mitch
Yes, I working GVRTextViewSceneObject.
but can not show GVRTextViewSceneObject in 'gvr-360video' demo project.
Do you know how to show GVRTextViewSceneObject in 'gvr-360video' demo project?
This is my GVRTextViewSceneObject code.

oninit{
        GVRSceneObject title = makeTitle(gvrContext);
        scene.addSceneObject(title);
}

 private GVRTextViewSceneObject makeTitle(GVRContext context){
        GVRTextViewSceneObject title = new GVRTextViewSceneObject(context, 6, 2, "Private Theater");
        GVRRenderData renderdata = title.getRenderData();
        renderdata.setAlphaBlend(true);
        title.attachComponent(new GVRMeshCollider(context, true));
        title.getTransform().setPosition(0.0f, 0.0f, -3.0f);
        title.setTextColor(Color.YELLOW);
        title.setGravity(Gravity.CENTER);
        title.setBackgroundColor(Color.argb((int) 0.5f, 1, 0, 0));
        return title;
}

**Comment by thomasflynn** [comment]
off-hand, this looks like it should work.  any thoughts @NolaDonato ?

**Comment by miraclehwan** [comment]
I want look like below image.

<img src="https://cloud.githubusercontent.com/assets/20110093/26353902/76e267aa-3ffd-11e7-85a3-de27a268ef93.png">

**Comment by liaxim** [comment]
@miraclehwan Color.argb takes values from 0 to 255. You could just use ``title.setBackgroundColor(Color.BLUE)`` instead.

**Comment by thomasflynn** [comment]
found the bug in the sample.  the scale is applied to the sphere, not the video.  we retrieve the mesh from the sphere to help create the VideoSceneObject, but that mesh has the original vertices of the default sphere.  applying the scale to the VideoSceneObject fixes the problem.  Will do a pull-request for this shortly.  

in short, you should add:
 video.getTransform().setScale(100f, 100f, 100f);
after the VideoSceneObject is created.  And yes, for setBackgroundColor(), you can just use Color.BLUE

**Comment by thomasflynn** [comment]
see: https://github.com/gearvrf/GearVRf-Demos/pull/450

**Comment by miraclehwan** [comment]
@thomasflynn Thank you for reply.
but I still have a problem.
I want show GVRTextViewSceneObject but can not show.
This is my code.

> public class Minimal360Video extends GVRMain
{
    Minimal360Video(GVRVideoSceneObjectPlayer<?> player) {
        mPlayer = player;
    }

    /** Called when the activity is first created. */
    @Override
    public void onInit(GVRContext gvrContext) {
        GVRScene scene = gvrContext.getMainScene();

        // create sphere / mesh
        GVRSphereSceneObject sphere = new GVRSphereSceneObject(gvrContext, 72, 144, false);
        GVRMesh mesh = sphere.getRenderData().getMesh();


        // create video scene
        GVRVideoSceneObject video = new GVRVideoSceneObject( gvrContext, mesh, mPlayer, GVRVideoType.MONO );
        video.getTransform().setScale(100f, 100f, 100f);
        video.setName( "video" );

        // apply video to scene
        scene.addSceneObject( video );


        GVRSceneObject title = makeTitle(gvrContext);
        scene.addSceneObject(title);

    }
    private GVRTextViewSceneObject makeTitle(GVRContext context){
        GVRTextViewSceneObject title = new GVRTextViewSceneObject(context, 6, 2, "Private Theater");
        GVRRenderData renderdata = title.getRenderData();
        renderdata.setAlphaBlend(true);
        title.attachComponent(new GVRMeshCollider(context, true));
        title.getTransform().setPosition(0.0f, 0.0f, -3.0f);
        title.setTextColor(Color.YELLOW);
        title.setGravity(Gravity.CENTER);
        title.setBackgroundColor(Color.BLUE);
        title.getRenderData().setRenderingOrder(1);
        title.getRenderData().setDepthTest(false);
        title.getRenderData().setCullFace(GVRRenderPass.GVRCullFaceEnum.Front);
        return title;
    }
    private final GVRVideoSceneObjectPlayer<?> mPlayer;
}

**Comment by thomasflynn** [comment]
remove the calls to setRenderingOrder() and setCullFace().

**Comment by miraclehwan** [comment]
@thomasflynn Wow!!! Thank you for your kind help.
