### ISSUE TITLE
Picking not aligned correctly when camera's z not at origin

### ISSUE THREAD

**Issue by mwitchwilliams** [Samsung/GearVRf#1214]
X3D allows cameras to be in locations other than the origin.
Prior to his leaving, Rahul suggested I set GVRCursorController's setOrigin() to the location of the camera.
However, the picking is not aligning correctly.

I have a code demo at https://github.com/mwitchwilliams/GearVRf/tree/pickCursorCtllrIssue.
I zipped an X3D file where the camera is at (-3, 0, -3).  The cylinder should rotate when over the orange sphere.  However, it rotates when over the area between the sphere and the red plane.

To run the demo, besides the code above, change X3DparserScript.java to set the file name to 'pickTest_CameraPos.x3d'.

[pickTest_CameraPos.zip](https://github.com/Samsung/GearVRf/files/1030304/pickTest_CameraPos.zip)

![screenshot_20170525-141941](https://cloud.githubusercontent.com/assets/18128830/26471994/0bb21680-4159-11e7-945d-b58141857ca4.png)

**Comment by mwitchwilliams** [comment]
Without the bringing in the code, it can be simulated by changing GVRCursorController.setOrigin(-3, 0, -3)
and then set:
mainCameraRig.getTransform().setPosition(-3.0f, 0.0f, -3.0f);

**Comment by liaxim** [comment]
@mwitchwilliams https://github.com/Samsung/GearVRf/pull/1332 has been merged. Could you please confirm this issue has been fixed. Thanks.

**Comment by mwitchwilliams** [comment]
test3d, looks good.
