### ISSUE TITLE
Question/ How to remove or change the GearVR Logo ?

### ISSUE THREAD

**Issue by miraclehwan** [Samsung/GearVRf#1216]
How to remove or change the GearVR Logo?
<img src="https://cloud.githubusercontent.com/assets/20110093/26549778/95be01b8-44b5-11e7-92d8-c31f2d93d16a.png">

**Comment by snti** [comment]
Hi @miraclehwan, for remove the Logo you need change the value to false in this flag "showLoadingIcon" in the gvr.xml

Regards!

**Comment by liaxim** [comment]
@miraclehwan There is also ``GVRMain.getSplashMode`` which lets you turn off the splash screen too. To change the image take a look at ``GVRMain.getSplashTexture``. If you want to customize further there is ``GVRMain.getSplashMesh`` and ``GVRMain.getSplashShader``.

**Comment by miraclehwan** [comment]
@liaxim Thank you for your reply.
Could I get a sample code?? I don't know how to setSplash....

**Comment by miraclehwan** [comment]
I find it!!!
