### ISSUE TITLE
Question / How to get a permission?

### ISSUE THREAD

**Issue by miraclehwan** [Samsung/GearVRf#1217]
hi, guys
I want to get a permission(READ_EXTERNAL_STORAGE).
How to use a dialog(popup) about permission??
Please let me know.

**Comment by liaxim** [comment]
@miraclehwan Hi. You do it the usual way. Follow the instructions from https://developer.android.com/training/permissions/requesting.html. There is a platform service that intercepts the request and shows a VR variant of the prompt. I just verified it this morning.

You will need to add the com.android.support:appcompat-v7 library to your project. See https://developer.android.com/topic/libraries/support-library/packages.html.

**Comment by miraclehwan** [comment]
@liaxim Thank you for reply.
I saw the #467 . 
I can use gvr-events and gvr-renderableview samples. but I want to another way. 
Do you know another way?

**Comment by thomasflynn** [comment]
i think you missed a word in your question..."but I want to ____<what>___ another way".

**Comment by miraclehwan** [comment]
@thomasflynn Sorry.. I don't speak English well.
Is there another way to solve the problem here??

**Comment by liaxim** [comment]
@miraclehwan We recently added runtime permissions request to our automated tests. See https://github.com/gearvrf/GearVRf-Tests/pull/90 for reference.

**Comment by miraclehwan** [comment]
Thanks for your comment~(^_^)

**Comment by miraclehwan** [comment]
@liaxim I saw [gearvrf/GearVRf-Tests#90](https://github.com/gearvrf/GearVRf-Tests/pull/90) so I used [gearvrf/GearVRf-Tests#90](https://github.com/gearvrf/GearVRf-Tests/pull/90) in my project. 
but my app is still crashing. 
Could you check my code please??


<img src="https://cloud.githubusercontent.com/assets/20110093/26706673/2a8ed364-477a-11e7-8dd0-33130a6f4dc4.png">
<img src="https://cloud.githubusercontent.com/assets/20110093/26706677/387513a8-477a-11e7-901d-ae313eade849.png">

**Comment by liaxim** [comment]
Attaching a diff for the changes I made to MainActivity.java: [diff.txt](https://github.com/Samsung/GearVRf/files/1048188/diff.txt); combined the two separate read and write requests into one.

Btw, you are missing the vr_only tag from your manifest. Diff: [diff2.txt](https://github.com/Samsung/GearVRf/files/1048194/diff2.txt)

**Comment by miraclehwan** [comment]
@liaxim 
Thanks for your comment.
If do you have another way, Please Could you let me know??
Thank you so much. 👍

**Comment by liaxim** [comment]
@miraclehwan If you are referring to another way of requesting permissions at runtime - no, I don't think there is another way.

**Comment by miraclehwan** [comment]
@liaxim 
appreciate your comment in everyday!!
