### ISSUE TITLE
Camera Resolution Locked By "fast-fps-mode"?

### ISSUE THREAD

**Issue by lxc-xx** [Samsung/GearVRf#1225]
I was trying to get lower resolution frames from camera's onPreviewFrame callback for my QR code detection component. But I found simply setting the camera's parameter does not work.

It seems that, in the GVRCameraSceneObject, the "params.set("fast-fps-mode", fpsMode);" makes all the following resolution settings invalid. In the source, there is a code block of setting resolution commented out. How is the "fast-fps-mode' setting related to the camera resolution?

Now, I just deleted the the 'fast-fps-mode' code in the gearvrf. I did get the lower resolution, but not sure how enabling/disabling this setting affects the app.

Hardware: Galaxy S6

**Comment by lxc-xx** [comment]
Another observation.
After deleting the 'fast-fps-mode', I got lots of log like this,
`E/BufferQueueProducer: [unnamed-12945-0] dequeueBuffer: min undequeued buffer count (2) exceeded (dequeued=7 undequeued=1)`

**Comment by liaxim** [comment]
fast-fps-mode is there so it gives you more fps when you use the camera passthrough. I guess it has its own limitations. If you don't care about getting the highest possible fps out of the camera, then don't worry about removing it.

**Comment by lxc-xx** [comment]
Thanks :)
