### ISSUE TITLE
How to render objects independent of Z distance?

### ISSUE THREAD

**Issue by sam16222** [Samsung/GearVRf#1228]
I am rendering a 360 video and would like to add objects to the environment. The spherical mesh has a radius of 1.0 and if I render text within that distance, it appears blurry. Any text outside is understandably hidden. Is there a way to render text independent of the object distance from the camera?

**Comment by liaxim** [comment]
Hi. You could scale the mesh by using GVRSceneObject.getTransform().setScale(x, y, z). If you want the text to be always on top of everything else then use GVRSceneObject.getRenderData().setRenderingOrder(GVRRenderingOrder.OVERLAY).

**Comment by thomasflynn** [comment]
agreed.  my first instinct was to scale up the sphere.  you can look at the current version of gvr-360video in master for an example.  otherwise, setting the RenderingOrder to OVERLAY and also disabling depth test with getRenderData().setDepthTest(false); would do the job.

**Comment by sam16222** [comment]
I have tried using setDepthTest(false) but the views did not merge in the VR headset. Is there a reason that would happen? Scaling worked though. Thanks!

**Comment by liaxim** [comment]
@sam16222 Not sure what do you mean by "views did not merge". Are you seeing double-images in the headset? Maybe you could attach a screenshot? Thanks.

**Comment by thomasflynn** [comment]
My interpretation was that of convergence.  The effect where you put your finger in front of your nose, but look at something further away and you end up seeing two copies of your fingers.  If his sphere is 1 meter in diameter and he has text big enough and close enough to be readable inside of that,  it could be too close to converge on the text and the sphere at the same time.

**Comment by Cyganieszka** [comment]
I'm facing same problem now. I want to display "Pause" on paused 360 3D video. Text is ok when displayed on black screen, but when background is video, it's extremely difficult to focus sight on text. 
video sphere code:
`
        GVRSphereSceneObject sphere = new GVRSphereSceneObject(getContext(), 72, 144, false);
        GVRMesh mesh = sphere.getRenderData().getMesh();
        sphere.getTransform().setScale(300f, 300f, 300f);
        sphere.getTransform().setPosition(0, 0, 0);
        video = new GVRVideoSceneObject(getContext(), mesh, player, GVRVideoSceneObject.GVRVideoType.VERTICAL_STEREO );
        video.getTransform().setRotation(0.7071f,0,-0.7071f,0);
        video.setName( "video" );`

pause button code:
` 
pauseButton = new GVRTextViewSceneObject(getContext(), 100, 24, "Paused");
        pauseButton.setTextSize(12.0f);
        pauseButton.setTextColor(Color.WHITE);
        pauseButton.setGravity(Gravity.CENTER);
        pauseButton.getRenderData().getMaterial().setOpacity(0f);
        pauseButton.getTransform().setPosition(0, 0, -90);
        pauseButton.getRenderData().setDepthTest(false);
        pauseButton.getRenderData().setRenderingOrder(100000);`

Sam someone give me a hint how to tune parameters / change something to make pause text sharp?

**Comment by liaxim** [comment]
@Cyganieszka You can try putting it at a distance similar to the sphere radius: ``pauseButton.getTransform().setPosition(0, 0, -300)``.

I am not sure you will see the text at all with ``setOpacity(0f)``.

Please use ``setRenderingOrder(GVRRenderingOrder.OVERLAY)`` instead of hard-coded values.

**Comment by liaxim** [comment]
@Cyganieszka Do you still experience problems? Can we close this issue?

**Comment by liaxim** [comment]
@Cyganieszka Closing for now. You can always reopen in case you have something for us.
