### ISSUE TITLE
Problem on GVRTextViewSceneObject

### ISSUE THREAD

**Issue by nathan-almeida** [Samsung/GearVRf#123]
When we try to create more than 1 GVRTextViewSceneObject, the scene objects start flickering after moving head.

This even happen in the sample gvrtextviewsample, after creating another GVRTextViewSceneObject

**Comment by chenchao1407** [comment]
I will take a look at that later. 

Do you mind sending your test sample to me? My email address is c.chen@samsung.com

**Comment by JonShemitz** [comment]
Yes, please do send along test code - I did a quick smoke test, and saw no flickering:

    GVRTextViewSceneObject sceneObject, sceneObject2;
    
    /* snip */

    @Override
    public void onInit(GVRContext gvrContext) {
        GVRScene nextMainScene = gvrContext.getNextMainScene();

        sceneObject = new GVRTextViewSceneObject(gvrContext, mActivity);
        textSize = sceneObject.getTextSize();

        sceneObject2 = new GVRTextViewSceneObject(gvrContext, mActivity);
        
        // set the scene object position
        sceneObject.getTransform().setPosition(0.0f, 0.0f, -2.0f);
        sceneObject2.getTransform().setPosition(0.1f, 0.1f, -1.0f);

        // add the scene object to the scene graph
        nextMainScene.addSceneObject(sceneObject);
        nextMainScene.addSceneObject(sceneObject2);
        
        sceneObject2.setText("scene object 2");
    }

**Comment by nathan-almeida** [comment]
I've sent the code to chen`s email

**Comment by chenchao1407** [comment]
Hi Nathan

I tested with your codes and I don't see the view flickering. Can you tell me what device you used to test? Is it Qualcomm chipset(adreno) or Samsung chipset(mali)?

**Comment by nathan-almeida** [comment]
It is a Qualcomm.

It's the scene objects that flick when we keep moving our head. Have you run the sample in Oculus?

**Comment by chenchao1407** [comment]
Yeah. I still can't see flickering or blinking. What is your android version?

Thanks in advance.

**Comment by nathan-almeida** [comment]
My android version is 5.0.1

I am using a note 4, but I noticed that on S6 it is harder to notice this with only 2 GVRTextViewSceneObjects. Please change the source code I set to:

```java
for (int i = 0; i < 5; i++) {
...
```java

It is easier to see it when there are more objects in scene.

Now with more objects, they are also blinking.

**Comment by chenchao1407** [comment]
Hi. 
We just found there are two side effects we can see in your sample. One is because that in your sample, every GVRTextViewSceneObject has the same Z-value and they are overlapping with each other so there will be kind of Z-offer fighting effect. Actually all 2-D SceneObjects will trigger such effect in that case and I am not quite sure if it is a bug.

Another thing we can see is like flickering while moving head, maybe it is what you talked about. It is caused by the bad performance of SurfaceTexture and I just make a work around patch. Maybe you can take a look at it #134
