### ISSUE TITLE
Does the framework support playback of 4K 3D Videos out of the box?

### ISSUE THREAD

**Issue by TimecodePete** [Samsung/GearVRf#1231]
When loading a 4096x4096 top-down 3D video, I can hear the sound, but the screen remains black.
When I scaled down the same video to 2880x1440 it played fine (but was a bit stretched, for obvious reasons :P)

Is this due a hardware limitation of the phone (Galaxy S6), an encoding issue?
Is there a chart or some recommendations somewhere for video compatibility?

Some specs of the video:
Codec: H264
Resolution: 4096x4096
Bitrate: 120mbps
Framerate: 30fps
Audio Bitrate 300kbps

**Comment by liaxim** [comment]
@TimecodePete Does the video play directly with the MediaPlayer? Any exceptions in the logs?

**Comment by bohuang3d** [comment]
@TimecodePete  Have you tried other resolutions? Or 2048x2048, or 2048x4096

or reduce the bitrate/framerate

**Comment by liaxim** [comment]
@TimecodePete Please re-open if you have information you could share with us.
