### ISSUE TITLE
Taking screenshot using GearVR Utilities Menu

### ISSUE THREAD

**Issue by ftofoli** [Samsung/GearVRf#1235]
Does GearVRf block taking screenshots using the GearVR Utilities Menu in any way? I tried this from my application and some of the GearVRf sample applications and the screenshot doesn't work (same for videos). Please advise? 

I don't see the blinking red dot signifying the countdown, nothing happens really.

Thank you,
Fabricio

**Comment by liaxim** [comment]
We are shutting down completely the Oculus Mobile SDK on pause which disables their ScreenCaptureReceiver. We need to change our onPause/onResume handling for it to work as expected.

In the meantime:
- you can capture videos using the method outlined at https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-testing-capture/; see "Video Capture using Android System Properties"
- screenshot (stereo though) via the command line using screencap
- screenshot using GVRContext.captureScreen* to capture from GVRf

**Comment by pdiaz** [comment]
I need to make this work. @liaxim can you give any advice on how to do this?

**Comment by liaxim** [comment]
@pdiaz Should be fixed by https://github.com/Samsung/GearVRf/pull/1662

**Comment by liaxim** [comment]
@ftofoli We fixed it. Will be in the next release. Can we close the issue?
