### ISSUE TITLE
Q / Can I insert YouTube API in VideoSceneObject ??

### ISSUE THREAD

**Issue by miraclehwan** [Samsung/GearVRf#1242]
Hi, guys.
I trying to insert YouTubeVideoView in My GVRf App.
but I don't know how am i write my code...
I was refer to Exoplayer in GVRf-Demo. but I have a lot of problem.

if you have, Please let me know is it possible.

https://developers.google.com/youtube/android/player/?hl=ko

**Comment by liaxim** [comment]
This (https://github.com/Samsung/GearVRf/issues/1033#issuecomment-278244683) is what was verified as working some time ago.

Using the YouTube APIs is not option. GVRf requires your activity to derive from GVRActivity and YouTube requires you to derive from their YouTubeBaseActivity.

**Comment by miraclehwan** [comment]
Wow, Thanks for the reply!
It is really good!!
