### ISSUE TITLE
 loadFutureTexture makes main thread hang

### ISSUE THREAD

**Issue by miraclehwan** [Samsung/GearVRf#1252]
I have a problem. It is same issues [#807](https://github.com/Samsung/GearVRf/issues/807) , [#809](https://github.com/Samsung/GearVRf/issues/809).
Please help me to solve this problem.

**Comment by liaxim** [comment]
I highly recommend not using loadFutureTexture. We will completely remove this kind of API in the next major release. If you must, you can spawn a background thread and call loadTexture from there. Ideally you load this texture once from onInit and if this is the case, you can just call loadTexture directly from onInit.

We can be of more help if you could share with us a sample app that exhibits the problem. Thanks.

**Comment by liaxim** [comment]
@miraclehwan Do you still experience this issue? Do you have something to share with us?

**Comment by miraclehwan** [comment]
@liaxim 
yes, i will update in a week.
Thank you for your comment.

**Comment by liaxim** [comment]
@miraclehwan Assuming it is all good. If you have something for us regarding this issue, let us know. Otherwise I plan to close it some time next week.
