### ISSUE TITLE
Q/ Alpha blending on GVRExternalTexture 

### ISSUE THREAD

**Issue by hairanakh** [Samsung/GearVRf#1258]
Hello,

I am trying to modify [camera2renderscript](https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-camera2renderscript) sample to add alpha blending to processed image from the camera.

In principle, I am able to modify the alpha channel of the image (modifying mono.rs), e.g

```
  void root(const uchar4 *v_in, uchar4 *v_out) {
    float4 f4 = rsUnpackColor8888(*v_in);

    float3 mono = dot(f4.rgb, gMonoMult);
    *v_out = rsPackColorTo8888(mono);

// These lines are aded by me:
    if(v_out->r > 200)
        v_out->a = 50;
  }
```

However, even though the output is RGBA, it doesn't seem to be processed: the output is still opaque. 

Following what I understood from [here](https://github.com/Samsung/GearVRf/issues/1047), I have added `setAlphaBlend(true)` and `setRenderingOrder(TRANSPARENT)` to the GVRSceneObject RenderData, but it doesn't seem to change anything:

````
        GVRSceneObject effectObject = new GVRSceneObject(gvrContext, gvrContext.createQuad(3.0f, 1.5f), effectTexture);
        effectObject.getRenderData().getMaterial().setShaderType(GVRShaderType.OES.ID);
        effectObject.getRenderData().setAlphaBlend(true);
        effectObject.getRenderData().setRenderingOrder(GVRRenderData.GVRRenderingOrder.TRANSPARENT);
        effectObject.getTransform().setPositionY(0.8f);
        effectObject.getTransform().setPositionZ(-3.0f);

````

So there must be some obvious mistake in my side somewhere, but I am new to this and I am unable to figure it out. Any help would be really appreciated.

Thanks!

**Comment by J0Nreynolds** [comment]
Hi,

I've replicated your problem and am looking into it. For now, I've been able to produce your desired result by adding

`        effectObject.getRenderData().setAlphaToCoverage(true);`

However, it should work without needing this line of code. I will let you know anything else I find.

**Comment by J0Nreynolds** [comment]
@hairanakh It seems that the problem is caused by the blending function. By default, the source blend function is GL_ONE and the destination blend function is GL_ONE_MINUS_SRC_ALPHA. In order to achieve the transparent effect you desire, the source blending function should be GL_SRC_ALPHA and the destination blending function should be GL_ONE_MINUS_SRC_ALPHA.

To change your blending functions to these, please insert this line of code:
``
        effectObject.getRenderData().setAlphaBlendFunc(0x0302, 0x0303);
``

You should also remove the line I gave you in my previous comment as it's unnecessary.

**Comment by hairanakh** [comment]
@J0Nreynolds It works nicely! Thank you!
