### ISSUE TITLE
Video displaying on imported mesh

### ISSUE THREAD

**Issue by joelsung** [Samsung/GearVRf#1268]
I'm trying to display video on an imported mesh.
But it's not going what I wanted to do.

I used MeshLab to create simple mesh (with v, vn, vt, f),
and imported obj file by using loadMesh command.

But, I think, uv transformation is going wrong and each mesh is not assigned with proper video part.
Do I need a specific format, or mesh generation program to make a mesh?
(I also tested it inside of box, and got the same messed up result)
![meshlab](https://user-images.githubusercontent.com/29045791/27665031-78e21ba0-5c30-11e7-88d7-1a6104937265.jpg)
![screenshot_20170628-182218](https://user-images.githubusercontent.com/29045791/27665039-897f4d16-5c30-11e7-87c4-08d13f0e0514.png)

**Comment by bohuang3d** [comment]
What happens if you map a texture to the mesh within MeshLab?

**Comment by joelsung** [comment]
Within a MeshLab, I think it has no problem with it.
I opened obj file and found MeshLab does not export v, vn, vt, f in order (a bit mixed fashion).

![meshlab](https://user-images.githubusercontent.com/29045791/27665467-e773f9ec-5c32-11e7-9cef-58614bebc012.jpg)

**Comment by bohuang3d** [comment]
MeshLab's obj export has some customizations that other obj loaders may not understand. Could you import the mesh you made into Blender or other programs that can open Obj. If they open the mesh without problem, please share your mesh, code, and video.

**Comment by joelsung** [comment]
Thanks for letting me know about Blender.
Instead of installing it, I tried 3d Builder (from Windows 10), and it works without a problem.

The corresponding code is like these;

        mesh = gvrContext.getAssetLoader().loadMesh(new GVRAndroidResource(gvrContext, "cap.obj"));
...
        GVRVideoSceneObject video = new GVRVideoSceneObject(gvrContext, mesh, mediaPlayer, GVRVideoType.MONO);

[cap.zip](https://github.com/Samsung/GearVRf/files/1110582/cap.zip)

**Comment by thomasflynn** [comment]
Hi.  (just got a chance to chime in)  We use assimp (www.assimp.org) to import our models.  How does it look with their viewer? (open3mod.com)

**Comment by joelsung** [comment]
Thanks for the recommendation! It opens on open3mod, and looks nice.
But I think the problem is video assignment on each triangular mesh.

Whole geometry is maintained, but video segments are assigned on random triangle.
If I use GVRSphereSceneObject or GVRCylinderSceneObject, it shows good shape.

So I thought, I'm using some inappropriate setting on MeshLab.
I think I have to try another mesh provider to import model... :)

**Comment by bohuang3d** [comment]
@joelsung

The adjacent triangles in this model do not map to adjacent areas in the texture. See the two images comparing where two adjacent triangles map to in texture space:

![cap1](https://user-images.githubusercontent.com/5192187/27667037-bb41bacc-5c2c-11e7-839a-c4b2de6fd765.JPG)
![cap2](https://user-images.githubusercontent.com/5192187/27667038-bb4701d0-5c2c-11e7-88e7-4cbbe337cde7.JPG)

**Comment by joelsung** [comment]
@bohuang3d
Oh, Thanks a lot for checking it!!
I'll try making it by other tool or setting.

**Comment by joelsung** [comment]
@bohuang3d 
I used your recommendation Blender to make hemisphere, and made it out.
Thanks for your kind guidance :)

![screenshot_20170628-232825](https://user-images.githubusercontent.com/29045791/27671494-b9869d74-5c59-11e7-93d6-3f3cc895cdce.png)
