### ISSUE TITLE
Exposing the ProximityReceiver

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#127]
Receiving notifications from the proximity sensor would make it convenient for developers to detect device mount and unmount states allowing them to render objects in the current field of view rather than having the user look around to find the objects that were drawn when onInit() was last called.

Currently we can implement our own BroadcastReceiver for the proximity sensor intent just like the ProximityReceiver in VRLib.  Would it be beneficial to add it to GVRf?

**Comment by oliverRandom42** [comment]
Did this ever get addressed? Currently looking for a way to access the proximity sensor in the GearVR headset also

**Comment by liaxim** [comment]
See DockEventReceiver.java; there is nothing special about it and anybody can listen for those broadcasts.

There is also GVRConfigurationManager.isHmtConnected; it lets you query the current state.

**Comment by liaxim** [comment]
@rahul27 Do you still think we need this exposed? What value can we add on top of the standard APIs? We do expose the polling API.

**Comment by oliverRandom42** [comment]
Thanks @liaxim 

I didn't realize that onPaused() was called when you took the headset off.

It would however be handy to add on top of the standard API's - in my case I was merely trying to reset a video's playback position to 0 so simply called mediaPlayer.seekTo(0) and mediaPlayer.start() in onPause() which does the trick - but can definitely see how it could be useful to have easier access to it for other purposes.

Cheers!

**Comment by liaxim** [comment]
I see, makes sense. We will add it as an event to our ever-expanding events mechanism.

**Comment by oliverRandom42** [comment]
After doing a few tests - it seems as though the onPause() call once the headset is taken off does not quite work correctly.

onPause() is definitely called when the GearVR identifies it is not mounted - as my call to set my video playback position back to 0 is granted, but the application does not actually pause - the screen merely dims to black , and carry's on as normal.

Currently on a deadline to have this working for a client by the end of the week - it would be great if you could show me how to access the GVRConfigurationManager.isHmtConnected ?

Cheers :dancer: 

O.

**Comment by liaxim** [comment]
If you build the framework yourself you can just make GVRConfigurationManager public. I will add a proper public API too.

**Comment by oliverRandom42** [comment]
For anyone out there trying to find a work around until this is exposed...

In your manifest.xml in the <intent-filter>

`<action android:name="android.intent.action.proximity_sensor" />`

In your activity:

`import android.content.BroadcastReceiver;`

`private BroadcastReceiver mReceiver = null;`

`@Override
    protected void onResume() {
        super.onResume();
        IntentFilter intentFilter = new IntentFilter(
                "android.intent.action.proximity_sensor");
        mReceiver = new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {

                if(intent.getType().equals("1"))
                {
                	 Debug.out("mounted");
                         //DO SOMETHING 	 
                }
                else
                {
                	 Debug.out("unmounted");
                         //DO SOMETHING
                }
            }
        };
        this.registerReceiver(mReceiver, intentFilter);
    }
	
	 @Override
    protected void onPause() {
	super.onPause();
	unregisterReceiver(mReceiver);
    }`

**Comment by yjlintw** [comment]
Still have the same problem. onPause/onResume does not called when the proximity sensor is blocked/unblocked.

@oliverRandom42's code works for most of the time. However, if I blocked the proximity sensor before the phone is inserted to the dock, it will never receive any message(until I unblocked it) because the state is never changed.

**Comment by oliverRandom42** [comment]
The problem you might be experiencing @yjlintw is when the headset may be off / proximity sensor not blocked for an extended period of time - basically the app gets pushed to the back of the stack, and when the proximity sensor is fired - the app doesn't have enough time to register. If you print out to your log you will notice you will still receive a message from the sensor - but it will not resume. I managed to get around this by putting a delay into onResume() as follows:

`@Override
    protected void onResume() {
		
		
        super.onResume();
  
        
        new Timer().schedule(new TimerTask() {          
            @Override
            public void run() {
            	Debug.out("delayed - run here") 
            }
        }, 1000);
        
        if (mReceiver == null) {
	        IntentFilter intentFilter = new IntentFilter("android.intent.action.proximity_sensor");
	        mReceiver = new BroadcastReceiver() {
	            @Override
	            public void onReceive(Context context, Intent intent) {
	                if(intent.getType().equals("1"))
	                {	                	              	
	                	 Debug.out("mounted");	                	 	             	 
	                } else {
	                	 Debug.out("un-mounted");
	                }
	            }
	        };
	        registerReceiver(mReceiver, intentFilter);
        } 
    }`

**Comment by liaxim** [comment]
There is no API available to poll for the proximity status, to my knowledge. After the user stop wearing the headset onPause eventually gets called; after some delay.

**Comment by liaxim** [comment]
@oliverRandom42 Why not just register the receiver from onCreate and unregister from onDestroy?

**Comment by yjlintw** [comment]
@oliverRandom42 I have a background service which will be triggered when the phone insert on the headset. And then, the service will open a certain app that I want it to open automatically. Therefore, in a show condition, the operator doesn't need to bother open an app and can just plug and go.

The problem occurs if the headset's proximity sensor is blocked before the device is plugged in to the headset(for example, when the pad is a little off, which happens all the time). The app will never now that it should play since it will never receive the status change from proximity sensor.

**Comment by oliverRandom42** [comment]
@liaxim That makes a lot more sense to register in onCreate()/Destroy()! Ill have a look into that today :) Cheers!

@yjlintw That is a nice idea - I like it - I may also look into that - as in most cases for us it is a show situation where the app needs to be operated by people with little knowledge of how it all works behind the scenes.
I now understand what you mean by it being blocked before the device being plugged in - I'm not too sure how you would get around that being a physical constraint outside the control of the device. I think your solution should be a good way to solve the problem!

**Comment by liaxim** [comment]
@rahul27 Back to your original proposal. I think just trivially wrapping a BroadcastReceiver for proximity detection brings no value (it is just too easy to do). I think we probably need a way to let users configure their app to automatically re-center on proximity. Like an option in gvr.xml or a flag in GVRScene. Then we might be adding a little value.. What do you think?

**Comment by rahul27** [comment]
My original proposal was to add a convenience wrapper for the BroadcastReceiver but since it has been well documented in this thread (thanks @oliverRandom42) , I guess it is okay to go ahead and close this thread.

Re-centering is easy to implement over the BroadcastReceiver. We could implement it if there are more requests for this feature.

**Comment by liaxim** [comment]
Ok then. Will close this tomorrow if there are no further comments.
