### ISSUE TITLE
Question about "Reset headtransform"

### ISSUE THREAD

**Issue by sexydot** [Samsung/GearVRf#1271]
Hello, I have a problem with reset head transform.

To reset head transform, I used below code.

```
getGVRContext().getMainScene().getMainCameraRig().reset();


float yaw = getGVRContext().getMainScene().getMainCameraRig().getHeadTransform().getRotationYaw();
float pitch = getGVRContext().getMainScene().getMainCameraRig().getHeadTransform().getRotationPitch();
```

It works well in VR Developer mode without Gear VR.
But when I attach it to Gear VR, It does not reset head transform.

How can I solve this issue?
Please, Let me know If there is any other way to reset headTransform.

**Comment by bohuang3d** [comment]
@sexydot 
Can you tell me what action are you using to trigger the reset() while the phone is outside the GearVR?

So I can reproduce your case exactly. Best if you can supply a project with source code.

**Comment by liaxim** [comment]
I can see the problem on master. Created a pull request to fix it. In case you are using GVRf snapshots from maven, I uploaded new snapshots that include the fix.

**Comment by sexydot** [comment]
Thank you

**Comment by liaxim** [comment]
Assuming it is all good. Planning to close in few days.
