### ISSUE TITLE
GVRMaterial.setOpacity() not setting opacity

### ISSUE THREAD

**Issue by mwitchwilliams** [Samsung/GearVRf#1283]
The GVRMaterial.setOpacity() command is not having any effect.
Using X3D's &lt;Material transparency='_value_'/&gt; node [where '_value_' is a float between 0 and 1].

In X3DObject.java, this calls:
`gvrMaterial.setOpacity( value );`
but in the picture below, it has no effect.
As a test, I called 
`float opacity = gvrMaterial.getOpacity();`
to insure _value_ was being set correctly.

X3D test case plus images: 
[Opacity_Test.zip](https://github.com/Samsung/GearVRf/files/1142710/Opacity_Test.zip)
The transparencies in the scene are: upper left transparency=0; Upper right .25; Lower left .5, Lower right .75.  All orange planes against a gray background.

X3D file using the FreeWRL renderer:
![opacitytest_freewrl](https://user-images.githubusercontent.com/18128830/28128714-7f081cd6-66e5-11e7-8f77-3aefc0269ec7.png)

Same X3D file using GearVRf
![opacitytest_gearvrfx3d](https://user-images.githubusercontent.com/18128830/28128726-88e81742-66e5-11e7-9acc-d6f2b6fac283.png)

**Comment by NolaDonato** [comment]
This is because GVRMaterial.setOpacity sets the u_opacity uniform for the texture shader. The X3D exporter uses the Phong shader which does not have a u_opacity uniform. To set the opacity when using the phong shader you need to change the alpha component of the diffuse color: GVRMaterial.setVec4("diffuse_color", r, g, b, a);

**Comment by liaxim** [comment]
@mwitchwilliams Should we close?

**Comment by mwitchwilliams** [comment]
Let me test this difference first, and then I can close it.

**Comment by mwitchwilliams** [comment]
Ok, great.  This works.  Thanks.
