### ISSUE TITLE
Q / Periodically, showed the first frame during the playing animation.

### ISSUE THREAD

**Issue by miraclehwan** [Samsung/GearVRf#1286]
Hi, all.
I want to loading Animation. so I found the [issues](https://github.com/Samsung/GearVRf/issues/730)&[example code](https://github.com/rahul27/GearVRf-Demos/commit/56755c4a94070ad4c071a5588b4ad321e2b31922).
but It is have a little problem. 
Periodically, showed the first frame during the playing animation.
Sorry for my English is not good.

Could you check my code please ?

[My project](https://github.com/miraclehwan/AnimationTEST)

## I want to show this Image
<img src="https://user-images.githubusercontent.com/20110093/28170252-c9413d10-681f-11e7-8ee4-1f8f31609b69.gif" />

**Comment by liaxim** [comment]
From trying your app I can see that the frames are not animated in the right sequence. The files from the zip archive are not processed in the expected order. Without code changes renaming Frame0, Frame1, .., Frame9 to Frame00, Frame01, .., Frame09 should do the trick. Attaching the updated archive: 
[loading.zip](https://github.com/Samsung/GearVRf/files/1145802/loading.zip).

**Comment by miraclehwan** [comment]
@liaxim 
Thank you for your comment.
I solved the issues. :-)
