### ISSUE TITLE
Android Progressbar Does Not Spin on GVRViewSceneObject 

### ISSUE THREAD

**Issue by lxc-xx** [Samsung/GearVRf#1293]
The android progress bar widget seems not spin when rendered on the GVRViewSceneObject.

I test on the code from GearVRf-Demo (https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-events). I inserted the progressbar code into the activity_main.xml.
`        <ProgressBar
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />`

The progress bar can be shown on the GVRViewSceneObject but is not spinning. It spins only if I touch the touchpad.

**Comment by J0Nreynolds** [comment]
I believe the View will only be redrawn when you call `frameLayout.invalidate();` from the UI thread, or you can call `frameLayout.postInvalidate();` from any other thread. Perhaps the simplest solution to your problem would be to change make the onStep function of the EventsMain class call `postInvalidate` like so:

```
    @Override
    public void onStep() {
        frameLayout.postInvalidate();
    }
```

**Comment by lxc-xx** [comment]
This works well. Thanks for your answer!

**Comment by lxc-xx** [comment]
I did more tests on this and found that, actually, this simple solution introduces huge CPU overhead.  In the gearfr-demo example, the CPU usage doubled (from ~16% to ~30%) after I added the `frameLayout.postInvalidate();`. If I apply the same code to my a little larger project, the fps drops a lot.

Do you have any idea about this?

**Comment by liaxim** [comment]
@lxc-xx There is a texture that needs to be updated to pick up the view changes. Updating it too frequently is expensive. You could try calling postInvalidate less frequently than every 16ms. 32ms looks like a good tradeoff. 48ms might be possible too. The less frequently you call it the better but the animation will get choppier.

**Comment by ragner** [comment]
Hi @lxc-xx,
If possible, could remove `frameLayout.postInvalidate();` and test your application with my branch
https://github.com/ragner/GearVRf/tree/keyboardview ?

It could be a good test to my https://github.com/Samsung/GearVRf/pull/1345
it is about keyboard support but also has some improvement to GVRViewSceneObject

**Comment by liaxim** [comment]
@ragner Tried your branch with gvr-events but it throws NPE:

```
08-01 17:29:21.273  8872  8872 E AndroidRuntime: FATAL EXCEPTION: main
08-01 17:29:21.273  8872  8872 E AndroidRuntime: Process: org.gearvrf.events, PID: 8872
08-01 17:29:21.273  8872  8872 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.gearvrf.events/org.gearvrf.events.EventsActivity}: java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3317)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3417)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:226)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1843)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:158)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7522)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to write to field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at org.gearvrf.events.EventsActivity.onCreate(EventsActivity.java:65)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6876)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
08-01 17:29:21.273  8872  8872 E AndroidRuntime: 	... 9 more
```

The frameLayout's layoutParams is null. I see you have removed the registerView call. What is it replaced with now?

**Comment by ragner** [comment]
Hi @liaxim,
I have updated my branch to keep compatibility with current GVRView implementations ...
Could yout fetch it again?

But with my changes  gvr-events could be updated to use the following constructor: 


` /**
     * Constructs a scene object that inflate a view from an XML resource. The scene object
     * notifies the {@linkplain IViewEvents listener} of the view to set its initial properties
     * after it has been inflated.
     * Internally the scene object uses the {@linkplain GVRContext context} to create
     * its own quad mesh based on the the width and height of the view:
     *     gvrContext.createQuad(getWidth() / Math.max(getWidth(), getHeight()),
     *                           getHeight() / Math.max(getWidth(), getHeight()));
     *
     * @param gvrContext current {@link GVRContext}.
     * @param viewId The resource ID to inflate. See {@link LayoutInflater}.
     * @param eventsListener Listener to be notified after the view has been inflated.
     */
    public GVRViewSceneObject(GVRContext gvrContext, int viewId, IViewEvents eventsListener) {`

**Comment by ragner** [comment]
With my changes,
that call to `` frameLayout.invalidate(); `` should not be necessary anymore.

**Comment by liaxim** [comment]
@ragner It does work and it does perform very well. Why does it work though? updateTexImage is still there on every frame. What was the overhead in the old approach? We had to rely on invalidating the layout to get Android to draw apparently; is that it? Is your RootViewGroup something customized off the platform? Thanks.

**Comment by ragner** [comment]
Hi @liaxim,
I think that the overhead was call invalidade that causes draw() call unnecessarily even the View has not been changed.

About this invalidade issue I don't have a final fix but my workaround was override invalidateChildInParent(...) and call postInvalidate() inside of it. So RootViewGroup
will call draw(canvas) of its children only when its content has been changed.

 Also I am just calling setWillNotDraw(true) of RootViewGroup that allow some optimizations. https://developer.android.com/reference/android/view/View.html#setWillNotDraw(boolean)

**Comment by liaxim** [comment]
@lxc-xx We merged https://github.com/Samsung/GearVRf/pull/1345. The performance will be much better. You are not going to need postInvalidate anymore.

**Comment by liaxim** [comment]
@lxc-xx Assuming it is all good. Planning to close this issue some time next week.
