### ISSUE TITLE
Volume UI is shown on incorrect position (with my Galaxy S6 edge)

### ISSUE THREAD

**Issue by niusounds** [Samsung/GearVRf#132]
Volume adjustment UI of GearVR is shown on incorrect position (like mirrored).
I have only Galaxy S6 edge. I can't test that it is phone specific problem or not. sorry.

**Comment by chenchao1407** [comment]
Hi.

Did you merge recent commits from the repository? I thought this was resolved by the pull request #51

**Comment by niusounds** [comment]
Oh, sorry. It works perfect on newest version! Thank you.

**Comment by chenchao1407** [comment]
Never mind. Thanks for reporting this also.

**Comment by thomasflynn** [comment]
so, this issue could be closed, right?
