### ISSUE TITLE
Rendering order set TRANSPARENT when creating scene object with future texture

### ISSUE THREAD

**Issue by SteveGreatApe** [Samsung/GearVRf#1338]
Hi, I've just pulled the latest GearVRf code and found a bug in my App as a result of the rendering order being automatically changed to TRANSPARENT where I'm loading a GVRSceneObject with a future texture and mesh.

The problem is caused by the newly added GVRRenderData:adjustRenderingOrderForTransparency function. I can see the sense it doing this when it does detect a texture with transparency, but in my case both the main and diffuse textures are null. In this case the code behaves as if the textures have transparency and automatically switches the rendering order to TRANSPARENT, which is not what I was expecting.

**Comment by bohuang3d** [comment]
As a side note: maybe you know this already, it's been recommended to not use future texture

**Comment by thomasflynn** [comment]
he doesn't have a lot of easy choices in the current top of trunk.  once we merge the vulkan branch into master, then futureTextures will be unnecessary and be deprecated.

**Comment by thomasflynn** [comment]
and thank you @sushantojal for the quick diagnosis and fix!

**Comment by liaxim** [comment]
https://github.com/Samsung/GearVRf/pull/1341 has been merged. @SteveGreatApe Can we close?

**Comment by SteveGreatApe** [comment]
Yes, the fix looks good thanks.
