### ISSUE TITLE
Scene blinks after back key pressed 

### ISSUE THREAD

**Issue by ragner** [Samsung/GearVRf#1355]
Hi all,
The scene is blinking after back key pressed.
You can see this issue easily on gvr-keyboard demo but it happens at other demos also.

To reproduce you just need launch the application wait for it be ready
so press back key twice.

We are facing this issue at our "Look To The Sky" application also.

Does anybody could help me with this?

**Comment by ragner** [comment]
I am using a GearVR RM-R324 + S8 SM-G950FD

**Comment by liaxim** [comment]
Happens only on S8 from what I can see. Note 5 with Android N shows no problem. Have nothing thus far. Will keep looking over the next few days.

**Comment by liaxim** [comment]
Let me know how https://github.com/Samsung/GearVRf/pull/1379 works out for you.

**Comment by bohuang3d** [comment]
Closing per confirmation of fix
