### ISSUE TITLE
The screen can't be filled

### ISSUE THREAD

**Issue by zhangweizhe** [Samsung/GearVRf#1371]
![image](https://user-images.githubusercontent.com/18739215/29068573-ee2a6968-7c69-11e7-91c5-b57444884178.png)

The screen can't be filled by the white part on my device, the size of my device is 5.5inch, and 1920*1080
How can I solve the problem

**Comment by bohuang3d** [comment]
Which device is this?

Is it a white background that's supposed to occupy most of the screen?

Please send a simple class containing a test case demonstrating this

**Comment by zhangweizhe** [comment]
@bohuang3d 
My device is ZTE Nubia z7Max
Yes, the white background supposed to occupy most of the screen.
I am new to GitHub and don't know how to send a file.
Here are the codes demonstrating the problem
public class TestMain_1 extends GVRMain {

    private GVRScene mGVRScene;

    @Override
    public void onInit(GVRContext gvrContext) throws Throwable {
        super.onInit(gvrContext);

        mGVRScene = gvrContext.getMainScene();
        mGVRScene.setBackgroundColor(1,1,1,1);

        GVRSceneObject object = new GVRSceneObject(gvrContext, 3,3 );
        GVRMaterial material = new GVRMaterial(gvrContext);
        GVRTexture texture = gvrContext.getAssetLoader().loadTexture(new GVRAndroidResource(gvrContext, R.drawable.gearvr_logo));
        material.setMainTexture(texture);
        object.getRenderData().setMaterial(material);
        object.getTransform().setPosition(0,0,-3);

        mGVRScene.addSceneObject(object);
    }
}
and the capture of the screen
![image](https://user-images.githubusercontent.com/18739215/29101564-b30a6aaa-7ce5-11e7-8734-40b9cfe53759.png)

In fact, all the demos run on my device encounter this problem

**Comment by bohuang3d** [comment]
We don't have that device. It's from 2014 and I suppose it's not Daydream certified?

As you don't seem to be doing anything strange for the code, I'm sure if you run your project on a Samsung Galaxy S6,7,8 or Note 5 and above, you won't run into this problem.

**Comment by zhangweizhe** [comment]
@bohuang3d 
Yes, it runs on Galaxy S6 perfectly, I just want to know what's wrong on my device
![image](https://user-images.githubusercontent.com/18739215/29150060-ca2eaec4-7daa-11e7-996c-15cacdf68698.png)
thank you for your reply
![image](https://user-images.githubusercontent.com/18739215/29150129-085b6ec6-7dab-11e7-85a4-72e773e40fec.png)

**Comment by liaxim** [comment]
@zhangweizhe If you are willing to share your logcat output, we can take a look. Not likely it will be enough though. Have you tried different cardboard profiles? What happens if you run another cardboard app, one that is not using GVRf?

**Comment by zhangweizhe** [comment]
Hello @liaxim , thank you for your reply
Here is the logcat output with filter "org.gearvrf.sample.sceneobjects" [log.txt](https://github.com/zhangweizhe/hello-world/blob/master/log.txt)
I have tried other cardboard apps and encounter this problem too.

**Comment by liaxim** [comment]
Try https://play.google.com/store/apps/details?id=com.anrael.vrcc&hl=en. Try adjusting the FOV angles using the app and let us know whether it makes any difference. But most likely you need to install an appropriate profile.

**Comment by zhangweizhe** [comment]
Hello @liaxim Here are some screenshots of the app, it makes some differences by adjusting the parameter
The first time I opened the app
![image](https://user-images.githubusercontent.com/18739215/29260031-b36d803c-80f9-11e7-972e-2a7dd3a90c18.png)

adjusting the FOV angles
![image](https://user-images.githubusercontent.com/18739215/29260053-d06ec894-80f9-11e7-8c2d-0eda46ddb9ac.png)

adjusting the "screen to lens distance" from 42 to 171
![image](https://user-images.githubusercontent.com/18739215/29260087-23fe8f4e-80fa-11e7-9b30-35533935abcc.png)

It work perfectly by adjusting the "screen to lens distance"
But when I generate profile [here](https://vr.google.com/cardboard/viewerprofilegenerator/) using the parameters above, it's strange, the scene gets closer to me
 
![image](https://user-images.githubusercontent.com/18739215/29260302-92d23e9c-80fb-11e7-9422-a09dc59ba677.png)

**Comment by zhangweizhe** [comment]
Hello @liaxim , after trying different parameters, the scene can occupy the whole screen.
Thank you so much.

**Comment by liaxim** [comment]
@zhangweizhe Awesome. Can we close the ticket then?

**Comment by zhangweizhe** [comment]
@liaxim  I am sorry I forgot to close it. I will close it right now.
