### ISSUE TITLE
GVRTextViewSceneObject -> changing typeface

### ISSUE THREAD

**Issue by felislynx-silae** [Samsung/GearVRf#1372]
Is there any reason why changing typeface is not accessible in any other way than reflection?
Will it be supported or is there other way to change typeface in GVRTextViewSceneObject?

**Comment by mwitchwilliams** [comment]
Greetings,
Just want to get some information on your issue, could you copy the GVRTextViewSceneObject Constructor from your code?
Is it:
```
GVRTextViewSceneObject(GVRContext gvrContext, String name, String string, String font,
              justifyTypes justify, float spacing, float size, fontStyleTypes style) 
```

Are you using the setTypeface method:
`setTypeface(GVRContext gvrContext, String font)`

There has been an update to GVR framework to include the above constructor and method in the past 2 months.

Mitch

**Comment by felislynx-silae** [comment]
GVRTextViewSceneObject(GVRContext gvrContext, float width, float height, CharSequence text) 
or
 GVRTextViewSceneObject(GVRContext gvrContext, CharSequence text)

I'm using oficial 3.2 release. I'm asuming, that change is not released, and available only while building framework by myself?

**Comment by felislynx-silae** [comment]
Also is loading font not from assets but using Typeface.createFromFile("") from app cache also available?

**Comment by thomasflynn** [comment]
Yes, the change Mitch is mentioning is in master.  You'll need to build the framework to get it.

**Comment by thomasflynn** [comment]
Though, we have nightly builds uploaded to maven as 3.2.1-SNAPSHOT.  You can try that first before attempting to do a build.

**Comment by liaxim** [comment]
@thomasflynn The uploads are manual. Not that we can't automate. Not sure why we never did that - one reason would be spamming the maven repo.

**Comment by felislynx-silae** [comment]
I've checked nightly build. It's better but loading font not from hardcoded assets would be awesome :)

**Comment by mwitchwilliams** [comment]
Currently, the .ttf font file(s) must be in Android Studio's assets folder, same location as texture maps.
We also had an idea for getting text strings remotely too, so perhaps when we revisit that issue, we will discuss .ttf files from external sources.

**Comment by felislynx-silae** [comment]
@mwitchwilliams From my experience, using reflection to get textview, then setting typeface downloaded from google fonts works (sometimes not)

**Comment by liaxim** [comment]
@felislynx-silae The additional sources for text fonts has been noted. Do you think what is in master is adequate otherwise? If not, do you have specific suggestions? And finally, if it is all good, can we close the issue?

**Comment by felislynx-silae** [comment]
It works quite well :)
I have some issues with measuring view with custom font, to set quad size. But it's manageable for now (it is threading fault for sure) because sometimes measured textview gives smaller size than it should. I think after new release of framework i'll make extensive tests of how code is behaving :) Thank you very much

**Comment by liaxim** [comment]
All right. Closing for now and I will be expecting bug reports after our 3.3 release ;). Thanks.
