### ISSUE TITLE
Scale transformation has not been applied to children

### ISSUE THREAD

**Issue by ragner** [Samsung/GearVRf#1383]
Hi,
I maybe doing something wrong but at current master branch
if I make  changes of scale It is not been propagated to the children of a GVRSceneObject instance.

Does anybody get this issue also?

For example:
```
A = new GVRSceneObject(ctx, null mesh);
B = new GVRSceneObject(ctx, quad mesh);

A.addChildObject(B).
A.getTransform().setScale(2.0f, 2.0f, 1.0f);
```
The scale of B keeps the same on the scene.

**Comment by mwitchwilliams** [comment]
Greetings Ragner,

Thanks for your comments.  I ran a test of scaling with child objects using our X3D implementation, a file format that builds a GearVR data structure with GVRSceneObjects and Transforms.  It scaled objects as expected.  In the screen shot, the red cone is scaled (3, .75, 1) and the green and blue cones are child objects.  The white cone is not a child object and has no scaling.
![screenshot_20170814-114710](https://user-images.githubusercontent.com/18128830/29286625-93488106-80e7-11e7-8320-d5ea3c266e5a.png)

I attached the X3D sample file to assist in our further testing.  
[scaleTest.zip](https://github.com/Samsung/GearVRf/files/1223138/scaleTest.zip)
Perhaps you could supply a larger code sample.

Mitch

**Comment by bohuang3d** [comment]
@ragner 

Here is one possibility to partially explain your situation:

Your quad mesh lies in the XZ plane

Its parent transform is scaling in the XY plane

So the Z dimension of the quad is not scaled


Can you try with a cube? Please provide a minimal project example to me.

Thanks

**Comment by ragner** [comment]
Hi @mwitchwilliams, after your comment
 I took a look at the change log of my source code and saw a mistake 
Sorry for the inconvenience ...

I will close this.
