### ISSUE TITLE
How to handle GVRScene objects' displaying order and How to access GVRScene' methods from on click listeners in GVRActivity class?

### ISSUE THREAD

**Issue by channae** [Samsung/GearVRf#1384]
I'm working on a VR application which shows scene objects upon startup (cube scene etc). Upon gazing at certain scene objects it should pop up an android listview. This listview contains submit and a cancel button.  

However Im having few issues within the application.

1. Upon gazing at the cube scene object, list view does not pop up (no exceptions are thrown either). I assume this is happening even though the layout scene object is added to the scene, Its added to the bottom. I can see the layout scene object if i call "scene.clear();" before adding layout scene object to the scene. But doing this I assume my current scene objects gets deleted so I won't be able to navigate back. How can i add and show layout scene object on top while maintaining my existing scene objects within scene?  

2. Since the back button onclick listener is in the UI thread (GVRActivity), I'm not able to call "scene.getMainCameraRig().removeChildObject(myLayout);". How can I access scene object from the activity class' onclick listener. Or are there any other solution for this?      

Appreciate your insight into this. Thanks.

**Comment by channae** [comment]
I managed to get above done with multiple GVRScene objects. I created static GVRScene object in GVRActivity and assigned the current scene before switching so I could go back to the previous scene. Hope I'm not violating best practices. Closing the ticket.
Thanks,

**Comment by liaxim** [comment]
@channae Generally using multiple GVRScenes can be considered discouraged. One day we may remove the ability to switch them out. You could look at the GVRSwitch node and the related gvr-switch demo app as an alternative solution to your problem.

**Comment by bohuang3d** [comment]
@channae 

Here is a different approach using scale factors and still maintain just one scene:

Add the cube object, layout object to the same scene. 
Upon gazing onto the cube, set the layout object's scale to 1, thus showing it.
Upon exiting gaze from the cube, set the layout object's scale to 0, thus hiding it.

Thus do this instead of add/remove scene objects that causes you problems
