### ISSUE TITLE
GVRAndroidResource private constructor with InputStream

### ISSUE THREAD

**Issue by jeanpul** [Samsung/GearVRf#1391]
Hi, 

Thank your for your great sdk !

I do not understand why GVRAndroidResource(String, InputStream) is private ? Our application has already is own assets manager (SDcard, resource, assets, Urls...) and can return a FileDescriptor or an InputStream so we don't have to worry about the source. Could we move this constructor public or is it possible to add a public constructor GVRAndroidResource(FileDescriptor fd) ?

Thanks for your reply

**Comment by bohuang3d** [comment]
For our purposes, it's currently used only by the ZipLoader according to comments:

     * Note that this constructor is package private and is only used by the {@link ZipLoader}
     * (for now).

This could change though before any such decision you are welcome to extend/modify this class and add your own functionalities

**Comment by liaxim** [comment]
@jeanpul Historical reasons. I find it all very convoluted (even somewhat broken) but is not likely we will refactor soon.

You might be able to do something like the following; have not verified it as working:

```
    private class YourResourceVolume extends GVRResourceVolume {
        private InputStream mYourStream;

        public YourResourceVolume(GVRContext context, InputStream yourStream) {
            super(context, VolumeType.INPUT_STREAM);
            mYourStream = yourStream;
        }

        @Override
        public GVRAndroidResource openResource(String ignored) throws IOException {
            return super.addResource(new YourResource(mYourStream));
        }

        private class YourResource extends GVRAndroidResource {
            private InputStream inputStream;

            public YourResource(InputStream inputStream) throws FileNotFoundException {
                super("");
                this.inputStream = inputStream;
            }

            @Override
            public synchronized void openStream() throws IOException {
                setStream(inputStream);
            }
        }
    }

....

        InputStream yourStream = null; // get it from somewhere
        YourResourceVolume volume = new YourResourceVolume(getGVRContext(), yourStream);
        GVRAndroidResource androidResource = volume.openResource(null);
```

Or just use reflection and mark the package private ctor as accessible.

And finally, considering how much detail we already expose, I will just make this one public too.

**Comment by jeanpul** [comment]
Hi @bohuang3d ,@liaxim , thanks for your replies.
Using your "GVRResourseVolume" is not working, I have errors "Cannot set the stream of an open resource" and "Input stream doesn't support mark" so finally I've used reflection as described bellow : 

```
// get private GVRAndroidResource(String,InputStream) reference from reflection
Class[] args = new Class[2];
args[0] = String.class;
args[1] = InputStream.class;
Constructor<GVRAndroidResource> constructor = GVRAndroidResource.class.getDeclaredConstructor(args);
                constructor.setAccessible(true);

// then later create any GVRAndroidResource with inputstream as you want
GVRAndroidResource res = constructor.newInstance("my 360 3D 4k photo!", myInputStream);
```
Regards

**Comment by liaxim** [comment]
@jang7875 Yeah. Forgot you have to also wrap your InputStream in something like the following. Then pass that. Much better to use reflection though.
```
    static class BufferedInputStream extends InputStream {
        private BufferedInputStream in;
        private InputStream realStream;

        public BufferedInputStream(InputStream realStream) throws IOException {
            this.realStream = realStream;
            in = new BufferedInputStream(realStream);
        }

        public boolean markSupported() {
            return true;
        }

        public void reset() throws IOException {
            this.in = new BufferedInputStream(realStream);
        }

        public int read() throws IOException {
            return in.read();
        }

        public int read(byte[] buffer, int byteOffset, int byteCount) throws IOException {
            return in.read(buffer, byteOffset, byteCount);
        }
    }
```
