### ISSUE TITLE
Don't start in "minifyEnabled true" mode

### ISSUE THREAD

**Issue by Ongoza** [Samsung/GearVRf#1394]
Hi Guys!
If i set up "minifyEnabled true" my app does not start with message:
` E/gvrf: unable to find method onDrawEye`
With "minifyEnabled false" - no problem

**Comment by bohuang3d** [comment]
Actually, that's a proguard thing. It could be obfuscating too aggressively, and not something we have control over which function is gotten rid of or not

**Comment by Ongoza** [comment]
Ok

**Comment by liaxim** [comment]
@Ongoza Regarding proguard rules, https://github.com/Samsung/GearVRf/wiki/Q&A 's item 22 has the rules verified as working some time ago. Might be outdated but it is a start.
