### ISSUE TITLE
Synchronize head movement between two device 

### ISSUE THREAD

**Issue by channae** [Samsung/GearVRf#1403]
Hi,

I want to sync one of the devices head movement with the other device. So the second device should move (override) according to the values passed by the first device. 

**Device 1**
I'm retrieving following on onStep method of first device (Device used for sending data). And these will be sent over the network to the second device. 

```
float w = mainCameraRig.getHeadTransformObject().getTransform().getRotationW();
float x = mainCameraRig.getHeadTransformObject().getTransform().getRotationX();
float y = mainCameraRig.getHeadTransformObject().getTransform().getRotationY();
float z = mainCameraRig.getHeadTransformObject().getTransform().getRotationZ() ;
```

**Device 2**
CameraRig is set to freeze during onInit of second device.
`mainCameraRig.setCameraRigType(GVRCameraRig.GVRCameraRigType.Freeze.ID);`

Then using a listener upon retrieving data following method is called,

`mainCameraRig.getHeadTransformObject().getTransform().setRotationByAxis(w,x,y,z);` 

I'm able to successfully retrieve data from the device 1. However upon movement, device 2 does not move. Appreciate your input.

**Comment by channae** [comment]
Additionally I have tried,

mainCameraRig.getHeadTransformObject().getTransform().rotate(w,x,y,z);
mainCameraRig.getHeadTransformObject().getTransform().setRotation(w,x,y,z);

However the screen blinks upon executing above methods. No luck in rotating the current scene.

**Comment by bohuang3d** [comment]
I think 
setRotationByAxis() returns an angle axis pair
where as
getRotationX(), Y(), Z(), W() returns a quaternion (x,y,z,w)

**Comment by liaxim** [comment]
@channae Is it all good now? Can we close the issue now?

**Comment by channae** [comment]
Seems like GVRTransform.setRotation()  does the job here. Closing the issue since it was resolved. 

Thanks,
Channa
