### ISSUE TITLE
 GVRVideoSceneObject Video with alpha channel

### ISSUE THREAD

**Issue by retterdesdialogs** [Samsung/GearVRf#1409]
I am trying to show a video with alpha channel in Android with the Gear VR SDK, but the background is black instead of transparent.

What i have is

```
try {

  final AssetFileDescriptor afd = context.getActivity().getAssets().openFd("video/Monitor1.webm");
  final MediaPlayer mediaPlayer = new MediaPlayer();
  mediaPlayer.setDataSource(afd.getFileDescriptor(), afd.getStartOffset(), afd.getLength());
  mediaPlayer.setLooping(true);

  mediaPlayer.prepare();

  GVRSceneObject board = getColorBoard(2,1);

  board.getTransform().setRotationByAxis(-90, 1, 0, 0);
  board.getTransform().setPositionY(-1.5f);

  GVRVideoSceneObject video = new GVRVideoSceneObject(context,   board.getRenderData().getMesh(), mediaPlayer, GVRVideoSceneObject.GVRVideoType.MONO);
  video.setName("video");

  video.getTransform().setRotationByAxis(-90, 1, 0, 0);
  video.getTransform().setPositionY(-1.5f);

  scene.addSceneObject(video);

  mediaPlayer.start();
  } catch (IOException e) {

  }
```

This shows the video but with a black background. I found out that MediaPlayer and ExoPlayer are not able to handle the alpha channel.

What i also tried is to use the ffmpeg player, but there i have the problem that the GVRVideoSceneObject need to get a MediaPlayer as parameter.

So how to handle this?

**Comment by bohuang3d** [comment]
How do we know MediaPlayer / ExoPlayer can't handle alpha channel?

If we can get the alpha data, GVRF can make use of the alpha channel:
https://github.com/Samsung/GearVRf/blob/master/GVRf/Framework/framework/src/main/jni/shaders/material/oes_shader.cpp

`out_color = vec4(color.r * u_color.r * u_opacity, color.g * u_color.g * u_opacity, color.b * u_color.b * u_opacity, color.a * u_opacity);`

**Comment by retterdesdialogs** [comment]
Thanks for help. I cannot use another format. But anyway, we decided to use a 3d object and animate this instead of having a video.
