### ISSUE TITLE
GearController dissapear when changing scene

### ISSUE THREAD

**Issue by felislynx-silae** [Samsung/GearVRf#1443]
I've successfully managed to add controller to my app based on gvr-controller demo code and latest lib snapshot. Going to menu and back to app, controller is visible.
Changing from initial scene A to scene B, controller is invisible but picker is working and all events are going trough. Going back from B to A, controller is fully visible.
While changing scene i'm reataching picker:
mControllerPicker?.detachComponent(mPicker.type)
mPicker = GVRPicker(gvrContext, currentScene)
mPicker?.setPickRay(0.0f, 0.0f, 0.0f, 0.0f, 0.0f, -699f)
mControllerPicker?.attachComponent(mPicker)

**Comment by NolaDonato** [comment]
I am in the process of reforming the controller / picking interface. I am changing the API so that all controllers have their own picker and set the pick ray appropriately. When attached to a controller, the picker will be able to emit touch events as well as pick events. This code is in testing now and should be available as a pull request later this week. It might solve some of your problems, perhaps you would be willing to be an early tester.

**Comment by felislynx-silae** [comment]
@NolaDonato In my app i'm changing scene frequently with this code (maybe that will help to check out this bug). I would be glad to test out your changes. Unfortunatelly i'll be unable to build framework since there is something wrong with my builds and they cause crashes (i've reported issue with build), so only local build & snapshosts
```
currentScene = scene
cursorManager?.setScene(scene)
gvrContext.mainScene = currentScene
```

**Comment by felislynx-silae** [comment]
I've checked 3.3.0 and 3.3.1-SNAPSHOT. Issue still persist. Changing scene makes controller dissapear. Trying to call gearController?.resetSceneObject() to re-add scene object in new scene allways fails with 
```
java.lang.UnsupportedOperationException: GVRSceneObject cannot have multiple parents
                                                                                     at org.gearvrf.GVRSceneObject.addChildObject(GVRSceneObject.java:686)
                                                                                     at org.gearvrf.GVRScene.addSceneObject(GVRScene.java:123)
                                                                                     at org.gearvrf.GearCursorController.setSceneObject(GearCursorController.java:117)
                                                                                     at org.gearvrf.scene_objects.GVRGearControllerSceneObject.setCursorController(GVRGearControllerSceneObject.java:187)
```

**Comment by liaxim** [comment]
@felislynx-silae Calling first ``GVRCursorController.resetSceneObject()`` and then ``setMainScene(newScene)`` worked for me. Assuming this is followed by something similar to this loop from gvr-controller:
```
        GVRInputManager inputManager = gvrContext.getInputManager();
        inputManager.addCursorControllerListener(cursorControllerListener);
        for (GVRCursorController cursor : inputManager.getCursorControllers()) {
            cursorControllerListener.onCursorControllerAdded(cursor);
        }
```

I highly recommend not using multiple main scenes. We are thinking about removing the feature as it complicates things, as you can see. One alternative is to use the GVRSwitch instead.

---
In case you wonder, this is the branch where I modified gvr-controller: https://github.com/liaxim/GearVRf-Demos/tree/issue1443

**Comment by felislynx-silae** [comment]
I'll try this ASAP. For now we were treating scenes like fragments. Is there recomended way to work with scenes (or scene)?
If changing scenes is bad, then would you recomend creating "scene-like" objects which we would change by root in main scene instead of changing main scene?

**Comment by liaxim** [comment]
Just have different GVRSceneObjects as roots of your "scenes" and enable/disable them as you wish while keeping them in the scene graph. It is all wrapped up by the GVRSwitch scene object - see the gvr-switch demo for an example.

**Comment by felislynx-silae** [comment]
How it'll impact performance? If we are talking about very object rich app?

**Comment by liaxim** [comment]
No impact. If a scene object is in the scene graph but disabled it will be skipped very early on. It is very much a micro optimization to start worrying about disabled scene objects. If it truly bothers you, you could add and remove the scene objects from the scene graphs too.

**Comment by felislynx-silae** [comment]
i'll try both, and will get back to you

**Comment by felislynx-silae** [comment]
So from my tests, using reset before setting new scene and after that doing this loop, works like charm. I believe that this could be mentioned in tutorial since i'm quite sure, i'm not the only one using scenes like fragments :). Rewriting code to use sceneobjects instead scenes will take some time for me, but, i'll do that to check how code will behave.

**Comment by liaxim** [comment]
@felislynx-silae Can we close this issue?

**Comment by felislynx-silae** [comment]
Yeah, i belive so
