### ISSUE TITLE
Change intersectsBoundingVolume to public

### ISSUE THREAD

**Issue by ragner** [Samsung/GearVRf#1450]
Does anybody have any objection of making public the following function?
`boolean GVRSceneObject::intersectsBoundingVolume(float ox, float oy, float oz, float dx, float dy, float dz);`

Do I have any alternative function?

I need it :)

**Comment by liaxim** [comment]
Should be ok. We already have one overload public.

**Comment by ragner** [comment]
Thank you,
I will make a pull request soon.
