### ISSUE TITLE
How to play a video with alpha channel? 

### ISSUE THREAD

**Issue by retterdesdialogs** [Samsung/GearVRf#1460]
I try to play a video (webm) with the GVRVideoSceneObject. It is playing but the background is black.

How to solve this?

**Comment by bohuang3d** [comment]
Do you mean your video is supposed to have transparency? It's not supported

**Comment by thomasflynn** [comment]
by default, it is not supported by our existing shader.  @bohuang3d perhaps you can show him how to use a custom shader for this?

**Comment by bohuang3d** [comment]
Certainly @thomasflynn. @retterdesdialogs The video you attached has a black background when I play it on Windows. Is the black area supposed to be where transparency occurs?

I assumed your problem is the same or similar to 
https://github.com/google/ExoPlayer/issues/2509
This thread indicates webm on Android does not support transparency?

**Comment by bohuang3d** [comment]
If your video already has transparency, the shader that corresponds to GVRVideoSceneObject.GVRVideoType.MONO:
https://github.com/Samsung/GearVRf/blob/master/GVRf/Framework/framework/src/main/jni/shaders/material/oes_shader.cpp

should already support alpha blending via the line

`out_color = vec4(color.r * u_color.r * u_opacity, color.g * u_color.g * u_opacity, color.b * u_color.b * u_opacity, color.a * u_opacity);
`

**Comment by retterdesdialogs** [comment]
Ok, thank you all for your help. 

Normally, the shader i am using is supporting alpha, because i can make a transparent object.

Like you said, the problem is maybe that Android is not supporting this. I dont find really a documentation about this.

At the end we will find a workaround. If i found something i will post it here.

**Comment by liaxim** [comment]
@retterdesdialogs Modified gvr-sceneobjects to make the black non-opaque. The video needs to be carefully authored though. Another option for you.

https://github.com/liaxim/GearVRf-Demos/tree/issue1460

**Comment by bohuang3d** [comment]
To close EOD. Feel free to open new issue as they come
