### ISSUE TITLE
Calling GVRGUISceneObject's Constructor... 

### ISSUE THREAD

**Issue by channae** [Samsung/GearVRf#1473]
I'm trying to create a GVRGUISceneObject by making following call to the constructor. I'm using 3.3.1-SNAPSHOT. 

`GVRGUISceneObject gvrguiSceneObject = new GVRGUISceneObject(gvrContext, (GVRView)webView);
`

Android Studio is showing errors seems like I'm passing wrong object.

I have attached screenshot for the reference.

![screen shot 2017-09-25 at 2 50 41 pm](https://user-images.githubusercontent.com/28370121/30801611-786dc1d0-a201-11e7-83b5-0234efc9c0f5.png)

Appreciate your input.

Thanks,

**Comment by J0Nreynolds** [comment]
Do you think you could attach or link the entire source for the application you're trying to debug? I have a feeling that `webView` is not the correct type, but I'd like to see the source to make sure.

After you attach the full source, I think it'll be easier for me to help you.

It also seems like some of the types that GVRGUISceneObject refers to have been deprecated, so I may submit a pull request to update the class for you, so it works properly with the most recent codebase.

**Comment by liaxim** [comment]
@channae Show us the webView type. The constructor expects something that derives from View and implements GVRView. By casting to GVRView you are passing something that from the compiler's perspective doesn't derive from View.

**Comment by NolaDonato** [comment]
Jonathan thanks for helping! Ragnar added GVRKeyboardSceneObject and made these changes as part of that (not sure why he had to do it though).

**Comment by ragner** [comment]
Hi,
before my last changes it was necessary to override the method onDraw(Canvas canvas) of each Android view that you would like to render in the scene.

Now with my recent changes it is not necessary override onDraw(...) anymore. GVRViewSceneObject can inflate and render any Android View directly.

So GVRView is deprecated because of this.

**Comment by channae** [comment]
Hi @J0Nreynolds & @liaxim,

Thank you for your response. I'm trying to get Gear VR's touchpad to work for onClick events. Basically I have two requirements. 
1. WebView which requires user interaction 
2. Android Layout which requires user interaction (FrameLayout with buttons, clickable ListView etc).

 I could resolve the constructor calling problem with the given insight. Initially I was trying to pass View, GVRView, WebView, FrameLayout objects to the GVRGUISceneObject's constructor and IDE was giving errors due to type mismatch.

Then I tried passing GVRWebView & GVRFrameLayout objects respectively. Even though these classes are deprecated, objects of these classes derive from View and implements GVRView. Then IDE stopped giving errors but I noticed a very strange behavior when testing out the application. 

As an example, If I pass GVRWebView to the GVRGUISceneObject's constructor, when testing out the application, my application starts and displays my web view in native android's fullscreen mode (as in there were no two camera rigs, just one webview entirely filled the phone's screen). If I pass GVRFrameLayout, my entire screen gets filled with one frame layout. Even though these web views and frame layouts gets added to GVRScene only If I gaze at certain GVRCubeSceneObjects, gazing gets ignored and these views fills entire screen and only shows the respective passing view.

Then I could resolve this by writing custom classes as follows and use them for GVRGUISceneObject's constructor. 
1. CustomFrameLayout extends FrameLayout implements GVRView
2. CustomWebView extends WebView implements GVRView 

Now the application starts in the expected behavior with VR mode (2 camera rigs). As expected, respective web view and frame layout only displays if I gaze at GVRCubeSceneObject.  

**Now the problem is with getting Gear VR's touchpad to work for the WebView and android activity (Frame Layout). I posted my frame layouts code below (web view is also written in a similar way). Am I missing a step?** (I know multiple GVRScene(s) are not recommended but I have written this way for the time being).

```
public class EmailActivity {

    private final CustomFrameLayout frameLayout;
    private static final float QUAD_X = 1.5f;
    private static final float QUAD_Y = 1.0f;
    private static float NORMAL_CURSOR_SIZE = 0.1f;
    private GVRSceneObject cursor;
    public GVRScene emailScene;
    private GVRContext context;
    private GVRGUISceneObject gvrguiSceneObject;

    public EmailActivity(SilVRActivity activity, final CustomFrameLayout frameLayout) {
        this.frameLayout = frameLayout;
    }
    // new GVRScene object is passed here to view layout scene object
    public void initScene(GVRContext gvrContext, GVRScene scene) {

        this.emailScene = scene;
        context = gvrContext;

        // setting new GVRScene as the MainScene
        gvrContext.setMainScene(emailScene);

        GVRCameraRig mainCameraRig = scene.getMainCameraRig();

        mainCameraRig.getLeftCamera()
                .setBackgroundColor(Color.BLACK);
        mainCameraRig.getRightCamera()
                .setBackgroundColor(Color.BLACK);

        /*gvrguiSceneObject = new GVRGUISceneObject(gvrContext, frameLayout,
                context.createQuad(QUAD_X, QUAD_Y));*/

        gvrguiSceneObject = new GVRGUISceneObject(gvrContext, frameLayout, context.createQuad(QUAD_X, QUAD_Y));

        emailScene.addSceneObject(gvrguiSceneObject);

        gvrguiSceneObject.getTransform().setPosition(0.0f, 0.0f, -1.5f);

        // set up the input manager for the current main scene
        GVRInputManager inputManager = context.getInputManager();
        inputManager.addCursorControllerListener(listener);
        for (GVRCursorController cursor : inputManager.getCursorControllers()) {
            listener.onCursorControllerAdded(cursor);
        }
    }

    private CursorControllerListener listener = new CursorControllerListener() {

        @Override
        public void onCursorControllerRemoved(GVRCursorController controller) {
            if (controller.getControllerType() == GVRControllerType.GAZE) {
                if (cursor != null) {
                    emailScene.getMainCameraRig().removeChildObject(cursor);
                }
                controller.setEnable(false);
            }
        }

        @Override
        public void onCursorControllerAdded(GVRCursorController controller) {
            // Only allow only gaze
            if (controller.getControllerType() == GVRControllerType.GAZE) {

                cursor = new GVRSceneObject(context,
                        context.createQuad(NORMAL_CURSOR_SIZE, NORMAL_CURSOR_SIZE),
                        new GVRAssetLoader(context).loadTexture(new GVRAndroidResource(context,
                                R.raw.cursor)));

                cursor.getTransform().setPosition(0.0f, 0.0f, -1.5f);
                emailScene.getMainCameraRig().addChildObject(cursor);
                cursor.getRenderData().setDepthTest(false);
                cursor.getRenderData().setRenderingOrder(100000);
                controller.setPosition(0.0f, 0.0f, -1.5f);
                controller.setNearDepth(-1.5f);
                controller.setFarDepth(-1.5f);
            } else {
                // disable all other types
                controller.setEnable(false);
            }
        }
    };
}
```
Thanks,
Channa

**Comment by liaxim** [comment]
@channae You might to look at @J0Nreynolds 's gvr-gui demo in https://github.com/J0Nreynolds/GearVRf-Demos/tree/gui-demo. Does it do what you want?

**Comment by channae** [comment]
Hi @liaxim,

Thanks for pointing me to the right direction. I tested and went through the given gvr-gui sample. Seems like this sample fulfills my requirement of interacting with android layout. 

Then I further checked the onClick not executing issue by comparing my application’s source with the gvr-gu sample. To understand the issue I copy pasted the sample code and added a very simple layout with two Buttons which changes the TextView (doing this lessen the interactive.xml layouts height as I removed sample’s UI elements. 

Seems like buttons are working however onClick methods only gets executed If I point the cursor away from the framelayout. Seems like positioning/size of my android UI is not in sync with the GearVRfs UI coordinates. 

According to the GVRGUIScene doc [1], "the mesh will always have the correct aspect ratio”. Which makes me suspect this could be a positioning issue. Are there any logic behind keeping positioning in sync with android UI and gearvr UI elements? 

private static final float DEPTH = -1.5f;

layoutSceneObject = new GVRGUISceneObject(gvrContext, frameLayout, 3f, 45f);
mainScene = gvrContext.getMainScene();
mainScene.addSceneObject(layoutSceneObject);
layoutSceneObject.getTransform().setScale(1.0f, 1.0f, 1.0f);
layoutSceneObject.getTransform().setPosition(-1.5f * DEPTH, 0.0f, 1.5f * DEPTH);
layoutSceneObject.getTransform().setRotationByAxis(-45.0f, 0.0f, 1.0f, 0.0f);
layoutSceneObject.setName("GUIObject”);

As you can see above I’m using the same values for my FrameLayout as given in gvr-gui. But my touch events does not get dispatched accurately.

Thanks,
Channa 

[1] http://gearvrf.org/api_reference/v3.3/Framework/org/gearvrf/scene_objects/GVRGUISceneObject.html

**Comment by channae** [comment]
It is confusing since my application's touch events dispatched very accurately when I was using 3.1.2-SNAPSHOT.

I positioned the cursor 0,0,-1.5, ViewSceenObject (frameLayout) at 0,0,-1.5. Seems like this positioning does not work when working with GVRGUISceneObject

**Comment by channae** [comment]
Seems like even though the touch events gets dispatched onClick (tapping screen in developer mode or using touch pad of GearVR device) did not work due to following line in GVRGUISceneObject class.

`properties.toolType = MotionEvent.TOOL_TYPE_MOUSE;`

Changing above to following fixed the issue. 

`properties.toolType = MotionEvent.TOOL_TYPE_FINGER;`

Therefore closing the ticket.
