### ISSUE TITLE
Overheating message

### ISSUE THREAD

**Issue by mathieurazafimahazo** [Samsung/GearVRf#1474]
Hi,

More a question than an issue, is there a way to force an app not displaying the "overheating message" that puts the running app in the background ?
That is really annoying, we would prefer to keep the user inside the running app and display our own "overheating message".

Thank you

**Comment by bohuang3d** [comment]
That seems like a OS safeguard feature. Without it the running app would deplete battery or cause damage to the phone.

As this is a system feature, you may want to consider Android's:

> https://developer.android.com/reference/android/os/BatteryManager.html
> 
> String EXTRA_TEMPERATURE
> Extra for ACTION_BATTERY_CHANGED: integer containing the current battery temperature.

and display warning messages accordingly

**Comment by bohuang3d** [comment]
to close tomorrow
