### ISSUE TITLE
GVRCubeSceneObject is not visible by default

### ISSUE THREAD

**Issue by nitosan** [Samsung/GearVRf#1476]
If you create a `GVRCubeSceneObject` with the following code, it will not be visible

```java
            GVRCubeSceneObject cube_obj = new GVRCubeSceneObject(gvrContext);
            cube_obj.getRenderData().getMaterial().setColor(1, 0, 0);
            cube_obj.getTransform().setPosition(0, -1, -2);
            gvrContext.getMainScene().addSceneObject(cube_obj);
```

Ideally, you should be able to see a red cube with above code.

Here is the sample project that can reproduce this issue.

https://github.com/nitosan/GearVRf-bugs/blob/master/create_cube/app/src/main/java/com/example/org/gvrfapplication/MainActivity.java#L38

**Comment by NolaDonato** [comment]
The default shader if none is specified is the Texture shader. If you don't supply a texture when you are using this shader, it will not render the object. If you use the Phong shader with only a color, that will work. This is fixed in the upcoming 4.0 release.

**Comment by liaxim** [comment]
@nitosan 

This will do what you want:
```
            GVRCubeSceneObject cube_obj = new GVRCubeSceneObject(gvrContext);
            cube_obj.getRenderData().getMaterial().setVec4("diffuse_color", 1, 0, 0, 1);
            cube_obj.getRenderData().setShaderTemplate(GVRPhongShader.class);
            cube_obj.getTransform().setPosition(0, -1, -2);
            gvrContext.getMainScene().addSceneObject(cube_obj);
```

setColor sets the u_color uniform for the texture and other legacy shaders.

**Comment by nitosan** [comment]
@liaxim Thanks for the sample code, although this code sample works, I kinda feel that a developer should be able to set the color w/o digging into the inner works of material.

**Comment by liaxim** [comment]
@nitosan No question about that. There needs to be a specific method for something as common as this.

**Comment by liaxim** [comment]
@nitosan Your snippet works in 4.0. Can we close the issue? Do you have any specific suggestion how to improve the code in 4.0?

**Comment by nitosan** [comment]
Verified working with 4.0.0
