### ISSUE TITLE
MainCameraRig.HeadTransform -> strange values on black headset

### ISSUE THREAD

**Issue by felislynx-silae** [Samsung/GearVRf#1477]
I'm getting very strange values of head transform from black headset (bought with S7). On white headset(bought with S6) values are correct.
My team developed system which shows on pc where i'm looking in VR. In S6, S7 with dev mode on it looks perfect, dev mode off and white headset, perfect. Black headset, completely strange values from camera rig headtransform.

**Comment by liaxim** [comment]
Rather unusual and unexpected. The only real difference is that we slightly change the fov-y for the black headset. As usual, if you can give us some sample we will study it. If the head transform is weird I expect your whole experience in VR is not going to be very pleasant.

It is also possible to be a thread-safety problem. You can try putting all operations dealing with the head transform on the GL thread by using GVRContext.runOnGlThread.

**Comment by felislynx-silae** [comment]
```
 val cameraTransform = gvrContext.mainScene.mainCameraRig.headTransform
val quat = Quaternionf(cameraTransform.rotationX, cameraTransform.rotationY,
                    cameraTransform.rotationZ, cameraTransform.rotationW)
            val vec = Vector3f(0f, 0f, -1f)
            vec.rotate(quat.rotate(0f, 0f, 0f))
            vec.normalize()

```
This is code that i'm calling in GVRDrawFrameListener to create vector which is then sent to pc to display where i'm looking. And only on black headset it's not pointing "forward", but other way around.

**Comment by bohuang3d** [comment]
If you can list the erroneous value sets, wonder if we can see some clues. I.e., check orthogonality, mirroring, etc..

**Comment by felislynx-silae** [comment]
Values from Galaxy S6, both headsets in same position (on table), so values should be almost identical between headsets
```
Black Headset
GVRTransform 44b7367f, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.9988307, rotationX = -0.027601117, rotationY = 0.039217375, rotationZ = 0.006117688
GVRTransform 44b7367f, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.9988308, rotationX = -0.027637353, rotationY = 0.039198652, rotationZ = 0.006070407
GVRTransform 44b7367f, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.9988268, rotationX = -0.027863104, rotationY = 0.03918404, rotationZ = 0.005790068
GVRTransform 44b7367f, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.9988263, rotationX = -0.027954463, rotationY = 0.039139785, rotationZ = 0.005725508
GVRTransform 44b7367f, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.998826, rotationX = -0.027942883, rotationY = 0.039155256, rotationZ = 0.005758143
GVRTransform 44b7367f, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.99882853, rotationX = -0.027926676, rotationY = 0.039111305, rotationZ = 0.0057380847
GVRTransform 44b7367f, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.99883056, rotationX = -0.027873315, rotationY = 0.03907512, rotationZ = 0.0058893263
GVRTransform 44b7367f, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.99883235, rotationX = -0.027875626, rotationY = 0.039034747, rotationZ = 0.0058722035
GVRTransform 44b7367f, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.9988309, rotationX = -0.027893981, rotationY = 0.03907219, rotationZ = 0.005830617
GVRTransform 44b7367f, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.9988322, rotationX = -0.027856786, rotationY = 0.039053004, rotationZ = 0.005883728

White Headset
GVRTransform 130761ff, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.9997338, rotationX = 0.0027420712, rotationY = -0.022590924, rotationZ = 0.003850496
GVRTransform 130761ff, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.99973387, rotationX = 0.002739822, rotationY = -0.022585567, rotationZ = 0.0038536491
GVRTransform 130761ff, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.999734, rotationX = 0.0026979586, rotationY = -0.02259492, rotationZ = 0.0038381864
GVRTransform 130761ff, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.99973404, rotationX = 0.0027237844, rotationY = -0.022598252, rotationZ = 0.0038357489
GVRTransform 130761ff, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.99973375, rotationX = 0.0027217455, rotationY = -0.022608561, rotationZ = 0.0038202375
GVRTransform 130761ff, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.99973357, rotationX = 0.0027040183, rotationY = -0.022629598, rotationZ = 0.0038024914
GVRTransform 130761ff, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.9997345, rotationX = 0.0026731663, rotationY = -0.022601396, rotationZ = 0.0037924184
GVRTransform 130761ff, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.99973446, rotationX = 0.0026604948, rotationY = -0.022600997, rotationZ = 0.0038074825
GVRTransform 130761ff, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.9997348, rotationX = 0.0026023986, rotationY = -0.022596786, rotationZ = 0.0037969085
GVRTransform 130761ff, positionX = 0.0, positionY = 0.0, positionZ = 0.0, scaleX = 1.0, scaleY = 1.0, scaleZ = 1.0, rotationW = 0.9997353, rotationX = 0.0026024804, rotationY = -0.022570862, rotationZ = 0.0038060115
```

**Comment by liaxim** [comment]
@felislynx-silae The quaternions represent some rotation, not orientation in the physical world. Do you want to somehow determine whether the phones have the same physical orientation?

**Comment by felislynx-silae** [comment]
@liaxim Imagine streetview. You can watch photosphere, and camera is stationary inside of sphere "world". All you can move is "head" to look around. This is almost the same situation in my case. In my world camera is stationary (or rig, i'm not sure how to name it in English :) ), all you can do is move your head to look around. I have been using head transform to create vector. 5 vectors actually.
```
fun transferViewport() {
        val cameraTransform = gvrContext.mainScene.mainCameraRig.headTransform
        fun createVector(x: Float, y: Float, z: Float): Vector3 {
            val quat = Quaternionf(cameraTransform.rotationX, cameraTransform.rotationY,
                   cameraTransform.rotationZ, cameraTransform.rotationW)
            val vec = Vector3f(0f, 0f, -1f)
            vec.rotate(quat.rotate(x, y, z))
            vec.normalize()
            return vec.toVec3(Vec3Type.UnitForward)
        }
        val xRot = gvrContext.mainScene.mainCameraRig.centerCamera.fovY / 2
        val yRot = xRot * gvrContext.mainScene.mainCameraRig.centerCamera.aspectRatio
        val viewport = Viewport(createVector(xRot, yRot, 0f), // TOP LEFT
                createVector(-xRot, yRot, 0f), // BOTTOM LEFT
                createVector(xRot, -yRot, 0f), // TOP RIGHT
                createVector(-xRot, -yRot, 0f), // BOTTOM RIGHT
                createVector(0f, 0f, 0f)) // CENTER
        sendCameraViewport(viewport)
    }
```

**Comment by felislynx-silae** [comment]
[Image](https://drive.google.com/open?id=0Bzu1FkBNLSmkVkJ5LWE3c2k0bG8) <-- this is how it looks in pc when everything is correct

**Comment by liaxim** [comment]
@felislynx-silae Fyi, while we apply some operations to them, the quaternions we get from the Oculus SDK (ovr_activity.cpp).
```
        const ovrQuatf& orientation = updatedTracking.HeadPose.Pose.Orientation;
        const glm::quat tmp(orientation.w, orientation.x, orientation.y, orientation.z);
        const glm::quat quat = glm::conjugate(glm::inverse(tmp));

        cameraRig_->setRotationSensorData(0, quat.w, quat.x, quat.y, quat.z, 0, 0, 0);
        cameraRig_->updateRotation();
```

Based on my understanding, these are rotation quaternions so there is no reference coordinate system. They are the result of the integration the sensor fusion the Oculus SDK does.

**Comment by thomasflynn** [comment]
in any case, I would expect the rotations to be pretty similar between headsets.  I am half wondering if this is a docking problem.

**Comment by felislynx-silae** [comment]
@liaxim I understand that. We are transforming rotations to "lat,lang" system. Which works pretty well. Except, that black headset makes no sense. And as @thomasflynn said, rotations should be similar since i'm testing both headsets on table within same spot. I've tried 2 galaxy S6 and 1 S7 and result is the same. All phones in black headset send different data than in white headset or in programmer mode.

**Comment by felislynx-silae** [comment]
I've cleaned connectors in headset, checked them, phone also. Still nothing changed in them. Is this a possibility that this headset is somehow broken?

**Comment by liaxim** [comment]
The different headset models have different calibration data. If the apps run fine and the head tracking is nice and smooth with this headset, then it can't possibly be broken. For geographic coordinate system I think you should be looking at the magnetometer.

**Comment by felislynx-silae** [comment]
it's not lat,lang it's "lat","lang". So instead of typical 3D coordinates i'm using X (degrees), Y (degrees). Since my world is similar to world in streetview (sphere) X,Y was easier to use. head transform is used to pass my viewport as you can see in screenshot. To determine where i'm looking at sphere.

**Comment by felislynx-silae** [comment]
I'll try to get my hands on S8 and S8 headset. This one i haven't tried yet. But i don't think that headtransform should be different if phone is in exact same position.

**Comment by bohuang3d** [comment]
These two images correspond to the first entry of the two list converted to Euler angles (in ZYX order). 

Note: the positive and negative values for Y do not make a difference in terms of the final orientations. Thus these two sets of Euler angles, and by extension the corresponding quaternions, are the same.

![quart2](https://user-images.githubusercontent.com/5192187/30981945-c71b73dc-a43a-11e7-8193-25c3c5fa76dd.JPG)
![quat1](https://user-images.githubusercontent.com/5192187/30981944-c718353c-a43a-11e7-982f-47e2786999c6.JPG)

**Comment by felislynx-silae** [comment]
@bohuang3d (-180,177,0) and (-179,-175,-3) are not identical since Y is negative in second rotation. i think, that beeing in one headset and in another should give same result for same rotation.

**Comment by bohuang3d** [comment]
@felislynx-silae 

Let's simplify to (-180, 180, 0), and (-180,-180, 0)

The way I interpret these two vectors is,

(-180,180,0):
1. rotate 0 degree around z, which can be ignored.
2. Then rotate +180 degree around y (vertical up). +180 is equivalent to the GearVR turning left 180 degrees if using the right hand rule.
3. and finally rotate -180 degree around x.

(-180,-180,0):
1. rotate 0 degree around z, which can be ignored.
2. Then rotate -180 degree around y (vertical up). -180 is equivalent to the GearVR turning right 180 degrees if using the right hand rule.
3. and finally rotate -180 degree around x.

The second steps for both cases produce equivalent result for that particular step --- that the GearVR faces the opposite direction of where it started at the previous step.

**Comment by bohuang3d** [comment]
to close tomorrow.

I assume there is no visual problems
