### ISSUE TITLE
Creating GVRWebView or GVRFrameLayout in onCreate forces the GVR application to run declared view in Monoscopic

### ISSUE THREAD

**Issue by channae** [Samsung/GearVRf#1545]
**GVRf version**: 3.3.1-SNAPSHOT
**gvr.xml**:

```
        <mono-mode-parms
            monoFullScreen="false"
            monoMode="false" />
```

GVR application forces to run in monoscopic view when we create an object as follows,
`GVRWebView webView = new GVRWebView(this)`
or
`GVRFrameLayout frameLayout = new GVRFrameLayout(this);`

Further debugging above classes I found out its causing when executing following line in above constructors:
`context.registerView(this);`

I know GVRWebView and GVRFrameLayout classes are deprecated but I need to use these as GVRGUISceneObject expects objects of these classes.

Thanks,

**Comment by liaxim** [comment]
@channae Replace the use of GVRWebView with WebView and GVRFrameLayout with FrameLayout. That should be enough.

For example I updated one of our demos exhibiting the same problem: https://github.com/gearvrf/GearVRf-Demos/pull/540

**Comment by channaAuxenta** [comment]
Hi @liaxim,

Thanks for the quick response. I was using the GVRViewSceneObject with WebView before GVRGUISceneObject class was introduced. 

Problem with GVRViewSceneObject is that touch events cannot be dispatched to the WebView. However even though GVRGUISceneObject class is handling touch events it uses deprecated classes which results in forcing to monoscopic mode.

Thanks,

**Comment by channae** [comment]
Hi @liaxim,

Thanks for the quick response. I was using the GVRViewSceneObject with WebView before GVRGUISceneObject class was introduced. 

Problem with GVRViewSceneObject is that touch events cannot be dispatched to the WebView. However even though GVRGUISceneObject class is handling touch events it uses deprecated classes which results in forcing to monoscopic mode.

Thanks,

**Comment by liaxim** [comment]
@channae Luckily changing GVRGUISceneObject is rather straightforward. Here is the pull request https://github.com/Samsung/GearVRf/pull/1554. Let us know how it works for you. Thanks.

**Comment by channae** [comment]
Hi @liaxim, Good news is now the touch events gets when using View in GVRGUISceneObject class as you suggested. Now the issue is touch events coordinates are inaccurate.  

![screenshot_20171018-073553](https://user-images.githubusercontent.com/28370121/31698038-d72d367c-b3d8-11e7-84da-1f91679e7b83.png)

As you can see in the screenshot, I was able to navigate to "Getting Started" page. However clicking on top of the "Getting Started" link did not do anything. Navigation worked when I click on middle of the page (where the cursor is right now). I assume height and width of Android WebView is not in sync with rendered GVRGUISceneObject. Thanks :)

**Comment by liaxim** [comment]
@channae I have modified gvr-sceneobjects in https://github.com/liaxim/GearVRf-Demos/tree/webviewtest. While there is some offset, it is not as big as you describe. I want to get our tests in sync. There have been api changes and what not recently. This demo works with the 3.3 snapshot which I presume you use also. Are you consistently observing vertical offset only? If the app I shared is not quite what you have, could you please share a sample project?

**Comment by channae** [comment]
Hi @liaxim,

I was able to resolve the touch dispatch issue with WebView as you suggested. However I was seeing an extreme lag in dispatching touch events to the WebView.

**Approach with GVRWebView**

Then I tried to identify the root cause behind forcing GVRWebView to monoscopic view in my project (For this purpose I reverted GVRGUISceneObject to work with GVRWebView).

After further analyzing I could identify the root cause behind the issue and get it resolved. Now GVRWebView works in sterioscopc mode and its lag free and touch events are very accurate and responsive.

My app pop up with an interactive webview once the user gaze at a specific GVRCubeSceneObject. So the webview creation logic was used to execute at onStep after gazing at GVRCubeSceneObject. When using the 3.1.2-SNAPSHOT webview worked in sterioscopic mode even though touch events did not work.

Seems like when using gearvrf 3.3 onwards we need to create the GVRGUISceneObject with GVRWebView within onInit (which forces to run in sterioscopic mode) and add it to the main scene during onStep.

Now I'm trying to get my GVRFrameLayout working so I added below in onInit and got rid of the monoscopic issue of my GVRFrameLayout,

`layoutObject = new GVRGUISceneObject(gvrContext, gvrFrameLayout, gvrContext.createQuad(Utils.QUAD_X, Utils.QUAD_Y));`

However touch events does not get dispatched when I follow the same steps I did as GVRWebView. Do you have a working sample which uses GVRGUISceneObject with GVRFrameLayout?

Thanks,
Channa

**Comment by channae** [comment]
Hi @liaxim,

As I couldn't move ahead with the GVRGUISceneObject with GVRFrameLayout approach (Even though I could managed to work with GVRGUISceneObject with GVRWebView). I changed my previous picking code and replaced following deprecated method and got it to work with GVRViewSceneObject.

deprecated: `float[] hitPoint = event.getHitPoint();`
replaced by: `float[] hitPoint = event.getPickedObject().getHitLocation();`

Thanks,
Channa

**Comment by liaxim** [comment]
@channae I am glad you are moving along nicely. Can we close this issue then? Please open other issues in case you experience different problems.

You must have learned a lot. Do you have any fixes or suggestions how to improve the framework? We would be happy to incorporate them.

**Comment by channae** [comment]
Hi @liaxim,

Sorry for the late response. This issue can be closed as I'm creating GVRGUISceneObjects with respective GVRFrameLayout, GVRWebView objects during onInit to get rid of monoscopic issue. 

Sure I'll let you know if I find any more issues/fixes that could help to improve the framework. Also appreciate the support given to me through out the development.

Thanks,
Channa
