### ISSUE TITLE
[UPDATE] Can't run samples on S5 [+with Lollipop libraries]. 

### ISSUE THREAD

**Issue by phi-lira** [Samsung/GearVRf#155]
When I run samples on S5 I only get a screen with clear color displayed. Nothing gets rendered besides that. Checking logcat it outputs a couple of <core_glEnableVertexAttribArray:193>: GL_INVALID_VALUE

I'm on Android 5.0. G900M.

Here follows logcat output.
![logcat_s5](https://cloud.githubusercontent.com/assets/7453395/8607832/d67385c4-2663-11e5-9b6e-672eeabec886.JPG)

**Comment by lokeshguddu** [comment]
Hi @phi-lira ,

I think you can only use the devices that are mentioned in the developer documentation.

Hardware Requirements: Samsung Galaxy Note 4 or Samsung Galaxy S6.

Hope it helps.

**Comment by thomasflynn** [comment]
The S5 I have has a QualComm GPU.  Is your a Mali device?

And @lokeshguddu if you run on a device other than Note 4 or S6, then it will fall back to the monoscopic renderer.  It will still run, but you will only see one eye, centered in the middle of the screen.

**Comment by phi-lira** [comment]
@thomasflynn  Mine is Qualcomm Snapdragon too. Can you send me an apk so I can confirm is not something on my build settings?

**Comment by thomasflynn** [comment]
There's a limit on the size of attachments we can send over email and even simple-sample is just barely over the limit.  Instead, I created a branch and checked them in :).  Go here:

https://github.com/thomasflynn/GearVRf/tree/s5/GVRf/apks

I have apks for both simple-sample and solar-system.  They both work on my s5.  Let me know if they work for you.

**Comment by phi-lira** [comment]
@thomasflynn Thanks for the apks and sorry for the delay to reply this. I got tangled in some issues. 

Ok. Both of them are working perfecly here, which means it's definitely something on my environment. Do you make any changes to manifest (like vr-dual or something else) or to project to get this working on S5?

**Comment by thomasflynn** [comment]
no changes.

**Comment by phi-lira** [comment]
Oh boy. I'll try to figure it out what's happening. 

I'll close this.

**Comment by phi-lira** [comment]
Found out the problem. It does work on S5 when building with lollipop libraries (api 21 and above). 
I built with api 19 and it's working now. 

I'm not sure if this is a known issue or not. That's why I'm reopening this.

**Comment by thomasflynn** [comment]
perhaps we need to start comparing configurations?  I changed simple-sample's AndroidManifest.xml from:

    <uses-sdk
        android:minSdkVersion="19"
        android:targetSdkVersion="21" />

to

    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="21" />

and that still works.  Also made sure all my android sdks were up to date.  What else do I need to do?

**Comment by phi-lira** [comment]
I was previously building libOVR, VrApi, VrAppFramework and Framework with Library 5.0.1 set on my Android build target. Now that I changed it to 4.4.2 it worked.

![buildpath](https://cloud.githubusercontent.com/assets/7453395/8730596/cdd95162-2bbf-11e5-9e28-8b7a4dc1190a.JPG)

I also changed Oculus SDK 0.6.0 to 0.6.1 (but I'm almost certain I tested before changing build path and it didn't work)

**Comment by thomasflynn** [comment]
ok, set all my projects to 5.0.1, still worked.  still worked.  I've been using Oculus SDK 0.6.0.1 since i did the port to it.  maybe there's a difference between building on Linux vs Windows.  i'm about to be sucked into endless meetings most of the rest of the day.  I'll try a build from Windows after I get out.

**Comment by phi-lira** [comment]
No. Don't bother. I just reverted back to 5.0.1 and it worked. I guess this is one of those problems that gets fixes by itself and I'm just glad it's working now. 

Closing again. Sorry for the mess.
