### ISSUE TITLE
Don't call virtual functions from destructors and constructors

### ISSUE THREAD

**Issue by dnvasilev** [Samsung/GearVRf#1567]
**"Don't call virtual functions from destructors"** is a rarely-thought-of C++ (mis)feature. When a C++ object goes away, destructors are called in sequence, first the leaf class (most derived) destructor (destroying the leaf-specific parts of the object) in turn all the way to the top-of-the-inheritance-tree base object. Destructor destroys the underlying _slice_ of the object, and memory occupied by this slice becomes a graveyard of non-functioning bits. However if a base destructor calls into a virtual function, implementation will pick ~~the most-derived implementation of the virtual function and pass _this_ pointer to a corpse of the corresponding derived object.~~ the current class implementation of the virtual function and derived-class-specific actions will not be run. Bad. 

And yes, it happens in our code.

Example:
Component class has virtual destructor

      virtual ~Component();

that calls virtual function Component::set_owner_object(). There is only one implementation of this function, and it is in Component itself, and _we dodged one bullet_. Here's the implementation:

    inline Component::~Component() {
        set_owner_object(NULL);
    }

Component::set_owner_object() is another virtual function (_second bullet dodged_), and it calls other virtual functions, including, for example, Component::onDetach(). 

    virtual void onDetach(SceneObject* owner) { }

    inline void Component::set_owner_object(SceneObject *owner_object) {
        if (owner_object_) {
            onDetach(owner_object_);
        }
        . . .

EDIT: _during Component::~Component, onDetach() call selects Component::onDetach() implementation and never calls Transform::onDetach(). We don't call onTransformChanged(). This is a real bug._
~~onDetach() has implementation in Transform object, which will be destroyed and decompositing at the time Transform::onDetach() is called indirectly from Component::\~Component(). Luckily, Transform::onDetach() does not use any data members (why is it a member function then?) and _we dodged the third bullet_, but why are we **pushing our luck**?~~

    void Transform::onDetach(SceneObject *owner_object) {
        owner_object->onTransformChanged();
    }

**Comment by NolaDonato** [comment]
?Do you have an suggestion on what we should do about it?


________________________________

**Comment by dnvasilev** [comment]
But yes of course I have a suggestion!
**Don't call virtual functions from destructors**
Meaning: all polymorphism must be handled in the destructor itself. If you need to do something specific to Transform during destruction time, do it in Transform::~Transform(), and don't even think about calling a virtual function from Component::~Component()

**Comment by NolaDonato** [comment]
I understand you don't like that we call virtual functions from inside destructors. Let me know when you have a constructive suggestion for how we can implement the existing functionality while avoiding this pitfall.


________________________________

**Comment by dnvasilev** [comment]
In this particular case, the simplest solution is:

    inline Component::~Component() 
    {
        owner_object_ = nullptr; // avoid calling virtual set_owner_object(NULL);
    }

    inline Transform::~Transform() 
    {
        Transform::onDetach(owner_object_); // executed before code in Component::~Component()
    }

We need to refine the above to avoid code duplication and refine for the clarity of intent,
and then double-check and fix every constructor and destructor.

**Comment by dnvasilev** [comment]
My mistake -- description of the problem is inaccurate. After reading Dewhurst's Gotcha #75, CERT OOP50-CPP, and relevant parts of ISO IEC 14882, I see that during destruction object behaves as if its dynamic type is the same as static type of the destructor. That means we never call into a bucket of bits, but we also never call Transform::onDetach().

**Comment by dnvasilev** [comment]
- [ ] GLRenderer() should not call virtual createUniformBlock()
