### ISSUE TITLE
Internal sensor should be used only in developing

### ISSUE THREAD

**Issue by niusounds** [Samsung/GearVRf#157]
I think it is good idea that internal sensor rotates viewport in developing but it should be turned off in release APK for performance reason.
Probably `GVRInternalSensorListener.onSensorChanged` is no worth with in production environment. 

...isn't it?

**Comment by chenchao1407** [comment]
Do you mean that for released APK it will only be able to run with GearVR? Correct?

**Comment by niusounds** [comment]
I think GearVRf can be used only in app with GearVR.
If GearVRf supports (will support) not only GearVR but also other devices like a Cardboard or standalone app, I'm barking up the wrong tree.

**Comment by phyuzion** [comment]
@niusounds Yes correct, but we have plan that spread out to every devices. Thank you for your comment and we will do asap. :)
