### ISSUE TITLE
The ray in GVRGearControllerSceneObject is white instead of grey

### ISSUE THREAD

**Issue by SteveGreatApe** [Samsung/GearVRf#1588]
This seems to a be problem that's come in V4.0.0. The code for GVRGearControllerSceneObject tries to set the ray color to grey with all 0.5f RGB values, but it hasn't selected the GVRPhongShader so it still comes out white.

Here's a little function to work around the problem, and also let you change the color.

```
    private static void setRayColor(GVRGearControllerSceneObject controllerSceneObject, float red, float green, float blue, float alpha) {
        for(GVRSceneObject sceneObject : controllerSceneObject.getChildren()) {
            if (sceneObject instanceof GVRLineSceneObject) {
                GVRMaterial material = new GVRMaterial(sceneObject.getGVRContext(), new GVRShaderId(GVRPhongShader.class));
                material.setDiffuseColor(red, green, blue, alpha);
                material.setLineWidth(2.0F);
                sceneObject.getRenderData().setMaterial(material);
                break;
            }
        }
    }
```

**Comment by liaxim** [comment]
@SteveGreatApe Thank you for reporting this bug. Fixed by https://github.com/Samsung/GearVRf/pull/1604.

**Comment by liaxim** [comment]
We merged the fix. Can we close the issue?

**Comment by SteveGreatApe** [comment]
Yes, looks fixed now, thanks.
