### ISSUE TITLE
Problem building demos with AS 3.0 / Build Tools 26.0.2 on Windows

### ISSUE THREAD

**Issue by NolaDonato** [Samsung/GearVRf#1594]
I am trying to build gvr-simplesample with the latest master using Android Studio 3.0. It insists on using build tools 26.0.2 so I let it upgrade the gradle files. After upgrading, it complains it cannot refresh the project:
Error:Cannot set the value of read-only property 'outputFile' for ApkVariantOutputImpl_Decorated{apkData=Main{type=MAIN, fullName=debug, filters=[]}} of type com.android.build.gradle.internal.api.ApkVariantOutputImpl.

I looked this error up on the web and a suggestion led to changing outputFile to outputFileName in common.gradle:
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.outputFileName = new File(
                    output.outputFile.parent,
                    System.getProperty("appName") + ".apk")
        }
    }
This will let Android Studio read the project in but I still cannot build gvr-simplesample:
Execution failed for task ':gvr-simplesample:packageDebug'.
> Cannot create directory D:\projects\android\GearVRf-Demos\gvr-simplesample\app\build\outputs\apk\debug\D:\projects\android\GearVRf-Demos\gvr-simplesample\app\build\intermediates\instant-run-resources

There appears to be some issue using Build Tools 26.0.2 but I did not run into this problem on Linux. It only started after I tried to build at home using Windows.

**Comment by liaxim** [comment]
The problem is Gradle v4.1. Do not update to it. One day somebody will upgrade our gradle files to work with it but not today.

**Comment by liaxim** [comment]
Can we close?

**Comment by NolaDonato** [comment]
Yes, older grade works.
