### ISSUE TITLE
GVRCylinderSceneObject ignores HasBottomCap parameter

### ISSUE THREAD

**Issue by SteveGreatApe** [Samsung/GearVRf#1638]
The GVRCylinderSceneObject(GVRContext gvrContext, CylinderParams params) version of the constructor ignores the HasBottomCap parameter and always adds the bottom cap. From looking at the code other versions of the constructor might take note of this parameter and work correctly.

The problem is in the `void generateCylinder(CylinderParams params)` function, you can see when creating the top cap it checks params.HasTopCap is true, but the similar check when creating the bottom cap is missing.

**Comment by mwitchwilliams** [comment]
I hope to address this issue beginning December 11 (2017 of course).

**Comment by liaxim** [comment]
@SteveGreatApe Fixed by https://github.com/Samsung/GearVRf/pull/1661. Can we close the issue? Thanks.

**Comment by SteveGreatApe** [comment]
The change looks right, but I'm not using the latest branch so can't actually test it.

I did look at moving over to the latest code, but changes to the Picker handling seemed quite complex, and I couldn't find any example to help show to move over to them so I've stuck on 4.0 for now. Maybe that subject needs a new issue itself.

**Comment by liaxim** [comment]
Sure, for the picker created https://github.com/Samsung/GearVRf/issues/1666.
