### ISSUE TITLE
collision.getTextureCoords() in onInside(GVRSceneObject sceneObj, GVRPicker.GVRPickedObject collision) returns null

### ISSUE THREAD

**Issue by channae** [Samsung/GearVRf#1639]
Hi,

Im trying to find coordinates where my ray/cursor hits in GVRWebView. I implemented public void onInside(GVRSceneObject sceneObj, GVRPicker.GVRPickedObject collision) of IPickEvents interface for this purpose.

I put logs and I can see onInside method gets triggered when I point cursor towards it. However the collision.getTextureCoords() method always returns a null float array.

My use case is to programmatically trigger a touch event in my GVRWebView. However it requires texture coords as an input parameter to create an instance of MotionEvent.     

Gearvrf version: 3.3.1-SNAPSHOT

Thanks,
Channa

**Comment by NolaDonato** [comment]
Your mesh collided needs to enable the texture coordinate generation. Use the GVRMeshCollider(GVRContext, GVRMesh, Boolean) constructor and set the last argument to true to enable records. The mesh may be null and it will be obtained from the GVRSceneObject the collided is attached to.

**Comment by channae** [comment]
Hi @NolaDonato,

Thanks for the prompt reply. Now I changed my code from, 

`webViewObject.attachComponent(new GVRMeshCollider(gvrContext, true));`

to 

`webViewObject.attachComponent(new GVRMeshCollider(gvrContext, new GVRMesh(gvrContext), true));`

Now my onInside method does not trigger at all. Is there anything else that I'm missing here? Thanks

**Comment by channae** [comment]
update: If I pass new GVRMesh(gvrContext), onInside methods does not trigger at all

**Comment by NolaDonato** [comment]
You don't need to give it a separate mesh. If you leave the mesh as null, it will use the mesh attached to the GVRRenderData component of the GVRSceneObject that owns the collider.

**Comment by channae** [comment]
Hi @NolaDonato,

Your solution works. Closing the ticket.

Thanks,
Channa
