### ISSUE TITLE
Render GVRWebView/WebView in a curved rectangle SceneObject

### ISSUE THREAD

**Issue by channae** [Samsung/GearVRf#1645]
Hi all,

I would like to discuss your suggestions/approaches to implement GVRWebView/WebView to render into a curved SceneObject (other than flat rectangle) so that it will be more comfortable to view in the VR headset.

Also will this cause issues with touch dispatch inaccuracy issues? Or any functionalities that would break?

Thanks,
Channa

**Comment by NolaDonato** [comment]
GVRMesh.createCurvedMesh can be used to create the mesh for the web view. Then you can use the normal GVRWebViewSceneObject constructor:
GVRMesh mesh = new GVRMesh.createCurvedMesh(context, width, height, centralAngle, radius);
GVRWebViewSceneObject webview = new GVRWebViewSceneObject(context, mesh, webview);
Is this what you are looking for?

**Comment by channae** [comment]
Hi @NolaDonato,

This is exactly what I was looking for. 

Thanks,
Channa
