### ISSUE TITLE
Camera parameter "vrmode" for camera2

### ISSUE THREAD

**Issue by sexydot** [Samsung/GearVRf#1673]
Hello,
I want to use camera2 api on my app.

`parms.set("vrmode", 1); // vr mode `

Can I use above parameter for camera2?
I checked camera2 api for this and It has different parameter settings compare with camera api.
If it can be used, Please tell me how I can use it.

Thank you!

**Comment by nitosan** [comment]
Do you want to use camera2 api to achieve high FPS for the android camera?

Take a look at this sample 
https://stackoverflow.com/questions/41945407/low-fps-with-camera2-api

Keep in mind that in order to have high FPS, record at a low resolution.

**Comment by sexydot** [comment]
Thank you for your answer @nitosan 

`parms.set("vrmode", 1); // vr mode`
Is above code only for high FPS?

`                // set vr mode
                params.set("vrmode", 1);

                // true if the apps intend to record videos using
                // MediaRecorder
                params.setRecordingHint(true);

                // set preview size
//                params.setPreviewSize(1440,1080);
//                params.setPreviewSize(640, 480);

                // set fast-fps-mode: 0 for 30fps, 1 for 60 fps,
                // 2 for 120 fps
                params.set("fast-fps-mode", fpsMode);

                switch (fpsMode) {
                    case 0: // 30 fps
                        params.setPreviewFpsRange(30000, 30000);
                        break;
                    case 1: // 60 fps
                        params.setPreviewFpsRange(60000, 60000);
                        break;
                    case 2: // 120 fps
                        params.setPreviewFpsRange(120000, 120000);
                        break;
                    default:
                }
`

This code is in "GVRCameraSceneObject.java".
I'm not sure But I think "vrmode" is something different function with fps range.

**Comment by nitosan** [comment]
Yes, mostly for enable high FPS camera, checkout previous discussion

https://github.com/Samsung/GearVRf/issues/270

**Comment by sexydot** [comment]
I got it! Thank you.

**Comment by tangobravo** [comment]
I don't think there is a way to access the 60FPS "vrmode" camera modes via the camera2 API. It's something I'm interested to know too.
