### ISSUE TITLE
How to use it with UE4?

### ISSUE THREAD

**Issue by sambuev** [Samsung/GearVRf#1694]
Hello, I need to make a simple demo for GearVR using Unreal Engine 4.18.2 
I only know UE4, therefore, I can't use anything outside of it due to limited time and simplicity of the project for me it's better to use Unreal Engine. Do you know any templates for gearVR with a controller for UE4?

**Comment by nitosan** [comment]
Please follow this tutorial for Gear VR development in UE4. You should be able to have a working Gear VR UE4 project once you finish this tutorial.

https://docs.unrealengine.com/latest/INT/Platforms/GearVR/QuickStart/

**Comment by sambuev** [comment]
I've done a project in UE4 with GearVR, I looking for the ways to use Controller and probably some good templates to quickly get some basic functions. Is it possible with this GearVRf framerwork and UE4?

**Comment by nitosan** [comment]
Use GearVR framework with UE4 will be difficult at this stage. We'll let you know once we have better support in the future
