### ISSUE TITLE
Loading .obj file from assets: Fatal signal 11

### ISSUE THREAD

**Issue by Nathipha** [Samsung/GearVRf#1698]
I'm loading a single .obj and its texture from the "assets" folder using this code:

```
private void showObj() {
        try {
            GVRTexture dinoTex = gvrc.loadTexture(new GVRAndroidResource(gvrc,"A625.png"));
            GVRMaterial dinoMat = new GVRMaterial(gvrc);
            dinoMat.setMainTexture(dinoTex);
            GVRSceneObject dino = new GVRSceneObject(gvrc);
            GVRRenderData dinoRender = new GVRRenderData(gvrc);
            GVRMesh dinoMesh = gvrc.loadMesh(new GVRAndroidResource(gvrc, "A625_v2.obj"));
            dinoRender.setMesh(dinoMesh);
            dinoRender.setMaterial(dinoMat);
            dino.attachRenderData(dinoRender);
            scene.addSceneObject(dino);
        } catch (IOException e) {
            Log.e(tag, "Dino not found!");
            e.printStackTrace();
        }
    }
```

I've already managed to load a couple of files (.fbx/.obj + .jpg/.png) but this specific one is a huge one (80mb, 1.5mb for the png file - generated by Meshlab with 582379 vertices & 1161603 faces) and every time I try and load it, my app barely reacts to moving my head anymore, then freezes and crashes with these error messages:

> E/gvrf(27099): _ASSIMP_SCENE_NOT_FOUND_
> A/libc(27099): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x154 in tid 27099 (.company.myapp)

Google tells me that "fatal signal 11" probably means that the app ran out of memory, so I tried adding "android:largeHeap="true"" to the manifest but no luck.

2-3 mb files (including the trex and car one from the samples) don't seem to be a problem and using only parts of the vertices of the 80mb file, which ended up being a 20mb file, also worked, even though loading it took a couple of seconds, while everything else was pretty much instant.

Is there anything else I could try (framework version: 3.0.1, Galaxy S7 with Android 7) or is the file simply too huge to be loaded?

And another question:
Oculus Home keeps reminding me that there's a new version available and I can't use it anymore because of that message. Does anyone know if the latest version is still compatible with version 1.0.3 of the Oculus mobile SDK (which I'm using)?

**Comment by bohuang3d** [comment]
SIGSEGV is segmentation fault or bad memory access

You probably don't want to render 1+ million faces on a mobile device anyways

You can try split your mesh into multiple .obj files and see if that helps

**Comment by thomasflynn** [comment]
we should investigate the segv.  if a model is too big, we should fail more gracefully.

that being said, like Bo said, a model that big probably won't perform well.  Oculus has some mobile performance guidance here:  https://developer.oculus.com/documentation/unity/latest/concepts/unity-integration-mobile-performance-intro/

in short, keep vertices under 50,000 per eye and less than 100 draw calls.

**Comment by NolaDonato** [comment]
I would suggest that you try a mesh reduction tool if you want your application to perform on mobile. Did your mesh come from a digital content creation tools like Maya or Max? These can reduce mesh complexity. If not , then perhaps MeshLab might work for you.

http://www.meshlab.net/

**Comment by liaxim** [comment]
@Nathipha Do you happen to have a model you could share with us that exhibits the problem? We can at least make sure we fail gracefully.

**Comment by Nathipha** [comment]
Sorry for the late reply everyone (again :/)!

@bohuang3d 
Ah, that's what I thought. Interesting enough, I can load the 20mb 10x just fine, even 100x works, even though it's a little bit laggy then (lol).
I guess I wanted to see if it can do that. My .obj files currently are <10mb (usually <5mb or around that) and I won't load more than 4 or 5 at the same time, so that should be fine.

@thomasflynn 
Thanks for the link!

@NolaDonato 
The mesh was created with Meshlab. Thanks for the tip but it's not a problem, I just wanted to see if the app/phone can even handle a file that big and there shouldn't be any problems with the smaller files I'm currently using.

@liaxim 
Sorry, I didn't create (or "own" for that matter) the file, I'll have to ask the creator first.


Sorry, I know it's off topic but maybe someone here still knows:
Oculus Home keeps reminding me that there's a new version available. Does anyone know if the latest version is still compatible with version 1.0.3 of the Oculus mobile SDK (which I'm using)?

**Comment by bohuang3d** [comment]
loadModelFromSD() and loadModel() are deprecated and 
SD is for from the SD card.

GVRAssetLoader.loadModel(String) is the replacement that handles both SD and non-SD

**Comment by Nathipha** [comment]
@bohuang3d 
I'm using a pretty old version (3.0.1, just can't get the whole thing to work with Android Studio) and they aren't even marked as deprecated but so far I'm fine with what the version can do.
Ah, so only SD card, not also the internal storage, I see. Thanks!

I don't think so, my whole app builds on the framework and I'm not using any additional libraries. The only thing that isn't from the original 3.0.1 build is a change I had to make to the framework itself (NolaDonato posted the code) because there's a bug in 3.0.1 that won't let you clear the scene without crashing.

**Comment by bohuang3d** [comment]
I think Oculus always reminds you of updates independent of GearVRf.

Here is a past thread on Oculus Mobile SDK 1.7.0 seemingly working
https://github.com/Samsung/GearVRf/issues/1398

If your resources allow, consider migrating to latest as there will be less and less knowledge about past SDK and apis

**Comment by Nathipha** [comment]
@bohuang3d 
I'm not talking about the SDK but the version of the actual Oculus app. If I remember correctly, the last time I updated the app, it also told me to update the Oculus SDK, which is only compatible with so many versions of the GearVR framework.
I know for sure that the framework version 3.0.1 (which is the last version that's still compatible with Eclipse) is compatible with the Oculus SDK 1.0.3 because I'm currently using both. The thing is that I don't just want to update because I simply can't get my project (or even the framework) to work with Android Studio and I'd rather get my app to the point it needs to be soon first and only then deal with the problems of migrating to Android Studio (tried before and failed miserably).

**Comment by bohuang3d** [comment]
I don't know if the particular version combinations you seek would be compatible. How about you make a copy of your project and upgrade that copy to the versions you have doubts with?

Or you can start with a very simple example from one of the many in the GearVRf-demos repository. It is already integrated with Android Studios. And then you can incorporate your project into the sample you've chosen to start with.

**Comment by Nathipha** [comment]
@bohuang3d 
You're misunderstanding me. I'm not directly talking about my project but the Oculus app on the S7 I'm using to debug my app and also running it on.
To use the Gear VR glasses you have to install the Oculus app or, to be more exact, it installs itself and then also installs the e.g. Gear VR Service app, which lets you enable the Developer mode (to test your VR app without actually having the phone in the Gear VR glasses).
Said Oculus app checks for updates when (if) you connect your phone to the internet - which I sometimes have to do, even though I only use it for VR stuff - and, if I remember correctly, the second to last time I updated said Oculus app, it later complained, when I wanted to start my VR app I'm working on, that it wanted a new version of the Oculus SDK.
My problem is that if I install the new version of the Oculus app, I can't just revert back to the old one if it does the same thing again, which would then require me to also update the Gear VR framework, which would require me to port my whole project to Android Studio, which I currently don't have the time (or the patience) for.
That's why it would be good to know if anyone here is still using version 1.0.3 of the Oculus SDK but is also running the latest version of the Oculus app on their phone (in my case: the S7 with Android 7.0) and can actually still run their own app without Oculus or anything else complaining about versions.

I did already try to at least have the framework in Android Studio but that wouldn't build, even an empty project with tiny bits of code didn't.
Once I'm done with what I have to finish atm, I can still open a new thread here to get Android Studio to work finally but until then I'd rather use Eclipse with the old version that I know is working properly.

@liaxim 
I got permission to upload the .obj file, is it possible to send you the link in a pm?

**Comment by bohuang3d** [comment]
I assume chances are slim that someone is using the same combination as you. If you don't want to wait, perhaps another option is to get a new device and do the upgrade along with your app and see what happens

Or post your dilemma at Oculus's developer forum for a potentially wider reach

**Comment by Nathipha** [comment]
@bohuang3d 
I borrowed a friend's S7 and I actually got my app (still 3.0.1 of framework and 1.0.3 of Oculus SDK) to run with a fresh install of the Oculus/Gear VR apps. :)
Haven't fully tested it yet but it starts up and loads my polylines, which is a good sign. I did notice a slightly laggier crosshair (with headtracker) but that could have a lot of other reasons too.

**Comment by liaxim** [comment]
@Nathipha You can send me the file to m.marinov@samsung.com

**Comment by liaxim** [comment]
@Nathipha Tried some apks included in the Oculus Mobile SDK 1.0.3. They installed and ran fine on my S8 with the most recent Oculus runtime installed.

**Comment by liaxim** [comment]
@Nathipha I dare to say that it is easier to use the framework now than at the 3.0.1 times. Please look at http://www.gearvrf.org/getting_started/. We supply a template project and the framework binaries get downloaded automatically for you. You could try using the 3.3 release as it should require less changes to your code. If that is what you choose, then you need to use this template project: https://github.com/gearvrf/GearVRf-Demos/tree/release_v3.3/template/GVRFApplication.

**Comment by liaxim** [comment]
@Nathipha Can we close this issue?

**Comment by Nathipha** [comment]
Sorry for reopening this, unfortunately I now keep randomly running into the same problem:

    _ASSIMP_SCENE_NOT_FOUND_
    Fatal signal 11 (SIGSEGV), code 1, fault addr 0x154 in tid 29113 (Thread-11)

So the same "addr 0x154" again.

The biggest model is almost 7mb, usually they're around 4mb and I'm not displaying more than 20 at the same time. What I am doing is pre-loading models into memory (creating the GVRSceneObject without doing a "scene.addSceneObject", so I can display them faster afterwards), it doesn't seem to cause the crash to happen faster than without pre-loading though.

I already checked the memory usage of my app: After pre-loading around 120 models it was at 158mb ("Runtime.getRuntime().totalMemory()") with 16mb of free memory ("Runtime.getRuntime().freeMemory()"), the former eventually went down to about 70mb on its own - so the garbage collector seems to be doing its job properly.

Plus, I am using "android:largeHeap="true"", which can give my app 512mb but even with the usual 256mb the peak of 158mb really shouldn't be a problem.

Any ideas what I could try here? I'm not sure what "_ASSIMP_SCENE_NOT_FOUND_" even means (something OpenGL related?).

**Comment by liaxim** [comment]
@Nathipha 3.0.1 is way too old by now. Since then we have made a ton of bug fixes and improvements. Including moving to the latest version of assimp. Please do consider moving to the latest release. We will assist with any issues you may encounter.

ASSIMP_SCENE_NOT_FOUND means that somehow assimp failed to process the model and produce its own scene for it. We don't even have that code anymore.

**Comment by Nathipha** [comment]
@liaxim Thanks for your fast reply!
Unfortunately I still have a couple of bugs in my own app that I have to fix before I can upgrade (and deal with the ugliness that's Android Studio...).

Even if you don't have the code, do you know/remember if this only happens when you create the GVRSceneObject (so adding a mesh to it,...) or when you actually add the object to the scene?

In your new version is there any type of exception I can catch to at least prevent it from crashing and try again? Or does that error usually not crash the app but instead the "fatal signal 11" does?
