### ISSUE TITLE
ovr_sdk_mobile 1.12.0 compatibility

### ISSUE THREAD

**Issue by pdiaz** [Samsung/GearVRf#1718]
As it is unfortunately too habitual on every ovr_sdk_mobile release, changes to the API break functionality. This time it compiles correctly but it crashes immediately at run time. The change that produces this crash is:

- Applications are now required to pass through explicit EGL objects (Display, ShareContext, NativeWindow) to vrapi_EnterVrMode, otherwise the call will fail.

This update is interesting to support the new A-series devices like the Samsung Galaxy A8.

**Comment by thomasflynn** [comment]
i believe this is complete, right?

**Comment by liaxim** [comment]
Yes.
