### ISSUE TITLE
EmissiveColor not working

### ISSUE THREAD

**Issue by mwitchwilliams** [Samsung/GearVRf#1732]
emissive color appears broken. I know this used to work.
Below is an X3D file sent to an X3D broswer (FreeWRL) which is correct.
![emissivecolor_frewrl](https://user-images.githubusercontent.com/18128830/35989350-d14576b2-0cb5-11e8-99ad-cfa9195b1112.png)
Same file sent to GearVR
![emissivecolor_gearvr](https://user-images.githubusercontent.com/18128830/35989432-f7f7d25a-0cb5-11e8-8ca7-07672ad58753.png)

The X3d file is attached
[emissivecolor.zip](https://github.com/Samsung/GearVRf/files/1708206/emissivecolor.zip)

**Comment by NolaDonato** [comment]
The PhongShader does not look at anything but diffuse color if there are no light sources in the scene. We could change it to add the diffuse and emissive colors when there are no lights. It is currently behaving as designed. If you put a light source in the scene, it will use the emissive color.

**Comment by mwitchwilliams** [comment]
Emissive color is not dependent on lights.
Here is an online demo from NIST (Nat'l Inst. of Standards and Technology) on emissive color:
http://www.web3d.org/x3d/content/ConformanceNist/Appearance/Material/emissiveColorIndex.html

The X3D equations from the spec shows emissive is never multiplied by light color:
http://www.web3d.org/documents/specifications/19775-1/V3.2/Part01/components/lighting.html#Lightingequations

X3D's lighting equations are based from Foley and OpenGL specs 
http://www.web3d.org/documents/specifications/19775-1/V3.2/Part01/components/lighting.html#References

Perhaps X3D should reference its own shaders

**Comment by bohuang3d** [comment]
In the AddLight() function in addlight.fsh, the emissive is added to any attenuated ambient/diffuse/spec: 
kE + r.attenuation * (kA + kD + kS)

It looks most similar to 
OE rgb + SUM( oni × attenuationi × spoti × ILrgb
                             × (ambienti + diffusei + specular i)

in the X3D spec. 

Wonder if we can map X3D shader to this if not already

**Comment by NolaDonato** [comment]
Fixed by #1744

**Comment by NolaDonato** [comment]
This is the shader X3D is using.

**Comment by mwitchwilliams** [comment]
Tested with the PR above and works
