### ISSUE TITLE
Performance regression on master (4.x)

### ISSUE THREAD

**Issue by thomasflynn** [Samsung/GearVRf#1735]
the transform_dirty_ flag that was introduced sometime recently is causing a constant, and unnecessary recomputation of bounding volumes.

if you go into scene_object.h in setTransformDirty() and change:
transform_dirty_ = true;
to
dirtyHierarchialBoundingVolume();

Performance goes back to normal.  I'm not sure on the origin of the transform_dirty_ flag or if my fix is correct.  Nola said she would look into it.

**Comment by thomasflynn** [comment]
@NolaDonato you asked if i still saw this on master.  I do.  Even on an S8.  If I change to dirtyHierarchialBoundingVolume() performance is back up.

**Comment by liaxim** [comment]
@thomasflynn The regression has been fixed. Can we close?
