### ISSUE TITLE
Increase viewing range

### ISSUE THREAD

**Issue by Nathipha** [Samsung/GearVRf#1739]
I'm loading a couple of .obj files at runtime in my app that have pretty big dimensions (the files are usually around 5mb each) and/or have to sit at specific coordinates that are a little bit further out and I've noticed that the viewing range isn't the greatest for big objects like that.

Is it possible to increase the viewing range, maybe even at runtime, so I can set it dynamically depending on the size of the objects? Or is it maybe even possible to completely disable the vanishing of objects that are further away (no point for me to use it really if I only have a few loaded at the same time anyway)?

Framework version: 3.0.1

**Comment by thomasflynn** [comment]
@Nathipha are you referring to the near and far clipping planes?  I don't remember if this was in 3.0.1, but we did add some convenience apis for getting and setting the near and far clipping planes in the GVRCamreaRig.  The APIs are:

float getNearClippingDistance();
void setNearClippingDistance(float near);
float getFarClippingDistance();
void setFarClippingDistance(float far);

if 3.0.1 does not have those APIs, you can get a handle to the left and right cameras from the camera rig, then cast the left and right cameras to a GVRPerspectiveCamera which has APIs for setting the near and far distances.  You can look at the setFarClippingDistance() implementation in master for reference.

**Comment by bohuang3d** [comment]
@Nathipha 
Disabling vanishing of objects require you to manipulate the projection matrix yourself with some math

And it could give you more problems because the depth buffer's usually 32 bit-depth will run out in a sense for really large scenes. So it really depends on what you are displaying

**Comment by Nathipha** [comment]
@thomasflynn 
Sorry, yes, that's what I'm talking about.
Thanks, they're in GVRCamerRig. :)
"Near" is set to 0.1 (which is okay) and "far" to 1000 by default. I've played around with it for a bit and 2500 seems to be just right. Any recommendation what value "far" should never exceed?

@bohuang3d 
I'm still working with polylines, there are around 50 of [these](http://i.imgur.com/4eLH8Oi.png) (can be more or less, usually less), there also can be a single plane (same screenshot) that was built with GL_TRIANGLES or GL_TRIANGLE_FAN or a rectangle with a texture instead and now also additionally .objs (usually <5 with an average size of 5mb+texture).
Fortunately @thomasflynn's APIs are here, so no need to mess with matrices.

**Comment by bohuang3d** [comment]
@Nathipha 
It's always a trade off between range and precision.

What you may see is a flickering for distant geometry. I.e., one geometry is at Z, and another at Z+1, where Z is some large number. But in the depth buffer both get mapped to the same depth=d due to insufficient bit-depth. So sometimes the object at Z+1 may get drawn before the object at Z. Other times the draw order is as expected.

2500 sounds fine. What you want to roughly ask is: do the distinctness of your geometry uniquely fit into 2^16 or 2^32 bins (which correspond to 16 bit or 32 bit depth buffer)

**Comment by Nathipha** [comment]
@bohuang3d 
I see, thanks for the explanation!
I did some more testing and it's running surprisingly well with even 10000 and the biggest object (dimension wise), no flickering as far as I've seen. I'm still going to keep it at roughly 2500 though, once I'm done with the testing but it's good to know that it works with more too.

Thanks, @thomasflynn @bohuang3d !
