### ISSUE TITLE
[SUGGESTION] Use Trello for feature Requests/Discussion

### ISSUE THREAD

**Issue by phi-lira** [Samsung/GearVRf#176]
I'd like to propose to separate issues from feature requests and discussion. I think Trello has a nice and easy API in which someone can add feature requests and improvements. Also it makes possible to people vote on each suggested feature/improvement making it really easy to see the ones that are most urgent/desider.

A real world example of trello can be found here: https://trello.com/b/gHooNW9I/ue4-roadmap

**Comment by phyuzion** [comment]
I agree with you.

**Comment by thomasflynn** [comment]
I need more convincing.  I really don't enjoy having multiple issue trackers for the same project.  New users, especially ones used to github, will use github's issue system even if we give lots of links to the associated trello page.  We do this now with the developer mailing list.  Yet other developers seem to prefer to open a new issue than have a discussion on the mailing list.  

You can already label issues as 'enhancement' or 'bug' and a few others in github's system.  Aside from voting up feature requests, what would Trello give us?  And how we ensure we don't end up managing multiple issue databases (trello and github publicly (and Jira and Redmine internally))?

**Comment by phi-lira** [comment]
I agree there'll be an increase in complexity and management and there's no argument for this. What I can speak in favor of trello over github is that it will increase focus on both features and bugs. So, for instance, when you open up a trello board, features are already categorized, prioritized and organized in a single view. One can easily spot the most urgent/desired features and tackle them. 

While in github, the more issues we have the more hard to manage them will be. So, for instance, there are some really interesting features down on the second page and probably no one is paying attention to them. Imagine when you have +10 pages. There will be people starting to create duplicates of feature requests just because they didn't bother to scroll through all the pages. 

IMO, when GearVRf scales to more contribution, the complexity to add and manage a trello board will pay off for the complexity of telling people they created duplicates of bugs and features. 

Regarding the labels, I think only contributors and above have permission to add. (at least I didn't find a way for me to do it). Is there a way to add permission to all users?
