### ISSUE TITLE
native crash after app launch

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1762]
Hi,
i am trying to create the video streaming app with theatre mode enabled(by referring  the "disabled-gvr-video" sample app but when app launches a native crash occurred with below logtrace:

`02-23 02:27:49.658  2916  2916 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-23 02:27:49.661  2916  2916 F DEBUG   : Abort message: 'art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.IllegalArgumentException: Receiver not registered: com.oculus.vrapi.SystemActivitiesReceiver@47193bd'
02-23 02:27:49.661  2916  2916 F DEBUG   :     r0 00000000  r1 00000b0e  r2 00000006  r3 00000008
02-23 02:27:49.661  2916  2916 F DEBUG   :     r4 ef70558c  r5 00000006  r6 ef705534  r7 0000010c
02-23 02:27:49.661  2916  2916 F DEBUG   :     r8 00000000  r9 ec36a624  sl 000022cc  fp ec32fd2f
02-23 02:27:49.661  2916  2916 F DEBUG   :     ip 0000000b  sp ff90de58  lr ecf71f97  pc ecf747f4  cpsr 20070010`

Version: 4.0.1-SNAPSHOT
This issue seems to be because of oculus .so file problem.

Thanks

**Comment by liaxim** [comment]
@spakanati123 This application still doesn't work with our latest version of the framework. If you really want to try it out you can use the older release: https://github.com/gearvrf/GearVRf-Demos/tree/release_v3.3.
