### ISSUE TITLE
How to check null at remote-script console

### ISSUE THREAD

**Issue by ragner** [Samsung/GearVRf#1763]
Hi all,
is it possible to use "if" conditional to check null object at remote-script console? 

The following code does not work for me:

var obj = scene.getSceneObjectByName("Cube.fbx");
if (!obj) {scene.removeSceneObject(obj);}

**Comment by bohuang3d** [comment]
What's the error you get? If it's remote, do you need some kind of callback

**Comment by dsazulay** [comment]
The console returns nothing at all. We wanted to check if an object is already on the scene to remove it.

**Comment by liaxim** [comment]
Try this
```
if ("undefined" == typeof obj) { scene.removeSceneObject(obj); }
```

**Comment by liaxim** [comment]
@dsazulay @ragner Are you still having problems?

**Comment by dsazulay** [comment]
@liaxim It worked. Thanks!

**Comment by liaxim** [comment]
Closing then.
