### ISSUE TITLE
Repeated setMesh() calls makes other objects vanish

### ISSUE THREAD

**Issue by SteveGreatApe** [Samsung/GearVRf#1765]
I created some code that was animating an object by updating it's mesh every frame, possibly not the most efficient way of doing things, but was only for a short while when the user was interacting with an object.

This quickly resulted in other scene objects vanishing. Dumping a log of all objects in the scene showed nothing wrong, they were all there with sensible looking values.

I even tried adding some code to remove and re-add the missing objects from the scene, this didn't make them re-appear. What I found did work and make them re-appear was to re-create their meshes.

I'm guessing this must be an issue with something like a mesh cache. I had noticed the occasional object vanishing before, but with no pattern to try and track down why. Now the problem is very repeatable, try adding the class below into a test project to re-create the problem. I add it into gvr-tutorial-lesson6 by calling it's onDrawFrame from the ParticleEmitter onDrawFrame() function, but I'd guess it'll cause problems in almost any project.

```
package org.gearvrf.balloons;

import org.gearvrf.GVRContext;
import org.gearvrf.GVRMaterial;
import org.gearvrf.GVRMesh;
import org.gearvrf.GVRSceneObject;

class TestMesh {
    private static GVRSceneObject sSceneObject;
    private static float sHeight = 0.5f;

    static void onDrawFrame(GVRContext gvrContext) {
        GVRMesh mesh = gvrContext.createQuad(1f, sHeight);
        sHeight = sHeight > 1f ? 0.5f : sHeight + 0.01f;
        if (sSceneObject == null) {
            GVRMaterial material = new GVRMaterial(gvrContext, GVRMaterial.GVRShaderType.Phong.ID);
            material.setDiffuseColor(0f, 1f, 0f, 1f);
            sSceneObject = new GVRSceneObject(gvrContext, mesh, material);
            sSceneObject.getTransform().setPositionZ(-4f);
            gvrContext.getMainScene().addSceneObject(sSceneObject);
        } else {
            sSceneObject.getRenderData().setMesh(mesh);
        }
    }
}

```
In org/gearvrf/balloons/ParticleEmitter.java add this TestMesh.onDrawFrame call.
```
    public void onDrawFrame(float elapsed)
    {
        if (isEnabled())
        {
            step(elapsed);
            TestMesh.onDrawFrame(getGVRContext());
        }
    }
```

**Comment by NolaDonato** [comment]
I looked at the code and I think this is because the bounding volume of the scene object does not get updated when the mesh is changed. I will try to fix that.

**Comment by NolaDonato** [comment]
Pull request #1754 may fix this problem. Try it with your app and let us know.

**Comment by SteveGreatApe** [comment]
Thanks, but that doesn't fix the problem. I think this is a much bigger issue than that, it's not just the object who's mesh is being updated that vanished, it's a scattering of random objects from all across the scene that vanish. Looks like some sort of shared mesh cache is getting corrupted.

**Comment by liaxim** [comment]
@SteveGreatApe Verified that https://github.com/Samsung/GearVRf/pull/1768 fixes your problem.

**Comment by SteveGreatApe** [comment]
I certainly haven't verified that #1768 fixed the problem, it looks like all that does is add a macro to help check for errors in GL calls. I have merged the #1768 changes in and enabled the 'checkGLError' version of the GL macro, but no errors are showing up when the problem occurs.

**Comment by liaxim** [comment]
@SteveGreatApe May be it is hard to spot but the thing that matters in that change is the switch from glDeleteBuffers to glDeleteVertexArrays. The GL macros are disabled by default. If you'd like them enabled see gvr_log.h.

**Comment by SteveGreatApe** [comment]
Sorry about that, you're right I had missed the glDeleteBuffers to glDeleteVertexArrays change. I've put that in now and it's looking much better, seems to be fixed from the quick try out I've just given it.

**Comment by liaxim** [comment]
@SteveGreatApe Please let us know whether we can close the issue then.

**Comment by liaxim** [comment]
@SteveGreatApe Planning to close the issue in few days. Let us know if you object.

**Comment by SteveGreatApe** [comment]
Yes you can close it, it's looking good now, haven't seen any reoccurrence of the problem.
