### ISSUE TITLE
It would be desirable to have Quaternion and Vector classes on GearVRf Java API

### ISSUE THREAD

**Issue by phi-lira** [Samsung/GearVRf#177]
I think it would be a great addition to have a GVRVector class to handle things like cross/dot/forward and a GVRQuaternion class to handle quaternion creation.

**Comment by mkeblx** [comment]
I believe GearVRf utilizes the Apache Commons Mathematics Library (v3.2): http://commons.apache.org/proper/commons-math which has such math objects and methods that work well.

**Comment by dankex** [comment]
Good suggestion. I will try to make a patch to reflect this, and see how it goes.

**Comment by liaxim** [comment]
We have JOML included nowadays. Planning to close this one.
