### ISSUE TITLE
It's possible to 'pass through' mode on GearVRF?

### ISSUE THREAD

**Issue by ssorttang** [Samsung/GearVRf#1770]
hello, I try to realization 'pass through' mode on GearVRF.
I wanna switch this mode before playback.
would you help me?

**Comment by bohuang3d** [comment]
Do you mean you want view the real world via a pass-through camera, and then via some action you play another 360 video?

**Comment by ssorttang** [comment]
thank you for your information!

**Comment by liaxim** [comment]
@ssorttang Is it all good? Can we close the issue?
