### ISSUE TITLE
Flickering observed because of onEnter() multiple calls

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1778]
Hi ,
I implemented Discovery page with movie posters and each poster is one GVRSceneObject.
So my GvrScene has multiple GVRSceneObjects(movie posters). 
Initially, all my posters showed with grey color and when Controller moved to the poster(hovered onEnter() will call) i will change color to white, but here i can see that my poster started flickering.
onEnter() -> set color to white
onExit() -> set color to grey
This is happening because of PickHandler(implements GVREventListeners.PickEvents) onEnter() and onExit() calling multiple times so poster color changing from white to grey and vice versa continuously.

As per the docs,
- onEnter() should call when the pick ray first enters a scene object.
- onExit() should call when the pick ray first exits a scene object.

But if pick ray inside sceneObject also onExit() calling and then onEnter() calling and it's repeating infinitely.
And also i observed when my controller inside scene object,
- onPick() calling multiple times.
- onInside() calling multiple times
Please make me understand these callbacks.

Please suggest me the proper callback which calls only once when my sceneObject picked and non-picked.

Thanks

**Comment by bohuang3d** [comment]
I can't yet understand fully. Could I assume you are looking to detect the first time you enter the poster? And the first time you exit the poster? And you don't care about the interactions if it's not the first time?

If so, can you keep a flag of enter/exit states and check if your current state is different from last frame's?

**Comment by spakanati123** [comment]
@bohuang3d when my controller focused on GVRSceneObject firstly onEnter() and then onExit() calling continuously so keeping flag won't help.
Can u please let me know that why onEnter() and onExit() calling many times even my controller ray on same the same scene object, as per the docs onExit() should not call until controller ray moves out os SceneObject.

**Comment by bohuang3d** [comment]
Could you send an example project

**Comment by spakanati123** [comment]
i got the solution to fix this problem.
