### ISSUE TITLE
Loading light, camera, scene from .fbx files

### ISSUE THREAD

**Issue by dsazulay** [Samsung/GearVRf#1780]
Is it possible to load light, camera or an entire scene from a .fbx file?

**Comment by bohuang3d** [comment]
You can try

 public GVRModelSceneObject loadModel(String filePath, IAssetEvents handler) throws IOException

or the other loadModel() functions in GVRAssetLoader
It seems to support loading AssImp models

**Comment by thomasflynn** [comment]
@NolaDonato if we load an fbx, does assimp load in the light and camera info?  and do we use it?

**Comment by liaxim** [comment]
Quick look at GVRJassimpAdapter shows that we import the lights and the first camera from a model file. We are capable of loading an entire scene with caveats. @dsazulay We will be happy to assist you if experience problems. You may have to tune your fbx files for mobile. Some guidelines here: https://developer.oculus.com/documentation/unity/latest/concepts/unity-integration-mobile-performance-intro/. Thanks.

**Comment by dsazulay** [comment]
I've done some tests using the loadModel() method of GVRAssetLoader and it seems that the light loads but with different rotation.
I'm exporting fbx files from blender.

**Comment by bohuang3d** [comment]
What's the difference between the expected and actual rotational values?

**Comment by dsazulay** [comment]
90 degrees on X axis. This only occurs when loading light. If I load a fbx mesh, the rotation is all right.

**Comment by bohuang3d** [comment]
I recall Blender's fbx exporter has options to let you select the front facing axis. 
Can you verify the rotation for the light has not changed from the blender file to fbx?
Then we can take a look at code

**Comment by NolaDonato** [comment]
Please send me the file and I will take a look. Our lights have a default direction to account for differences between content creation programs. GearVRf assumes that the default direction for Jassimp lights is pointing up and corrects to make them point down the negative Z axis. It is possible that for some FBX files the default direction is not up. Perhaps there is some setting in your DCC tool that lets you specify the default light direction.

**Comment by dsazulay** [comment]
The fbx files are exported with -Z forward and Y up. I use this configuration to export both meshes and lights.

I found this code on the GVRJassimpAdpter. Maybe it's because of this method that the lights rotation differ?

https://github.com/Samsung/GearVRf/blob/e64d074350fbcc0f21c93ddd80a48376b97bc963/GVRf/Framework/framework/src/main/java/org/gearvrf/GVRJassimpAdapter.java#L562-L573

**Comment by bohuang3d** [comment]
That matches your rotated by 90 degrees on X axis description, though it may match some content tools you are not using. For your use case, try comment out the Quaternion:

if (light != null) { 
         //Quaternionf q = new Quaternionf(); 
         //q.rotationX((float) Math.PI / 2.0f); 
         //q.normalize(); 
         //light.setDefaultOrientation(q); 
         sceneObject.attachLight(light); 
     } 

or simply set the rotation angle to 0 like rotationX(0)

**Comment by NolaDonato** [comment]
The problem with commenting that out is that it breaks most of the other FBX files.

**Comment by bohuang3d** [comment]
Wonder if it should be an option left to the user when loading

**Comment by NolaDonato** [comment]
We are using assimp for loading our models. Assimp does not have any way to detect the default orientation of a light. GearVRf assumes the default orientation to be down the -Z axis. Most assimp files (but not all apparently) assume the default orientation to be down the -Y axis which is why we do the rotation.

We will be upgrading to a new version of assimp which might have this bug fixed (they are discussing fixes on the assimp forum now).

A workaround for now would be to get all the lights in the scene and set their default orientation to what you want:

GVRSceneObject root;
List<GVRLight> lights = root.getAllComponents(GVRLight.getComponentType());
Quaternion q = new Quaternion();
for (light : lights)
{
    light.setDefaultOrientation(q;
}

**Comment by dsazulay** [comment]
The best-case scenario is to detect the default rotation indeed.
The workaround I used is to compensate the rotation before exporting and the GVRf loads the light in the correct direction.
Thanks for your support!
