### ISSUE TITLE
Showing a 3D image (360 TB) as background

### ISSUE THREAD

**Issue by mconfalonieri** [Samsung/GearVRf#1781]
Hi,

I am new to Gear VR development. I would like to show a 360 top-bottom (stereoscopic) image as the background of my app. I tried to load it as a texture (following the 360-photo example, but it is showed as a normal image. I tried to see if I could use some method in the camera rig to set the background for each eye, but it does not seem possible. Would you have any suggestion?

Regards,

Marco

**Comment by bohuang3d** [comment]
Do you have two images or one image that contains both eyes? Is it a specific format?

The 360 example does not support stereoscopic

**Comment by thomasflynn** [comment]
the 360 photo example doesn't show how to do it, but you could use the GVRUnlitVerticalStereoShader for rendering your images.

**Comment by mconfalonieri** [comment]
> Do you have two images or one image that contains both eyes? Is it a specific format?

It's a single JPEG, but I can convert it to other formats, or cut it if necessary. I scaled it down to show it here.

![img](https://user-images.githubusercontent.com/7748015/37231874-0d5efc4c-23ed-11e8-8409-466247e516f8.jpg)

> the 360 photo example doesn't show how to do it, but you could use the GVRUnlitVerticalStereoShader for rendering your images.

Thank you, I will try this.

**Comment by mconfalonieri** [comment]
@thomasflynn could you please tell me if there are examples on using `GVRUnlitVerticalStereoShader`?

**Comment by thomasflynn** [comment]
i've modified the 360 photo sample here:
https://github.com/thomasflynn/GearVRf-Demos/blob/stereophoto/gvr-360photo/app/src/main/java/org/gearvrf/gvr360Photo/Minimal360PhotoMain.java

in short, you just create a GVRMaterial with the specified shader, assign the texture to it and then use that material when creating the sphere.

though, it looks like top of trunk might have a bug with the shader...it doesn't seem to compile for me.  I'm having @roshanch and @apjagdale take a look.

**Comment by mconfalonieri** [comment]
Thanks, I will try that!

**Comment by mconfalonieri** [comment]
I tried your suggestion @thomasflynn, but the screen goes black using `material` as the last parameter for the `GVRSphereSceneObject` constructor. To check if I correctly loaded the resource, I tried to build `GVRSphereSceneObject` with the `texture` and it works, of course giving the "double" image.
Should I add some light source to correctly use the material?

**Comment by thomasflynn** [comment]
As I mentioned, there is a bug with the shader.  It is failing to compile.  We're working on a fix.  Once that is fixed, you will be able to view your image.

**Comment by liaxim** [comment]
@mconfalonieri The fix is up for review and test - https://github.com/Samsung/GearVRf/pull/1782

**Comment by liaxim** [comment]
@mconfalonieri Fix merged. Let us know how it works for you. Thanks.

**Comment by mconfalonieri** [comment]
@liaxim it worked! Thank you :-)
