### ISSUE TITLE
[backend_oculus] build error branch maint_v3.x ovr sdk both 1.9.0/1.12.0 versions 

### ISSUE THREAD

**Issue by sukhwanyoon** [Samsung/GearVRf#1796]
I run into build error backend_oculus because ovr sdk version conflicts.

` /media/sukhwan.y/SSDDATA/vr/gvrf/GearVRf/GVRf/Framework/backend_oculus/src/main/jni/util/ovr_configuration_helper.h:35:49: error: 'ovrHeadModelParms' has not been declared
       void getHeadModelConfiguration(JNIEnv& env, ovrHeadModelParms& parmsOut);
`

**Comment by liaxim** [comment]
The maint_v3.x branch uses 1.7.0.

**Comment by liaxim** [comment]
@sukhwanyoon Can we close the issue?

**Comment by sukhwanyoon** [comment]
Yes I can. Thanks.
