### ISSUE TITLE
Back event not working in demo app

### ISSUE THREAD

**Issue by mohanvthink** [Samsung/GearVRf#1810]
I tried to run some demo apps which has back event but it doesn't work as expected.
when I pressed back button app ask to return oculus home.

Can anyone suggest which app has back event

**Comment by liaxim** [comment]
@mohanvthink Hi. The gvr-immersivepedia demo app shows how to handle the back key. Specifically you need to look at the GVRMain.onBackPress method. If the app handles it - return true; otherwise per Oculus requirement we have to bring up the return-to-oculus-home prompt.

**Comment by liaxim** [comment]
@mohanvthink Still having problems?

**Comment by liaxim** [comment]
@mohanvthink Planning to close the issue soon. Let us know if you have more information for us.
