### ISSUE TITLE
how to add load progress bar and video control UI(overlay)  always user direction

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1820]
Hi,
we have implemented video streaming app for 360-degree videos and the user can rotate in 360 degrees to watch the video. 
Whenever video buffers we show loading circular progress bar and also video controller buttons(seek bar, pause, forward, rewind buttons)  but here the problem is how to show the progress bar and Controller UI(seek bar, forward, rewind , pause buttons) in user watched direction, I mean how to change the loading progress bar and Controller UI position based on user direction.
Whenever volume increased or decreased i can see volume increment or decrement texture showing in user direction, i want to implement the same behavior for my circular loading bar and Controller UI.
Please suggest the approach or any reference sample app.

Thanks

**Comment by liaxim** [comment]
@spakanati123 Hi. Sounds like you need GVRScene.getMainCameraRig().addChildObject which would attach a scene object to the camera rig and should do what you are asking for. You can look at the gvr-switch sample and how the headTracker is added (``scene.getMainCameraRig().addChildObject(headTracker)``).

**Comment by spakanati123** [comment]
@liaxim Thanks for the update, it's working as required.
