### ISSUE TITLE
Controller not working as expected some times

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1826]
Hi,
In our app i implemented the cursor controller with mentioned logic.

```
gvrContext.getInputManager().selectController(new GVRInputManager.ICursorControllerSelectListener()
        {
            public void onCursorControllerSelected(GVRCursorController newController, GVRCursorController oldController)
            {
                GazeController cursor = GazeController.get();

                if (cursor == null)
                {
                    new GazeController(newController);
                }
                else
                {
                    newController.setCursor(cursor.getCursor());
                }
                mController = newController;
                newController.addPickEventListener(pickHandler);
            }
        });
```

But i can see sometimes controller
- controller bumping to reverse direction 
- shifting position to left-hand side even i hold remote with right hand
- controller position not in exact sync with hand position.
Issue can be observed with sample app gvr-controller.

please suggest the way to implement controller to fix these issues.

Thanks

**Comment by liaxim** [comment]
@spakanati123 Are you using Daydream or Oculus?

**Comment by spakanati123** [comment]
@liaxim with Oculus only, this issue replicate sometime only.

**Comment by liaxim** [comment]
Do you see any problems if you use the controller in the Oculus Home?

**Comment by spakanati123** [comment]
@liaxim i did n't find in Oculus home.

**Comment by liaxim** [comment]
What device are you using?
Have you tried to unpair the controller, pair again and go through the calibration?
Can you share logcat output?

**Comment by spakanati123** [comment]
i am unable to reproduce the issue, will attach the logcat once facing this again.

**Comment by liaxim** [comment]
@spakanati123 Can we close until you have clear reproduction steps?

**Comment by spakanati123** [comment]
okay.
