### ISSUE TITLE
Stereoscopic 360 Video

### ISSUE THREAD

**Issue by sheveg** [Samsung/GearVRf#1828]
I have a problem with playing a 360 stereoscopic video with this framework. I followed [this](http://www.gearvrf.org/tutorials/play_with_vr_video/) tutorial on how to display a monoscopic 360 video. What I changed is just this line:

`GVRVideoSceneObject video = new GVRVideoSceneObject(gvrContext, mesh, mPlayer, GVRVideoSceneObject.GVRVideoType.MONO);`
to
`GVRVideoSceneObject.GVRVideoType.VERTICAL_STEREO`

But the problem is that I can only hear the audio and it also seems that the sound is not directional because the direction does not change when I turn my head.

**Comment by liaxim** [comment]
I tried the same and VERTICAL_STEREO produced the expected result for me. Are you using a different video?

For spatial audio you will need ResonanceAudio and our extension that adds support for it - GearVRf/GVRf/Extensions/ResonanceAudio/. We have a demo app that shows how to use it - GearVRf-Demos/gvr-cardboard-audio.

**Comment by sheveg** [comment]
Yes I use a different video with 4k x 4k resolution. But I changed it to the EXO player and then it worked. So this Issue can be closed.
