### ISSUE TITLE
gvr-keyboardviewer no longer echoes keypresswes

### ISSUE THREAD

**Issue by Caprica666** [Samsung/GearVRf#1829]
This demo used to echo the keys pressed on the virtual keyboard on the selected line in the box. Now it never prints the keys.

**Comment by liaxim** [comment]
I believe this is one more Android O specific problem. Not reproducing on my Android N devices.

**Comment by NolaDonato** [comment]
I will test on another phone

**Comment by liaxim** [comment]
@ragner By adding ``mRootGroup.findFocus().requestLayout()`` to ``InputMethodHandler.handleCharacter`` characters start to show up but I am not convinced this is the right fix. Could you please take a look at this issue too and let us know what you think? Thanks.

**Comment by liaxim** [comment]
Fixed by https://github.com/Samsung/GearVRf/pull/1854.
