### ISSUE TITLE
Is there any way to show only one camera and it is full screen?

### ISSUE THREAD

**Issue by EricSKCheng** [Samsung/GearVRf#1832]
Is there any way to show only one camera and it is full screen? Like camera preview.
I try to integrate GearVRF with Vuforia and I don't need the VR function for the project.

**Comment by liaxim** [comment]
Hi @EricSKCheng. If you use the development version from the master branch then you can configure one of our demo apps to use the monoscopic backend for GVRf. Please add these to your gradle.properties file:

```
// have the build use local build artifacts instead of fetching snapshots from maven
useLocalDependencies=true
// configure the demos to include only the monoscopic backend
backend_monoscopic=true
```

You can use https://github.com/gearvrf/GearVRf-Demos/blob/master/common.gradle as an example how to update your app. Basically you need to include only the ``backend_monoscopic`` module.

If you use an older version of GVRf then the instructions are different. Let us know.

**Comment by EricSKCheng** [comment]
Thanks @liaxim,
I am able to use the monoscopic backend. 
I also want to know if there is any way to get the frame data? So the user can take a screen shot or record a video. 
Thanks.

**Comment by liaxim** [comment]
We have screenshotting apis - see GVRContext.captureScreen<*>. To record video with the monoscopic backend you could try third-party utilities (or the built-in Android screenrecord command line tool).

**Comment by liaxim** [comment]
@EricSKCheng Is it all good? Can we close the issue?
