### ISSUE TITLE
Example of GearVRf with ARCore

### ISSUE THREAD

**Issue by itanbp** [Samsung/GearVRf#1833]
Hi,
in [this](https://github.com/google-ar/arcore-android-sdk/issues/52#issuecomment-368436722) post was mentioned GearVRf can be integrated with ARCore in order to load 3D file formats and render the virtual objects.

Is there an example demonstrating this capability?

Thanks

**Comment by liaxim** [comment]
Hi. There is one in the works here: https://github.com/gearvrf/GearVRf-Demos/pull/598

**Comment by itanbp** [comment]
@liaxim thanks, looks great!

**Comment by thomasflynn** [comment]
@itanbp , if you have feedback on what you feel an ARCore developer would like to see from an example, please let us know in that pull-request: https://github.com/gearvrf/GearVRf-Demos/pull/598
thanks

**Comment by itanbp** [comment]
@thomasflynn thanks for the opportunity! I added my thoughts to the PR

**Comment by itanbp** [comment]
@thomasflynn @liaxim @ragner I tried to get a feeling of the `gvr-arcore` sample app, but I get a gradle error `Error:(1, 0) Plugin with id 'com.android.application' not found`.

I cloned [sidia-dev-team/GearVRf-Demos](https://github.com/sidia-dev-team/GearVRf-Demos/tree/feature_arcore) and [GearVRf](https://github.com/Samsung/GearVRf) in a sibling directory, and checkout the `feature_arcore` branch.
Then I tried to open the [GearVRf-Demos/gvr-arcore/app/](https://github.com/sidia-dev-team/GearVRf-Demos/tree/feature_arcore/gvr-arcore/app) but got the above gradle error.

Any advice? Thanks!

**Comment by bohuang3d** [comment]
Try this
https://stackoverflow.com/questions/24795079/error1-0-plugin-with-id-com-android-application-not-found

**Comment by liaxim** [comment]
@itanbp You need to open GearVRf-Demos instead.

**Comment by itanbp** [comment]
@liaxim I opened GearVRf-Demos and now I see the project structure, but I get a different error now `Error:Failed to resolve: org.gearvrf:resonanceaudio:4.0.1-SNAPSHOT`.

I added to the projects `gradle.properties` this line `androidNdkPath=C:/Users/Lenovo-PC/AppData/Local/Android/Sdk/ndk-bundle`, same error.

**Comment by liaxim** [comment]
@itanbp Please make sure you have the latest GearVRf-Demos. There was a case sensitivity bug that was fixed couple of weeks ago. Gradle automatically downloads the corresponding aars.

**Comment by itanbp** [comment]
@Liahim I tried GearVRf-Demos and it worked!
Until now I worked with [**sidia-dev-team**/GearVRf-Demos](https://github.com/sidia-dev-team/GearVRf-Demos/tree/feature_arcore) as the `feature_arcore` wasn't merged yet to GearVRf-Demos. 
Any chance you can point to the relevant fix commit, so I can apply the changes locally?

**Comment by liaxim** [comment]
@itanbp Now that we have the sample, can we close the issue?

**Comment by itanbp** [comment]
@liaxim yes, thanks
