### ISSUE TITLE
what is best way to implement Discovery page for best user experience 

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1836]
My application makes a n/w call to discovery server and the received posters (different genres and around 150 to 250 count) need to inflate on the scene. 

Please suggest me the best way to inflate all these posters on the scene with horizontal and vertical smooth scrolling.

**Comment by bohuang3d** [comment]
Could you elaborate? Is each poster a 3d object or some text or picture? It sounds similar to all the 360 video VR apps. Are you looking for tech or design advice?

Techwise, would be good to have an object pool. Don't want to keep on allocating data

**Comment by spakanati123** [comment]
@bohuang3d  each poster is a picture, yeah it same as video VR apps which support both 360 and normal video playback. We are looking for tech advice in implementation perspective.

**Comment by bohuang3d** [comment]
You can make a 2d array of quadrilaterals that face the viewer. As your network calls brings you image data, convert images to textures and assign to the quadrilaterals.

Make some planning on the memory consumed by each image with the minimal resolution. Divide your available memory by image memory size to see if 100-200 images can be loaded without hiccups.

Then look at the speed of drawing say 100 quads each representing a video. Those 100 draw calls could be the bottleneck depending on what else you are doing

**Comment by spakanati123** [comment]
@bohuang3d Thanks for your inputs.

**Comment by bohuang3d** [comment]
If you use ListView or other Android containers, consider at least:

can they be found in the scene during ray casts or collision detection?
do you need to write code to visualize them? (including scrolling)
UI elements/toolkits are usually slow. How expensive are the auto adjustment?

**Comment by spakanati123** [comment]
my listview is not scrolling while the swipe up and down on controller, when i check the listview focus it returns true, enableGestureDetector() added for my GvrActivity.
am i missing something to enable auto scroll for the list view .?
-> click event working fine for each list item.
-> GVRMain onSwipe() calling in which i added the logic to scroll listview but performance is not good.
Why listView not scrolling even hasFocus() returns true?
