### ISSUE TITLE
build failing with latest code

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1843]
The build getting failed with latest code with mentioned error
```
Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> More than one file was found with OS independent path 'lib/armeabi-v7a/libc++_shared.so'
```
This is this happening because of recent PR:
https://github.com/Samsung/GearVRf/commit/6413b50dcd5422240101aeb2c8d3b23ea0db42d1

I am unable to find exact way to exclude the one of libc++_shared.so from app gradle.
The issue can be observed with sample app as well.

**Comment by liaxim** [comment]
If you update to the latest GearVRf-Demos you will see this section in GearVRf-Demos/common.gradle:

```
     packagingOptions {
         pickFirst 'lib/*/libc++_shared.so'
         pickFirst 'lib/*/libgnustl_shared.so'
     }
```

This is the way to take care of this error.

**Comment by spakanati123** [comment]
Thanks for your inputs.
