### ISSUE TITLE
unable to scroll listview 

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1853]
i can feel very difficult to scroll the listview when using in GVRF.
 hasFocus() returns true for listview when hover and swipe using the controller. So i can say scroll functionality is missing here.
i can observe issue in gve-events sample app as well.

**Comment by thomasflynn** [comment]
just ran gvr-events in the headset and the list scrolled just fine using the headset trackpad, though picking in the list seemed a little off.  I tried to add controller support (adding useControllerTypes="gaze,controller" in vr-app-settings in the gvr.xml) to see if there is a problem with the controller, but i'm having some pairing issues with my phone.  once i sort that out (maybe new batteries?), i'll test with the controller.

**Comment by spakanati123** [comment]
@thomasflynn i guess u tried on latest gvr-events code branch, even using headset trackpad also i need to struggle many number of times to scroll to end of the list.
i am using the latest model of samsung VR headset.

**Comment by spakanati123** [comment]
Yeah...my Galaxy S8 runs on Android 'O'.

**Comment by thomasflynn** [comment]
ok, thanks for confirming.  we're looking into it.

**Comment by liaxim** [comment]
This may have some relation to https://github.com/Samsung/GearVRf/issues/1829.

**Comment by liaxim** [comment]
It is related to #1829. After adding ``super.requestLayout();`` near the end of ``GVRViewSceneObject.RootViewGroup.dispatchDraw`` scrolling works as expected. @ragner Do you have any advice on the correct approach for fixing this refresh problem?

**Comment by ragner** [comment]
@liaxim  I will take a look

**Comment by ragner** [comment]
@spakanati123  We have a fix for this.

**Comment by spakanati123** [comment]
Thanks @ragner , @thomasflynn, @liaxim

**Comment by liaxim** [comment]
Fixed by https://github.com/Samsung/GearVRf/pull/1854. Planning to close in few days.

**Comment by spakanati123** [comment]
@liaxim it seems the build not triggered by this change, can u please trigger build.

**Comment by liaxim** [comment]
@spakanati123 Snapshots have been updated.

**Comment by spakanati123** [comment]
I am unable to increase my scene size even changing the frame layout width and height , it always fixed size(small rectangle box) irrespective of the width and height i gave. 
Can u please suggest to change the size of scene for my layout. i tried scale as well.
```
        frameLayout = new FrameLayout(this);
        frameLayout.setBackgroundColor(Color.WHITE);
        registerView(frameLayout);
         frameLayout.getLayoutParams().height = frameLayout.getLayoutParams().width = 1000; //dpToPx(3000);
        View.inflate(this, R.layout.activity_main, frameLayout);
        main = new RecyclerMain(this, frameLayout);
```

**Comment by spakanati123** [comment]
i am using the 4.0.1-snapshot version but still my generated GVRViewSceneObject.class does nt showing the added change onDescendantInvalidated() so on Android o devices still scrolling not working. I did my gradle sync and clean project as well.

**Comment by liaxim** [comment]
@spakanati123 You need to force gradle to refresh the dependencies. See https://stackoverflow.com/questions/13565082/how-can-i-force-gradle-to-redownload-dependencies.
