### ISSUE TITLE
GearVRf together with ARCore supported devices

### ISSUE THREAD

**Issue by itanbp** [Samsung/GearVRf#1855]
Hi,
My intention is to integrate ARCore and GearVRf, and I try to understand what will be the supported devices.

In the [documentation](http://www.gearvrf.org/getting_started/#hardware-requirements) mentioned:

> GearVR Framework supports following devices
Gear VR compatible Samsung phone:
Note 8
Galaxy S8
Galaxy S8+
Galaxy S7
Galaxy S7 Edge
Note 5
Galaxy S6
Galaxy S6 Edge
Galaxy S6+
Samsung Gear VR headset
Daydream-ready phone
Google Daydream View VR headset

But I assume this list is relevant for VR headset development?

Can I assume that developing AR using ARCore, and GearVRf's `Loading Assets`, `Rendering` and `Scene Graph` features will be limited to the [ARCore supported devices](https://developers.google.com/ar/discover/#supported_devices)?

**Comment by bohuang3d** [comment]
If you want AR and VR together, then the supported devices should be the overlap of the ARCore supported devices list and GVRF supported list

**Comment by itanbp** [comment]
@bohuang3d I want to achieve only an AR capability, without VR.
I'm actually asking, what will be the supported device list for the [ARCore integration sample app](https://github.com/gearvrf/GearVRf-Demos/pull/598)?

**Comment by itanbp** [comment]
@bohuang3d thanks, this confirms my assumption.

**Comment by liaxim** [comment]
@itanbp Do you need more information? If not, planning to close the issue in few days.
