### ISSUE TITLE
full-screen regular view instead of stereoscopic view

### ISSUE THREAD

**Issue by itanbp** [Samsung/GearVRf#1862]
Hi,
I'm going over the `gvr-arcore` sample and looking for a way to use the rendering capability of GearVRf, but display a full-screen regular view, instead of the stereoscopic view.

Essentially I'm trying to use `gvrContext.getAssetLoader().loadModel()` as the rendering engine, together with `ARCore`, to give a full screen AR experience.

I will appreciate any advice...

Thanks!

**Comment by liaxim** [comment]
Hi @itanbp. We have our so-called monoscopic backend for that purpose. See https://github.com/Samsung/GearVRf/wiki/Q&A - Q23.

**Comment by itanbp** [comment]
@liaxim thanks for the quick response. 

In `gvr-arcore/app/build.gradle` I added 
`
implementation "org.gearvrf:backend_monoscopic:$gearvrfVersion"
`

and I also changed `gvr-arcore/app/.../assets/gvr.xml` to
```
<lens name="N4" >

    <vr-app-settings
        framebufferPixelsHigh="DEFAULT"
        framebufferPixelsWide="DEFAULT"
        showLoadingIcon="true"
        useProtectedFramebuffer="false"
        useSrgbFramebuffer="false" >

        <mono-mode-parms
            monoFullScreen="true"
            monoMode="true" />

        <mode-parms
            allowPowerSave="true"
            resetWindowFullScreen="true" />

        <performance-parms
            cpuLevel="2"
            gpuLevel="2" />

    </vr-app-settings>

</lens>
```

But I still see the same stereoscopic view.

**Comment by liaxim** [comment]
For our demos all you need to do is run ```./gradlew -Pbackend_monoscopic=true gvr-arcore:installDebug```.

**Comment by itanbp** [comment]
@liaxim thanks, that worked

**Comment by liaxim** [comment]
@itanbp Can we close the issue?

**Comment by itanbp** [comment]
@liaxim yes, thanks
