### ISSUE TITLE
registerView(view) inflating the layout(showing layout) before splash screen 

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1871]
```
 @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if(mShowLoginPage) {
            frameLayout = new FrameLayout(this);
            frameLayout.setBackgroundColor(Color.WHITE);
            registerView(frameLayout);
            View.inflate(this, R.layout.custom_credentials_dialog, frameLayout);
            appMain = new AppMain(this, frameLayout);
        }
        setMain(appMain, "gvr.xml");

    }
```
I created my login page using above code then i can see my layout page after app launch  in normal mode(like how my mobile app show login page) before splash screen logo shows

App launch -> normal login page layout(for small interval) ->  splash screen -> login page in vr mode

when i removed the registerView(frameLayout) issue not observed.

**Comment by liaxim** [comment]
registerView is not optional. Your android view may not refresh correctly without this call. @ragner can comment further on registerView.

Your problem is there is too much time between creating and registering the view and the time setMain starts having an effect. You can keep the registerView and have the view's visibility set to invisible. Then from GVRMain.onInit you can make it VISIBLE back again. Remember that the setVisibility call must happen on the Android main thread.

**Comment by ragner** [comment]
Hi @liaxim  and @spakanati123,
@spakanati123  you can remove registerView(frameLayout) from your code. I have made some improvements to GVRViewSceneObject so it is not necessary call registerView(...) any more. It is handled internally by GVRViewSceneObject.

@spakanati123 you could improve your code using constructor: GVRViewSceneObject(GVRContext gvrContext, int viewId,IViewEvents eventsListener)  http://gearvrf.org/api_reference/v4.1/Framework/org/gearvrf/scene_objects/GVRViewSceneObject.html#GVRViewSceneObject-org.gearvrf.GVRContext-int-org.gearvrf.IViewEvents-

It notifies you through IViewEvents#onInitView(GVRViewSceneObject sceneObject, View view)
when your layout has been inflated.

**Comment by ragner** [comment]
@spakanati123  whether you don't want use that listener you can use the constructor:
GVRViewSceneObject(GVRContext gvrContext, int viewId) and call GVRViewSceneObject#waitFor()
to wait for the layout has been inflated.

**Comment by ragner** [comment]
@spakanati123 see gvr-keyboardview demo:  https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-keyboardview

It has a input form inflated from a  xml layout.

**Comment by liaxim** [comment]
@spakanati123 Has your problem been solved? Can we close the issue?

**Comment by spakanati123** [comment]
Thanks @ragner , @liaxim
