### ISSUE TITLE
Unable to use android Support library

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1877]
Since GVRActivity extends Activity we are unable to use android supported libraries, 
like getSupportFragmentManager() not allowed .
Is it possible to change GVRActivity extends AppCompatActivity .  ?

**Comment by liaxim** [comment]
We probably should not make apps derive from our activity base class at all. There are no reasons for this anymore. It is not something that can be quickly changed though.

Shouldn't be terribly complicated and a good idea we may consider in the future.

**Comment by NolaDonato** [comment]
I totally support this. I can work with you on changing it.

**Comment by liaxim** [comment]
@spakanati123 We have a pending pull request that does that. See https://github.com/Samsung/GearVRf/pull/1930.

**Comment by liaxim** [comment]
@spakanati123 It is now possible not to derive from GVRActivity. Planning to close the issue in few days if there are no comments.
