### ISSUE TITLE
android components are not smooth on GVRSceneObject

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1879]
i added the recycler view to my GVRViewSceneObject but the components like ImageView and Button edges are not smooth and i can see aliasing(nasty little-jagged edges) all over edges, some kind of lines moving on edges, it's making eys strain very quickly.
Is there any params i can add to minimize this effect ..?

**Comment by thomasflynn** [comment]
another user had some hints in this thread: https://github.com/Samsung/GearVRf/issues/1155

**Comment by ragner** [comment]
Hi @spakanati123,
 @liaxim may give you some RenderData's configuration.

But could you try
https://developer.android.com/studio/write/draw9patch as background?
9patch may give you a good result as well.

**Comment by ragner** [comment]
Hi @spakanati123 could try the thread https://github.com/Samsung/GearVRf/issues/1155 mentioned by @thomasflynn and send us any feedback?

**Comment by spakanati123** [comment]
@ragner the conclusion on the thread #1155 is to use the layout size in proportion to quad size. 
700 pix layout ~ 1F quad size.
But this is not the good idea as far as i know, we can not hardcode layout values which is not a recommended approach.

**Comment by liaxim** [comment]
@spakanati123 While in general Android development that is true, using Android views in VR is a special case which merits considering breaking the rules. Thread #1155 has pretty much everything we have on the topic. You could try applying only the convolution shader and see how that works for you.

**Comment by liaxim** [comment]
@spakanati123 Assuming it is all good. Planning to close in few days.
