### ISSUE TITLE
jAssimp: 3D Model loading fails if first level children has no mesh

### ISSUE THREAD

**Issue by deepakrawat22** [Samsung/GearVRf#188]
GearVRf jAssimp feature will fail to load a 3D model if the node hierarchy is such that first level children do not have any mesh.

![untitled](https://cloud.githubusercontent.com/assets/8952072/8920906/4f86b07a-3484-11e5-9876-975c104ab0a0.png)

Currently it just ignores rest of hierarchy in the function getAssimpModel().

The test file I used is f16a.fbx (https://github.com/deepakrawat22/GearVRApps/tree/master/gvrtest1/assets)

**Comment by lokeshguddu** [comment]
Hi @deepakrawat22 ,

Thanks for bringing this to our notice. We will have a look into the implementation and revert back with a solution. Meanwhile if you find something else, please let us know.

Thanks.

**Comment by lokeshguddu** [comment]
Hi @deepakrawat22 ,

We've fixed the issue. Please have a look [https://github.com/Samsung/GearVRf/pull/189].

In case we missed something, please let us know.

Thanks
