### ISSUE TITLE
how to attach our own video surface to GVRViewSceneObject

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1881]
We have our own custom exo-library plugin which provides the exo-player instance.
But GVRF allow only SimpleExoPlayer instance for GVRVideoSceneObjectPlayer so we decided to eliminate the GVRVideoSceneObjectPlayer which causes the missing logic to set surface.

We have our own surface which is not possible to attach to GVRVideoSceneObject so i decided to attach to GVRViewSceneObject.
steps i followed:
-> attach our surface view to Framelayout and then call 
`mPlayerScene = new GVRViewSceneObject(mGVRContext, playerlayout, PLAYER_WIDTH, PLAYER_HEIGHT);`

but i can listen only audio without any video so please suggest how to achieve this behavior.
I did not find any api to set material type OESHorizontalStereo.ID for my scene.

A quick suggestion will be appreciated.
Thanks in advance.

**Comment by spakanati123** [comment]
@liaxim thanks for quick reply, as u said it's not working even after adding OESHorizontalStereo.ID to GVRViewSceneObject. I will check for alternate solution.

**Comment by ragner** [comment]
Hi @spakanati123, 
GVRViewSceneObject will not work for this issue.

I am not sure whether the following code is what you need,
but I guess you could try it :)

```
final GVRTexture texture = new GVRExternalTexture(mGVRContext);
final GVRMaterial material = new GVRMaterial(mGVRContext, GVRShaderType.OES.ID);
final SurfaceTexture surfaceTexture = new SurfaceTexture(texture.getId());
final Surface  surface = new Surface(surfaceTexture);

surfaceTexture.setDefaultBufferSize(video.getWidth(), video.getHeight());

SceneObject videoObject = new SceneObject(gvrContext, width, height);

 material.setMainTexture(texture);
 videoObject.getRenderData().setMaterial(material);

```

Set surface instance to your player.

**Comment by spakanati123** [comment]
i fixed this issue by creating a wrapper class to connect to our exo-player plugin.
Thanks for your inputs @ragner , @liaxim
