### ISSUE TITLE
is there any high end sample app to refer and build high end business application

### ISSUE THREAD

**Issue by sams89** [Samsung/GearVRf#1901]
i am checking for any high-end sample app like adding many scene objects to the main scene and the output should be like listview or recycler view functionality.
The scene objects added to parent scene should be scroll very smooth and fast without any memory leaks.
The provided sample apps are pretty simple and not much helpful while writing for high-end business.
Is there any possibility to add sample app which covers
 - the UI should be like recylerview or listview(many scene objects with vertical scrolls) 
 - setting image to scene object from network url

Thanks

**Comment by thomasflynn** [comment]
Hi @sams89 .  What you're asking for is certainly possible.  I believe EvryPlace: https://www.oculus.com/experiences/gear-vr/1739742929422865/ (which is a GearVRf app) accomplishes this.  But I assume you're looking for source code on how to do this.

The good news is that our friends at SIDIA in Brazil are working on a more comprehensive 360 video player sample app that should provide source and demonstrate what you're looking for.  But you'll have to be a bit patient, its release is still several weeks away.  @ragner please keep this issue/thread in mind as your team develops this app.  Thank you.

**Comment by praveenpokuri** [comment]
Yes, It could be helpful if there is a comprehensive app.

**Comment by ragner** [comment]
Hi @thomasflynn,
We will prioritize this working to do a pull request soon.

**Comment by spakanati123** [comment]
@ragner when we can expect the PR commit?

**Comment by spakanati123** [comment]
@ragner any update on this?
cc @thomasflynn , @liaxim

**Comment by acosta** [comment]
Hi all, we have submitted a PR with video player example. See https://github.com/gearvrf/GearVRf-Demos/pull/630 for more details.

**Comment by liaxim** [comment]
@sams89 The video player has been merged. See https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-videoplayer/app. Planning to close the issue in few days if you don't have any other comments.

**Comment by felislynx-silae** [comment]
@sams89 Evryplace developer here ;). It is not that hard to apply high quality of android views right now. GearVRf traveled long road from first versions on which we worked. Playing videos (normal or 360) is also quite easy. Only thing that you will have to handle is hover events and or clicks. And be aware of on which thread you are launching events :). Good luck
