### ISSUE TITLE
signature problem on testing models

### ISSUE THREAD

**Issue by spakanati123** [Samsung/GearVRf#1919]
Hi,
since to build dev apk we need to give Oculus signature file in assets folder but it's becoming very difficult to generate apk based on each device id.
Is there any way to generate single apk which wil fit for all our testing models.

**Comment by liaxim** [comment]
Hi @spakanati123. sideloadvr.com might be of use to you.

**Comment by spakanati123** [comment]
Thanks @liaxim

**Comment by liaxim** [comment]
@spakanati123 Can we close the issue?

**Comment by liaxim** [comment]
Closing for now. Let us know if you have other questions.
