### ISSUE TITLE
GVRVideoSceneObject automatically restarts paused videos

### ISSUE THREAD

**Issue by SteveGreatApe** [Samsung/GearVRf#1923]
I've got a problem with GVRVideoSceneObject pausing and resuming videos when the headset goes to sleep.

I had a video playing in a GVRVideoSceneObject that I've paused myself using the MediaPlayer pause() function. I then remove the headset, let the device go to sleep, put the headset back on and the video automatically starts playing again.

I can see why this is happening, in GVRVideoSceneObject it has this code.

```
    private IActivityEvents mActivityEventsListener = new GVREventListeners.ActivityEvents() {
        @Override
        public void onPause() {
            gvrVideoSceneObjectPlayer.pause();
        }

        @Override
        public void onResume() {
            gvrVideoSceneObjectPlayer.start();
        }
```

This code assumes the video was already playing and always restarts it on onResume regardless

I've tried adding calls to GVRVideoSceneObject activate()/deactivate() alongside my MediaPlayer start()/pause() calls. This causes the display not to refresh the video when it re-starts, but I can still see from the logs the video has restarted and is running even though the display isn't being refreshed due to the GVRVideoSceneObject deactivate() call.

**Comment by liaxim** [comment]
Let me know how https://github.com/Samsung/GearVRf/pull/1925 works out for you. Thanks.

**Comment by SteveGreatApe** [comment]
The fix looks good thanks, working for me okay.

**Comment by liaxim** [comment]
@SteveGreatApe Can we close the issue? Fix has been merged. Thanks.

**Comment by SteveGreatApe** [comment]
Yes, merged fix is looking good,thanks.
