### ISSUE TITLE
Touch screen with picker in monoscopic mode to AR applications

### ISSUE THREAD

**Issue by ragner** [Samsung/GearVRf#1965]
We are facing some use cases at our AR application where the user needs interact with virtual objects in the scene by touch screen.
Is it possible add some "Touch Controller" for monoscopic mode?

**Comment by liaxim** [comment]
Let's gather some requirements. How does the existing gaze controller not work with monoscopic well enough for you?

**Comment by ragner** [comment]
Hi @liaxim,
The following links show some example of interaction that we are expecting to do:

https://youtu.be/bNJJCREZgVM?t=1616
https://youtu.be/bNJJCREZgVM?t=1167

Other more:

https://youtu.be/bNJJCREZgVM?t=418
https://youtu.be/bNJJCREZgVM?t=1102
https://youtu.be/bNJJCREZgVM?t=1601

I think we could have some  "touch mode" at GazeController.
 So at "touch mode" the cursor's position should be updated by touch on screen.

**Comment by liaxim** [comment]
@ragner Can we close?

**Comment by ragner** [comment]
yes, you can close this.
