### ISSUE TITLE
how can I get controller clicked

### ISSUE THREAD

**Issue by bell-one** [Samsung/GearVRf#1970]
I'd like to check controller clicked or not,

In daydream controller, it can be easily done by check clickButtonState variable in controller.

I search for this job in Gearvrf, but I can only find picking events on controller pickEventListener,

In my app I don't need to check picking Event. only need clicked or not information of controller,
I found some Log EVENT :: Keypressed on GVRGearCursorController.java but I can't use this part.

How can I get information that controller clicked or not?

**Comment by liaxim** [comment]
@bell-one Made a small change that I believe addresses your concern. See https://github.com/Samsung/GearVRf/pull/1971.

You can receive the event with this code (no picking involved, as you requested):
```
        getGVRContext().getApplication().getEventReceiver().addListener(new GVREventListeners.ActivityEvents() {
            @Override
            public void onControllerEvent(GVRGearCursorController.CONTROLLER_KEYS key, Vector3f position, Quaternionf orientation, PointF touchpadPoint, boolean touched, Vector3f angularAcceleration, Vector3f angularVelocity) {
            }
        });
```

Whenever the ``key`` is not BUTTON_NONE the controller is reporting a key press. Bear in mind that you will get that key continuously for as long as the user keeps the key pressed.
