### ISSUE TITLE
Sphere with stereo image and position of GVRSceneObject

### ISSUE THREAD

**Issue by zagart** [Samsung/GearVRf#1974]
Hi! I have a question regarding relationships between stereoscopic environment and SDK objects.

To be precise, I have a sphere with texture which is rendered using shader `UnlitVerticalStereo`. It works just fine. Problem appears when I try to add object, which should be bound to something in texture - in my case it is `GVRVideoSceneObject`. I want video object be associated with TV screen in texture. Image for left and right eye is different, hence video object is located in different positions for each eye.

Is there any way to render same object with different position for every eye?
![preview](https://user-images.githubusercontent.com/14848139/44529863-ca896380-a6f5-11e8-9c71-c3eef800d801.JPG)

**Comment by zagart** [comment]
Issue was resolved by setting correct distance between eyes (as on rendered image) in [configuration file](http://www.gearvrf.org/programming_guide/gearvr_settings_files/) (`interpupillaryDistance`).

**Comment by liaxim** [comment]
@adiliqbl Can you please open a new issue and add a bit more detail? Like snippet of code, a screenshot.. Thanks.
