### ISSUE TITLE
Bones animation issue at model with parent

### ISSUE THREAD

**Issue by ragner** [Samsung/GearVRf#1975]
Steps to  reproduce at meshanimation demo:
1) Add a parent object A to the scene.
2) Load the model B with animation.
3) Add the loaded model B as child of object A.
4) Set a new position to the parent object A
5) Start the animation at model B.

The bones animation is missing the parent's transform.

**Comment by liaxim** [comment]
@ragner This I believe has been fixed by the recent skeletal animation PR. Based on my tests it is. Please confirm.

**Comment by dsazulay** [comment]
The parent problem seems to be fixed. But we are having other problems. The engine is deforming some models and it's not possible to select specific animations when a model has more than one animation.

![screenshot_20180914-093009_gvr-simplesample](https://user-images.githubusercontent.com/4058875/45555572-259b0b80-b807-11e8-87fc-67973739afef.jpg)

I modified the simple sample demo to show you the problems.
https://github.com/dsazulay/GearVRf-Demos/tree/animation_test

**Comment by NolaDonato** [comment]
The asset importer we have does not support multiple animations. You will need to separate the animations into different files. The best way to do this is to import the model separately from the animation. Put your model in an FBX file with no animation. Then put each animation in a separate FBX or BVH file. BVH is probably best because it just represents animation and no skins or geometry. For FBX, put the meshes in but no textures. It needs the bones in there to properly import animation.

The gvr-avatar demo shows how to do this. We will be merging in the bvhAnimation pull request shortly which fixes bugs in that importer. It is also possible to retarget animations from one skeleton to another if they are similar. The demo shows how to do that as well.

**Comment by liaxim** [comment]
There is still the problem with the messed up animations. See gvr-javascript in master.

**Comment by ragner** [comment]
Hi @NolaDonato,
GVRAvatar requires a "String bone map" to load the bvh animation.

Is it possible to provide a api to load the bvh file and map its bones automatically when the 
armature are the same for both bvh and fbx file? 

If my request is not possible to be provided,
How could I generate that "string bone map"?

**Comment by NolaDonato** [comment]
If you omit the bone map it will do that automatically. GVRPoseMapper will construct its own bone map based on matching bone names from the source and target skeletons.
If the source and target skeletons are different, it needs to know how to map the bones. The bone map string tells it how to do this. Each line of the string has the name of the source bone a space and the name of the corresponding target bone.

**Comment by ragner** [comment]
Hi @NolaDonato,
I have a FBX file with the mesh and skeletons and other FBX with the animation and skeleton.
But I am getting the follow error message when I try to load the FBX with the animation.

```

10-10 11:56:56.406 13771-14028/org.gearvrf.avatardemo E/Threads: java.lang.ClassCastException: org.gearvrf.animation.keyframe.GVRNodeAnimation cannot be cast to org.gearvrf.animation.keyframe.GVRSkeletonAnimation in thread 5662
10-10 11:56:56.406 13771-14028/org.gearvrf.avatardemo W/System.err: java.lang.ClassCastException: org.gearvrf.animation.keyframe.GVRNodeAnimation cannot be cast to org.gearvrf.animation.keyframe.GVRSkeletonAnimation
10-10 11:56:56.407 13771-14028/org.gearvrf.avatardemo W/System.err:     at org.gearvrf.animation.GVRAvatar$3.onAssetLoaded(GVRAvatar.java:488)
        at org.gearvrf.GVRAssetLoader$AssetRequest.onAssetLoaded(GVRAssetLoader.java:383)
        at org.gearvrf.GVRAssetLoader$AssetRequest.generateLoadEvent(GVRAssetLoader.java:438)
        at org.gearvrf.GVRAssetLoader$AssetRequest.onModelLoaded(GVRAssetLoader.java:270)
        at org.gearvrf.GVRAssetLoader.loadJassimpModel(GVRAssetLoader.java:1837)
        at org.gearvrf.GVRAssetLoader.access$100(GVRAssetLoader.java:64)
10-10 11:56:56.408 13771-14028/org.gearvrf.avatardemo W/System.err:     at org.gearvrf.GVRAssetLoader$6.run(GVRAssetLoader.java:1593)
        at org.gearvrf.utility.Threads$1.run(Threads.java:108)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
10-10 11:56:56.409 13771-14028/org.gearvrf.avatardemo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ragner** [comment]
We don't know how to create a bvh file to a quadruped.
Do you have any suggestion of software or anything else?

**Comment by spodila1** [comment]
MotionBuilder tool helps to import fbx and export into bvh animation files.

**Comment by ragner** [comment]
Hi @spodila1,
do you have any tutorial about exporting bvh from MotionBuilder or
could you help us to export if a send you our FBX with the animations?

**Comment by spodila1** [comment]
Ok, please send me the FBX.

**Comment by dsazulay** [comment]
Hi @spodila1, this file contains the animations that we need. Thank you!

[Pet.fbx.zip](https://github.com/Samsung/GearVRf/files/2470897/Pet.fbx.zip)

**Comment by ragner** [comment]
Hi @spodila1,
if possible, use it to test the bvhAnimation support.

Thank you.

**Comment by spodila1** [comment]
@dsazulay I do not see the animations on model. I just got the model when imported in Maya

**Comment by liaxim** [comment]
@spodila1 There are animations. I can see them with Autodesk's FBX review.

**Comment by spodila1** [comment]
@liaxim Ok. some how I could not see the keyframes when imported in Maya. I could see the animations in Motion Builder

**Comment by spodila1** [comment]
@dsazulay Hi, the attached file contains bvh files. I will also be testing with them. 
[BVHEXPORT.tar.gz](https://github.com/Samsung/GearVRf/files/2474229/BVHEXPORT.tar.gz)

**Comment by spodila1** [comment]
@ragner Hi, I tried to test the bvh animations on the fbx file you sent me. The animations are not as the expected because of the fbx file contains some extra information and the parser can not handle it.
Could you send me the Maya file or Blender file in which the pet model was originally created. I will try to export into fbx by my self and then will test the animations.

Thank you.

**Comment by dsazulay** [comment]
@spodila1 Hi, here is the maya project.
[PET_ANIMATIONS_baked.mb.zip](https://github.com/Samsung/GearVRf/files/2475604/PET_ANIMATIONS_baked.mb.zip)

**Comment by spodila1** [comment]
@dsazulay Hi, I am unable to open the file in Maya. Could you send me the ASCII file. I will try with that.

**Comment by dsazulay** [comment]
Which version of Maya are you using? This project was created with the 2018 version.
[PET_ANIMATIONS_009_baked.ma.zip](https://github.com/Samsung/GearVRf/files/2480171/PET_ANIMATIONS_009_baked.ma.zip)

**Comment by spodila1** [comment]
Ok. I am using Maya 2016 version. Lost information when tried with ASCII file.

**Comment by spodila1** [comment]
I have tested with bvh Animations. It worked for me. I used collada instead of fbx.

**Comment by ragner** [comment]
Hi @spodila1,
about the "extra information" from our FBX file. Do you have any suggestion about the right way to export it?

We still don't have our pet working with animations.

**Comment by ragner** [comment]
Hi @spodila1,
does it work on master branch our should I use Nola's bvhAnimation branch?

**Comment by spodila1** [comment]
I used Nola's bvhAnimation branch

**Comment by dsazulay** [comment]
Hi @spodila1 
I'm getting this error on gvr-avatar


```
10-19 16:01:05.983 29857-29893/org.gearvrf.avatardemo E/Threads: java.lang.IndexOutOfBoundsException: Animation index out of bounds in thread 2136
10-19 16:01:05.983 29857-29893/org.gearvrf.avatardemo W/System.err: java.lang.IndexOutOfBoundsException: Animation index out of bounds
        at org.gearvrf.animation.GVRAvatar.start(GVRAvatar.java:391)
10-19 16:01:05.984 29857-29893/org.gearvrf.avatardemo W/System.err:     at org.gearvrf.avatardemo.AvatarMain$1.onAnimationLoaded(AvatarMain.java:77)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:312)
        at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:147)
        at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
        at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
        at org.gearvrf.animation.GVRAvatar.loadAnimation(GVRAvatar.java:274)
        at org.gearvrf.avatardemo.AvatarMain.loadNextAnimation(AvatarMain.java:134)
        at org.gearvrf.avatardemo.AvatarMain.access$400(AvatarMain.java:24)
        at org.gearvrf.avatardemo.AvatarMain$1.onAvatarLoaded(AvatarMain.java:66)
        at java.lang.reflect.Method.invoke(Native Method)
10-19 16:01:05.985 29857-29893/org.gearvrf.avatardemo W/System.err:     at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:312)
        at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:147)
        at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
        at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
        at org.gearvrf.animation.GVRAvatar$2.onAssetLoaded(GVRAvatar.java:518)
        at org.gearvrf.GVRAssetLoader$AssetRequest.onAssetLoaded(GVRAssetLoader.java:383)
        at org.gearvrf.GVRAssetLoader$AssetRequest.generateLoadEvent(GVRAssetLoader.java:438)
        at org.gearvrf.GVRAssetLoader$AssetRequest.onModelLoaded(GVRAssetLoader.java:270)
        at org.gearvrf.GVRAssetLoader.loadJassimpModel(GVRAssetLoader.java:1837)
        at org.gearvrf.GVRAssetLoader.access$100(GVRAssetLoader.java:64)
        at org.gearvrf.GVRAssetLoader$6.run(GVRAssetLoader.java:1593)
        at org.gearvrf.utility.Threads$1.run(Threads.java:108)
10-19 16:01:05.986 29857-29893/org.gearvrf.avatardemo W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by spodila1** [comment]
Which gvr-avatar demo are you you using? Please take from the Nolas masteredit branch. For the demo, put the attached file in the assets folder and edit path in mBoneMapPath. This does the bone mapping.
[pet_map.txt](https://github.com/Samsung/GearVRf/files/2503191/pet_map.txt)

**Comment by ragner** [comment]
@spodila1 How did you create this pet_map.txt file?
Our pet's FBX file has the same skeleton than the BVH files. So this pet_map.txt should not be necessary.

**Comment by ragner** [comment]
@spodila1 Could you please send to me your collada file of the pet?

**Comment by spodila1** [comment]
Please find the attached
[pet_E.tar.gz](https://github.com/Samsung/GearVRf/files/2507528/pet_E.tar.gz)

**Comment by spodila1** [comment]
I could not find when imported in MotionBuilder, Could you please let me know frame number range where the IDLE animation is in the file.

**Comment by ragner** [comment]
Hi @spodila1,
it is missing in the FBX file that @dsazulay  sent to you :(

IDLE animation is in the follow FBX, but it was exported from Maya 2018.

[PET_ANIMATIONS_03.fbx.zip](https://github.com/Samsung/GearVRf/files/2516485/PET_ANIMATIONS_03.fbx.zip)

**Comment by spodila1** [comment]
[BVHEXPORT_IDLE.zip](https://github.com/Samsung/GearVRf/files/2516731/BVHEXPORT_IDLE.zip)
Please find the attached.

**Comment by ragner** [comment]
Hi @spodila1,
I just sent a new PR with our pet demo.  https://github.com/gearvrf/GearVRf-Demos/pull/650
It depends on https://github.com/Samsung/GearVRf/pull/2016

We are facing a issue with the pet model.
Sometimes it is not rendering the head of the pet during the animations :(

We need help with this issue.

**Comment by ragner** [comment]
Sometimes it is not rendering the eyes and head of the pet during the animations.
It looks a Culling issue. But I can report it on SXR repository

**Comment by liaxim** [comment]
Ok, thanks. Please open a new one then.
