### ISSUE TITLE
Access to raw HMD sensor data

### ISSUE THREAD

**Issue by Joshf17000548** [Samsung/GearVRf#1984]
Is there a way to get access to the raw HMD sensor data to create and log the rotation matrix as the user uses an application?

**Comment by liaxim** [comment]
Hi. We have no access to the raw HMD sensor data but we do get the orientation quaternion from the Oculus Mobile SDK. You can obtain it from GVRContext.getMainScene().getMainCameraRig().getHeadTransform().

**Comment by Joshf17000548** [comment]
Yes, that was what I was looking for. Thank you.
