### ISSUE TITLE
Current state of project [QUESTION]

### ISSUE THREAD

**Issue by schoenobates** [Samsung/GearVRf#1990]
Hi all! I'm just wondering what the current state of the project is? Just come back after a while away and the releases seem to be labelled as (GearVRF_Full_Maint_0.1.436) - does this mean that it's now only in maintenance mode or are there plans for a new release soon? I noticed the last one was 4.0 back in Oct 2017.

Thanks for any info!

**Comment by thomasflynn** [comment]
We are still actively developing.  We have another release coming up in the beginning of November.

**Comment by schoenobates** [comment]
Awesome! Thanks @thomasflynn - good to know. Still such an awesome project :1st_place_medal:
