### ISSUE TITLE
WidgetLib gives build failure in framework-tests

### ISSUE THREAD

**Issue by NolaDonato** [Samsung/GearVRf#2004]
gearvrf/framework-tests/WidgetLibTests does not compile. It gets the following error:

error: <anonymous org.gearvrf.tester.WidgetLibTests$3> is not abstract and does not override abstract method getFlingHandler() in ContentScene

**Comment by joker-b** [comment]
I get widgetlib errors when building gearvr-demos as well, using a fresh Win10 environment

`Could not find org.gearvrf:widgetlib:4.0.1-SNAPSHOT`

Possibly related? I'm on gradle 4.4

**Comment by liaxim** [comment]
@joker-b Your problem was fixed by https://github.com/gearvrf/GearVRf-Demos/pull/651.

**Comment by liaxim** [comment]
As far as I know it builds now
