### ISSUE TITLE
Hi, Can we create two GVRActivity inside a app.If I am doing so,getting this exception :.--->E/libEGL: call to OpenGL ES API with no current context (logged once per thread)

### ISSUE THREAD

**Issue by talk2saroj** [Samsung/GearVRf#2012]

**Comment by talk2saroj** [comment]
Is the above exception happening because of the two GVRActivities?

**Comment by liaxim** [comment]
This particular message can be considered a minor annoyance and can be ignored.

Two GVRActivities is/can be a backend-dependent question. I have a vague memory of Oculus publishing restrictions - better to be checked on their web site.

There have been attempts to use more than one GVRActivity with Oculus and generally it didn't work. It is not something we officially support. Depending on how important it is to you, we could take a look at it again.

**Comment by liaxim** [comment]
And no, that message can be observed with a single GVRActivity too.

**Comment by liaxim** [comment]
@talk2saroj Do you have further questions regarding this topic? If not, can we close the issue?
