### ISSUE TITLE
Distorted View

### ISSUE THREAD

**Issue by talk2saroj** [Samsung/GearVRf#2014]
When I am trying to rotate one scene object, the corner end of the view is getting distorted.Here is my code:
  viewSceneObject.getTransform().setScale(5f, 5, 1);
  viewSceneObject.getTransform().setPosition(10,0,0);
  viewSceneObject.getTransform().setRotation(0.7071f,0,-0.7071f,0);
  viewSceneObject.setTextureBufferSize(1024);

How to fix it.Please help.

**Comment by liaxim** [comment]
@talk2saroj Do you a screenshot or two to share with us? Thanks.

**Comment by ragner** [comment]
@talk2saroj could try reducing the texture buffer size?
You may get a better result to small text:
viewSceneObject.setTextureBufferSize(512);

**Comment by talk2saroj** [comment]
Still the same

**Comment by liaxim** [comment]
@talk2saroj Where are you with this issue? Do you need further assistance?

**Comment by talk2saroj** [comment]
Hi, Sorry for the late reply.
I have fixed my issue in some different way.I do not need any assistance
regarding this now.
Thank you for your valuable support.
