### ISSUE TITLE
Scene Object's position is getting reset on movement of head.

### ISSUE THREAD

**Issue by talk2saroj** [Samsung/GearVRf#2015]
Scene object position is getting reset some time when we move our head.How to fix it exactly at some particular coordinate.

**Comment by liaxim** [comment]
@talk2saroj Can you share some sample code? Any additional information will be helpful. Are you trying to have a head-locked object? See ``getMainScene().getMainCameraRig().addChildObject(your-object)``.

**Comment by liaxim** [comment]
@talk2saroj Please reopen when you have a little bit more information you can share with us.
