### ISSUE TITLE
Override GearVR Headset Back Key Press

### ISSUE THREAD

**Issue by serarmatloob** [Samsung/GearVRf#2017]
Hello,

A recent push to GearVRf seems to have broken the listening to Back Key press events of GearVR headset. It used to work by overriding onBackPressed() method, but now it doesn't at all. Any workaround to get the override capability of the back key? I am trying to map the back key so that it resets the view orientation on key press.

Thanks,
Serar

**Comment by liaxim** [comment]
Are you using the snapshots or are you building yourself?

**Comment by serarmatloob** [comment]
I'm using snapshot: 4.0.1-SNAPSHOT

**Comment by liaxim** [comment]
It seems this is side-effect of using the new Oculus Mobile SDK.

**Comment by serarmatloob** [comment]
Thanks @liaxim for looking into this. Does that mean there is no fix for that or a way around it? How can I use an older version of Oculus Mobile SDK?

**Comment by liaxim** [comment]
There will be a fix. We just need to implement the back key handling according to the new SDK requirements.

**Comment by serarmatloob** [comment]
Ok thank you for confirming that. Will wait for the fix 👍

**Comment by liaxim** [comment]
Fixed by https://github.com/Samsung/GearVRf/pull/2019; the snapshot for the oculus support module has been updated.

**Comment by liaxim** [comment]
@serarmatloob Assuming it is all good. Let us know if otherwise.
