### ISSUE TITLE
org.gearvrf:platformsdk_support 4.0.1-SNAPSHOT GVRActivity cast error

### ISSUE THREAD

**Issue by Sorduea** [Samsung/GearVRf#2026]
Trying to use the PlatformEntitlementCheck with gearvrf 4.0.1-SNAPSHOT and I'm getting the following error:

Caused by: java.lang.NoSuchMethodError: No virtual method getActivity()Lorg/gearvrf/GVRActivity; in class Lorg/gearvrf/GVRContext; or its super classes (declaration of 'org.gearvrf.GVRContext'

I believe it is casting to GVRActivity when GVRContext.getActivity returns Activity.

**Comment by liaxim** [comment]
@Sorduea The snapshot was outdated. Please make sure your gradle dependencies are refreshed and try again.

**Comment by Sorduea** [comment]
Refreshed dependencies and the entitlement check now succeeds. Thank you for the help and quick response.
