### ISSUE TITLE
Android 9 Frame Rate Slowed Down

### ISSUE THREAD

**Issue by Sorduea** [Samsung/GearVRf#2040]
After upgrading different Samsung phones to Android 9, the apps using GearVRf are now rendering slow at about 1-2 FPS. I tested this using the most recent build on GearVRf-Demos - gvr-360video. Can anyone confirm this behavior?

**Comment by seungchan90** [comment]
I met same issues.
It happened after PIE os update.

`@Override
public void onStep() {
    getGVRContext().getActivity().getFullScreenView().invalidate();
}`

It works but It is not proper fix for this issue.
Please check this frame issue.

**Comment by liaxim** [comment]
Fix has been merged in master. The master snapshots on maven have been updated too. Thanks for letting us know.

**Comment by Sorduea** [comment]
The fix is working for my applications. Thank you for the quick turnaround. Closing the issue.
