### ISSUE TITLE
Black texture.

### ISSUE THREAD

**Issue by lokeshguddu** [Samsung/GearVRf#206]
Hi,

While trying to test some models with min filter set as GL_LINEAR_MIPMAP_LINEAR and warp state set as GL_REPEAT, I'm getting a black texture on all the objects.

Anyone else having same issue?

**Comment by thomasflynn** [comment]
are the textures mipmapped or mipmappable?  For example TEXTURE_EXTERNAL won't work with trilinear filtering, there's no mimap levels.  I think we had a similar problem with cubemaps.

Another thing to look into is if you are loading asynchronously.  if you load synchronously, does the problem go away?

**Comment by lokeshguddu** [comment]
Hi @thomasflynn ,

I'll try synchronously and test.

Thanks for the reply.
