### ISSUE TITLE
GVRAccelerateDecelerateInterpolator::mapRatio(float) - Negative infinity 

### ISSUE THREAD

**Issue by nathan-almeida** [Samsung/GearVRf#21]
A map ratio for positive infinity value returns NAN instead of NEGATIVE_INFINITY

```java
public void testMapRatioNegativeInfinity() {
        GVRAccelerateDecelerateInterpolator interpolator = GVRAccelerateDecelerateInterpolator.getInstance();
        assertEquals(interpolator.mapRatio(Float.NEGATIVE_INFINITY), Float.NEGATIVE_INFINITY);
}
```

**Comment by JonShemitz** [comment]
I'm not sure there's any point to testing this parameter: This is _not_ user-facing code; it is only called by the animation engine, and the inputs are always in the range [0, 1].
