### ISSUE TITLE
Better way to deal with multiple shaders

### ISSUE THREAD

**Issue by rongguodong** [Samsung/GearVRf#210]
To be able to apply different shaders on a same mesh correctly, my commit #73 generates different VAOs for different shaders and cached them in a map. The reason for that is because the order of the parameters in different shaders may be different. As the result, a same attribute may be in different locations in different shaders (e.g. "normal" may be the 2nd attribute in shader 1, but be the 3rd attribute in shader 2). Although commit #73 fixed the problem, it is not very efficient to keep multiple VAO's for a mesh.

I recently realized that we can in fact explicitly bind attributes and locations. No matter what order the attributes are in a shader, we can always use the same locations for them. As the result, we can always use the same VAO for all shaders. This could greatly simplify the code and improve the efficiency.

More details of explicitly binding attributes and locations can be found at:
http://stackoverflow.com/questions/4635913/explicit-vs-automatic-attribute-location-binding-for-opengl-shaders/4638906#4638906

I may not have time to make a new pull request implementing this idea. So I would like to just post the better approach here, and someone may want to implement it following the idea.

**Comment by thomasflynn** [comment]
Thanks Guodong!  Good to hear from you :).  I have a new guy starting on Monday.  I now know his first assignment :)  Thanks again man.

**Comment by danke-sra** [comment]
This is fixed by https://github.com/Samsung/GearVRf/commit/eb2f16d79cfe7d08ec13162c53fd0360fa3321d9

Can this be closed?
