### ISSUE TITLE
Fix memory leak in native layer

### ISSUE THREAD

**Issue by danke-sra** [Samsung/GearVRf#214]
C++ objects allocated in JNI files are never deallocated.

For example, the Material object allocated in the native constructor is never freed.

JNIEXPORT jlong JNICALL
Java_org_gearvrf_NativeMaterial_ctor(JNIEnv * env, jobject obj,
    jint shader_type) {
return reinterpret_cast<jlong>(new Material(static_cast<Material::ShaderType>(shader_type)));
}

This applies to other C++ objects allocated in the JNI files too.

**Comment by liaxim** [comment]
See hybrid_object_jni.cpp and GVRHybridObject.GVRReference.

**Comment by dknaan** [comment]
Please check GVRF2.0 commit by Jon regarding dislocation of JNI objects: https://github.com/Samsung/GearVRf/commit/9a8df14a37cdd99c48d8df9565cfe9a69639d293
