### ISSUE TITLE
BUG gvrContext.loadFutureCubemapTexture()

### ISSUE THREAD

**Issue by douglasalipio** [Samsung/GearVRf#219]
I have a file home.zip in folder raw. When I load file home.zip using the gvrContext.LoadFutureCubemapTexture I get error:

`java`
E/gvrf(28904): Error detected in Renderer::renderRenderData; name : , error : Material::getTexture() : main_texture not found
`java`

Just change beach.zip file from the sample gvrCubmap.

![enricokitchen_07](https://cloud.githubusercontent.com/assets/896757/9233920/cf9b334a-4103-11e5-863b-a7b1a45dd879.png)
![enricokitchen_08](https://cloud.githubusercontent.com/assets/896757/9233921/cf9bca94-4103-11e5-91b9-d8920873b11a.png)
![enricokitchen_09](https://cloud.githubusercontent.com/assets/896757/9233922/cf9d2a10-4103-11e5-8f6a-897e04ae5761.png)
![enricokitchen_10](https://cloud.githubusercontent.com/assets/896757/9233923/cf9e7b54-4103-11e5-842b-368305d9f047.png)
![enricokitchen_11](https://cloud.githubusercontent.com/assets/896757/9233925/cfa9b924-4103-11e5-8786-920fddc105a5.png)
![enricokitchen_12](https://cloud.githubusercontent.com/assets/896757/9233924/cfa80b2e-4103-11e5-8d86-c0c5ddcee00e.png)

**Comment by thomasflynn** [comment]
FYI, Danke on our team will take a look at this issue.

**Comment by danke-sra** [comment]
@douglasalipio 

Thanks for reporting the issue. We are working on a fix.

Meanwhile you may try a workaround. 
1) Use another environment type supported by the sample gvrcubemap. That is, in the file CubemapScript.java, change mEnvironmentType from 0 to 1 (line 48).

2) Put your images in Android resource res/drawable-xxxhdpi, and replace the existing images "back.png", "bottom.png", "front.png", "left.png", "right.png" and "top.png".

3) In the method onInit() in CubemapScript.java, disable stats with "scene.setStatsEnabled(false);" if it is currently on.

Please let us know how it helps. We will push a fix as soon as possible. Thanks again for reporting the issue.

**Comment by douglasalipio** [comment]
Thank you @danke-sra it's work for me.

**Comment by danke-sra** [comment]
The sample gvrcubemap has been updated to include a sample showing how to use cubemap with textures loaded from a .zip file. I think the issue can be closed. https://github.com/Samsung/GearVRf/pull/225
