### ISSUE TITLE
native mipmappedConstructor:(I)J not found

### ISSUE THREAD

**Issue by elidelsonc** [Samsung/GearVRf#230]
Hello,

I am trying to write unit test for class GVRCompressedTexture and I am getting the following error:

GVRCompressedTexture :: NativeCompressedTexture

java.lang.UnsatisfiedLinkError: Native method not found: org.gearvrf.asynchronous.NativeCompressedTexture.mipmappedConstructor:(I)J 

```
class NativeCompressedTexture {
    static native long normalConstructor(int target, int internalFormat,
            int width, int height, int imageSize, byte[] data,
            int[] textureParameterValues);

    static native long mipmappedConstructor(int target);
}
```

Best regards,

Elidelson Carvalho
Sidia Brazil - UX team

**Comment by liaxim** [comment]
In compressed_texture_jni.cpp the method name has been changed to Java_org_gearvrf_asynchronous_1textures_NativeCompressedTexture_mipmappedConstructor (notice the "1textures"). You could correct the name to "Java_org_gearvrf_asynchronous_NativeCompressedTexture_mipmappedConstructor" and it should be found. Maybe someone knows why was this done - the history log is of no help.

**Comment by thomasflynn** [comment]
@elidelsonc, did you try what @liaxim suggested?  did that fix it for you?  if so, we'll submit a quick fix.

**Comment by elidelsonc** [comment]
Hello Thomas,

I have tried to liaxim´s suggestion and it solved the issue.

Thank you.

**Comment by thomasflynn** [comment]
the fix is merged into master.

**Comment by elidelsonc** [comment]
Ok! Thank You.
