### ISSUE TITLE
GearVR TouchPad MotionEvent.AXIS always start in center.

### ISSUE THREAD

**Issue by DanielNogueiraAndroid** [Samsung/GearVRf#231]
I'm having a hard time getting the absolute touch position on GearVR TouchPad, the value of X and Y always start with 0 even if I'm not touching on the center of touch pad.
To get position x and y, I'm using :
```java
public class MainActivity extends GVRActivity{
...
    @Override
    public boolean onTouchEvent(MotionEvent event) {
         float x = event.getAxisValue(MotionEvent.AXIS_X);
         float y = event.getAxisValue(MotionEvent.AXIS_Y);
        return super.onTouchEvent(event);
    }
 ...   
}
```

**Comment by thomasflynn** [comment]
That is how the touchpad works on the GearVR works.  No matter where you touch down on the pad, it reports the initial position as 0 and then gives relative coordinates from there.  It's configured that way in the firmware of the touchpad.  The touchpad is really only good for taps and swipes.

**Comment by mteofilo** [comment]
Thank you for the clarification. We'll represent just tap, long press, and swipes in Controls sample. This issue can be closed.
