### ISSUE TITLE
Find SceneObject by name

### ISSUE THREAD

**Issue by thomasflynn** [Samsung/GearVRf#239]
I can't believe this doesn't already exist (that I could find anyway).  We should add a method to both GVRScene and GVRSceneObject to find a SceneObject by name.  So when people load in their models, they can find the articulated objects (by name) and move them.

**Comment by chenchao1407** [comment]
Let me take care of it.

**Comment by thomasflynn** [comment]
how's that coming along?-)  or should I take it up?

**Comment by liaxim** [comment]
@thomasflynn, I could help with this one if you'd like.

**Comment by thomasflynn** [comment]
Sure, go for it.  Should be quick enough.

**Comment by liaxim** [comment]
The corresponding APIs have been added to GVRScene and GVRSceneObjects.
