### ISSUE TITLE
GVRF reference counting

### ISSUE THREAD

**Issue by JonShemitz** [Samsung/GearVRf#24]
GVRF uses a (native code) `std::shared_ptr` based reference counting scheme. It works well enough in 'normal' cases, but does break down in the not-so-special case where you have an object (we see this commonly with scene objects and textures, but it could happen with other objects, too) that goes in and out of the scene graph: When GVRF sees that an object has no native references (just the reference from the Java wrapper) it will 'forget' about the native wrapper and/or `recycle()` the GL resource. This can lead to consequences like eye picking returning a `GVRSceneObject` instead of the subclassed instance (holding app values) that you put into the scene graphs, or even to GVRF crashing when it dereferences `null` in native code.

We have what amounts to work-arounds for this: we can manually add references (as _per_ the JavaDoc for `GVRShaders.setMainTexture()`) and we can set the `GVRHybridObject.setKeepWrapper()` flag. Perhaps it would be better to add explicit

    long GVRHYbridObject.touch(); // addReference()?
    void GVRHYbridObject.release(long); // removeReference()?

methods?

**Comment by thomasflynn** [comment]
I think we need to go back and investigate how other scene graphs handle this issue.  Grant it, we might have a bit of a special case by having this division between native code and java code.  But I don't remember encountering these kinds of problem with other scene graphs.

**Comment by chenchao1407** [comment]
How about something like register/unregister mechanism or add flag in constructor to let developer to say if it should be reserved without recycling?

**Comment by JonShemitz** [comment]
There are a lot of constructors; I don't think we want to change each and every one to handle something that only applies to maybe 1% to 5% of all GVRF objects.

How does a "register/unregister mechanism" differ from touch/release?

**Comment by jason2kim** [comment]
Can’t it be more natural to keep object intact by default unless the user explicitly call recycle(), I mean the opposite approach? From the app developers’ perspective, I think they’d better don’t know about the reference counts in the framework. As Tom suggested, one way would be learn best practices for it from investigating other SGs.

**Comment by JonShemitz** [comment]
Leaving resource lifecycle management to the app is one heck of a burden, Jason. It would slow app development tremendously, and most app developers would get it wrong: They'd leak some resources by not freeing them, and have dangling reference issues from freeing other resources prematurely. (Just look at how much easier app development is in a garbage collected environment than it is in C!)

**Comment by JonShemitz** [comment]
Huh - I thought I replied to Tom's reply. I think it may indeed be the case that we are in a very sparsely populated part of the 'state space'. 

It's 100% common for managed code (Java or C# or whatever) to have classes that wrap native code. But - generally - there's a 1:1 relationship between native instances and managed wrappers, and most of the action happens in the 'wrapped side'. An Android `Bitmap`, for example, does not have native references to components that also have Java wrappers, the way that a GVRF `GVRSceneObject` does. In this sort of environment, one can rely on managed side garbage collection and finalizers (and explicit `close()` methods) in a way that we simply can't, in GVRF.

An all-C or all-C++ game engine isn't going to have the issues that we have.

The Unity docs talk about a Mono runtime, and supporting ".NET languages" that compile to a DLL. That - to me - suggests that what's going on in Unity is a pretty standard .NET scenario: the managed (C#  or 'equivalent') objects are the masters, and the native objects are implementation details. (In GVRF, by contrast, the native objects are the masters, and the Java objects are mere tails,  attached in a way that was designed by someone who clearly was not a Java programmers.)

That is, if I had to place a bet, I'd bet that we'll be better served by looking at the design we inherited and trying to solve its problems in the cleanest way possible, than by spending time digging into the details of other game engines that will (I suspect) turn out to have little in common with the GVRF scenario.

**Comment by JonShemitz** [comment]
A different - though much more programmer-intensive - way to solve this problem is to totally ditch the native reference counting, and let Java drive the recycling. We would only free a native object when its Java object is `finalize()`d (or, perhaps, explicitly `close()`d). This would eliminate all need for the 'object identity' code, manually manipulating reference counts, and `setKeepWrapper()`.

We would keep all the lists of references (in `GVRScene` and `GVRSceneObject` &c) _in Java_, though we would probably let the native implementations keep native lists as well, as an optimization.

Things like traversing the scene graph would be a lot cheaper in Java, but this isn't currently a major expense: Overall, we'd be spending a lot of effort (40 hours, maybe more) to provide a clean solution to a problem that may not justify the effort. Otoh, we do seem to keep running into it, and we may still have race conditions: For example, what if a low-priority background thread creates a scene object, but the wrapper is released before the creating code can link it into the scene graph or call `setKeepWrapper()`?

**Comment by chenchao1407** [comment]
Actually I was thinking of finalized() also. But I guess somehow we would lose direct control for the gabbage collection because those JNI object will be released only when GC cycle is triggered. And also, the whole mechanism for our current reference counting recycling may need to be restructured.

**Comment by JonShemitz** [comment]
Chao wrote:
> I guess somehow we would lose direct control for the gabbage collection because those JNI object will be released only when GC cycle is triggered. 

In some ways, this is good: we currently poll for dead objects, 60 times a second. Leaving most of that work to the much less frequent garbage collection will leave more cycles for rendering.

Plus, adding a manual `close()` method lets app code release transient resources well before gc would get to them. (This, too, is Industry Standard.)

> the whole mechanism for our current reference counting recycling may need to be restructured.

No, not "restructured": it would be gutted.

**Comment by JonShemitz** [comment]
https://github.com/Samsung/GearVRf/pull/41
