### ISSUE TITLE
Lots of threads

### ISSUE THREAD

**Issue by kuldeep-samsung** [Samsung/GearVRf#243]
looks like GVRF is creating lots of thread in startup (~30) and inherits the render thread's priority.

**Comment by xcaostagit** [comment]
I will work on this one together with some other thread-related issues.

**Comment by thomasflynn** [comment]
what's the status on this?

**Comment by xcaostagit** [comment]
With my commit fcf7f36174dc35034c1906abd6778f538d1107fd (Using GrowBeforeQueueThreadPoolExecutor as the threadPool) merged this is no longer an issue. Can we close this ticket?

**Comment by thomasflynn** [comment]
ok, good, that's what i thought

**Comment by thomasflynn** [comment]
looks like i cannot close it.  perhaps @kuldeep-samsung is supposed to close it.
