### ISSUE TITLE
Can I set typeface font in GVRTextViewSceneObject class?

### ISSUE THREAD

**Issue by douglasalipio** [Samsung/GearVRf#246]
How do I set typeface font in GVRTextViewSceneObject?

```GVRTextViewSceneObject textView = new GVRTextViewSceneObject(gvrContext, activity);
textView.setTypeface();```

Android example:

```TextView textView = new TextView();
Typeface myTypeface = Typeface.createFromAsset(context.getAssets(), "fonts/futura-condensed-normal.ttf");
textView.setTypeFace(myTypeface);```

**Comment by mkeblx** [comment]
Currently you cannot as `GVRTextViewSceneObject` uses a `TextView` internally that isn't fully accessible besides a few helper methods. (See:  https://github.com/Samsung/GearVRf/blob/master/GVRf/Framework/src/org/gearvrf/scene_objects/GVRTextViewSceneObject.java) 

`setTypeFace` would be a useful one to add, or a method that returns the `TextView` so one could call any of it's methods.

**Comment by chenchao1407** [comment]
I think you can do that since at the beginning I created this type of scene object with just basic APIs. You can add whatever is available from TextView.
