### ISSUE TITLE
Video sample help

### ISSUE THREAD

**Issue by Ncit** [Samsung/GearVRf#254]
Can you assist in creating simple video play demo?

**Comment by thomasflynn** [comment]
We have some samples that use video in our Samples/ directory.  There's gvr-video/ and then our scene-objects/ sample is a bit simpler.  After trying / looking at those, let us know what you need.

**Comment by Ncit** [comment]
Is it possible to add 3d support for existing app? Do that I don't need to change layouts?

**Comment by thomasflynn** [comment]
I'm not sure what you're asking for.  You can add any 3d objects you want into the scene.  If you want to texture map a 3d object with a video, you'll need to use a GVRExternalTexture and can look at the source code for GVRVideoSceneObject.java as an example of how that is done.

**Comment by chenchao1407** [comment]
/GVRf/Framework/src/org/gearvrf/scene_objects/GVRVideoSceneObject.java

Please take a look at this class and also gvrsample app, it shows how we port Android MediaPlayer to play video.

**Comment by Ncit** [comment]
I have a project that use custom ooyala player for drm videos, I need to add support for that app. Also I need to migrate to android studio, because of lots of gradle dependecies.

**Comment by thomasflynn** [comment]
I don't think any of us are familiar with ooyala, but if you have it already running in Android, you should be able to get it running with GVRf.  As for Android studio, it might be easier to work with one of our binary releases.  @jason2kim might be able to help you with what you need to do for that.  Our source currently needs to be either built with Eclipse or with our experimental ant build script (build.sh).

**Comment by Ncit** [comment]
How can I contact with him, because I did not manage to run android 1.4 with gvr-video

**Comment by thomasflynn** [comment]
i've talked with him, he'll write you back here.

**Comment by jason2kim** [comment]
Please refer to these pages in case you are using pre-built binaries:

https://github.com/Samsung/GearVRf/releases/tag/2.2
(older: https://github.com/Samsung/GearVRf/releases/tag/2.1  gvr-video-staticlib-androidstudio.zip\README.txt)
http://www.gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start#BuildInstruct

**Comment by Ncit** [comment]
Is it possible to add simple frame layout to the scene?

**Comment by chenchao1407** [comment]
As far as I can see, the answer should be yes. Actually you can take a look at some customized scene objects like GVRWebViewSceneObject, GVRTextViewSceneObject which render android layout into a surface texture and make it as a Android's View-based scene object.

**Comment by Ncit** [comment]
I found that, so for now trying to create cinema with framelayout as screen

**Comment by chenchao1407** [comment]
Good. Please let me know if you face any issue or not. Please be aware that the refresh rate should be handled well otherwise there will be a performance issue since SurfaceTexture is not that efficient.

**Comment by Ncit** [comment]
I used gear-video sample from 2.2 version, but it asks for vrappframework.VrActivity dependency. Using framework jar from oculus sdk gives me nothing.

**Comment by Ncit** [comment]
I did not manage to run in android studio 1.4 gear video https://github.com/Ncit/gear_video

**Comment by jason2kim** [comment]
Ncit, in case you are still stuck with Android Studio, this new release would be helpful: https://github.com/Samsung/GearVRf/releases/tag/2.2.1
Let me know if you have any further questions.

**Comment by thomasflynn** [comment]
@Ncit, did you ever get anywhere?

**Comment by Ncit** [comment]
I failed in running sample from 2.2.1 and also failed in created relative layout in the scene

**Comment by jason2kim** [comment]
@Ncit, 
Were you able to build this app, 2.2.1 gvr-video-staticlib-androidstuido.zip, using binaries collected from both gear vrf and oculus as instructed?

**Comment by Ncit** [comment]
No I did not. I downloaded the 2.2.1 sample project. Added all libs as said in readme. But after opening in android stuido I cannot find a lot of imports

**Comment by Ncit** [comment]
I managed to create GVRRelativeLayoutSceneObject with relativelayout, but when I created such object, added subviews to layout, nothing happens. On the screen I can see only relativeLayout.

**Comment by Ncit** [comment]
Can you advise, on how can I replace surfacetexture for mediaplayer on my custom ooayala player layout?

**Comment by liaxim** [comment]
Hi there. I had a quick look at OoyalaPlayer and I don't see an equivalent to MediaPlayer's setSurface api. You may want to ask Ooyala this question as they have a better chance of answering conclusively.

**Comment by liaxim** [comment]
@Ncit do you still have any gvrf issues we could help you with?

**Comment by Ncit** [comment]
big thanks,for now I do not have questions.
19 Окт 2015 г. 19:35 пользователь "Mihail" <notifications@github.com>
написал:

**Comment by liaxim** [comment]
You are welcome @Ncit . Closing this issue.
