### ISSUE TITLE
ovr_sdk_mobile instead of ovr_mobile_sdk

### ISSUE THREAD

**Issue by elidelsonc** [Samsung/GearVRf#255]
Hello!

The last Oculus mobile sdk comes with the label: ovr_sdk_mobile_0.6.2.0.zip.
That's different from version ovr_mobile_sdk_0.6.0.1.zip.
I mean the words sdk and mobile had their position changed.
So when one unzip the file will get the oculus path name different. ovr_sdk_mobile instead of ovr_mobile_sdk.
That can be confusing for users.

Best Regards,

Elidelson Carvalho
SIDIA BR - UX TEAM

**Comment by thomasflynn** [comment]
Oculus does a lot of confusing things :).  They had a different naming scheme before 0.5.0 as well.  And each minor 0.x.y point release has major, wide reaching API changes in it.  It can be a bit of a pain.  For all we know their release engineer got dyslexic with the name and it'll change back in the next release.  We'll have to see.  

At Oculus Connect, they announced they'll have a 1.0 release of their mobile sdk in november.  I assume we have at least one more sdk release from them coming before then (0.7 sdk to match the PC maybe?).  We'll see.  If they stick with this new naming convention, we'll change as well.  In the meantime, you can either rename the directory to the convention they've used for the past 5 releases or set the OVR_MOBILE_SDK environment variable to the directory where the oculus sdk is located.

**Comment by thomasflynn** [comment]
it looks oculus kept with ovr_sdk_mobile with the 1.0 release.  we'll update to that was well as part of porting to 1.0.

**Comment by thomasflynn** [comment]
the port to 1.0 has been merged and we now use ovr_sdk_mobile/.
