### ISSUE TITLE
Bug in solar-system sample

### ISSUE THREAD

**Issue by elidelsonc** [Samsung/GearVRf#257]
Hello,

We have noted the following strange behaving with solar-system sample:

1 - the sample starts normally
2 - We press the back button and the "exit to oculus home ?" message appears
3 - if We press "no" to come back to the application, the application's sceneObjects don't appear anymore.
4 - Only the statistical display, switch to on/off if we touch in the pad.

what could be happening?

Best Regards,

Elidelson Carvalho
SIDIA BR - UX TEAM

**Comment by thomasflynn** [comment]
i suspect we have a bug in onResume() or thereabouts with restoring the GL context and associated buffers.  will have to look more closely.  thanks for pointing this out.

**Comment by liaxim** [comment]
Fix has been merged.

**Comment by rahul27** [comment]
The texture loading issue seems to be fixed with this patch. But on relaunch the splash screen cuts off for me. Do you see the same?

**Comment by liaxim** [comment]
Could you please open another issue then? I doubt it is related to the original reported here.
