### ISSUE TITLE
Head tracking threshold

### ISSUE THREAD

**Issue by ethernyEonian** [Samsung/GearVRf#262]
Hi, when i change my head direction (left to right and invert), i have a strange effect.
A little threshold i needed to detect new move direction.
This give me a bad feeling.

**Comment by ethernyEonian** [comment]
I have this problem in each samples.

**Comment by liaxim** [comment]
Hi there,
What kind of a device do you have? Have you tried the Oculus apps - do they work well? Asking about Oculus because we use the Oculus SDK for head tracking.

**Comment by ethernyEonian** [comment]
Hi, yes oculus native apps works well and unity app too, perfect head tracking.
I have a note4 and gear vr stuff.
I m an unity dev, and i want to migrate to your framework, but i need to check some requirements.
I your samples, i have a little tracking effect when make little moves left to right.

**Comment by ethernyEonian** [comment]
No idea ?
Do you have the same problem ?

**Comment by liaxim** [comment]
I have no idea. Will run few tests and probably come up with some logs that could help identify the problem.

In the meantime, could you let me know what happens if you change in activity_jni.h "typedef GVRActivityT<OculusHeadRotation> GVRActivity;" to "typedef GVRActivityT<KSensorHeadRotation> GVRActivity;"? Thanks.

**Comment by ethernyEonian** [comment]
Hi perhaps a type mistake you want i change typedef to the same ?
I tried on change this : 

//typedef GVRActivityT<OculusHeadRotation> GVRActivity;
typedef GVRActivityT<KSensorHeadRotation> GVRActivity;

But no effect.

**Comment by thomasflynn** [comment]
Yeah, I think those were the lines he was referring to.  The OculusHeadRotation line uses the Oculus code for sensor fusion and predicted head movement.  The KSensorHeadRotation uses code we originally had for sensor fusion.  We switched to the Oculus code because it had better prediction and filtering.  The OculusHeadRotation code is using the same vrapi any Oculus app ends up using so _theoretically_ there shouldn't be any difference between a gvrf app and a native oculus app.

we're open to suggestions.

**Comment by liaxim** [comment]
@ethernyEonian, your issue is rather unique and I don't know where to start. I can add logging to various places and the whole process will most likely take numerous iterations. Are you willing to help me out with testing various builds and sending back the logs?

Another suggestion: what happens if you run the samples without the phone being docked into GearVR? To allow the apps to run in this case, you can either enable developer mode in the GearVR Service or you could just comment out the line containing "com.samsung.android.vr.application.mode" in the android manifest.

**Comment by ethernyEonian** [comment]
Hi, yes i can send you logs. What i need to do ? Pull the new code and restart app ?

For you suggestion : i tried but it's difficult to see that on a little screen, but it seems to be the same.

**Comment by liaxim** [comment]
For starters you can do a "adb shell dumpsys" and send me the output. I am having doubts your problem has anything to do with the head-tracking.

I will see what logs I can enable and add and will send you a link to a branch in my forked repo.

**Comment by liaxim** [comment]
You could also capture the complete output of "adb logcat -v threadtime V:*" when you start some of the GVRF apps that exhibits the problem you describe.

**Comment by ethernyEonian** [comment]
could you give me an email address to send you my logs, i don't want to put this in public area. Thank you.

**Comment by liaxim** [comment]
Sure, you can send to m.marinov@samsung.com

**Comment by liaxim** [comment]
Do you see this strange effect when you are moving your head left/right very slowly? Is it any different to when you move your head at normal speed? How about when you try to move fast?

**Comment by ethernyEonian** [comment]
When i do long moves (slow or fast) it's ok.
It's when i make little moves left to right like if you have a parkinson disease (very small moves).
I have a move log entry when i make long moves, but not with this kind of "parkinson disease" move.

**Comment by thomasflynn** [comment]
@ethernyEonian, can you try this change request and see if it improves things?
https://github.com/Samsung/GearVRf/pull/268

**Comment by ethernyEonian** [comment]
Yes i tried.
It's better but i have always the problem but smaller

**Comment by thomasflynn** [comment]
alright, well, perhaps we're on the right track.  merged the change.  Mihail is on PTO tomorrow, but he'll continue to work with you on this.

**Comment by ethernyEonian** [comment]
Hi, i m working of a use of your lib in clojure.

When i run the application i have this log :

Perhaps this talk you. I m lost :)
I checked the content of my apk and all is the same as in one of your final
sample apk.

D/NativeLibraryHelper(  925): Successfully fsync
/data/app/vmdl1746303542.tmp/lib/arm/libgvrf.so
D/NativeLibraryHelper(  925): Successfully fsync
/data/app/vmdl1746303542.tmp/lib/arm/libvrapi.so
I/ActivityManager(  925): Start proc
29792:com.samsung.android.app.vrsetupwizardstub/u0a43 for broadcast-3
com.samsung.android.app.vrsetupwizardstub/.system.PackageIntentReceiver
V/BroadcastQueue(  925): [background] Process cur broadcast
BroadcastRecord{10cc6702 u0 android.intent.action.PACKAGE_REMOVED}
DELIVERED for app ProcessRecord{1bf6a813
29792:com.samsung.android.app.vrsetupwizardstub/u0a43}
I/ActivityManager(  925): Start proc
29812:com.samsung.android.app.vrsetupwizard/u0a217 for broadcast-3
com.samsung.android.app.vrsetupwizard/.system.PackageIntentReceiver
V/BroadcastQueue(  925): [background] Process cur broadcast
BroadcastRecord{10cc6702 u0 android.intent.action.PACKAGE_REMOVED}
DELIVERED for app ProcessRecord{211df14e
29812:com.samsung.android.app.vrsetupwizard/u0a217}
D/RCPManagerService(  925):  PackageReceiver onReceive() bundle
Bundle[{com.samsung.android.vr.application.mode=vr_only}]
I/VrApi   (30001): ----------- vrapi_Initialize ----------
I/LocalPreferences(30001): ovr_InitLocalPreferences
D/OvrConsole(30001): !!#######!! Registering console receiver
D/VrApp   (30001): com.oculus.vrappframework.VrApp@3e7140d0 surfaceCreated()
I/VrApi   (30001): ---------- vrapi_EnterVrMode ----------
I/VrApi   (30001): vrapi_EnterVrMode: defaulting to docked due to lack of
dock events
I/VrApi   (30001): vrapi_EnterVrMode: defaulting to mounted due to lack of
mount events
F/art     (30001): sart/runtime/check_jni.cc:65]   native: #08 pc 0000a93c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libvrapi.so (???)
F/art     (30001): sart/runtime/check_jni.cc:65]   native: #09 pc 00010cdc
 /data/app/test.leindroid.sample.debug-2/lib/arm/libvrapi.so
(vrapi_EnterVrMode+164)
F/art     (30001): sart/runtime/check_jni.cc:65]   native: #10 pc 0011a5e0
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::EnterVrMode()+144)
F/art     (30001): sart/runtime/check_jni.cc:65]   native: #11 pc 0011eb8c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::HandleVrModeChanges()+72)
F/art     (30001): sart/runtime/check_jni.cc:65]   native: #12 pc 0011b15c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::Command(char const*)+384)
F/art     (30001): sart/runtime/check_jni.cc:65]   native: #13 pc 0011c008
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::VrThreadFunction()+1104)
F/art     (30001): sart/runtime/check_jni.cc:65]   native: #14 pc 0011d3a8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::ThreadStarter(OVR::Thread*, void*)+8)
F/art     (30001): sart/runtime/check_jni.cc:65]   native: #15 pc 00139cc8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so (???)
F/art     (30001): sart/runtime/check_jni.cc:65]   native: #16 pc 0013a0d0
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so (???)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #12 pc 0000a93c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libvrapi.so (???)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #13 pc 00010cdc
 /data/app/test.leindroid.sample.debug-2/lib/arm/libvrapi.so
(vrapi_EnterVrMode+164)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #14 pc 0011a5e0
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::EnterVrMode()+144)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #15 pc 0011eb8c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::HandleVrModeChanges()+72)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #16 pc 0011b15c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::Command(char const*)+384)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #17 pc 0011c008
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::VrThreadFunction()+1104)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #18 pc 0011d3a8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::ThreadStarter(OVR::Thread*, void*)+8)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #19 pc 00139cc8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so (???)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #20 pc 0013a0d0
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so (???)
F/art     (30001): sart/runtime/runtime.cc:292]   at java.lang.String
com.oculus.vrapi.VrApi.getApplicationName(android.app.Activity)
(VrApi.java:183)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #02 pc 0013afb8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so (???)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #03 pc 0013080c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::ovrMessageQueue::PostMessage(char const*, bool, bool)+432)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #04 pc 00130ae4
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::ovrMessageQueue::SendPrintf(char const*, ...)+116)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #05 pc 00127a3d
 /data/dalvik-cache/arm/data@app@test.leindroid.sample.debug-2@base.apk@classes.dex
(Java_com_oculus_vrappframework_VrApp_nativeSurfaceCreated__JLandroid_view_Surface_2+120)
F/art     (30001): sart/runtime/runtime.cc:292]   at
com.oculus.vrappframework.VrApp.nativeSurfaceCreated(Native method)
F/art     (30001): sart/runtime/runtime.cc:292]   at
com.oculus.vrappframework.VrApp.surfaceCreated(VrApp.java:75)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #12 pc 0000a93c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libvrapi.so (???)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #13 pc 00010cdc
 /data/app/test.leindroid.sample.debug-2/lib/arm/libvrapi.so
(vrapi_EnterVrMode+164)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #14 pc 0011a5e0
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::EnterVrMode()+144)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #15 pc 0011eb8c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::HandleVrModeChanges()+72)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #16 pc 0011b15c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::Command(char const*)+384)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #17 pc 0011c008
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::VrThreadFunction()+1104)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #18 pc 0011d3a8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::ThreadStarter(OVR::Thread*, void*)+8)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #19 pc 00139cc8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so (???)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #20 pc 0013a0d0
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so (???)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #02 pc 0013afb8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so (???)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #03 pc 00130ce8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::ovrMessageQueue::SleepUntilMessage()+72)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #04 pc 00130f30
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::TalkToJava::TtjThreadFunction()+292)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #05 pc 00130f74
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::TalkToJava::ThreadStarter(OVR::Thread*, void*)+32)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #06 pc 00139cc8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so (???)
F/art     (30001): sart/runtime/runtime.cc:292]   native: #07 pc 0013a0d0
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so (???)
I/DEBUG   (  328):     #11 pc 0000a93c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libvrapi.so
I/DEBUG   (  328):     #12 pc 00010cdc
 /data/app/test.leindroid.sample.debug-2/lib/arm/libvrapi.so
(vrapi_EnterVrMode+164)
I/DEBUG   (  328):     #13 pc 0011a5e0
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::EnterVrMode()+144)
I/DEBUG   (  328):     #14 pc 0011eb8c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::HandleVrModeChanges()+72)
I/DEBUG   (  328):     #15 pc 0011b15c
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::Command(char const*)+384)
I/DEBUG   (  328):     #16 pc 0011c008
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::VrThreadFunction()+1104)
I/DEBUG   (  328):     #17 pc 0011d3a8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
(OVR::AppLocal::ThreadStarter(OVR::Thread*, void*)+8)
I/DEBUG   (  328):     #18 pc 00139cc8
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
I/DEBUG   (  328):     #19 pc 0013a0d0
 /data/app/test.leindroid.sample.debug-2/lib/arm/libgvrf.so
I/ActivityManager(  925): Killing
29792:com.samsung.android.app.vrsetupwizardstub/u0a43 (adj 15): emptyCount
##31
D/ActivityManager(  925): isAutoRunBlockedApp::
com.samsung.android.app.vrsetupwizardstub, Auto Run ON
I/ActivityManager(  925): Killing
29812:com.samsung.android.app.vrsetupwizard/u0a217 (adj 15): emptyCount ##31
D/ActivityManager(  925): isAutoRunBlockedApp::
com.samsung.android.app.vrsetupwizard, Auto Run ON
I/ActivityManager(  925): Start proc
30459:com.samsung.android.app.vrsetupwizardstub/u0a43 for broadcast-3
com.samsung.android.app.vrsetupwizardstub/.system.PackageIntentReceiver
V/BroadcastQueue(  925): [background] Process cur broadcast
BroadcastRecord{2e7c8489 u0 android.intent.action.PACKAGE_ADDED} DELIVERED
for app ProcessRecord{65c5c8e
30459:com.samsung.android.app.vrsetupwizardstub/u0a43}
I/ActivityManager(  925): Start proc
30478:com.samsung.android.app.vrsetupwizard/u0a217 for broadcast-3
com.samsung.android.app.vrsetupwizard/.system.PackageIntentReceiver
V/BroadcastQueue(  925): [background] Process cur broadcast
BroadcastRecord{2e7c8489 u0 android.intent.action.PACKAGE_ADDED} DELIVERED
for app ProcessRecord{23cc2354
30478:com.samsung.android.app.vrsetupwizard/u0a217}
I/ActivityManager(  925): Killing
30459:com.samsung.android.app.vrsetupwizardstub/u0a43 (adj 15): emptyCount
##31
D/ActivityManager(  925): isAutoRunBlockedApp::
com.samsung.android.app.vrsetupwizardstub, Auto Run ON
I/ActivityManager(  925): Killing
30478:com.samsung.android.app.vrsetupwizard/u0a217 (adj 15): emptyCount ##31
D/ActivityManager(  925): isAutoRunBlockedApp::
com.samsung.android.app.vrsetupwizard, Auto Run ON
I/ActivityManager(  925): Start proc
30968:com.samsung.android.app.vrsetupwizardstub/u0a43 for broadcast-3
com.samsung.android.app.vrsetupwizardstub/.system.PackageIntentReceiver
V/BroadcastQueue(  925): [background] Process cur broadcast
BroadcastRecord{1157a4f6 u0 android.intent.action.PACKAGE_REPLACED}
DELIVERED for app ProcessRecord{22d860f7
30968:com.samsung.android.app.vrsetupwizardstub/u0a43}
I/ActivityManager(  925): Start proc
30983:com.samsung.android.app.vrsetupwizard/u0a217 for broadcast-3
com.samsung.android.app.vrsetupwizard/.system.PackageIntentReceiver
V/BroadcastQueue(  925): [background] Process cur broadcast
BroadcastRecord{1157a4f6 u0 android.intent.action.PACKAGE_REPLACED}
DELIVERED for app ProcessRecord{39b6bb64
30983:com.samsung.android.app.vrsetupwizard/u0a217}
I/ActivityManager(  925): Killing
30968:com.samsung.android.app.vrsetupwizardstub/u0a43 (adj 15): emptyCount
##31
D/ActivityManager(  925): isAutoRunBlockedApp::
com.samsung.android.app.vrsetupwizardstub, Auto Run ON
I/ActivityManager(  925): Killing
30983:com.samsung.android.app.vrsetupwizard/u0a217 (adj 15): emptyCount ##31
D/ActivityManager(  925): isAutoRunBlockedApp::
com.samsung.android.app.vrsetupwizard, Auto Run ON

**Comment by ethernyEonian** [comment]
Any new for this issue ?

**Comment by liaxim** [comment]
We found the low-hanging fruit and fixed that. I will continue to look into this but I don't have anything at the moment.

**Comment by ethernyEonian** [comment]
Cool thank you !

**Comment by liaxim** [comment]
Hi again. I created a branch in my repo with an experimental commit that tries to improve the head-tracking latency further. It seems to slightly help but I am just not sensitive enough to be certain. Please let me know whether you see an improvement, if any. Thanks.

The repo&branch here: https://github.com/liaxim/GearVRf/tree/issue-262

**Comment by liaxim** [comment]
We have applied the head-model too; pr #312.
