### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by mrgzadeh** [Samsung/GearVRf#264]
Dear All, 

How can I add button to my GearVR framework application (If Possible at all)?
Thanks,

**Comment by thomasflynn** [comment]
i think you might need to be a little more specific.  

one suggestion could be to look at the eye-picking sample and then listen to taps from the touchpad for 'clicking' the 3d object you're pointing to.

**Comment by Maginador** [comment]
gvrf_controls_sample has some facilitators related to button, interaction and things like that, take a look, specially in the ControlSceneObject.

https://github.com/Samsung/GearVRf/blob/805bedebb3eb957539cb649c2afee426615a57dd/GVRf/Sample/gvrf_controls_sample/src/org/gearvrf/controls/focus/ControlSceneObject.java

**Comment by liaxim** [comment]
@mrgzadeh did the two samples mentioned help you? Do you need further help? If not, can we consider this issue closed?

**Comment by liaxim** [comment]
I assume it is all good. @mrgzadeh please open another issue if necessary.
