### ISSUE TITLE
camera preview faster

### ISSUE THREAD

**Issue by Bonch90** [Samsung/GearVRf#270]
I've made a simple app on Galaxy S6 that activate the rear camera and show the preview, I've used the 0.5 version of the ovr sdk. Comparing with the Passthrough Camera app inside the Gear Menu I've noticed that this one is "faster" than mine, the preview seems be accelerated, I've tried to change fps range preview but is not possible going over 30 fps, is there a way to reach the same result?

Thank you

**Comment by thomasflynn** [comment]
I think there's some special calls that can be made on Samsung phones to set the camera into a higher fps.  I'll have someone investigate and report back.

**Comment by gaurav-mcl** [comment]
Hello @Bonch90, @thomasflynn asked me to look into this. We have some internal code that may be used to run cameras on Samsung phones with a higher fps. I will investigate as to whether we can use that to accelerate the pass through camera fps in GVRF.

**Comment by liaxim** [comment]
@Bonch90 Just letting you know that @gaurav-mcl is still looking into this.

**Comment by gaurav-mcl** [comment]
Hello @Bonch90,

our Samsung HQ camera team gave us the following code snippet that can change the camera speed to 60 or 120 fps. We have tried it out but can not get those speeds for some weird reason. There's something we are missing. We are working with the HQ team to figure out what may be the reason. You are welcome to also try out the following code and see if you get anything different. Please share your observations. In the meantime, I will try to get this resolved at my end.

The 'fast-fps-mode' parameter that you will see below is proprietary to Samsung camera hardware. This is not public android api so will not work on non-Samsung phones. They may have their own vendor-specific calls for high framerate, if any.

```c++
camera = Camera.open();
Camera.Parameters parms = camera.getParameters();
if ("true".equalsIgnoreCase(parms.get("vrmode-supported"))) { //check if the device supports vr mode preview
    // set vr mode
    parms.set("vrmode", 1); // vr mode 
 
    // true if the apps intend to record videos using MediaRecorder
    parms.setRecordingHint(true); 
 
    // set preview size
    // default resolution of camera preview: fhd @ 60fps, hd @ 120fps
    // parms.setPreviewSize(960, 540);
    // parms.setPreviewSize(800, 600);
    // parms.setPreviewSize(640, 480);
    // parms.setPreviewSize(640, 360);
 
    // for 120fps
    parms.set("fast-fps-mode", 2); // 2 for 120fps
    parms.setPreviewFpsRange(120000, 120000);
 
    // for 60fps
    //parms.set("fast-fps-mode", 1); // 1 for 60fps
    //parms.setPreviewFpsRange(60000, 60000);
 
    // for 30fps
    //parms.set("fast-fps-mode", 0); // 0 for 30fps
    //parms.setPreviewFpsRange(30000, 30000);
 
    // for auto focus
    parms.set("focus-mode", "continuous-video"); 
} else {
    // not support vr mode
}
camera.setParameters(parms);
camera.startPreview();   
 
camera.stopPreview();
camera.release();
camera = null; 
```

**Comment by Bonch90** [comment]
Many thanks @gaurav-mcl  I've already tried that settings with no luck, if I set previewFpsRange with a value greater than 30000 the camera won't show anything.
This happens with Galaxy S6, before I've used a Note 4 and this settings worked like a charm.

**Comment by gaurav-mcl** [comment]
Hello @Bonch90, we had some success with the fps issue. Basically on a S6 device with 'user firmware binary' (or in other words, device available to consumers in the market), we could get 30 and 60 fps working. The 60 fps mode looks much smoother within the GearVR headset. The 120 fps mode is not yet supported due to some performance issues on S6. 

Earlier we were not able to get 60 fps because  we were testing on a device with 'engineering firmware binary' (or in other words, devices which we use for internal testing) and there the 60 fps performance is not guaranteed because certain optimizations are not turned on.

So, the S6 device that you have should be able to give 60 fps performance (assuming you got it from some store or phone carrier). You can not have a device with engineering binary unless you are a Samsung employee who is testing these devices. 

I am in the process of preparing a test app to measure the fps and will upload it as a GVRF sample. And then you can use it to benchmark the performance at your end.

**Comment by gaurav-mcl** [comment]
Hello @Bonch90, I have updated the sample 'scene-objects' in the GVRf/Sample/ directory to show 60 fps camera preview. Please pull latest code from https://github.com/Samsung/GearVRf/ and you should be able to get 60 fps preview. As mentioned earlier, this should work on your S6 device (assuming it is a consumer device. The 60 fps feature is not likely to work on test devices which we use internally at Samsung but this is not applicable to you).

A word about the 'scene-objects' sample: it is supposed to demo several different types of scene objects supported in GVRF e.g. quad, cylinder, cone, sphere, etc. One of them is a camera scene object which shows camera preview. Run the sample in GearVR headset and tap on the trackpad to cycle through the scene objects. Eventually you should come to camera scene object and should be able to see 60 fps preview. If you want to compare it with 30 fps, change line 93 in the file https://github.com/Samsung/GearVRf/blob/master/GVRf/Sample/scene-objects/src/org/gearvrf/sample/sceneobjects/SampleViewManager.java to following:

```
cameraObject.setUpCameraForVrMode(0);
```

, rebuild the sample and run. Now you should see 30 fps camera preview.

**Comment by liaxim** [comment]
@Bonch90 did this help? Can we close the issue?

**Comment by liaxim** [comment]
Assuming it is all good now with the camera preview performance.
