### ISSUE TITLE
GVRBitmapTexture problems when instantiated from non-GL thread

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#274]
@ejsamsung had problem when creating two scene objects from non-GL thread. He created two separate GVRBitmapTextures, GVRMaterials and GVRSceneObjects but the two scene objects were rendered with the same texture. Once the instantiation was moved to the GL thread everything worked. GVRBitmapTexture's ctor uses the update call which can be made on any thread but the native ctor makes GL calls so there are two options:

1. throw exceptions if GVRBitmapTexture is not run on the GL thread
2. do something about the native code

I will try to do 2. in the next few days.

**Comment by danke-sra** [comment]
Any new findings about this?

Looks like the culprit is the GL commands to load the bitmap into the texture. This is done in the native constructor as follows:

    glBindTexture(GL_TEXTURE_2D, gl_texture_->id());
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, info.width, info.height, 0,
                    GL_RGBA, GL_UNSIGNED_BYTE, pixels);
    glGenerateMipmap (GL_TEXTURE_2D);

Because GL is not thread-safe, it seems we have to create GVRBitmapTextures in the GL thread.

**Comment by liaxim** [comment]
There are no new findings - the issue is the one you stated. The idea is to make the whole thing transparent to the user. Haven't got to it yet.

**Comment by liaxim** [comment]
Danke made a number of changes that resolved this issue.
