### ISSUE TITLE
GVRCameraRig::getFloat(String) - native crash

### ISSUE THREAD

**Issue by nathanalmeida** [Samsung/GearVRf#28]
When passing a not inatialized  key to **GVRCameraRig::getFloat(String)**, a native crash occurs.

``` java
public void testGetFloatWithoutSettingItBefore() {
        mGVRContext.getMainScene().getMainCameraRig().getFloat("ratio_r");
}
```

If we add the line

``` java
mGVRContext.getMainScene().getMainCameraRig().setFloat("ratio_r", 1.0f);
```

before calling the **get** method, the error doesn`t happen anymore.

**Comment by nathan-almeida** [comment]
In fact, maybe just a better feedback for the user, telling in which line or which object made this issue happen, could be enough.

**Comment by liaxim** [comment]
Will close in few days as it is just too outdated.
