### ISSUE TITLE
can not record the screen when in stereoscopic mode

### ISSUE THREAD

**Issue by andersonkxiass** [Samsung/GearVRf#285]
It can not record the screen when in stereoscopic mode, I have tried a lot of different ways to record screen but none are able to record the screen when the mode is stereoscopic.

When we change to the monoscopic mode all forms work well.

any idea what  happens?

**Comment by liaxim** [comment]
Hi. Are you trying to capture a video? If all you need is a screen shot - GVRF has built-in API to do that.

**Comment by andersonacs** [comment]
yes, I need to capture a video.

**Comment by liaxim** [comment]
I see. Nothing works for me too. We will have to study this further. There might be a need of special facility in GVRF like the one for the screenshots.

**Comment by Maginador** [comment]
We are developing a screen mirror api to work with GVRF, to achieve it we would need to record and stream the screen content. Do you think you could give us some starting point and/or guideline on how to get into it? We could help develop this facility through the screen mirror development.

**Comment by liaxim** [comment]
The built-in Samsung Screen Mirroring doesn't work either? If you want something in GVRF itself, there is always the screenshot code in the GVRViewManager. It may be a decent starting place.

**Comment by Maginador** [comment]
The built-in Samsung Screen Mirroring FPS goes down a lot when entering GVRF application, probably something around 1/2 fps

**Comment by tflynnt** [comment]
Have you tried 'adb shell screenrecord'?  We've done some internal video captures with that.  Though, i wasn't doing the recording, so i don't know the performance.

**Comment by Maginador** [comment]
Yes @tflynnt we've tried this way. When we do it, it just does not record anything while we are inside the GVRF application.

**Comment by tflynnt** [comment]
Hm, maybe it worked because it was on an engineering build?  Mihail, can you ask waddah about this?  He did the recording.

**Comment by liaxim** [comment]
I tried it too. On engineering build. Didn't work - if lucky it might capture a frame or two. Most of the times it was all black. I tried one of the popular third-party recorders (Recordable) with the same results. Will check with Waddah.

**Comment by andersonacs** [comment]
I'm not sure about this, but I checked the Android Screen Record API and it requires an Activity so in order to use it, It's moved to background (generally using this `moveTaskToBack(true);` ). Android can kill backgound processes when it needs extra resources could it be the case?

**Comment by liaxim** [comment]
The recording issue is related to using Oculus..

**Comment by mteofilo** [comment]
Do you have more information about Oculus issue?

**Comment by liaxim** [comment]
I have no specifics other that I can't record any of the Oculus apps I tried (non-gvrf based). Someone will investigate.

**Comment by m-blix** [comment]
I saw this a while back, grabs frame buffers among other things. If works might help narrow down.
https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-remote-monitor/

**Comment by liaxim** [comment]
Interesting tool.. Even that works for 5-10 seconds before it stops capturing. It is still much better than anything else: while it works it captures seemingly all the frames. The resolution though is very low.

**Comment by liaxim** [comment]
The only thing that seems to record for extended period of time is Mobizen. Choppy video and everything.. but still.

**Comment by andersonacs** [comment]
the mobizen was the first application we try to use, though it can record for a long time, the result is pretty bad, and video is lagging.

**Comment by dbrant** [comment]
FWIW, the only thing that has worked for me is the SideSync utility from Samsung (I mirrored the display to my PC, and recorded the video by capturing the SideSync window contents). I get about 15-20 FPS.

**Comment by mkeblx** [comment]
It looks like better support inbound from Oculus. Their remote monitor was downscaling heavily. Perhaps can implement a similar method, or just wait for update.
https://twitter.com/ID_AA_Carmack/status/662429992169709568
https://twitter.com/ID_AA_Carmack/status/662434322599845889

**Comment by danke-sra** [comment]
From GVRf side, we can provide fast API for capturing stereo frames. The pixel buffers can be available for CPU access at 60 FPS. However, the bottleneck would be H.264 compression and disk I/O.

**Comment by danke-sra** [comment]
How come nobody thinks this is the front-buffer rendering issue with Oculus? I can get the first frame using "adb shell screenrecord", but it does not capture continuously.

**Comment by thomasflynn** [comment]
because this used to work back on KitKat.  and the point where this breaks seems to coincide with one of the Oculus sdk version.  i think around the 0.6.0 version or so.  that being said, i think there are two routes:

1) supposedly in the latest Oculus System Activities updates, they've added some support for better capturing of what's on screen, but it hasn't been exposed yet (source: some random tweet by Carmack).
2) expand a bit further on the work @danke-sra did for the external renderer for the other shaders or something so we can read back one of the eyebuffers and find a way to stream that to disk.

**Comment by liaxim** [comment]
This is what I accidentally found to work (enableCapture is probably optional):
adb shell "echo dev_enableCapture 1 dev_frontbuffer 0 > /sdcard/.oculusprefs"

Afterwards I was able to use the built-in screenrecord just fine.

**Comment by danke-sra** [comment]
Good find. Does it turn off front buffer rendering?

**Comment by danke-sra** [comment]
I updated wiki page to include the solution. https://github.com/Samsung/GearVRf/wiki

Maybe this issue can be closed?

**Comment by liaxim** [comment]
Yes, it apparently turns off the front buffer rendering.
