### ISSUE TITLE
Textures not loading while loading a 3d model.

### ISSUE THREAD

**Issue by bonniemathew** [Samsung/GearVRf#286]
Hi, 

While working on loading a 3d model, we have found that some of the textures are not loading. It works on models with very few textures but the models with 8 - 12 texture references fails to load. This issue started happening from this commit c108b1af2220eb30b6df0062689c365e17b3caa0 (#253). 

-private static ExecutorService threadPool = Executors.newCachedThreadPool();
+private static ExecutorService threadPool = new GrowBeforeQueueThreadPoolExecutor("gvrf");

The usage of GrowBeforeQueueThreadPoolExecutor() seems to be the culprit. If I use Executors.newCachedThreadPool(), all textures are loading fine. 

Thanks, 
Bonnie M

**Comment by liaxim** [comment]
Thank you for the detailed report. We will investigate. Do you happen to have a problematic model you could share?

**Comment by bonniemathew** [comment]
I have sent the problematic model via email... (to m.marinov@samsung.com).

**Comment by liaxim** [comment]
The pool gets exhausted. There are so many Future.get()'s waiting that they use up all the threads and prevent the actual texture loading from proceeding.

**Comment by liaxim** [comment]
Please let me know whether pull request #289 works for you. Thanks.

**Comment by bonniemathew** [comment]
It's loading all the textures. Verified with two other models. Thanks for the change..
