### ISSUE TITLE
GVRRenderData.setDrawMode is being ignored

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#293]
If someone wants to render with, say,  GL_LINES, he or she can't currently do that. The draw_mode is not being used by the renderer.

**Comment by Vittalbabu** [comment]
We have hardcoded GL_TRIANGLES for all the glDrawElements() calls. We can change this to the requested draw_mode but we would need to test to ensure we don't have any hidden dependencies.  (ie) (mesh/shader setup/..) don't assume the presence of triangles.

**Comment by thomasflynn** [comment]
drawMode used to be hooked up.  it seems it got disconnected in a subsequent check-in.
