### ISSUE TITLE
Minimum Spherical video player...

### ISSUE THREAD

**Issue by ChrisCheil** [Samsung/GearVRf#317]
Whats the minimum GearVRf code for a spherical video player?
This sample generates audio only - it seems there are some issues regarding mesh / sphere?

```
@Override
    public void onInit( GVRContext gvrContext ) {

        mGVRContext = gvrContext;

        GVRScene scene = mGVRContext.getMainScene();

        // set camera background color
        scene.getMainCameraRig().getLeftCamera().setBackgroundColor( 0.0f, 0.0f, 0.0f, 1.0f );
        scene.getMainCameraRig().getRightCamera().setBackgroundColor( 0.0f, 0.0f, 0.0f, 1.0f );

        // set up camerarig position (default)
        scene.getMainCameraRig().getOwnerObject().getTransform().setPosition( 0.0f, 0.0f, 0.0f );

        // create sphere / mesh
        GVRSphereSceneObject sphere = new GVRSphereSceneObject( mGVRContext );
        GVRMesh mesh = sphere.getRenderData().getMesh();

        // retrieve first file from default oculus video folder
        String downloadsPath = Environment.getExternalStoragePublicDirectory( "Oculus/360Videos/" ).toString();
        File f = new File( downloadsPath );
        File file[] = f.listFiles();

        Uri videoURI = Uri.fromFile( file[ 0 ] );

        // create mediaplayer instance
        MediaPlayer mediaPlayer = MediaPlayer.create( mGVRContext.getContext(), videoURI );
        mediaPlayer.setLooping( true );
        mediaPlayer.start();

        // create video scene
        GVRVideoSceneObject video = new GVRVideoSceneObject( mGVRContext, mesh, mediaPlayer, GVRVideoType.MONO );
        video.setName( "video" );

        // apply video to scene
        scene.addSceneObject( video );
    }
```

**Comment by thomasflynn** [comment]
you're pretty close.  by default, GVRSphereSceneObject() orients its triangles to be visible from outside the sphere.  there's a flag to have the triangles face inward.  new GVRSphereSceneObject(mGVRContext, false);

a few other minor corrections in your sample code:
you don't need to call getOwnerObject() for the MainCameraRig, just call getTransform()
you also don't need to bother to set the background color since you'll be inside the sphere.

**Comment by thomasflynn** [comment]
and fwiw, i tested with one of the videos from here:  https://theta360.com/en/gallery/videos.html

i don't know what format(s) the videos in the Oculus/360Videos/ directory are in or if they're encrypted.  the theta360 videos seem to be equirectangular and wrap around a sphere trivially.

**Comment by thomasflynn** [comment]
so that others don't go through the same pain you did, i created a minimal 360 video sample based on your code.  it's up as a pull-request: https://github.com/Samsung/GearVRf/pull/320

**Comment by ChrisCheil** [comment]
Thanks! Is there a working project for Android Studio using latest GVRf and Mobile SDK?

**Comment by thomasflynn** [comment]
I thought we used to have instructions on how to use our binaries with Android Studio on our build instructions page, but I'm not seeing them now.  We'll have to write some up and update it.

**Comment by jason2kim** [comment]
Please find the latest information from our release links: https://github.com/Samsung/GearVRf/releases/tag/2.3
To use Android Studio, you can replace libs/ in the gvr-video-staticlib-androidstuido.zip sample with the latest gvrf library files and OVR library files as instructed in there.

**Comment by thomasflynn** [comment]
Hi @ChrisCheil , do you have what you need?

**Comment by ChrisCheil** [comment]
yep, works fine thanks for your support!
