### ISSUE TITLE
GVRContext::loadMesh(GVRAndroidResource androidResource) - non-triangle meshes are not getting visible

### ISSUE THREAD

**Issue by DanielNogueiraAndroid** [Samsung/GearVRf#32]
When trying to load non-triangle meshes as parameter to **GVRContext.loadMesh(GVRAndroidResource androidResource)**, application runs normally without crashing but the Mesh is not visible.

We are using this code (that works, the cube is visible):
 ```java
      GVRAndroidResource androidResourceCube = new GVRAndroidResource(mGVRContext, R.mipmap.smallcubet);
      GVRAndroidResource androidResourceTexture = new GVRAndroidResource(mGVRContext, R.drawable.texture3);
      GVRMesh cubeTMesh = mGVRContext.loadMesh(androidResourceCube);
      GVRSceneObject objectCube = new GVRSceneObject(mGVRContext, cubeTMesh, mGVRContext.loadTexture(androidResourceTexture));
      objectCube.getTransform().setPosition(0.0f, 0.0f, -2.0f);
      mGVRContext.getMainScene().addSceneObject(objectCube);
 ```
And that code (that does not works, the cube is invisible):
  ```java
      GVRAndroidResource androidResourceCube = new GVRAndroidResource(mGVRContext, R.mipmap.smallcubeq);
      GVRAndroidResource androidResourceTexture = new GVRAndroidResource(mGVRContext, R.drawable.texture3);
      GVRMesh cubeMesh = mGVRContext.loadMesh(androidResourceCube);
      GVRSceneObject objectCube = new GVRSceneObject(mGVRContext, cubeMesh, mGVRContext.loadTexture(androidResourceTexture));
      objectCube.getTransform().setPosition(0.0f, 0.0f, -2.0f);
      mGVRContext.getMainScene().addSceneObject(objectCube);
 ```
About Triangulation Ricardo Maginador explained:
 
The only difference between the ".obj" files is their mesh format, cubeT's mesh is divided using triangles while cubeQ's mesh by quads. The one using quads can not be rendered while  the mesh based in triangles is fully rendered. Just to complement, in Open GL quad mesh rendering is deprecated, that would explain what is happening, but the default structure used in 3D modeling is quad mesh, this generally is solved by converting quads to triangles during import.

**Comment by JonShemitz** [comment]
http://ogldev.atspace.co.uk/www/tutorial22/tutorial22.html suggests that Assimp does support non-triangle meshes; a quick glance at our code shows that we don't seem to be using those APIs.

I think changing this should be a pretty low-priority, but we should probably add a 'triangles only' note to the JavaDoc, in the meanwhile.

**Comment by deepakrawat22** [comment]
#153 resolved this issue. A quad face from 3D model is added as 2 triangles in GearVRf
