### ISSUE TITLE
Transform::getModelMatrix and setModelMatrix have different semantics

### ISSUE THREAD

**Issue by danke-sra** [Samsung/GearVRf#323]
Transform::getModelMatrix() returns the model matrix including parent's transform, but Transform::setModelMatrix() sets the local transform without parent's transform.

In other words, if you do Transform::setModelMatrix(A), Transform::getModelMatrix() will not return A, but Parent->transform() * A.

This became an issue when assimp node transforms are loaded into GVRf. Assimp API assumes local transform for both set() and get(). But GVRf has no way to get back the local transform(). I think some guideline may be needed or maybe a simple fix is possible.

**Comment by ragner** [comment]
If you do Transform::setModelMatrix(A), Transform::getModelMatrix() could return A
and we could implement a convenience function at SceneObject to return Parent->transform() * A

**Comment by danke-sra** [comment]
This is handled by https://github.com/Samsung/GearVRf/pull/335.

We can use getLocalModelMatrix now to get back the transform.
