### ISSUE TITLE
File import fails on using loadJassimpModelFromSD(...)

### ISSUE THREAD

**Issue by lokeshguddu** [Samsung/GearVRf#334]
Hi @danke-sra ,

I'm trying to load a model file which is present in the Device Storage on the Note4 test device. The models load fine if they are part of the assets folder of the application but fails when trying to access the same from external storage.

I'm copying the log that reflects the error.

```
...
...
...
11-12 08:23:16.674: W/System.err(19349): java.io.IOException: Unable to open file "astro_boy.dae".
11-12 08:23:16.674: W/System.err(19349): 	at org.gearvrf.jassimp2.Jassimp.aiImportFile(Native Method)
11-12 08:23:16.674: W/System.err(19349): 	at org.gearvrf.jassimp2.Jassimp.importFile(Jassimp.java:96)
11-12 08:23:16.674: W/System.err(19349): 	at org.gearvrf.GVRImporter.loadJassimpModelFromSD(GVRImporter.java:122)
11-12 08:23:16.674: W/System.err(19349): 	at org.gearvrf.GVRContext.loadJassimpModelFromSD(GVRContext.java:512)
...
...
...
```

You can also reproduce the same error if you keep the astro_boy.dae in the external storage and use 
```
loadJassimpModelFromSD("astro_boy.dae");
```
in the place of loadJassimpModel(...) at line 69 of [gvrjassimpmodelloader sample code](https://github.com/Samsung/GearVRf/blob/master/GVRf/Sample/gvrjassimpmodelloader/src/org/gearvrf/jassimpmodelloader/JassimpModelLoaderViewManager.java#L69).

**Comment by danke-sra** [comment]
This is a known issue. Do you mind providing a patch for that?

**Comment by lokeshguddu** [comment]
@danke-sra ,

Will try.

**Comment by danke-sra** [comment]
Fixed in https://github.com/Samsung/GearVRf/pull/345. However, Jassimp model loading still has a couple of low-priority issues. I will log them separately.
