### ISSUE TITLE
Universal Menu not accessible

### ISSUE THREAD

**Issue by dbrant** [Samsung/GearVRf#355]
There doesn't seem to be a way to launch the Universal Menu (which usually comes up on long-press of the Back button) from a GearVRf app, unless it's so trivial that I missed it.

**Comment by dbrant** [comment]
Looking into this a bit, I see that in `activity_jni.cpp`, you do a check for `keyCode == 4`, which looks right, but when I debug the actual number that comes in when long-pressing the Back button, it's actually `40` for some reason... When I change the 4 to 40 and rebuild the library, the long-back-press behavior works as expected. (?)

**Comment by liaxim** [comment]
We should be checking against OVR::OVR_KEY_BACK (which has value of 40). Fix is coming.

**Comment by liaxim** [comment]
@rahul27 the recent change for the sensors prevents the keys from getting to Oculus. Please take a look it. I think the GVRInputManager treats GearVR's trackpad as a mouse or something.

**Comment by rahul27** [comment]
@liaxim Sure. Will look at it.

**Comment by rahul27** [comment]
@liaxim this pull request should fix the issue:

https://github.com/Samsung/GearVRf/pull/356
