### ISSUE TITLE
Overlapping text in GVRTextView for transparent backgrounds

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#364]
Using transparent or no background on GVRTextView results in overlapping text being shown in the app (see the screenshot below).

This happens when I update the GVRTextView text inside `GVRScript.onStep()`.

![screenshot](https://cloud.githubusercontent.com/assets/609380/12104836/074b3804-b304-11e5-83ff-d2c90bb2a098.png)

This does not happen for solid background colors like black or white.

**Comment by ragner** [comment]
Hi @rahul27,
I put a new commit at #378 to fix this issue.

**Comment by liaxim** [comment]
@rahul27 Please confirm the fix addressed your issue. Thanks.

**Comment by rahul27** [comment]
@ragner @liaxim yup, that fixes it. Thanks.
