### ISSUE TITLE
import .dae file with textures = no textures

### ISSUE THREAD

**Issue by thomasflynn** [Samsung/GearVRf#385]
I tried to import this model: http://tf3dm.com/download-page.php?url=r2d2-21038
and wound up with no textures.  Figuring maybe Android didn't load .tga files, i converted them to .png and modified the .dae accordingly.

for someone who knows the model importing part of this, could you take a look?  thanks.

**Comment by danke-sra** [comment]
The model cannot be downloaded from the website (it doesn't start downloading). Can you please upload the original model and the modified one to another location? I will take a look as soon as I can get the model files. Thanks.

**Comment by thomasflynn** [comment]
let's try this link:  http://tf3dm.com/3d-model/r2d2-21038.html

**Comment by danke-sra** [comment]
Thanks for the new link. I've found a fix for this issue. Please check out the pull request: https://github.com/Samsung/GearVRf/pull/386
