### ISSUE TITLE
Setting Up A Project

### ISSUE THREAD

**Issue by dotunadegbite** [Samsung/GearVRf#394]
I am a beginner and having a difficult time trying to set up a new project in Eclipse that I can still access the different packages that are in the framework that is also imported into Eclipse

**Comment by thomasflynn** [comment]
hi, sorry for the late reply.  can you give more details on what you've tried and what the result was?  have you tried following the steps in our developer guide: http://gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start#BuildInstruct

**Comment by liaxim** [comment]
@dotunadegbite Do you still experience problems? If not, can we close this issue?

**Comment by liaxim** [comment]
@dotunadegbite Assuming it is all good for you now.
