### ISSUE TITLE
dev_videoCapture causes an insta-crash

### ISSUE THREAD

**Issue by johnspurlock** [Samsung/GearVRf#400]
Can someone confirm that dev_videoCapture works as expected on the gear vr?  It causes any vr app to crash immediately on my device.

To reproduce:
1. build and install one of the samples from the samples repo
2. enter development mode
3. adb shell "echo dev_videoCapture 1 dev_gpuLevel 3 dev_cpuLevel 3 > /sdcard/.oculusprefs"
4. launch the sample

Sample logcat output: [dev_videoCapture-fail-logcat.txt](https://github.com/Samsung/GearVRf/files/112668/dev_videoCapture-fail-logcat.txt)

More info on dev_videoCapture here: https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-testing-capture/

**Comment by liaxim** [comment]
I can report the same following the instructions. Will look into it more.

In the meantime, we have used this method in the past: https://github.com/Samsung/GearVRf/wiki. Most recently it hasn't worked for me but it may for you.

**Comment by johnspurlock** [comment]
Thanks for taking a look.  The preference is relatively new [1], but added as part of the 1.0 oculus sdk so I would have expected it to work on the gear vr.

[1] https://twitter.com/id_aa_carmack/status/686933482702942208

**Comment by liaxim** [comment]
Oculus's own VrTemplate crashes like this when capturing is enabled. There must be some undocumented prerequisites.

**Comment by liaxim** [comment]
VrCubeWorld_Framework crashes too. I tried including VrCapture in our build but that makes no difference.

**Comment by liaxim** [comment]
See https://twitter.com/ID_AA_Carmack/status/671730347634122752

The SystemActivities apk can be downloaded from the Mobile SDK download page - look for "SystemActivities APK". Apparently the update hasn't been pushed yet as I am using the latest and it doesn't work.

Summary: nice feature but it will work after a new SystemActivities apk is available. No recompilation, no GVRF changes required.

Can I close this issue?

**Comment by johnspurlock** [comment]
Ah ok - go ahead and close this issue and I guess we'll wait for an auto-update of Oculus System Activities.

Which version of that package do you have?  I have 1.0.1.3-20034506, which sounds newer than the one referenced on the mobile sdk page.

**Comment by liaxim** [comment]
I use SystemActivities-P4-119024-FB-16656924.apk (which shows version 1.0.1.3-20034506). 

Maybe it is better to close this after the SystemActivities has been updated to a version that is supposed to work and we have verified it. Will wait.

**Comment by johnspurlock** [comment]
Great - sounds good to me

**Comment by johnspurlock** [comment]
Still reproduces on com.oculus.systemactivities 1.0.1.4-21431179, which was pushed to me yesterday.

**Comment by liaxim** [comment]
Planning to close this one.

**Comment by johnspurlock** [comment]
Ok, fine with me
