### ISSUE TITLE
Add a GL workqueue for native code

### ISSUE THREAD

**Issue by danke-sra** [Samsung/GearVRf#403]
I am opening this issue to track discussion about OpenGL calls in native layer.

Currently, our onInit() callback is responsible for creating the scene. It typically includes I/O and other slow operations. Ideally, this onInit() should be called in a non-GL thread, and only GL-ops are queued for the GL thread.

This is however not possible because constructors in the C++ code directly calls GL functions. If we add a GL workqueue in native layer, the problem could be solved. We can run onInit() and onStep() from outside GL thread, and still allow GL-related ops to get the right context.

This will also reduce unpredictability of the code in the long term -- some ordering of GL ops is also possible in our multithreaded environment. We make also improve the safety and functionality of "Future" resources. Some of them do behavior unpredictably until some point and may generate some untracked GL errors -- which makes it hard to track down real errors.

I will write up a basic implementation for the GL workqueue, and hopefully others can provide inputs for its improvement.

**Comment by thomasflynn** [comment]
i don't know that a work queue is necessary.  yes, onInit and onStep should happen in an application thread and not the GL thread.  that's the way most other scenegraphs work.  the objects created / manipulated in those threads should only perform their GL calls when we are in the GL thread.  For example a new GVRTexture() should do whatever non-GL initialization is necessary and then that GVRTexture() is going to be used, it should verify that the GL initialization has completed.

**Comment by danke-sra** [comment]
i agree. the use of the workqueue is to allow constructors to start GL work. but whether they are completed needs to be checked. i think these resources may also need an interface (like isReady()) for that. but that's a separate issue -- it's good that it is brought up here. it may be implemented together.

**Comment by thomasflynn** [comment]
again, a work queue is not necessary.  that class just needs to be modified to make its GL calls when it is being used in the GL thread.  very simple.

**Comment by danke-sra** [comment]
i know the fix for the texture is simple. but since java layer has a gl queue and c++ layer does not, it can be a utility to solve similar problems. anyway, this is for inputs. i will help fixing the texture in a simple way.

**Comment by danke-sra** [comment]
This is a version that does not require a workqueue. I have verified it works on basic textures. https://github.com/Samsung/GearVRf/pull/407

**Comment by liaxim** [comment]
@danke-sra Can we close this now?

**Comment by danke-sra** [comment]
Yeah, please close it.
