### ISSUE TITLE
Video / Format / 3D / 180

### ISSUE THREAD

**Issue by ChrisCW1** [Samsung/GearVRf#408]
Hi *

in the native environment you can use these video formats to specify type of 3D video content:
“3D” : 3D movie side-by-side
“3DLR” : 3D movie side-by-side (same as “3D”)
“3DLRF” : 3D movie side-by-side full screen
“3DTB” : 3D movie top-to-bottom
“3DTBF” : 3D movie top-to-bottom full screen
and 180 POV

Is there something similar for GearVRf?

BR

Chris

**Comment by danke-sra** [comment]
Do you mean supporting these 3D formats in something like GVRVideoSceneObject? There are two built in formats: GVRVideoType.HORIZONTAL_STEREO and GVRVideoType.VERTICAL_STEREO. It should be similar to 3DLR and 3DTB. However, I haven't tested them yet. You are welcome to try and provide some feedback. Anyone has more information about this?

**Comment by andrejsinigoj** [comment]
We use the GVRVideoType.VERTICAL_STEREO for split videos top/bottom and it works as it should.
