### ISSUE TITLE
Relax glthread assertion for loadTexture() and loadCubemapTexture()

### ISSUE THREAD

**Issue by danke-sra** [Samsung/GearVRf#429]
Now textures can be constructed in non-GL thread. GL commands are deferred until binding (e.g., getId()).

**Comment by danke-sra** [comment]
Fixed in https://github.com/Samsung/GearVRf/pull/432

**Comment by liaxim** [comment]
Can this be closed now?

**Comment by liaxim** [comment]
@danke-sra Do you think we can close this now?

**Comment by danke-sra** [comment]
Yes, please close it.
