### ISSUE TITLE
Note 5 Support

### ISSUE THREAD

**Issue by tjlian616** [Samsung/GearVRf#438]
Please add support for Note 5 devices.

The sample projects work on s6 but not note 5. Note 5 is a great device. Please add support for Note 5.

**Comment by liaxim** [comment]
Could you please elaborate further? What samples did you try? What happens when you run them?

I have been running various samples on my Note5 without a problem.

**Comment by tjlian616** [comment]
@liaxim   I run the gvr-vuforia sample project from the gearvrf/GearVRf-Demos repo. On S6, it works great. On Note 5, the screen is all black (no crash). 

The sample project has two device XML files. One is for S6 and the other one is for note4. I tried both but the result is same. So I thought it might need a device XML for note 5.

**Comment by liaxim** [comment]
Vuforia is a bit special. I will check it out. I expect the rest of the samples to work though.

**Comment by thomasflynn** [comment]
as for the xml files, naming them after devices is outdated.  we've since setup the xml so that they are device independent.  we'll need to do a pass through all the samples to update them to just have a single xml file not named after a device.

**Comment by tjlian616** [comment]
@liaxim 
the gvr-video and gvropacityanigallery demo are also not working on note 5. Only one window is rendered in the middle of the screen. Please check my screenshots here.
http://postimg.org/image/9gp28qkmd/
http://postimg.org/image/el5qgl2zb/

**Comment by tjlian616** [comment]
@liaxim 
Do you remember which sample work on Note 5? I have tried a few but they all don't work, including the simple-sample one. 

Thank you!

**Comment by thomasflynn** [comment]
are you building against a pre-built gvrf? or building from source?  it should work from source.

**Comment by tjlian616** [comment]
@thomasflynn  I'm using the pre-build from the samples. Will build from source today and report back. Thanks!

**Comment by thomasflynn** [comment]
alright, thanks.  we should do another release then.  i'll talk to the team about it.

**Comment by tjlian616** [comment]
Building from source works. Thank you for the help.

BTW, is the new S7 supported as well?

**Comment by thomasflynn** [comment]
In source, yes.  We’ll be spinning new binaries sometime this week.

**Comment by jason2kim** [comment]
A new release is available at
https://github.com/Samsung/GearVRf/releases/tag/2.4

**Comment by liaxim** [comment]
@tjlian616 We have a new binary release. Can we close this issue?
