### ISSUE TITLE
getMainScene and getNextMainScene and splash screens

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#439]
We should really do something about these. Enabling and disabling the splashScreen has profound consequences. With enabled splashScreen you should use getNextMainScene, with disabled splashScreen you shouldn't. We must make all this transparent.

**Comment by danke-sra** [comment]
Agreed. The splash screen should be transparent to developers.

**Comment by liaxim** [comment]
Just understood while immersivepedia did not use a splash screen. Because of the main/nextMain thing apps that want to create new GVRScenes experience complications since you can't just setMainScene from onInit with a splash screen enabled. Can be fixed of course but the whole concept of a nextMainScene should be scrapped instead.

**Comment by NolaDonato** [comment]
I wholeheartedly agree. The next main scene concept complicates asset loading and initialization horribly. Let’s fix this.

-Nola

**Comment by liaxim** [comment]
As Nola suggested we could simplify everything by having onInit return the GVRScene and do not allow swapping in and out main scenes.

**Comment by thomasflynn** [comment]
should we close this now?

**Comment by liaxim** [comment]
Addressed by https://github.com/Samsung/GearVRf/pull/1017
