### ISSUE TITLE
Problem with FBX file rotation animations

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#454]
I've tried quite a few fbx files with rotation animations in them and they don't seem to animate. Position and scale seem to be working fine.

**Comment by danke-sra** [comment]
Here is the issue: https://github.com/assimp/assimp/issues/406

Let's try to fix it...

**Comment by roshanch** [comment]
can you share the files? Also, do you have ascii version of files? it would make debugging easier.
