### ISSUE TITLE
GVRTransform::getRotationPitch - Result is NaN

### ISSUE THREAD

**Issue by santhyago** [Samsung/GearVRf#46]
We think that **pitch** value must be **between 0 and 360**, but the method is returning **NaN**.

```
    mSceneObject.getTransform().setRotation(1.0f,
    BoundsValues.getFloatList().get(0),
    BoundsValues.getFloatList().get(0),
    BoundsValues.getFloatList().get(0));

    float pitch = mSceneObject.getTransform().getRotationPitch();
    boolean result = (pitch >= 0) && (pitch <= 360);
    assertTrue("Pitch 1: " + pitch, result);
```
The first time, **pitch** gets a *"valid"* value (*1.63E-43*, I don't know if this is a valid value, but is in the range).
```
    mSceneObject.getTransform().setRotation(1.0f,
    BoundsValues.getFloatList().get(1),
    BoundsValues.getFloatList().get(1),
    BoundsValues.getFloatList().get(1));

    pitch = mSceneObject.getTransform().getRotationPitch();
    result = (pitch >= 0) && (pitch <= 360);
    assertTrue("Pitch 2: " + pitch, result);
```
The second time, with these values, **pitch** gets a **NaN** as value.

**Comment by JonShemitz** [comment]
>     mSceneObject.getTransform().setRotation(1.0f,
    BoundsValues.getFloatList().get(0),
    BoundsValues.getFloatList().get(0),
    BoundsValues.getFloatList().get(0));
    // ...
    mSceneObject.getTransform().setRotation(1.0f,
    BoundsValues.getFloatList().get(1),
    BoundsValues.getFloatList().get(1),
    BoundsValues.getFloatList().get(1));

This is probably a genuine bug - but what are the values returned by `BoundsValues.getFloatList().get(0)` and `BoundsValues.getFloatList().get(1)`? Please try to give us self-contained bug reports that we can reproduce and triage.

**Comment by santhyago** [comment]
```
private static final float UNPICKED_COLOR_R = 0.7f;
private static final float UNPICKED_COLOR_G = 0.7f;
private static final float UNPICKED_COLOR_B = 0.7f;
private static final float UNPICKED_COLOR_A = 1.0f;
```

```
BoundsValues.getFloatList().get(0) = Float.MIN_VALUE = 1.4E-45
BoundsValues.getFloatList().get(1) = Float.MAX_VALUE = 3.4028235E38
```

```
mSceneObject = getColorBoard(1.0f, 1.0f);
```

```
private GVRSceneObject getColorBoard(float width, float height) {
        GVRContext gvrContext = TestDefaultGVRViewManager.mGVRContext;
        ColorShader mColorShader = new ColorShader(gvrContext);
        GVRMaterial material = new GVRMaterial(gvrContext, mColorShader.getShaderId());
        material.setVec4(ColorShader.COLOR_KEY, UNPICKED_COLOR_R, UNPICKED_COLOR_G, UNPICKED_COLOR_B, UNPICKED_COLOR_A);
        GVRSceneObject board = new GVRSceneObject(gvrContext, width, height);
        board.getRenderData().setMaterial(material);
        return board;
}
```

**Comment by JonShemitz** [comment]
> BoundsValues.getFloatList().get(1) = Float.MAX_VALUE

Thanks - it's probably an over (or under) flow error. Would you take a look, @guodongrong? `jni/objects/components/transform.h` defines 

    float rotation_pitch() const {
        return glm::pitch(rotation_);
    }

I see that glm::pitch() takes an `precision` type parameter, but I don't know enough about (quaternions or) glm to start poking around.
