### ISSUE TITLE
Do not perform onInit and similar GVRScript callbacks on the GL thread

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#463]
Have prototyped something, it works mostly with a certain heavyweight app. Added a main gvrf (handler)thread on which to serialize these callbacks (to match order of execution with order of issuance).

- GVRTexture.getId() is exposed as a problem; it may be called on any thread but we rely on it to be called on the GL thread. So far simple workaround to ensure that on the Java side seems adequate.
- Some texture are missing, still investigating the cause.

As an added benefit we can finally make the splashScreen real. As soon as the onInit is done we can dismiss it. That seems to work without issues thus far.

**Comment by danke-sra** [comment]
Shouldn't we wait for all Futures done before closing the splash screen?

Can the main GVRF thread also include animation engine?

**Comment by liaxim** [comment]
Hard to say what the intended use of all these futures might be. They could be just preloaded for example. We might have to consider this but I rather not over-complicate right now. The app always has the option to do a Future.get() on everything it really needs before exiting onInit.

I am not sure of the exact implications of having the animation engine on this main thread but if possible, then sure.

**Comment by danke-sra** [comment]
If we don't wait for futures to complete, this will change the behavior of current apps. That's the concern. Even if they load things they don't need, it still makes sense for the splash screen to hide that.

**Comment by PsycoTodd** [comment]
Hello liaxim,

Can I know what is the workaround on java side you mentioned at the beginning about GVRTexture?

Thank you.

**Comment by liaxim** [comment]
Just change internally the getId() method to run on the GL thread and wait for its result. Something like:

```java
    public int getId() {
        final CountDownLatch cdl = new CountDownLatch(1);
        final int[] id = new int[1];
        getGVRContext().runOnGlThread(new Runnable() {
            @Override
            public void run() {
                id[0] = NativeTexture.getId(getNative());
                cdl.countDown();
            }
        });
        try {
            cdl.await();
        } catch (final Exception exc) {
            throw new IllegalStateException("Unable to obtain texture id");
        }
        return id[0];
    }
```

For this not to deadlock a change to the GVRViewManager is necessary:
```java
    @Override
    public void runOnGlThread(Runnable runnable) {
        if (Thread.currentThread().getId() != mGLThreadID) {
            mRunnables.add(runnable);
        } else {
            runnable.run();
        }
    }
```

**Comment by danke-sra** [comment]
This posted code is a bit overkill and a bit too complicated than needed. It should be OK to run some API on GL thread, especially those that are closely related to GL. This seems to make it asynchronous under the hood. Though in this case, this is not too complicated, it could be more complicated if the data could be released or changed after returning from the API. The immediately deadlock pattern is also a concern though it is fixed somewhere.

I would be very conservative about this change. If it is for creating GVRTextView on non-GL thread, I think there is a more straightforward way to do so.

**Comment by liaxim** [comment]
There is a problem with our getId api - we provide a public getId method that apps can call from any thread but we must have have it called on the GL thread. There is a certain important app that does that. This workaround just lets me proceed exploring and finding issues. What is wrong with that?

The change is the minimal possible to ensure the actual getId is on the GL thread but the app can call it from any thread. The semantics are preserved from app's point of view.

**Comment by danke-sra** [comment]
The GL thread check can be added on getId(). That's all we need to make sure apps are running as expected (or not running).

A potential issue with hiding GL call under the hood is that API can run with drastically different timing in different threads. I would rather not let it run when it has to run slowly and asynchronously. The indeterminism could cause deadlock if the code gets complicated. For example, the user code could be:

```
for (int i = 0; i < 500; ++i) {
    idArray[i] = texture[i].getId();
}
```

It runs fast in GL thread but takes 500 * 16ms to run in non-Gl thread. I think this kinda of problem should be made visible to users, and force them to run the piece of code in GL thread, instead of handling it under the hood by deferring it.

**Comment by liaxim** [comment]
The end result is https://github.com/Samsung/GearVRf/pull/522, I guess. We will deprecate GVRScript and provide a new base class which is never run on the GL thread.
