### ISSUE TITLE
best practice for switching activity/scene?

### ISSUE THREAD

**Issue by denghongcai** [Samsung/GearVRf#477]
any suggestion is preciated

**Comment by liaxim** [comment]
- You'd like to have multiple VR Activities? I recommend to not take this route as we are not even officially supporting it and it is almost certain to lead to crashes.

- You'd like to have different application views and switch between them somehow in the same activity? One option is to have multiple GVRScenes and switch the mainScene in GVRContext. Or have few root GVRSceneObjects you add and remove from the one and only mainScene. Or just have some entity add and remove all the sceneObjects you need in each view. There is no single right way. Whatever suits you best.

**Comment by liaxim** [comment]
@denghongcai Was this helpful? Can we close the issue if it was?

**Comment by denghongcai** [comment]
totally helpful!
