### ISSUE TITLE
Cannot build GVRf Framework

### ISSUE THREAD

**Issue by vanduijnjordi** [Samsung/GearVRf#483]
Hi guys,

I've been trying to locally build the GVRf Framework, but no luck so far.
The errors I'm getting now are all related to:

**make (e=2): The system cannot find the file specified.**

Is there any general direction I can look into or would you like to help me directly? Please let me know what you need to know to make this work.

Thanks so much in advance!!

Kind regards,
Jordi van Duijn

**Comment by liaxim** [comment]
Hi,

Are you using Windows? Can you please send to me or attach here the full build log?

**Comment by vanduijnjordi** [comment]
Hi Liaxim,

I'm using windows 7. I attached the build log. Also, I get the following error before building (when starting up Eclipse):

[2016-04-05 08:14:32 - Unable to launch cygpath. Is Cygwin on the path?] java.io.IOException: Cannot run program "cygpath": CreateProcess error=2, The system cannot find the file specified

[build_log.txt](https://github.com/Samsung/GearVRf/files/203954/b
about Cygwin, it can't find it
[build_log.txt](https://github.com/Samsung/GearVRf/files/203954/build_log.txt)

**Comment by liaxim** [comment]
Glad to hear that you have solved the problem. It doesn't seem to be a gvrf problem; I have found a number of references to similar issues and usually upgrading to the latest ndk helps.

Can we close this issue now?

**Comment by vanduijnjordi** [comment]
Thanks for your time Liaxim, the issue can be closed :) Be aware though that I solved the problem by downgrading to a previous version of the ndk. If you think that r11c should be working fine, then maybe you could look into that, but I'm good for now :+1:

**Comment by liaxim** [comment]
Thanks
