### ISSUE TITLE
Poor performance after update to android version 6.0.1

### ISSUE THREAD

**Issue by oliverellmers** [Samsung/GearVRf#485]
Has anybody else noticed a terrible drop in performance and poor sensor response after the most recent android update with the GearVRf?

The Oculus 360 player doesn't seem to have the same issue.

I have been working on an OSC based synchronization system for the past few weeks. Everything was working fine until we upgraded Android on our devices, and now the sensors don't seem to respond correctly - getting strange rotation/orientation issues.

Cheers,

O.

**Comment by liaxim** [comment]
Which version of the Oculus Mobile SDK do you build GVRF with? You might try 1.0.0.1 if you are not on it. What device models do you use?

**Comment by oliverellmers** [comment]
Currently building with Oculus Mobile SDK 1.0.0.1 on Samsung Galaxy S6's and having the same problem. It is as if there is some form of inertial bounce applied to the camera, and the sensors aren;t able to keep up with head orientation. also having the same issue in developer mode/not plugged into the headset

Al though the application is still running - in my log I am receiving two errors:

gvrf: FrameBufferObject::create: GL error on entry error: GL_INVALID_ENUM


libEGL:  call to OpenGL ES API with no current context (logged once per thread)

**Comment by oliverellmers** [comment]
I think it is safe to say it is something to do with Android version 6.01, as I am currently running identical software on three Samsung S6 devices running 6.01 and two Samsung S6 devices running 5.11 and the performance on the '5' devices is as expected, whereas the performance on the '6' devices is showing the issues.

**Comment by liaxim** [comment]
Sounds like an issue we had where we will keep using the internal sensors instead of switching to those on GearVR itself. Which version of GVRF do you use?

**Comment by liaxim** [comment]
I will get a hold of an S6 with M and investigate.

**Comment by liaxim** [comment]
Tried an S6 with M but it worked fine for me. I could create a branch with extra logging for you to try, if you could help us out? In any case, please send me or just attach here the complete logcat output.

---
gvrf: FrameBufferObject::create: GL error on entry error: GL_INVALID_ENUM - this is innocent, the Oculus SDK calls us with a GL error pending; we clear it and print it out, just in case.

libEGL: call to OpenGL ES API with no current context (logged once per thread) - this could be anything; hard to say but if we had no context nothing would have worked.

**Comment by oliverellmers** [comment]
Sorry for not getting back to you sooner. Thankyou for taking a look.

One thing that came to mind when you mentioned the sensor issue - is there any necessary permissions that need to be added to the android manifest to ensure that it accesses the sensors of  the gearvr headset as opposed to the accelerator within the phone with android 6.0.1? I have a feeling that it may be not using the gear's sensors.

will go through your suggestions today and put some logging info up for you.

happy to help - need to tackle this for work asap

**Comment by oliverellmers** [comment]
okay so unfortunately somebody from work has deployed all of our devices this morning to a client for a project and I am unable to develop on anything with the latest android version running on it.

I will have to revisit this when they come back.

Thanks!

**Comment by liaxim** [comment]
Hi, what is your target sdk (minSdkVersion&targetSdkVersion in the manifest)?

**Comment by oliverellmers** [comment]
minSdkVersion="19"
targetSdkVersion="23"

We just got an order of more devices in so can work on this now also

**Comment by liaxim** [comment]
There are no additional permissions required as far as I know. Tried on my S6+M and API level 23 but still no luck reproducing. The GVRF demo apps exhibit the same behavior on your devices, I presume? Can you give me the exact model number of your devices? Mine is SM-G920A.

**Comment by oliverellmers** [comment]
Hmm brand new device here and now the app is crashing on launch.

model number is: SM-G920F
android version: 6.0.1

logfile from last build attached
[log.txt](https://github.com/Samsung/GearVRf/files/207171/log.txt)

**Comment by liaxim** [comment]
Could the crash have something to do with this?

```
04-06 19:59:19.081: W/System.err(24910): java.io.FileNotFoundException: /storage/emulated/0/R42/gearvrfvideo.mp4: open failed: ENOENT (No such file or directory)
04-06 19:59:19.081: W/System.err(24910): 	at libcore.io.IoBridge.open(IoBridge.java:452)
04-06 19:59:19.081: W/System.err(24910): 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
04-06 19:59:19.081: W/System.err(24910): 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
04-06 19:59:19.081: W/System.err(24910): 	at com.Random42.gearVRfShowreel.Minimal360Video.onInit(Minimal360Video.java:79)
04-06 19:59:19.081: W/System.err(24910): 	at java.lang.reflect.Method.invoke(Native Method)
04-06 19:59:19.081: W/System.err(24910): 	at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:186)
04-06 19:59:19.081: W/System.err(24910): 	at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:94)
04-06 19:59:19.081: W/System.err(24910): 	at org.gearvrf.GVRViewManager$1.beforeDrawEyes(GVRViewManager.java:605)
04-06 19:59:19.081: W/System.err(24910): 	at org.gearvrf.GVRViewManager.beforeDrawEyes(GVRViewManager.java:294)
04-06 19:59:19.081: W/System.err(24910): 	at org.gearvrf.GVRActivity$3.onBeforeDrawEyes(GVRActivity.java:353)
04-06 19:59:19.081: W/System.err(24910): 	at org.gearvrf.VrapiActivityHandler$5.onDrawFrame(VrapiActivityHandler.java:410)
04-06 19:59:19.081: W/System.err(24910): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1649)
04-06 19:59:19.081: W/System.err(24910): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1354)
04-06 19:59:19.081: W/System.err(24910): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
04-06 19:59:19.081: W/System.err(24910): 	at libcore.io.Posix.open(Native Method)
04-06 19:59:19.081: W/System.err(24910): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
04-06 19:59:19.081: W/System.err(24910): 	at libcore.io.IoBridge.open(IoBridge.java:438)
04-06 19:59:19.081: W/System.err(24910): 	... 12 more
```

**Comment by oliverellmers** [comment]
Hmm that is in fact a new error - as the file is on the device and in the correct path

**Comment by oliverellmers** [comment]
Fixed the problem, rebuilt GearVRf with latest source from github (I'm more or less certain it was what I was using anyway..?), and set up a new eclipse project with my original project. The lag has disappeared.
