### ISSUE TITLE
Framework.apk?

### ISSUE THREAD

**Issue by Nathipha** [Samsung/GearVRf#496]
Hi everyone,

I finally managed to get the Framework to build successfully but now Eclipse is showing me a weird error message when I try to run one of the samples. Here's the console log:

```
[2016-04-13 17:18:26 - Minimal360PhotoActivity] ------------------------------
[2016-04-13 17:18:26 - Minimal360PhotoActivity] Android Launch!
[2016-04-13 17:18:26 - Minimal360PhotoActivity] adb is running normally.
[2016-04-13 17:18:26 - Minimal360PhotoActivity] Performing org.gearvrf.samples.Minimal360Photo.Minimal360PhotoActivity activity launch
[2016-04-13 17:18:26 - Minimal360PhotoActivity] Automatic Target Mode: using device 'xxxxx'
[2016-04-13 17:18:26 - Minimal360PhotoActivity] Uploading Minimal360PhotoActivity.apk onto device xxxxx
[2016-04-13 17:18:27 - Minimal360PhotoActivity] Installing Minimal360PhotoActivity.apk...
[2016-04-13 17:18:29 - Minimal360PhotoActivity] Success!
[2016-04-13 17:18:29 - Framework] Could not find Framework.apk!
[2016-04-13 17:18:29 - Minimal360PhotoActivity] Starting activity org.gearvrf.samples.Minimal360Photo.Minimal360PhotoActivity on device xxxxx
[2016-04-13 17:18:29 - Minimal360PhotoActivity] ActivityManager: Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.gearvrf.samples.Minimal360Photo/.Minimal360PhotoActivity VirtualScreenParam=Params{mDisplayId=-1, null, mFlags=0x00000000)} }
```
(I edited the device ID to "xxxxx", it actually shows the right one in the console.)
The same thing happens with the "gamepad" sample.
I already tried to export the Framework as apk but Eclipse didn't let me.
When I open one of the already installed samples on my S7, it only shows a black screen with a white "x" in one of the corners, then the app crashes. Yes, I added the Oculus signature file to the "assets" folder, so at least that shouldn't be the cause.

Does anyone know what's up with this Framework.apk and where I can get it/how I can get the samples to run?

**Comment by liaxim** [comment]
Hi,

The "Could not find Framework.apk" is a benign message. It is an artifact of the Framework being a library project and what it seems a bug in the Android plugin for Eclipse. See http://stackoverflow.com/questions/5580575/could-not-find-the-xxx-apk-message-in-console-while-starting-application-with - it may help you.

For the crash we will need logcat output - would you mind attaching it here? There might be something missing from the apk you are building - did you copy all the Oculus libraries GVRF depends on to the libs folder?

**Comment by thomasflynn** [comment]
do you just need to enable Oculus developer mode?  Settings->Application Manager->All->GearVR Service->Manage Storage  tap on the version number seven or eight times, then toggle the switch for developer mode.  I have no idea what it is that convoluted.

**Comment by Nathipha** [comment]
@liaxim 
Thanks, I'll look into it and post the log tomorrow.
If we're talking about the "libs" folder in "GVRf\Framework", then yes. I also copied the extra files from the libs-gvrf archiv into it.

@thomasflynn 
That's the problem, there's no "Manage Storage" button there for me. I did see it in the youtube video by gamefromscratch and in [this guide](https://docs.unrealengine.com/latest/INT/Platforms/GearVR/Debugging/) but the whole settings menu looks different on my phone.
What's even weirder is: The guide says that there has to be at least one app installed that has my device signature in it. The console in Eclipse said that both the "gamepad" and the "Minimal360PhotoActivity" app were installed successfully (they simply crashed 5-10 seconds after starting them), so I don't know, why it still won't show that button. Maybe it's different if you're using Marshmallow (6.0.1) instead of Lollipop?
The only thing that it would let me do was enabling the normal Android developer mode but that one apparently doesn't help with VR apps.

**Comment by thomasflynn** [comment]
ok, yeah, the menu is different on Marshmallow.  After I click on 'Gear VR Service', you need to click on 'Storage', then 'Manage Storage'.  Once there, you can start tapping on VR Service Version (7 or 8 times).  You do need to have an apk with your device signature installed.  If you don't, then when it searches your phone for apks, it'll give a toast that says, "you are not a developer".  If you do, then you'll get the developer mode switch.

**Comment by Nathipha** [comment]
@thomasflynn 
Okay, I got it and it worked. Thanks! Sorry, I think it's worth a *facepalm*. It always starts scrolled down and since there are two different entries with the same name (the phone isn't set to English), I didn't recognize the first one to be what I was looking for.

**Comment by thomasflynn** [comment]
Glad you're up and running.  Close this issue?

**Comment by Nathipha** [comment]
@liaxim 
Thanks, that solved one problem, it's not showing that error message anymore.
Afterwards I got the same error like in [this](http://stackoverflow.com/questions/7870265/unable-to-execute-dex-multiple-dex-files-define-lcom-myapp-rarray) post but I fixed it by only having "Android x.x.x" (x.x.x = version number), "gamepad/src" and "gamepad/gen" in "Project Properties/Java Build Path/Order and Export" ticked (the last two have that full square "check mark"). Is that the right one or should I better use "Android Private Libraries" or "Android Dependencies"?
No matter what I use, the app still crashes on startup, though (at least the developer mode is working now, yay). :/

Here's the crashlog from the LogCat tab in Eclipse:

```
04-15 16:31:25.239: W/ResourcesManager(11715): getTopLevelResources: /data/app/org.gearvrf.gamepad-1/base.apk / 1.0 running in org.gearvrf.gamepad rsrc of package org.gearvrf.gamepad
04-15 16:31:25.239: I/InjectionManager(11715): Inside getClassLibPath + mLibMap{0=, 1=}
04-15 16:31:25.249: D/ResourcesManager(11715): For user 0 new overlays fetched Null
04-15 16:31:25.249: I/InjectionManager(11715): Inside getClassLibPath caller 
04-15 16:31:25.259: D/InjectionManager(11715): InjectionManager
04-15 16:31:25.259: D/InjectionManager(11715): fillFeatureStoreMap org.gearvrf.gamepad
04-15 16:31:25.259: I/InjectionManager(11715): Constructor org.gearvrf.gamepad, Feature store :{}
04-15 16:31:25.259: I/InjectionManager(11715): featureStore :{}
04-15 16:31:25.259: W/ResourcesManager(11715): getTopLevelResources: /data/app/org.gearvrf.gamepad-1/base.apk / 1.0 running in org.gearvrf.gamepad rsrc of package org.gearvrf.gamepad
04-15 16:31:25.259: D/ContextRelationManager(11715): ContextRelationManager() : FEATURE_ENABLED=true
04-15 16:31:25.259: D/RelationGraph(11715): garbageCollect()
04-15 16:31:25.269: W/ResourcesManager(11715): getTopLevelResources: /data/app/org.gearvrf.gamepad-1/base.apk / 1.0 running in org.gearvrf.gamepad rsrc of package org.gearvrf.gamepad
04-15 16:31:25.269: I/GVRActivity(11715): onCreate 4c1b180
04-15 16:31:25.289: E/JniUtils(11715): FindClass( com/oculus/vrapi/loader/AppLoader ) failed
04-15 16:31:25.289: A/libc(11715): Fatal signal 6 (SIGABRT), code -6 in tid 11715 (gearvrf.gamepad)
```

Another weird thing I've noticed - and maybe that's how it's supposed to be - is that I get an error message when I start Eclipse:
`[2016-04-15 15:49:59 - Unable to launch cygpath. Is Cygwin on the path?] java.io.IOException: Cannot run program "cygpath": CreateProcess error=2, Das System kann die angegebene Datei nicht finden`
After loading the Android SDKs, everything's fine again and the red "x" on top of the "Framework" project icon vanishes.

**Comment by liaxim** [comment]
Hi,

In my projects I have "Android Private Libraries" and "Android Dependencies" checked in the Order and Export section and have no complaints.

Looks like you are missing the Oculus libraries GVRF depends on. You need to copy few files from the Oculus Mobile SDK (1.0.0.0 and 1.0.0.1 both work) to your libs folder. VrApi.jar and SystemUtils.jar should go to ./libs/ and libvrapi.so to ./libs/armeabi-v7a/.

And about the "Cannot run program "cygpath"" - maybe you can try what http://stackoverflow.com/questions/15459934/unable-to-launch-cygpath-in-android proposes and/or different ndk versions as I have seen reports that may matter. But if you build works otherwise you may just ignore the message.

**Comment by Nathipha** [comment]
I had both checked before too but that gave me the ["Unable to execute dex..."](http://stackoverflow.com/questions/7870265/unable-to-execute-dex-multiple-dex-files-define-lcom-myapp-rarray) error.
I already copied the 3 files into the libs folder (for me it's: G:\Dev\GearVR\GVRf\Framework\libs), so SystemUtils.jar, VrApi.jar and VrAppFramework.jar. It didn't say anything about "libvrapi.so" in the [instructions](http://www.gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start#BuildPreReq) but a file with that exact name is already in the "armeabi-v7a" folder.

I had a different NDK version (r11c, now I'm using r10e) installed before but that gave me a bunch of other errors and it didn't even build the Framework properly. I did set the NDK_HOME environment variable for Windows and just now added the "NDKROOT" variable for the project in eclipse (G:\Dev\AndroidNDK\ndk-build.cmd NDK_DEBUG=1) but it still gives me the same message. I thought you don't need Cygwin for newer versions?

**Comment by liaxim** [comment]
Based on this error:
```
04-15 16:31:25.289: E/JniUtils(11715): FindClass( com/oculus/vrapi/loader/AppLoader ) failed
```
I am pretty sure VrApi.jar is not found at runtime.

Regarding the NDK: yes, I am seeing references that Cygwin is not needed anymore. I am using Linux so I don't have first-hand experience building on Windows though.

**Comment by Nathipha** [comment]
Damn, the "Order and Export" settings reset itself after restarting Eclipse. Seriously?!

I can assure you, the file is in there:
[click](http://i.imgur.com/dCCdcsq.png)

Hm, okay, I guess I'll just ignore it then.

**Comment by liaxim** [comment]
You can enable verbose build logging (Windows->Preferences->Android->Build->Build output) and examine the console output. Do you see anything like the following?

```
[2016-04-15 09:04:09 - gvrsample] Dx processing com/oculus/...
[2016-04-15 09:04:09 - gvrsample] Dx processing com/oculus/vrapi/...
[2016-04-15 09:04:09 - gvrsample] Dx processing com/oculus/vrapi/loader/...
[2016-04-15 09:04:09 - gvrsample] Dx processing com/oculus/vrapi/loader/AppLoader.class...
[2016-04-15 09:04:09 - gvrsample] Dx processing com/oculus/vrapi/loader/BuildConfig.class...
```

**Comment by liaxim** [comment]
You shouldn't have to mess with the Order and Export settings really. Dropping the dependencies under libs is enough. The Android plugin for Eclipse takes care of the rest. If you explicitly modify your Java Build Path and/or Order and Export settings, it is almost certain you'll get in trouble.

**Comment by Nathipha** [comment]
I just deleted the samples and the framework, downloaded the latest version (from 42 minutes ago) and did the following:
- Import the framework in Eclipse and build it
- Copy the 3 files, plus the "armeabi-v7a" folder with the extra file from the Oculus SDK into the framework's "libs" folder
- Clean and build it
- Import the "gvr-cubemap" sample
- Copy my Oculus key into the sample's "asset" folder
- Clean and built it --> error because it's not linked to the framework
- Add the framework (Properties - Android - Library) & apply
- Clean and build again
- Enable Developer Mode (both Gear VR and general Android) on my phone and plug it in
- Run the "gvr-cubemap" sample as an Android Application
- Tada, the app is running! So do "gamepad" and "gvrf_minimal360photo".
I didn't change anything exept get the new Framework (didn't even restart my PC inbetween), maybe there was a bug in the old one but I have absolutely no idea what actually changed and I did pretty much the same things when I set everything up the first time..

Thank you very much for your help! I'm just glad that it's working now, even though I have no idea why.

Btw, my Oculus Mobile SDK is version 1.0.0.1.

**Comment by liaxim** [comment]
Glad to hear that things are working. Can we close the issue now?

**Comment by Nathipha** [comment]
Yes, thanks.
