### ISSUE TITLE
Missing constructor GVRTextViewSceneObject(GVRContext, MainActivity, int, int, String) 

### ISSUE THREAD

**Issue by dgoyal1504** [Samsung/GearVRf#497]
Line 152 of VRBasketBallAndroid/src/com/cesarandres/vr/vrbbals/android/BallSpinnerScript.java refers to this missing consturctor
textPanel = new GVRTextViewSceneObject(context, core, 7, 4, "");

**Comment by liaxim** [comment]
Thank you for the catch. Fixed in https://github.com/Samsung/GearVRf/pull/498.

**Comment by liaxim** [comment]
Fix merged. Thanks again.

**Comment by dgoyal1504** [comment]
Thanks - Can someone please look at issue # 499. I could handle scene object's setPosition call. But need some guidance on getOwnerObject() call on GVRCameraRig (line 255 of MUNIVisualizer.java)  

    On Wednesday, April 13, 2016 2:01 PM, Mihail <notifications@github.com> wrote:
 

 Fix merged. Thanks again.—
