### ISSUE TITLE
The method getOwnerObject() from the type GVRComponent is not visible (is protected, should be public)

### ISSUE THREAD

**Issue by dgoyal1504** [Samsung/GearVRf#499]
Line 71 of MainActivity/src/pw/ian/vrtransit/MUNIVisualizerScript.java is trying to access this method. I think it should be public if this code segment is correct.

		scene.getMainCameraRig().getOwnerObject().getTransform()
				.setPosition(0f, 0f, 0f);

**Comment by thomasflynn** [comment]
The vrtransit code needs updating.  calling getOwnerObject() is no longer necessary from user level code.

**Comment by thomasflynn** [comment]
just to be clear, you can just call scene.getMainCameraRig().getTransform().setPosition()

**Comment by dgoyal1504** [comment]
I downloaded GVRf code base yesterday night and found this issue in MUNIVisualizerScript.java under MainActivity. Perhaps that codebase needs to be modified. Many more must be using this codebase as a guide to write first VR project and will get confused. 
In line 255 of MUNIVisualizerScript.java we have a GVRCameraRig.GVRgetOwnerObject() call. How to resole that?   

    On Wednesday, April 13, 2016 12:59 PM, thomasflynn <notifications@github.com> wrote:
 

 just to be clear, you can just call scene.getMainCameraRig().getTransform().setPosition()—

**Comment by thomasflynn** [comment]
check out pull request: https://github.com/Samsung/GearVRf/pull/500

also, for other examples of how to use the GearVR Framework, check out our demos repository at https://github.com/gearvrf/GearVRf-Demos

**Comment by dgoyal1504** [comment]
Thanks. It worked. 

    On Wednesday, April 13, 2016 2:18 PM, thomasflynn <notifications@github.com> wrote:
 

 check out pull request: #500also, for other examples of how to use the GearVR Framework, check out our demos repository at https://github.com/gearvrf/GearVRf-Demos—

**Comment by thomasflynn** [comment]
ok, thanks for double checking it.  just merged the change.  close this issue now?

**Comment by dgoyal1504** [comment]
Yes please


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: thomasflynn <notifications@github.com> Date: 4/13/16  2:31 PM  (GMT-05:00) To: Samsung/GearVRf <GearVRf@noreply.github.com> Cc: dgoyal1504 <dgoyal@yahoo.com> Subject: Re: [Samsung/GearVRf] The method getOwnerObject() from the type
  GVRComponent is not visible (is protected, should be public) (#499) 
ok, thanks for double checking it.  just merged the change.  close this issue now?
