### ISSUE TITLE
Data rendering just for one eye not working

### ISSUE THREAD

**Issue by lassehe** [Samsung/GearVRf#509]
I was not able to set an object to be rendered only for a single eye by using e.g. GVRRenderData.setRenderMask(GVRRenderMaskBit.Right) like it worked earlier.

I suspect there was regression in commit 59920e25997612cf1f6068b1346fe46723c7f71d Renderer::renderRenderData()  if statement which compares render_mask in line 644.

I think this should be a bitwise operation as before, possibly:
if (!(render_mask & render_data->render_mask())) return;

**Comment by liaxim** [comment]
@lassehe Thank you for catching this. We will have it fixed soon.

**Comment by liaxim** [comment]
Your pull request https://github.com/Samsung/GearVRf/pull/510 was merged. Can we close this now?
