### ISSUE TITLE
GVRScene.clear() removes the camera rig's scene objects

### ISSUE THREAD

**Issue by thomasflynn** [Samsung/GearVRf#511]
if you call clear() on the scene, it also removes all the scene objects that the camera rig sets up (headTransform, left, right, center, etc.).  So, if you clear the scene, you cannot attach anything to the camera rig ever again.

**Comment by danke-sra** [comment]
What's the suggested fix? Is it to keep scene objects in the camera rig?

**Comment by thomasflynn** [comment]
as a hack, i named the camera rig objects and during clear(), i skipped the objects with those names.  i gave them all a prefix so it was easy.  this is what i came up with given approx 2ms worth of thought.  better ideas would be appreciated.

**Comment by liaxim** [comment]
Tom, does the fix look good to you? Would you like to verify first or can we close the issue?
