### ISSUE TITLE
We need to convert to Android Studio the GDX plugin project

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#513]
Just a reminder

**Comment by ja3son** [comment]
con't ndk-build the project
../../../../../ovr_sdk_mobile/cflags.mk: No such file or directory.

**Comment by liaxim** [comment]
@ja3son If you are referring to building the framework or one of the samples, you need to make sure you have the Oculus Mobile SDK (1.0.0.0 or 1.0.0.1) installed inside your GearVRf directory. For example I have these at the same level:

GearVRf/
GearVRf-Demos/

And then I have the ovr_sdk_mobile directory under GearVRf/. You can also always modify ./GearVRf/GVRf/Framework/framework/src/main/jni/Application.mk and change the OVR_MOBILE_SDK defined in there.

**Comment by liaxim** [comment]
Fixed by https://github.com/Samsung/GearVRf/pull/526
