### ISSUE TITLE
Weird artifacts on SM-R322 with Galaxy S7

### ISSUE THREAD

**Issue by cemkod** [Samsung/GearVRf#516]
Hello,

I'm using the new Gear VR (SM-R322) with Galaxy S7 Phone. There are some pixels repeat artifacts on the edges of views, and viewport sizes seem to be different than the native sdk as can be seen in the image:
![gearvrf](https://cloud.githubusercontent.com/assets/4003996/14835588/232c0d74-0c13-11e6-960e-c886ee25c9c5.jpg)
Here is a screenshot from a software running with NDK:
![native](https://cloud.githubusercontent.com/assets/4003996/14835589/23314aaa-0c13-11e6-8e14-f2c359a70ce8.jpg)

I am using the standard [gvr.xml](https://github.com/gearvrf/GearVRf-Demos/blob/3e71ed8815ff157a24e6eec4f4af470a4ee55272/gvr-360photo/gvr360photo/src/main/assets/gvr.xml) file supplied in the samples. Is this happening because the lens distortion parameters do not match my device?

**Comment by liaxim** [comment]
Hi,
This was fixed by pull request https://github.com/Samsung/GearVRf/pull/506. We don't have a binary release yet that includes this fix but we will soon have one. If you can't wait you can always build and use the latest framework code. Let us know if you need any help.

**Comment by cemkod** [comment]
Thank you @liaxim 
I'll just wait. New binary will probably be ready until I'm ready to release what I'm developing.
