### ISSUE TITLE
Wrong ovr library path in install instructions

### ISSUE THREAD

**Issue by lassehe** [Samsung/GearVRf#518]
Building instructions
http://gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start tell to copy Oculus Mobile SDK libraries to  GVRf/Framework/libs/. This resulted built applications failing in startup because of missing class, at least when building with Eclipse.

Copying libraries to GVRf/Framework/framework/src/main/libs/ instead made it work.

**Comment by liaxim** [comment]
Thank you for catching this. We will have it fixed.

**Comment by thomasflynn** [comment]
Ok, I updated it.  Take a look now.  Is anything else off?  Thanks!

**Comment by liaxim** [comment]
@lassehe Can we close this now?

**Comment by lassehe** [comment]
Thank you. Yes, the documentation looks now correct. Path Framework/framework/ feels a bit redundant though, but I guess there is some reason for that.

**Comment by liaxim** [comment]
Agreed about the redundancy. The 'framework' is a gradle module under the project root 'Framework'. Make the root 'GVRf'? Any suggestions? Thanks.

**Comment by jason2kim** [comment]
Right, the second 'framework' is the module name. And, we have a few other items under 'GVRf' umbrella already. 
How about ‘GearVRf-Frameworks’? Any other suggestions?
