### ISSUE TITLE
Gray-ish rowboat in the javascript sample

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#524]
The rowboat always flashes light gray for few frames on startup. I think it is initially rendered by the Assimp shader and then switches over to a generated shader. Probably Assimp renders without having the textures loaded. Maybe the loaded models shouldn't even try to use the Assimp shader anymore.

**Comment by danke-sra** [comment]
This sample doesn't have a light in the scene. In this case, probably the default assimp shader should be used? I haven't carefully looked at the generated shaders but it should be transparent?

**Comment by liaxim** [comment]
The model starts off with the Assimp shader since the main scene is not known and thus the light list is not available. Once the shaders are generated, light or no light, materials switch to the generated shaders. Which is a good thing.

It is also another instance of the issue of when sceneObjects are completely ready for rendering and how the user can know that.

**Comment by liaxim** [comment]
Fixed by https://github.com/Samsung/GearVRf/pull/528
