### ISSUE TITLE
Bounding box not correctly updated after GVRMesh.setVertices() method.

### ISSUE THREAD

**Issue by vanduijnjordi** [Samsung/GearVRf#525]
I've written a simple piece of code that updates an object "origin" (similar to Blenders "Set origin to geometry" functionality). It works by calculating the average position of every vertex and translating the object origin to this point:
```Java
public static void setOriginToGeometryCentre(GVRSceneObject obj) {
    //get mesh
    GVRMesh mesh = obj.getRenderData().getMesh();   
    float[] verts = mesh.getVertices();
    
    //get bounding box
    GVRMesh bbMesh = mesh.getBoundingBox();
    float[] bbVerts = bbMesh.getVertices();
    
    //keep track of the average position
    float avgX = 0.0f;
    float avgY = 0.0f;
    float avgZ = 0.0f;
    
    //calculate average locations of the bounding box vertices
    for (int i = 0; i < bbVerts.length; i += 3) {            
        avgX += bbVerts[i];
        avgY += bbVerts[i+1];
        avgZ += bbVerts[i+2];
    }
    int numVerts = bbVerts.length/3;
    avgX /= numVerts;
    avgY /= numVerts;
    avgZ /= numVerts;
    
    //update vertex positions
    for (int i = 0; i < verts.length; i += 3) {            
        verts[i] -= avgX;
        verts[i+1] -= avgY;
        verts[i+2] -= avgZ;
    }        
    mesh.setVertices(verts);
    
    //update object location in the opposite direction to maintain vertex world position
    GVRTransform trans = obj.getTransform();     
    trans.setPosition(trans.getPositionX() + avgX, 
                      trans.getPositionY() + avgY, 
                      trans.getPositionZ() + avgZ);
    
    obj.getRenderData().setMesh(mesh.getBoundingBox());
}
```
However, the bounding box of the mesh is not updated properly: the upper bounds remain the same while the lower bounds are updated nicely. As there is no GVRMesh.setBoundingBox() method, I assume that the bounding box is calculated per step automatically.

I've tried updating the data of the bounding box by doing: mesh.getBoundingBox().setVertices(new_vertices), but it does nothing (because it updates itself, but it updates wrong)

Unless I've totally missed something, I'm thinking this must be a bug. If it's not, can someone help me to fix this problem?

Thanks so much in advance!

Kind regards,
Jordi van Duijn

**Comment by NolaDonato** [comment]
You are quite correct – this is a bug that needs fixing in GearVRf. The Mesh::getBoundingVolume function does not clear the bounds before recomputing. I will fix this ASAP.

-Nola

**Comment by liaxim** [comment]
Hi there. Nola made the fix. The pull request is https://github.com/Samsung/GearVRf/pull/532. Let us know how it works. Thanks.

**Comment by vanduijnjordi** [comment]
Thank you! Good luck and I’ll make sure to let you know about anything else I might find while developing for GearVRf ☺

Kind regards,
Jordi

**Comment by liaxim** [comment]
@vanduijnjordi Can we close this issue?

**Comment by vanduijnjordi** [comment]
Yes, thank you!
