### ISSUE TITLE
OESVerticalStereo shader does not work

### ISSUE THREAD

**Issue by xdestiny110** [Samsung/GearVRf#531]
Using OESVerticalStereo shader only render top half of the texture in left and right eye.

I think variable uniforms.u_right should be initialized correctly in renderer.cpp at line 793.

**Comment by liaxim** [comment]
Pull request https://github.com/Samsung/GearVRf/issues/531 should fix the issue. Let us know what you think. Thanks.

**Comment by xdestiny110** [comment]
The problem is solved.
