### ISSUE TITLE
How can I display a stereo image?

### ISSUE THREAD

**Issue by xdestiny110** [Samsung/GearVRf#535]
I want to display a stereo image on a GVRSphereObject, so I write this code: 

```
Future<GVRTexture> texture = gvrContext.loadFutureTexture(new GVRAndroidResource(gvrContext.getContext(), R.drawable.photosphere));
GVRSphereSceneObject sphereSceneObject = new GVRSphereSceneObject(gvrContext,false,texture);
sphereSceneObject.getRenderData().getMaterial().setShaderType(GVRMaterial.GVRShaderType.OESVerticalStereo.ID);
gvrContext.getMainScene().addSceneObject(sphereSceneObject);
```

But errors occurs. It says `error : OESVerticalStereoShader::render : texture with wrong target`. It means I should use GVRExternalTexture. But I want to load a texture from local disk instead of video stream. What should I do?

**Comment by gearvrf** [comment]
(answering from my phone)...use two spheres, get the renderdata, set the rendermask.   I think you can look at opacityanigallery as an example of that.

**Comment by xdestiny110** [comment]
Thank you for you answer. This is a good way to solve my question if I have left and right eyes image separately. In fact, my stereo image is similar to stereo movie. Top half of the image is left eye's image and bottom half is right eye's.
By the way, I think using two sphere is a little redundant.

**Comment by liaxim** [comment]
@xdestiny110 What happens if you try this?
```
sphereSceneObject.getRenderData().getMaterial().setShaderType(GVRMaterial.GVRShaderType.UnlitVerticalStereo.ID);
```

**Comment by xdestiny110** [comment]
That is work. Thank you for you response.
