### ISSUE TITLE
Delayed video

### ISSUE THREAD

**Issue by Arct1k** [Samsung/GearVRf#536]
Hi all .
i'm doing first steps with GVR.

after built first app with steps from online guide[http://www.gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide300BasicApp](url)

when start this app on mobile i see that video is delayed when head moving

**Comment by liaxim** [comment]
Hi, are you seeing this when docked into GearVR? What phone model are you using? Which version of Android? Thanks.

**Comment by Arct1k** [comment]
Hi. Thx for you response. 
Yes , problem when attach to GearVR , phone is s6.Android 6

**Comment by liaxim** [comment]
Any chance you might share the logcat output?

**Comment by liaxim** [comment]
How do some of the samples we have work for you? See https://github.com/gearvrf/GearVRf-Demos

**Comment by liaxim** [comment]
@Arct1k Still having issues? Do you have more answers for us? Thanks.

**Comment by liaxim** [comment]
Assuming it is all good. Will close the issue if you don't mind.

**Comment by Arct1k** [comment]
Yes , was HW problem.(with any phone all ok)
