### ISSUE TITLE
Cannot build with lint turned on

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#539]
To recreate just turn on lint for a sample application and try to run it. 

Below is a link describing the steps to turn on lint in studio:

http://stackoverflow.com/a/27068675

The problem is with unused classes in the js.jar file:

`../intermediates/exploded-aar/gvr-renderableview/framework/unspecified/jars/libs/js.jar: Invalid package reference in library; not included in Android: java.awt.event. Referenced from org.mozilla.javascript.tools.debugger.ContextWindow.`

**Comment by rahul27** [comment]
@danke-sra opened this issue to track the lint build problems.

**Comment by rahul27** [comment]
@danke-sra manually deleting the unused packages from the jar file worked for me. Do you have a better solution?

**Comment by danke-sra** [comment]
I thought the warning could be suppressed from lint configuration file (xml?). Do you mean you've manually edited js.jar to fix the problem, or removed js.jar itself? If 'js.jar' has to be manually removed to suppress the warning, it's probably not the best. I found a way to suppress this specific warning in lint. If needed, I will check it.

**Comment by rahul27** [comment]
Edited js.jar to fix the problem.

If we choose to go with lint.xml, then only providing one in the framework would not suffice. We would need to create one per sample project, which may not be desirable:

https://code.google.com/p/android/issues/detail?id=68808#c7

**Comment by danke-sra** [comment]
@rahul27 Can you please make a pull request for the updated js.jar? This seems to be the ideal solution.

**Comment by liaxim** [comment]
@rahul27 Can we close this issue now?

**Comment by rahul27** [comment]
Yup.
