### ISSUE TITLE
Issue with GVRSphereSceneObject.

### ISSUE THREAD

**Issue by chenchao1407** [Samsung/GearVRf#55]
I just merged the pull request #48 for not stopping our progress on other stuffs. But actually as you may see in the sample app provided by #48 . The texture content is somehow distorted in a wrong way.

**Comment by rongguodong** [comment]
Can you check whether this issue is fixed with my change #68?

**Comment by thomasflynn** [comment]
This should be fixed now.  Let me know if it isnt

**Comment by liaxim** [comment]
Planning to close this in few days. I am not aware of recent problems with GVRSphereSceneObject.
