### ISSUE TITLE
Framework uses incorrect toolchain for Android Studio (4.8 instead of 4.9)

### ISSUE THREAD

**Issue by stephen-kruger** [Samsung/GearVRf#551]
Android Studio with latest NDK installed (Version 12).

The build tools use the location
........android-sdk-windows\ndk-bundle\toolchains\arm-linux-androideabi-4.9

But current code head version of GearVRf, is trying to build Framework project using 4.8 : 
Get error : 
`process_begin: CreateProcess(NULL, C:/Tools/android-sdk-windows/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.8/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++ -MMD -MP -MF ./obj/local/armeabi-v7a/objs/gvrf/engine/picker/picker_jni.o.d -fno-exceptions -fno-rtti -IC:\Tools\GearVrSDK\ovr_sdk_mobile/VrAppFramework/Src -IC:\Tools\GearVrSDK\ovr_sdk_mobile/LibOVRKernel/Include -IC:\Tools\GearVrSDK\ovr_sdk_mobile/LibOVRKernel/Src -IC:\Tools\GearVrSDK\ovr_sdk_mobile/VrApi/Include -IC:\Tools\GearVrSDK\ovr_sdk_mobile/VrAppSupport/Src -IC:\Tools\GearVrSDK\ovr_sdk_mobile/VrAppSupport/SystemUtils/Include -Ijni/contrib/assimp -Ijni/contrib/assimp/include -Ijni/contrib/assimp/include/Compiler -Ijni/contrib/jassimp2 -Ijni/contrib -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppSupport/SystemUtils/Projects/AndroidPrebuilt/jni/../../../../LibOVRKernel/Src -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppSupport/SystemUtils/Projects/AndroidPrebuilt/jni/../../../../VrApi/Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppSupport/SystemUtils/Projects/AndroidPrebuilt/jni/../../../Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppSupport/VrModel/Projects/AndroidPrebuilt/jni/../../../Src -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppFramework/Projects/AndroidPrebuilt/jni/../../../../LibOVRKernel/Src -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppFramework/Projects/AndroidPrebuilt/jni/../../../../VrApi/Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppFramework/Projects/AndroidPrebuilt/jni/../../../../VrAppSupport/SystemUtils/Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppFramework/Projects/AndroidPrebuilt/jni/../../../Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/LibOVRKernel/Projects/AndroidPrebuilt/jni/../../../Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/LibOVRKernel/Projects/AndroidPrebuilt/jni/../../../Src -IC:/Tools/android-sdk-windows/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.9/include -IC:/Tools/android-sdk-windows/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -IC:/Tools/android-sdk-windows/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.9/include/backward -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrApi/Projects/AndroidPrebuilt/jni/../../../Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/3rdParty/minizip/build/androidprebuilt/jni/../../../src -IC:/Tools/GearVrSDK/ovr_sdk_mobile/3rdParty/stb/build/androidprebuilt/jni/../../../src -IC:/Tools/GearVrSDK/ovr_sdk_mobile/1stParty/OpenGL_Loader/Projects/Android/jni/../../../Include -Ijni -DANDROID -Wattributes -Wa,--noexecstack -Wformat -Werror=format-security -Wno-type-limits -Wno-invalid-offsetof -std=c++11 -std=c++11 -D__GXX_EXPERIMENTAL_CXX0X__ -fexceptions -isystem C:/Tools/android-sdk-windows/ndk-bundle/build//../platforms/android-19/arch-arm/usr/include -c jni/engine/picker/picker_jni.cpp -o ./obj/local/armeabi-v7a/objs/gvrf/engine/picker/picker_jni.o, ...) failed.

make: *** [obj/local/armeabi-v7a/objs/gvrf/engine/picker/picker_jni.o] Error 2
process_begin: CreateProcess(NULL, C:/Tools/android-sdk-windows/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.8/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++ -MMD -MP -MF ./obj/local/armeabi-v7a/objs/gvrf/engine/renderer/renderer.o.d -fno-exceptions -fno-rtti -IC:\Tools\GearVrSDK\ovr_sdk_mobile/VrAppFramework/Src -IC:\Tools\GearVrSDK\ovr_sdk_mobile/LibOVRKernel/Include -IC:\Tools\GearVrSDK\ovr_sdk_mobile/LibOVRKernel/Src -IC:\Tools\GearVrSDK\ovr_sdk_mobile/VrApi/Include -IC:\Tools\GearVrSDK\ovr_sdk_mobile/VrAppSupport/Src -IC:\Tools\GearVrSDK\ovr_sdk_mobile/VrAppSupport/SystemUtils/Include -Ijni/contrib/assimp -Ijni/contrib/assimp/include -Ijni/contrib/assimp/include/Compiler -Ijni/contrib/jassimp2 -Ijni/contrib -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppSupport/SystemUtils/Projects/AndroidPrebuilt/jni/../../../../LibOVRKernel/Src -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppSupport/SystemUtils/Projects/AndroidPrebuilt/jni/../../../../VrApi/Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppSupport/SystemUtils/Projects/AndroidPrebuilt/jni/../../../Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppSupport/VrModel/Projects/AndroidPrebuilt/jni/../../../Src -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppFramework/Projects/AndroidPrebuilt/jni/../../../../LibOVRKernel/Src -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppFramework/Projects/AndroidPrebuilt/jni/../../../../VrApi/Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppFramework/Projects/AndroidPrebuilt/jni/../../../../VrAppSupport/SystemUtils/Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrAppFramework/Projects/AndroidPrebuilt/jni/../../../Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/LibOVRKernel/Projects/AndroidPrebuilt/jni/../../../Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/LibOVRKernel/Projects/AndroidPrebuilt/jni/../../../Src -IC:/Tools/android-sdk-windows/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.9/include -IC:/Tools/android-sdk-windows/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -IC:/Tools/android-sdk-windows/ndk-bundle/build//../sources/cxx-stl/gnu-libstdc++/4.9/include/backward -IC:/Tools/GearVrSDK/ovr_sdk_mobile/VrApi/Projects/AndroidPrebuilt/jni/../../../Include -IC:/Tools/GearVrSDK/ovr_sdk_mobile/3rdParty/minizip/build/androidprebuilt/jni/../../../src -IC:/Tools/GearVrSDK/ovr_sdk_mobile/3rdParty/stb/build/androidprebuilt/jni/../../../src -IC:/Tools/GearVrSDK/ovr_sdk_mobile/1stParty/OpenGL_Loader/Projects/Android/jni/../../../Include -Ijni -DANDROID -Wattributes -Wa,--noexecstack -Wformat -Werror=format-security -Wno-type-limits -Wno-invalid-offsetof -std=c++11 -std=c++11 -D__GXX_EXPERIMENTAL_CXX0X__ -fexceptions -isystem C:/Tools/android-sdk-windows/ndk-bundle/build//../platforms/android-19/arch-arm/usr/include -c jni/engine/renderer/renderer.cpp -o ./obj/local/armeabi-v7a/objs/gvrf/engine/renderer/renderer.o, ...) failed.

make: *** [obj/local/armeabi-v7a/objs/gvrf/engine/renderer/renderer.o] Error 2

make: Leaving directory `C:/Tools/GearVrSDK/GearVRf/GVRf/Framework/framework/src/main'
:framework:buildNative FAILED
`

**Comment by liaxim** [comment]
Yes.. kind of known issue. Please update ./GVRf/Framework/framework/src/main/jni/Application.mk to specify 4.9 for NDK_TOOLCHAIN_VERSION. I guess it is time to make the change.

**Comment by stephen-kruger** [comment]
Thanks, I was adding that prop in the wrong .mk file.
I think the change required might be a bit bigger than that though - there are a bunch of compilation errors now : 

`[armeabi-v7a] Compile++ arm  : gvrf <= mesh.cpp
Information:(Unknown) In file included
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex children_mutex_;
          ^
jni/objects/scene_object.h: In member function 'std::vector<gvr::SceneObject*> gvr::SceneObject::children()':
Error:error: 'mutex' is not a member of 'std'
         std::lock_guard < std::mutex > lock(children_mutex_);
                           ^
Error:error: 'mutex' is not a member of 'std'
Error:error: template argument 1 is invalid
         std::lock_guard < std::mutex > lock(children_mutex_);
                                      ^
Error:error: invalid type in declaration before '(' token
         std::lock_guard < std::mutex > lock(children_mutex_);
                                            ^
Error:error: 'children_mutex_' was not declared in this scope
         std::lock_guard < std::mutex > lock(children_mutex_);
                                             ^
[armeabi-v7a] Compile++ arm  : gvrf <= mesh_eye_pointee_jni.cpp
[armeabi-v7a] Compile++ arm  : gvrf <= mesh_eye_pointee.cpp
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex children_mutex_;
          ^
jni/objects/scene_object.h: In member function 'std::vector<gvr::SceneObject*> gvr::SceneObject::children()':
Error:error: 'mutex' is not a member of 'std'
         std::lock_guard < std::mutex > lock(children_mutex_);
                           ^
Error:error: 'mutex' is not a member of 'std'
Error:error: template argument 1 is invalid
         std::lock_guard < std::mutex > lock(children_mutex_);
                                      ^
Error:error: invalid type in declaration before '(' token
         std::lock_guard < std::mutex > lock(children_mutex_);
                                            ^
Error:error: 'children_mutex_' was not declared in this scope
         std::lock_guard < std::mutex > lock(children_mutex_);
                                             ^
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex children_mutex_;
          ^
jni/objects/scene_object.h: In member function 'std::vector<gvr::SceneObject*> gvr::SceneObject::children()':
Error:error: 'mutex' is not a member of 'std'
         std::lock_guard < std::mutex > lock(children_mutex_);
                           ^
Error:error: 'mutex' is not a member of 'std'
Error:error: template argument 1 is invalid
         std::lock_guard < std::mutex > lock(children_mutex_);
                                      ^
Error:error: invalid type in declaration before '(' token
         std::lock_guard < std::mutex > lock(children_mutex_);
                                            ^
Error:error: 'children_mutex_' was not declared in this scope
         std::lock_guard < std::mutex > lock(children_mutex_);
                                             ^
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex children_mutex_;
          ^
jni/objects/scene_object.h: In member function 'std::vector<gvr::SceneObject*> gvr::SceneObject::children()':
Error:error: 'mutex' is not a member of 'std'
         std::lock_guard < std::mutex > lock(children_mutex_);
                           ^
Error:error: 'mutex' is not a member of 'std'
Error:error: template argument 1 is invalid
         std::lock_guard < std::mutex > lock(children_mutex_);
                                      ^
Error:error: invalid type in declaration before '(' token
         std::lock_guard < std::mutex > lock(children_mutex_);
                                            ^
Error:error: 'children_mutex_' was not declared in this scope
         std::lock_guard < std::mutex > lock(children_mutex_);
                                             ^
[armeabi-v7a] Compile++ arm  : gvrf <= mesh_jni.cpp
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex children_mutex_;
          ^
jni/objects/scene_object.h: In member function 'std::vector<gvr::SceneObject*> gvr::SceneObject::children()':
Error:error: 'mutex' is not a member of 'std'
         std::lock_guard < std::mutex > lock(children_mutex_);
                           ^
Error:error: 'mutex' is not a member of 'std'
Error:error: template argument 1 is invalid
         std::lock_guard < std::mutex > lock(children_mutex_);
                                      ^
Error:error: invalid type in declaration before '(' token
         std::lock_guard < std::mutex > lock(children_mutex_);
                                            ^
Error:error: 'children_mutex_' was not declared in this scope
         std::lock_guard < std::mutex > lock(children_mutex_);
                                             ^
make: *** [obj/local/armeabi-v7a/objs/gvrf/engine/importer/assimp_importer_jni.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [obj/local/armeabi-v7a/objs/gvrf/engine/importer/jassimp_jni.o] Error 1
make: *** [obj/local/armeabi-v7a/objs/gvrf/engine/importer/importer_jni.o] Error 1
make: *** [obj/local/armeabi-v7a/objs/gvrf/engine/importer/importer.o] Error 1
make: *** [obj/local/armeabi-v7a/objs/gvrf/engine/importer/assimp_importer.o] Error 1
Information:(Unknown) In file included
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex children_mutex_;
          ^
jni/objects/scene_object.h: In member function 'std::vector<gvr::SceneObject*> gvr::SceneObject::children()':
Error:error: 'mutex' is not a member of 'std'
         std::lock_guard < std::mutex > lock(children_mutex_);
                           ^
Error:error: 'mutex' is not a member of 'std'
Error:error: template argument 1 is invalid
         std::lock_guard < std::mutex > lock(children_mutex_);
                                      ^
Error:error: invalid type in declaration before '(' token
         std::lock_guard < std::mutex > lock(children_mutex_);
                                            ^
Error:error: 'children_mutex_' was not declared in this scope
         std::lock_guard < std::mutex > lock(children_mutex_);
                                             ^
Information:(Unknown) In file included
jni/shaders/material/custom_shader.h: At global scope:
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex textureVariablesLock_;
          ^
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex attributeVariablesLock_;
          ^
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex uniformVariablesLock_;
          ^
Information:(Unknown) In file included
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex children_mutex_;
          ^
jni/objects/scene_object.h: In member function 'std::vector<gvr::SceneObject*> gvr::SceneObject::children()':
Error:error: 'mutex' is not a member of 'std'
         std::lock_guard < std::mutex > lock(children_mutex_);
                           ^
Error:error: 'mutex' is not a member of 'std'
Error:error: template argument 1 is invalid
         std::lock_guard < std::mutex > lock(children_mutex_);
                                      ^
Error:error: invalid type in declaration before '(' token
         std::lock_guard < std::mutex > lock(children_mutex_);
                                            ^
Error:error: 'children_mutex_' was not declared in this scope
         std::lock_guard < std::mutex > lock(children_mutex_);
                                             ^
jni/shaders/material/custom_shader.h: At global scope:
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex textureVariablesLock_;
          ^
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex attributeVariablesLock_;
          ^
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex uniformVariablesLock_;
          ^
Information:(Unknown) In file included
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex children_mutex_;
          ^
jni/objects/scene_object.h: In member function 'std::vector<gvr::SceneObject*> gvr::SceneObject::children()':
Error:error: 'mutex' is not a member of 'std'
         std::lock_guard < std::mutex > lock(children_mutex_);
                           ^
Error:error: 'mutex' is not a member of 'std'
Error:error: template argument 1 is invalid
         std::lock_guard < std::mutex > lock(children_mutex_);
                                      ^
Error:error: invalid type in declaration before '(' token
         std::lock_guard < std::mutex > lock(children_mutex_);
                                            ^
Error:error: 'children_mutex_' was not declared in this scope
         std::lock_guard < std::mutex > lock(children_mutex_);
                                             ^
jni/shaders/material/custom_shader.h: At global scope:
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex textureVariablesLock_;
          ^
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex attributeVariablesLock_;
          ^
Error:error: 'mutex' in namespace 'std' does not name a type
     std::mutex uniformVariablesLock_;
          ^
make: *** [obj/local/armeabi-v7a/objs/gvrf/engine/picker/picker.o] Error 1`

**Comment by liaxim** [comment]
Ok, looks like you are using a very very recent NDK (r12 beta). There is a problem with it we don't have a solution for yet. Please use http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip instead.

**Comment by liaxim** [comment]
Verified with the latest NDK, gvrf builds fine now. Whatever the problem was, it has already been fixed in the latest NDK.

Contents of my NDK's source.properties:
```
Pkg.Desc = Android NDK
Pkg.Revision = 12.0.2867246-beta2
```

@stephen-kruger Can we close the issue?

**Comment by stephen-kruger** [comment]
You can close the issue now - thanks
