### ISSUE TITLE
Samsung Galaxy S7?

### ISSUE THREAD

**Issue by arianaa30** [Samsung/GearVRf#559]
Hi,
Does the GearVRf work on Samsung Galaxy S7? Because GearVR is already shipped with a S7, not 6!

On the documentation of GearVR (http://wiki.gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start), here are the it says Note 4 or S6. I'm not sure if that is the _minimum_ requirements though.

**Comment by thomasflynn** [comment]
it works on S7.  We're in the midst of updating our Docs.  We'll make sure that gets updated as well.  Sorry for the confusion.

**Comment by arianaa30** [comment]
One general question about the framework: Can we play around video streaming/networking and quality metrics on the level on this framework? Or the framework is too high level for that?

**Comment by thomasflynn** [comment]
We have a few examples that use the Android MediaPlayer (https://developer.android.com/reference/android/media/MediaPlayer.html).  If that meets your needs, then you should be good to go.  If you have your own video player, it might be possible to use that as well (just modify/subclass GVRVideoSceneObject), we just need to use the associated SurfaceTexture.

**Comment by arianaa30** [comment]
Following on the installation documentation being outdated:
"Do not install CDT version higher than 8.0.2 Eclipse plugin": Is it still valid? I installed the latest version (8.8) as suggested by Eclipse Mars 2.

**Comment by thomasflynn** [comment]
That warning is referring to what will happen if you modify any of the .cpp files in framework/src/main/jni/.  if you're not modifying those files, then everything should build fine, even with the latest version.

**Comment by liaxim** [comment]
@arianaa30 Can we close this issue?

**Comment by arianaa30** [comment]
This one yes. Go ahead.

**Comment by freshindee** [comment]
I added GVRVideoScene to app, when I debug it seems video starting ,but at the final step it crash the app
Means when I try to add it to scene.
 mScene.addSceneObject( video );

Any help
Indika

**Comment by liaxim** [comment]
@freshindee Hi. Would you mind sharing the logcat output with us? Does you app run without creating and adding the GVRVideoSceneObject? You might want to open a separate issue so we don't lose track of this.

**Comment by freshindee** [comment]
Actually thing was by mistake I had off Open GL feature of the device. I switch on it. Problem solved.

Thanks.
