### ISSUE TITLE
loadModel() does not work when called inside onStep()

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#566]
Here is a modified sample that recreates the issue:

https://github.com/rahul27/GearVRf-Demos/commit/ccaa9ada6e739d592267a78923d04b71e07a8f34

**Comment by danke-sra** [comment]
Do you think you can use a background thread to run loadModel()? It could make rendering laggy when run from onStep(). If it throws an exception, we can fix it. What's the error you got?

**Comment by rahul27** [comment]
I don't see any exceptions running it on a background thread.

**Comment by NolaDonato** [comment]
I don't understand the logic behind running the animations before the model is loaded. mAssimpAnimations will be null until loadModel returns. If that run() function executes before that it will crash with a nullPointerException.

**Comment by NolaDonato** [comment]
I rearranged the logic slightly and loadModel seems to work from with onStep if you don't call getNextMainScene from there. If you initialize the scene first and just load the model in the background it seems to work. This is what I did:
    public void onInit(GVRContext gvrContext) {
        mGVRContext = gvrContext;
        mScene = gvrContext.getNextMainScene();
        mAnimationEngine = gvrContext.getAnimationEngine();
    }
    public void onStep() {
        if (mCharacter == null) {
            initialize(mGVRContext);
        }
    }    
    private void initialize(GVRContext context) {
        try {
            mCharacter = context.getAssetLoader().loadModel(mModelPath, GVRResourceVolume.VolumeType.ANDROID_ASSETS, mScene);
            mCharacter.getTransform().setPosition(0.0f, -10.0f, -10.0f);
            mCharacter.getTransform().setRotationByAxis(90.0f, 1.0f, 0.0f, 0.0f);
            mCharacter.getTransform().setRotationByAxis(40.0f, 0.0f, 1.0f, 0.0f);
            mCharacter.getTransform().setScale(1.5f, 1.5f, 1.5f);
            mAssimpAnimation = mCharacter.getAnimations().get(0);
            mAssimpAnimation.setRepeatMode(GVRRepeatMode.REPEATED).setRepeatCount(-1);
            mAssimpAnimation.start(mAnimationEngine);
        } catch (IOException e) {
            e.printStackTrace();
            mActivity.finish();
            mActivity = null;
            Log.e(TAG, "One or more assets could not be loaded.");
        }        
    }

**Comment by rahul27** [comment]
This issue has been resolved. Closing it.
