### ISSUE TITLE
Can't get hardware acceleration on WebView

### ISSUE THREAD

**Issue by aagocs** [Samsung/GearVRf#568]
Tried with custom & demo project, the hardware acceleration is disabled on the WebView.

**Comment by mkeblx** [comment]
What is your indication that hardware acceleration is disabled, and what are you trying to enable?
I have mActivity.getWebView().isHardwareAccelerated() returning true.
https://github.com/gearvrf/GearVRf-Demos/blob/master/gvr-renderableview/gvrrenderableview/src/main/java/org/gearvrf/renderableview/MainScript.java

**Comment by aagocs** [comment]
If I log it from the MainScript ctr it returns true indeed. Still getting transparent placeholder instead of WebGL content in the WebView. Any idea?

**Comment by mkeblx** [comment]
I've attempted to get WebGL to work on a WebView surface previously without luck, and I'm not sure possible with APIs exposed. But I will investigate further.

**Comment by liaxim** [comment]
WebGL support in a WebView seems to have a lot caveats based on my quick search. @aagocs Does WebGL work in your WebView in non-VR apps? If it doesn't work there too then I am afraid this has nothing to do with GVRF.

**Comment by liaxim** [comment]
@aagocs Do you still think there is an issue with GVRF? If not, can we close this issue? Thanks

**Comment by mkeblx** [comment]
It's not GVRf specific, but relates to broader usage of drawing WebGL in a locked canvas bound to Surface.

**Comment by liaxim** [comment]
Planning to close tomorrow then. Thank you.
