### ISSUE TITLE
Configure Frustum

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#570]
I am trying to configure the frustum or field but I can't find any hint in the documentation.
Is there a correct way to change the visible part of the scene dynamically (zooming in and out)?

**Comment by thomasflynn** [comment]
I'm not sure you really want to do that in VR.  Not sure things would end up looking right.  I would think the field of view needs to match your actual field of view.  But you can try and let us know :)  The way you can do that is to retrieve the left and right cameras from the camera rig, cast them to GVRPerspectiveCamera, and call setFovY().

**Comment by QKnows** [comment]
Thank you for your fast reply, it worked perfect and looks awesome... thank you very much...
