### ISSUE TITLE
Blackscreen when using GVRVideoType.VERTICAL_STEREO

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#574]
I am using the gvr-360video demo to test Vertical stereo videos, it worked fine a couple of weeks ago. Since recent updates the screen is black, no video can be watched. When I switch the VideoType to GVRVideoType.HORIZONTAL_STEREO or GVRVideoType.MONO everything works fine.

**Comment by thomasflynn** [comment]
Well, I can confirm the problem.  The shaders themselves looks fine.  I suspect some plumbing in between got disconnected.  @NolaDonato knows that plumbing well.  She'll help you out.

**Comment by NolaDonato** [comment]
I have figured out what the problem is and have prepared a patch to fix it. A line of code was missing in the OESHorizontalShader.cpp file.

**Comment by thomasflynn** [comment]
you mean OESVerticalShader.cpp?

**Comment by NolaDonato** [comment]
Yeah, I changed the vertical one.

**Comment by thomasflynn** [comment]
Nola's fix is merged.  please retest.  thanks.

**Comment by QKnows** [comment]
Thanks for your really fast fix - I can confirm that VERTICAL_STEREO works fine again for me.
