### ISSUE TITLE
Initial Set-up Help: Missing assets, Error "Cannot be Resolved"

### ISSUE THREAD

**Issue by EdmundoAn** [Samsung/GearVRf#588]
I have only just installed all the necessary everything meticulously and I am trying to load the sample applications, but Eclipse tells me that there are unresolved errors which don't allow me to build them.

Screenshot attached!

Where can I find these missing assets?

Thanks in advance,

E

<img width="1440" alt="screenshot 2016-05-27 23 20 00" src="https://cloud.githubusercontent.com/assets/19616110/15622535/90fd70e8-2461-11e6-9c5b-47eb50a53de0.png">

<img width="1440" alt="screenshot 2016-05-28 18 13 22" src="https://cloud.githubusercontent.com/assets/19616110/15628714/f8de158e-24ff-11e6-9c19-f30523cd958d.png">

**Comment by DalstonDiggity** [comment]
I'm new as well and I am getting the same error! very frustrating. Attached are screenshots of mine. 

Please help!

![capture1](https://cloud.githubusercontent.com/assets/19628073/15630175/e3fef472-2526-11e6-8e46-47b9a1508fb1.PNG)
![capture2](https://cloud.githubusercontent.com/assets/19628073/15630174/e3fe097c-2526-11e6-98e8-db5e0b4d89b2.PNG)

**Comment by gearvrf** [comment]
Off-hand, it looks like you havent imported and built the Framework itself.  Follow the instructions for cloning, importing, and building the framework.  If you do have it built, then maybe it is in the wrong directory relative to the demos?  when cloning, we typically do the following:
mkdir gearvrf
cd gearvrf
git clone https://github.com/Samsung/GearVRf.git
git clone https://github.com/gearvrf/GearVRf-Demos.git

**Comment by Nathipha** [comment]
I get errors like that directly after starting Eclipse too but it resolves it by itself after building everything.

This is how I made it work:
- Import the framework in Eclipse and build it
- Copy the 3 files, plus the "armeabi-v7a" folder with the extra file from the Oculus SDK into the framework's "libs" folder
- Clean and build it
- Import one of the samples
- Copy the Oculus key into the sample's "asset" folder
- Clean and built it --> error because it's not linked to the framework
- Add the framework (in Eclipse: Properties - Android - Library) & apply
- Clean and build again

Same thing for starting your own project.
Also, something I heard in a video about setting it up (so not sure if it's important): Rename the GearVR directory to "GearVRf" (instead of "GearVRf-master").

**Comment by thomasflynn** [comment]
I wouldn't think cleaning would be necessary so many times.  I would expect the steps to be:
- import framework
- copy the oculus files
- clean and build framework
- import sample
- copy signature file
- add the framework if it isn't already there (though, it should be)
- clean and build.

let us know what ends up working for you and we'll adjust the build instructions.

**Comment by EdmundoAn** [comment]
Hello everyone!

Firtstly, thank you very much for your responses. I am going to write the exact steps I followed to solve these errors, as there may well be other newbies that might find these very helpful :) 

(sorry to any experts in advance... my little tutorial is going to seem incredibly redundant to you all)

The comment 'gearvrf' made was crucial. To make this work, you must download the files through github.com from the your cmd/terminal. Downloading the ZIP file and manually placing it in the folder where you are gathering all your development files will not work.

I was using OSX in my first attempt, but then switched to windows so this steps are for Windows users. I hope they help OSX users too! Here:

1- Install git. You will need it to clone the file from github. Link: https://git-scm.com/downloads
2- Launch CMD.exe

(The two commands 'gearvrf' was making reference to where: 'cd' & 'mkdir'. 'cd' stands for 'change directory'. 'mkdir' stands for 'make directory')

(In my case I was placing all my file into a folder called 'dev' inside my C drive)

3- Type: 'c:' + ENTER to go into your C: drive
4- In my case I typed: 'cd \dev' + ENTER to change the commands directory to my 'dev' folder
5- Type 'git clone https://github.com/Samsung/GearVRf.git' +ENTER to make git start cloning the files to your directory.

I hope this helps! Maybe I over-read the part of installing 'git' on the 'getting started' instructions, but I don't remember reading it. 

All the best,

E

**Comment by EdmundoAn** [comment]
Hey, I am running into another problem... I suppose it is related. Screenshot attached.

The error is that it can't fing the file cflags.mk, but I have checked in the ovr_sdk_mobile folder and it is there. The folder is a clean copy unzipped from the oculus development centre.

On the note, and relating to Nathipha's and ThomassFlynn comment, when I go to 'Project-Properties-Android-Library', this section is absolutely empty (i.e. the framework isnt loaded there). When I click add, I am presented with no options to add it. Screenshot attached as well.

Please help! I'd love to get this working to start playing with it.

Best,

E

<img width="1440" alt="screenshot 2016-06-01 20 40 58" src="https://cloud.githubusercontent.com/assets/19616110/15723469/7045e114-283a-11e6-8bb1-383835a2957b.png">

<img width="1440" alt="screenshot 2016-06-01 20 57 00" src="https://cloud.githubusercontent.com/assets/19616110/15723668/6bab67f4-283b-11e6-918f-0f885dddfec5.png">

**Comment by NolaDonato** [comment]
Relative paths are used in some of the makefiles. This means that GearVRf and GearVRf-Demos have to be at the same level. The ovr_mobile_sdk directory has to be under GearVRf. Check to see that it is in the right place.

**Comment by Nathipha** [comment]
I never used Github to get the latest version but downloaded the zip file but it still worked/works just fine.
I had the same problem ("No such file") at first too. Like @NolaDonato said, you have to pay really close attention to the order structure.
Usually Eclipse doesn't care about whitespaces (so you can install it in C:/Program Files without problems) but NDK does, so does the Framework.

This is how it looks for me:
-GearVR
--GearVRf
---Extensions
---Framework
----assets, bin,...
---Samples
----VRHackathons
--ovr_sdk_mobile

Plus, for me the framework, the NDK and my own project have to be on the same HDD, otherwise I'll get another nasty error that specific files can't be found.

**Comment by EdmundoAn** [comment]
@NolaDonato , thank you very much. It now works!!! 

I guess this needs to be clearer for newbies as well... so any newbies, please follow:

When you clone the master folder from GitHub, there is two GearVRf folders. One inside the other. Whereas the GearVRf-Demos needs to be at the same level as the first GearVRf folder, the ovr_mobile_sdk folder needs to be inside the first one and at the same level as the other one. So:

- My GearVRf master file clone is in: :C/dev/
- My GearVRf-Demos file clone is in: :C/dev/
- My ovr_mobile_sdk unzipped folder is in: :C/dev/GearVRf

👍 

In regards to @Nathipha & @thomasflynn remark, I only had to build my framework once (i.e. followed @thomasflynn steps)

Thank you to everybody!

**Comment by liaxim** [comment]
Glad to hear your problem is fixed. Can we close the issue now?

Btw, you can define a path variable in Android Studio that points to your ovr_mobile_sdk, wherever it is; see https://github.com/Samsung/GearVRf/wiki/Android%20Studio%20Tips

**Comment by NolaDonato** [comment]
I made this mistake my first week at Samsung ☺

**Comment by EdmundoAn** [comment]
Yes @liaxim , let's close it. Thanks to everyone again!

I am going to add to the title "Initial Set-up Help" so that other new users can easily find all this valuable info :)

E
