### ISSUE TITLE
Issue with GVRBitmapTexture.update()

### ISSUE THREAD

**Issue by chenchao1407** [Samsung/GearVRf#60]
Right now, the GVRBitmapTexture.update() only works on VrThread. It means, if you want to trigger the update() with your input event or any other thread, the update() doesn't work.

We may find a way to fix it or somehow do a workaround like hold the most recent update until next onDrawEyeView get triggered.

**Comment by JonShemitz** [comment]
It's a GL operation - of course it has to run on the GL thread.
