### ISSUE TITLE
key events from bluetooth keyboard go to the view manager before the activity

### ISSUE THREAD

**Issue by imuli** [Samsung/GearVRf#604]
aad20ba20ed9e2ee6e90d12e45bba7d4180de844 removed the whole `onKeyEventNative` path added by #116. In any case, `onKeyDown` doesn't receive events from a keyboard, only the back button on the headset.

**Comment by liaxim** [comment]
@imuli Thank you for letting us know. Could you please supply a bit more details? Maybe a sample program that shows the problem you are experiencing? The onKeyEventNative was obsoleted by that change. We have used bt keyboards successfully - for example gvr-remote-scripting works.

**Comment by imuli** [comment]
Yes, I saw that as I dug in a little.

The specific problem I encountered was that adding

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event){
        Log.v("keylog", String.format("%d", keyCode));
        return true;
    }

to my activity, only logged the keypresses on the headset, as was the case in #74.

Catching events by overriding ´dispatchKeyEvent´ to invoke the appropriate handler first fixed this, and I have a patch written - I just need to verify that a key event  with ´ACTION_MULTIPLE´ and ´KEYCODE_UNKNOWN´ invokes ´onKeyDown´ rather than something else.

**Comment by liaxim** [comment]
Tried on an S7 with SMK-LINK BT keyboard. I do get the onKeyDown/onKeyUp events while the phone is docked. What is the phone that you use? Android version? Which BT keyboard do you use? Can you share a sample project that doesn't work for you? Thanks.

**Comment by imuli** [comment]
Add a view scene object that consumes keystrokes. Or try with the renderable demo.

**Comment by imuli** [comment]
So I've changed the name to reflect what my actual problem is, and I hope that communicates it better.

The current implementation calls the the view manager first, and then Activity's dispatchKeyEvent. I don't think the opposite order quite makes sense either - I don't think sending key events to the action bar or the window make sense. So pulling out the part that eventually sends the key event to the activity yields and putting *that* first yields something like this:

     @Override
     public boolean dispatchKeyEvent(KeyEvent event) {
        View decor = getWindow().getDecorView();
        boolean handled = event.dispatch(this, decor == null ? null : decor.getKeyDispatcherState(), this);
         if (handled == false) {
            handled = mViewManager.dispatchKeyEvent(event);
         }
         return handled;
     }

[Example that fails.](https://github.com/imuli/GearVRf-Demos/blob/9ca6f36c8e7b95b96cf3bb37190e2e8fc5f44948/gvr-renderableview/gvrrenderableview/src/main/java/org/gearvrf/renderableview/MainActivity.java)

**Comment by liaxim** [comment]
I see. The proposed patch does work. I think we would like to have the viewManager have a first go at the event (@rahul27 ?). How about that order? @imuli Would you like to open a pull request?

**Comment by rahul27** [comment]
We allow the IO framework to have a first crack at intercepting the KeyEvent using the viewManager. If the keyevent goes un handled then we pass it on to the VR activity. 

For. eg you may want to override the volume up/down buttons on the GearVR headset. 

As long as this change does not break that model it should be fine.

**Comment by imuli** [comment]
It sounds like the intended behavior is the opposite of what I expected. Closing this then. Is there a document that outlines how the framework is meant to be used - along the lines of the android developer's guide?

**Comment by liaxim** [comment]
We don't have anything as comprehensive yet. We have http://gearvrf.org/bin/view/GearVRfDeveloperGuide/WebHome though. Input handling is kind of under development still.

**Comment by rahul27** [comment]
@imuli Let me have a look at your example that fails.

**Comment by imuli** [comment]
@liaxim Ah, yes, not very comprehensive. I don't know if I will get very far or how high quality I'll manage, but I'll try to put something together as I go.

@rahul27 The basic need is to have a central location to get key events before anything else. I haven't waded through the viewmanager code to look see if such a hook is available there, but the obvious place to my mind would be in the activity. Overloading the activity's dispatchKeyEvent works, but then you need to know not to call super, and instead to pass it to the viewmanager/context.

**Comment by rahul27** [comment]
@imuli I had a look at your example and it looks like the current behavior of the framework is correct. The documentation for onKeyEvent states that the call is only made when no view in the activity handles the key event:

[onKeyDown](https://developer.android.com/reference/android/app/Activity.html#onKeyDown(int, android.view.KeyEvent))

In case of the your sample the webview handles this key event which results in onKeyDown() not being called. 

Let me know if this answers your issue.

Thanks.

**Comment by imuli** [comment]
@rahul27 It is good to be consistant with the rest of Android. I find that behavior surprising, as keyEvents bubble down through the view heirarchy, and unhelpful, as there's no clean place to listen to key events first, but ah well I can make one.
