### ISSUE TITLE
Documentation on configuration file

### ISSUE THREAD

**Issue by arianaa30** [Samsung/GearVRf#605]
Is there any documentation available just for the configuration file API? I mean, like, what each of these fields are and what are valid values and such?

```
        <eye-buffer-parms
            colorFormat="COLOR_8888"
            depthFormat="DEPTH_24"
            fov-y="90.0"
            multiSamples="1"
            resolutionWidth="DEFAULT"
            resolutionHeight="DEFAULT"
            resolveDepth="false" />
```

**Comment by thomasflynn** [comment]
Everything in there maps to the equivalent Oculus settings.  This stuff used to be documented on their website, but the Mobile SDK documents seem to have been rearranged since last year and actually seem to have less information than they used to have.  Disappointing.  We do have our own documentation in our own source code that reads this information here:

https://github.com/Samsung/GearVRf/blob/master/GVRf/Framework/framework/src/main/java/org/gearvrf/utility/VrAppSettings.java

Since you listed eye-buffer-parms  (named after the structure Oculus has a developer fill out..why they call it 'parms' and not 'params', i'll probably never know), I'll list out the explanations here:

For colorFormat:
            COLOR_565(0), // 5-bit red, 6-bit for green, 5-bit blue
            COLOR_5551(1), // one bit from green right now for alpha channel.
            COLOR_4444(2), // 4-bit red, 4-bit green, 4-bit blue, 4-bit alpha channel.
            COLOR_8888(3), // 8-bit red, 8-bit green, 8-bit blue, 8-bit alpha channel.
            COLOR_8888_sRGB(4), // SRGB color format
            COLOR_RGBA16F(5);   // GL_RGBA16F

for depthFormat:
            DEPTH_0(0), // No depth buffer
            DEPTH_16(1), // 16-bit depth buffer
            DEPTH_24(2), // 24-bit depth buffer
            DEPTH_24_STENCIL_8(3);// 32-bit depth buffer

For fov-y:
            This is the Field of View in the y direction.  This is for setting up the perspective camera.

For multiSamples:
            Number of multisamples to setup the framebuffer.
            1 = no multisampling.  really not recommended.  We need to update all our samples to not have this.  This was a bigger issue before Note4, but since Note4, you can pretty much have 2xMSAA for free.
            2 = 2xMSAA.  Recommended.
            4 = 4xMSAA.  Will take a hit in fill rate, but will look nicer.
            At the time of this writing, I don't think there are any mobile GPUs that support more than 4xMSAA :(

For resolutionWidth and resolutionHeight:
            These are the width and height of the eyebuffer FBOs.  default is 1024x1024.  this is the resolution that Oculus recommends.  However, some people pick a slightly higher set of resolution values so that text looks clearer.  Higher resolution means more fill.

resolveDepth is for indicating whether depth is resolved to a texture.  Not sure why one would enable that.  I'll have to ask around.

**Comment by arianaa30** [comment]
Thanks for the useful information. One thing: So generally Gearvrf is the same granularity level as Oculus mobile SDK itself, right? I mean, it is as low level as Oculus SDK; so basically whatever Oculus has control over, it is also adjustable in GearVRf. Am I right?

**Comment by liaxim** [comment]
GearVRf is a higher-level, scene-graph API that builds on top of Oculus. GearVRf has control over whatever is exposed by the public Oculus APIs; like VrApi.

**Comment by thomasflynn** [comment]
Yeah, I wanted to clarify that was well.  GearVRf lies on top of the Oculus Mobile SDK, so we should expose the same settings that are available at the lower level.  The Oculus Mobile SDK takes care of distortion, timewarp, and head tracking, but expects developers to write all their own OpenGL code and do it via the Android NDK.  GearVRf provides a full scene graph (similar in way to OpenSceneGraph) with Java apis and does not require knowledge of OpenGL.

**Comment by NolaDonato** [comment]
I have documented the settings file here: http://gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfSettingsFile

**Comment by arianaa30** [comment]
That's great! Thanks.
Does the API allow to change settings while playing? For instance, can I change fov-y after 10 seconds?

**Comment by NolaDonato** [comment]
Unfortunately not. We support initializing them from the file but not dynamically changing them while your app is running.

**Comment by thomasflynn** [comment]
actually, in the case of fov-y, you can get the left and right cameras from the camera rig, cast them to GVRPerspectiveCamera, and use the method in there to change the FovY.

**Comment by thomasflynn** [comment]
sorry, didn't mean to re-open.
