### ISSUE TITLE
Multi-video player support

### ISSUE THREAD

**Issue by arianaa30** [Samsung/GearVRf#609]
Hi,
I have a few concern before using GearVRf. I submit them separatenly. I noticed that GearVRf only can handle one VideoSceneObject at a time. Is that right? (from your 360 video demo). A feature that I need is to be able to play multiple videos simultaneously as if there is a single player similar to a regular 360 video player (as in your demos). Is it possible to achieve that and map them into the sphere as if there is a single and smooth media player? 

![fj62s](https://cloud.githubusercontent.com/assets/5509837/16089365/8b11bb12-32df-11e6-8da1-d9792f49aadd.png)

Note that in my case, each of these four videos are in fact a crop of the 360 video; so they are continuous as if you see a single video!

**Comment by arianaa30** [comment]
Any thoughts on this question?

I actually just created a multi-video player app on Android (2D) which nicely plays up to 8 videos on Samsung S7, almost smoothly. I just need to map the whole thing to the sphere. For a single mediaplayer, we already know given the 360 video demo provided, but now that we have a mother media player consisting of multiple media players, I don't know how to do that. 
Initially I thought it would be so simple; just identify a surface (even if it consists of multiple view objects) and feed it into the sphere. Do we need to modify the shaders? Any thoughts on how we can do that?

**Comment by liaxim** [comment]
If it is "almost smoothly" then it will far less smooth in VR with the additional overhead. Technically nothing prevents you from creating many GVRVideoSceneObjects. I had 8 run side-by-side but the performance wasn't good at all.

**Comment by thomasflynn** [comment]
for mapping the whole thing to the sphere, if you can get the SurfaceTexture, then you can modify GVRVideoSceneObject to use your surface texture.

**Comment by arianaa30** [comment]
@liaxim I see. I'm just wondering how. Can you share your example? I know the performance is not good, but just want to see how we can do that. I have no clue.

**Comment by liaxim** [comment]
@arianaa30 https://github.com/liaxim/GearVRf-Demos/tree/manyvideos Is that what you had in mind?

**Comment by arianaa30** [comment]
So which specific project is that? The link is a branch.

**Comment by liaxim** [comment]
gvr-360video; you can see the commit at the top of tree

**Comment by arianaa30** [comment]
I got it...am trying to run. 
Did you update the API? GVRMain is not recognized!

**Comment by liaxim** [comment]
You can just replace GVRMain/setMain with GVRScript/setScript.

**Comment by arianaa30** [comment]
Yes, this is what I did to resolve the setMain issue...

**Comment by arianaa30** [comment]
Ummm, interesting. Not exactly what I had in mind, but that's very close! I think we are almost there.
To give an example: So basically I just sliced the same video `videos_s_3.mp4' into 4 tiles: 00 (top-left), 01 (top-right), 10 (bottom-left), and 11 (bottom-right). I uploaded them here: https://www.dropbox.com/sh/nbg7jrubwcldtmf/AACsFilS8GX0TKFLvBEzb9bea?dl=0

Now the 4 media players here are positioned in a way and are playing the tiles seamlessly in a way that you think you are playing the original `videos_s_3.mp4' with a single media player, like the original _360-video_ demo. Is it clear enough? 

Given your example, I think it should be possible.

**Comment by arianaa30** [comment]
Any news on this?
The worst case scenario of doing this is to load 3D models of circle parts (in this example, a quarter of shpere) as a custom mesh, and map each video texture to that. I don't know if custom mesh upload is supported by GearVRf, but this is not scalable at all. I hope there is an easier way to do this in code within GearVrf.

**Comment by liaxim** [comment]
Yes, you should be able to arrange the tiles as you described. And you can definitely load and display your 3D models in gvrf. We have number of examples that load models.

**Comment by arianaa30** [comment]
I am wondering if we can assign tiles to parts of sphere in code instead of loading meshes, like what you were trying to do in your manyVideos example?

**Comment by liaxim** [comment]
Our GVRSphereSceneObject can't do that. You most definitely can build something that could.

**Comment by arianaa30** [comment]
Cool. Loading a model is at least a relief. I was just trying to load a hemisphere model, but this didn't work. Is there anything wrong? I'm just trying to simply follow the same pattern for a full sphere. Plus we don't have facingOut boolean.

```
//        GVRSphereSceneObject sphere = new GVRSphereSceneObject(gvrContext, false);
        GVRSceneObject sphere = new GVRSceneObject(gvrContext, new GVRAndroidResource(gvrContext, "hemisphere.obj"), null);
        GVRMesh mesh = sphere.getRenderData().getMesh();
```

**Comment by arianaa30** [comment]
Actually I just loaded my hemisphere.obj, attached, and just replaced the sphere mesh with the loaded mesh (everything else same as gvr-360video demo):

`GVRMesh mesh = gvrContext.loadMesh(new GVRAndroidResource(gvrContext, "hemisphere.obj"));`

When trying to run, the video is played, I hear the sound, But I don't know why I don't see any videos. Apparently it is being played in/on the hemisphere, but I just see a light-green shade instead of the karate video :-/ I was thinking maybe I'm inside and the video is played outside surface; but negated the normal (to simulate the missing faceOut boolean), but still the same.

What is the reason? Am I missing anything?
[hemispherical.zip](https://github.com/Samsung/GearVRf/files/332871/hemispherical.zip)

**Comment by arianaa30** [comment]
This can be closed. Thanks.
