### ISSUE TITLE
NativeBaseTexture native method setJavaOwner has wrong return value type

### ISSUE THREAD

**Issue by julee** [Samsung/GearVRf#613]
In jni, this method is
JNIEXPORT void JNICALL
    Java_org_gearvrf_NativeBaseTexture_setJavaOwner(JNIEnv * env, jobject obj, jlong jtexture, jobject owner);

but in java:
static native long setJavaOwner(long pointer, GVRTexture owner);

return value type should be void.

**Comment by liaxim** [comment]
Thank you for the catch. https://github.com/Samsung/GearVRf/pull/614

**Comment by liaxim** [comment]
https://github.com/Samsung/GearVRf/pull/614 merged
