### ISSUE TITLE
Add multi-view support since VrAppFramework supports it in 1.0.3

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#620]
Determine are there code changes necessary; verification.

**Comment by liaxim** [comment]
multiview support is in the VrAppFramework so we will need to add support for it ourselves.

**Comment by liaxim** [comment]
@roshanch has a small change required to build with 1.0.3. Leads to crashes for him but it did work for me.

**Comment by liaxim** [comment]
The basic change has been merged. The multiview support not addressed yet.

**Comment by roshanch** [comment]
It is addressed by PR #622.

**Comment by roshanch** [comment]
Can we close this?
