### ISSUE TITLE
Disallow adding a scene object to the same parent multiple times

### ISSUE THREAD

**Issue by ejsamsung** [Samsung/GearVRf#623]
Currently, it's possible to add a given GVRSceneObject to a parent object:

    parentObject.addChildObject(childObject);
    parentObject.addChildObject(childObject);
    parentObject.addChildObject(childObject);

When it's time to render, the child in this example will get rendered three times.  It's easiest to see this with a translucent scene object: the more times it's added, the more opaque it becomes.

It was suggested that attempting to do this should throw an exception.  I'd prefer a "gentler" approach: return `true` if the child was being newly added, `false` if it's already a child.  Then we can do this:

    if (parentObject.addChildObject(childObject)) {
        ...

instead of

    if (parentObject != childObject.getParent()) {
        parentObject.addChildObject(childObject);
        ...

Ever so slightly more concise.

**Comment by NolaDonato** [comment]
Pull request #629 addresses this issue

**Comment by liaxim** [comment]
https://github.com/Samsung/GearVRf/pull/663 merged. Erik, can we close this issue?
