### ISSUE TITLE
GVRFloatTexture::Constructor - It is not throwing the exception

### ISSUE THREAD

**Issue by elidelsonc** [Samsung/GearVRf#63]
The exception below is not been thrown.

*IllegalArgumentException - If width or height is <= 0, or if data is null, or if data.length < height * width * 2*
[GVRFloatTexture Documentation](http://docs.gearvrf.org/org/gearvrf/GVRFloatTexture.html#constructor_summary)

```
private float pixels[] = {
            0.0f, 0.0f, 0.0f,   1.0f, 1.0f, 1.0f,
            1.0f, 1.0f, 1.0f,   0.0f, 0.0f, 0.0f
    };
SomeGVRViewManager mGVRContext = new SomeGVRViewManager();
GVRFloatTexture gvrFloatTexture = new GVRFloatTexture(,0,1,pixels);
```

**Comment by JonShemitz** [comment]
Thanks! `GVRFloatTexture` line 49 should call Java `update()`, not `NativeFloatTexture.update()`.

My bad, will fix, though perhaps not until next week.

**Comment by JonShemitz** [comment]
Should be fine now, @elidelsonc.
