### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by rickymediaengine** [Samsung/GearVRf#632]
Hi,

i can't build the framework project, this is the error:

[armeabi-v7a] Compile++ arm  : gvrf <= cubemap_reflection_shader.cpp
[armeabi-v7a] Compile++ arm  : gvrf <= cubemap_shader.cpp

jni/oculus/activity.cpp: In member function 'void gvr::GVRActivity::onSurfaceChanged(JNIEnv&)':
jni/oculus/activity.cpp:128:62: error: 'struct ovrModeParms' has no member named 'AllowPowerSave'
         configurationHelper_.getModeConfiguration(env, parms.AllowPowerSave, parms.ResetWindowFullscreen);
                                                              ^
jni/oculus/activity.cpp:128:84: error: 'struct ovrModeParms' has no member named 'ResetWindowFullscreen'
         configurationHelper_.getModeConfiguration(env, parms.AllowPowerSave, parms.ResetWindowFullscreen);
                                                                                    ^

[armeabi-v7a] Compile++ arm  : gvrf <= custom_shader.cpp

make.exe: *** [obj/local/armeabi-v7a/objs/gvrf/oculus/activity.o] Error 1
make.exe: *** Waiting for unfinished jobs....

can you help me?

**Comment by rickymediaengine** [comment]
this occurs with Oculus sdk version 1.0.3

**Comment by liaxim** [comment]
We don't yet support 1.0.3. Please use 1.0.0.0 or 1.0.0.1 for now. Thanks.

**Comment by thomasflynn** [comment]
Yes, give us a little time to port.  Despite the version number only updating the minor number, there were quite a few major api breaking changes.

**Comment by liaxim** [comment]
1.0.3 support has been merged. Planning to close this issue tomorrow.
