### ISSUE TITLE
Publishing app avoid oculus signature

### ISSUE THREAD

**Issue by endriazizi** [Samsung/GearVRf#635]
Hello, I would like to find a way that does oculus signature.

**Comment by thomasflynn** [comment]
There are few ways that I've heard of:
1) publish on the Oculus Store ;-)
2) sideloadvr.com
3) if you need to securely share your apk with others: constructvr.io

**Comment by liaxim** [comment]
@endriazizi Do you need further help? Or can we close the issue? Thanks

**Comment by endriazizi** [comment]
No thanks, it works for me!
