### ISSUE TITLE
I get these error messages when try clean Framework

### ISSUE THREAD

**Issue by mohan6feet** [Samsung/GearVRf#643]
Please help. Been looking all over and can not resolve my problem. I'm trying to build the Framework project in android 2.1.2

When I clean my project I get the following error message:

Error:error: 'struct ovrModeParms' has no member named 'AllowPowerSave'
         configurationHelper_.getModeConfiguration(env, parms.AllowPowerSave, parms.ResetWindowFullscreen);

Error:error: 'struct ovrModeParms' has no member named 'ResetWindowFullscreen'
         configurationHelper_.getModeConfiguration(env, parms.AllowPowerSave, parms.ResetWindowFullscreen);

Error:Execution failed for task ':framework:buildNative'.
> Process 'command 'C:\Users\vThink\AppData\Local\Android\sdk\ndk-bundle\ndk-build.cmd'' finished with non-zero exit value 2

My build.gradle file looks as follows:

import org.apache.tools.ant.taskdefs.condition.Os

apply plugin: 'com.android.library'

android {
    compileSdkVersion 21
    buildToolsVersion '23.0.3'

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 19

        ndk {
            moduleName "gvrf"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
        }
    }

    sourceSets.main {
        java.srcDirs = ['src/main/java']
        jni.srcDirs = [] // no auto generation of Android.mk
        jniLibs.srcDir 'src/main/libs' // pre-compiled libraries
    }

    task buildNative(type: Exec) {
        if (rootProject.hasProperty("OVR_MOBILE_SDK")) {
            environment 'OVR_MOBILE_SDK', rootProject.property("OVR_MOBILE_SDK")
        }

        def ndkbuild = ""
        if (rootProject.hasProperty("ANDROID_NDK_HOME")) {
            ndkbuild = rootProject.property("ANDROID_NDK_HOME")
            ndkbuild += '/'
        }
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            ndkbuild += 'C:\\Users\\vThink\\AppData\\Local\\Android\\sdk\\ndk-bundle\\ndk-build.cmd'
        } else {
            ndkbuild += 'C:\\Users\\vThink\\AppData\\Local\\Android\\sdk\\ndk-bundle\\ndk-build'
        }

        if (rootProject.hasProperty("OVR_MOBILE_SDK")) {
            environment 'OVR_MOBILE_SDK', rootProject.property("OVR_MOBILE_SDK")
        }

        commandLine ndkbuild, '-C', file('src/main').absolutePath, '-j', 16//, 'NDK_DEBUG=1'
    }

    task cleanNative(type: Exec) {
        def ndkbuild = ""
        if (rootProject.hasProperty("ANDROID_NDK_HOME")) {
            ndkbuild = rootProject.property("ANDROID_NDK_HOME")
            ndkbuild += '/'
        }
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            ndkbuild += 'C:\\Users\\vThink\\AppData\\Local\\Android\\sdk\\ndk-bundle\\ndk-build.cmd'
        } else {
            ndkbuild += 'C:\\Users\\vThink\\AppData\\Local\\Android\\sdk\\ndk-bundle\\ndk-build'
        }

        if (rootProject.hasProperty("OVR_MOBILE_SDK")) {
            environment 'OVR_MOBILE_SDK', rootProject.property("OVR_MOBILE_SDK")
        }
        commandLine ndkbuild, '-C', file('src/main').absolutePath, '-j', 16, 'clean'
    }

    clean.dependsOn 'cleanNative'

    tasks.withType(JavaCompile) {
        compileTask -> compileTask.dependsOn buildNative
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile fileTree(dir: 'src/main/libs', include: ['*.jar'])
}

**Comment by mohan6feet** [comment]
I Command it this line 

configurationHelper_.getModeConfiguration(env, parms.AllowPowerSave, parms.ResetWindowFullscreen);

in GVRf\Framework\framework\src\main\jni\oculus\activity.cpp
 
Now its successfully Builed.

**Comment by liaxim** [comment]
Sounds like you are using Oculus Mobile SDK 1.0.3. Pull request https://github.com/Samsung/GearVRf/pull/637 adds support for that. Not merged yet so you could just fetch it or use Oculus Mobile SDK 1.0.0.0 or 1.0.0.1.

**Comment by liaxim** [comment]
Let us know if we can close the issue. Thanks.

**Comment by mohan6feet** [comment]
Its fine, close the issue.
