### ISSUE TITLE
Can't go back to the Activity

### ISSUE THREAD

**Issue by mohan6feet** [Samsung/GearVRf#648]
In gvr-events i set Clicklistner for to access 360 photo Activiity by adding these codes.
    private OnClickListener clickListener=new OnClickListener() {
        @Override
        public void onClick(View v) {
            startActivity(new Intent(EventsActivity.this, Minimal360PhotoActivity.class));
}
}

After seeing the 360 photo i press the back button in Gear VR, i can't go back previous activity, what code to go back and where it specified?

**Comment by rahul27** [comment]
There are ways to do this, but it is recommended that you be cautious with multiple activities. Let me know if this helps:

https://github.com/Samsung/GearVRf/issues/477

**Comment by mohan6feet** [comment]
Is there any coding examples for that?

**Comment by liaxim** [comment]
We don't have examples for that as it is not expected to "just work".
