### ISSUE TITLE
How to add 360 image as background image

### ISSUE THREAD

**Issue by mohan6feet** [Samsung/GearVRf#649]
I have an activity which contain buttons, I need to run some background 360 image for this activity.
One more thing is any possible to show the buttons on each side of activities?

**Comment by Nathipha** [comment]
Check out the "360photo" sample, it shows you how to set up 360° images. ;)
Can't really help you with the buttons, sorry but I would recommend checking out an Android tutorial for displaying buttons, I'm sure it's not that different.

**Comment by liaxim** [comment]
You could use Android Views and inflate a layout; see gvr-renderableview.

**Comment by thomasflynn** [comment]
Thanks @Nathipha , you're getting to be a real pro :)

**Comment by mohan6feet** [comment]
gvr-renderableview is example of multiple View on same screen, but i want like occulus 360 photos app home screen.
360 photo running behind the options to select other photos.

**Comment by rahul27** [comment]
From what I understand from your description, you want a 360 photo app with a tiled menu that you could use to switch between different photos.

You could start off by looking at the 360 photos app:

https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-360photo

Next you would need to create a tile based menu, for that you could look at the gvr-simplegallery app:

https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-simplegallery

Finally to switch between different photos you would need an eye picker, like the one implemented in gvr-eyepicking:

https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-eyepicking

In your case you would be using the picker to interact with the different tiles in your application.

**Comment by NolaDonato** [comment]
We now have documentation on picking: http://gearvrf.org/bin/view/GearVRfDeveloperGuide/Picking

**Comment by liaxim** [comment]
@mohan6feet Do you have more questions? In need of clarification?
