### ISSUE TITLE
CameraRig.reset() et al not working as intended?

### ISSUE THREAD

**Issue by imuli** [Samsung/GearVRf#650]
I want to be able to manually perform a reorientation, claim that the direction I'm currently looking in is the normal forward. It looks like the code to do this is something like `mGVRContext.getMainScene().getMainCameraRig().reset()` (or resetYaw for just the yaw). Calling this doesn't appear to have any effect.

Test app: GearVRf-Demo/gvr-modelviewer with the following addition to actually call onBackPressed upon pressing back. (Similar lack of behavior exhibited by the other two test apps that call resetYaw.)

    @Override
    public boolean onKeyUp(int keyCode, KeyEvent event) {
        if(event.getKeyCode() == KeyEvent.KEYCODE_BACK){
            onBackPressed();
            return true;
        }
        return super.onKeyUp(keyCode, event);
    }

(changes also at https://github.com/imuli/GearVRf-Demos/tree/reset-bug-example)

**Comment by liaxim** [comment]
Thank you for the catch. Fix is in https://github.com/Samsung/GearVRf/pull/655.
