### ISSUE TITLE
Background of GVRTextViewSceneObjects

### ISSUE THREAD

**Issue by Nathipha** [Samsung/GearVRf#657]
I already addressed my problem with TextViewSceneObjects in my other thread but there are a few new issues with it, so a new thread might be for the better now.

A short summary:
I have a couple of those objects with pretty much the same x & y but different z coordinates, so they're in a row. My main goal at the moment is to get rid if the black background that not only covers the other objects behind it but that you can also easily see if there are other non-black objects near it.

This is what I'm talking about:
http://i.imgur.com/gmEW7BK.png

I've already tried a couple of things to get rid of the black layer:

    material.setOpacity(0.5f);

    material.setDiffuseColor(1.0f, 0.0f, 0.0f, 0.5f);

    textviewobj.setBackGround(new ColorDrawable(Color.TRANSPARENT));

    Drawable d = new ColorDrawable();
    d.setAlpha(50);
    textviewobj.setBackGround(d);

but no luck yet. It doesn't even seem to matter if I'm using the standard or the Phong shader.
Btw, "rd.setRenderingOrder(GVRRenderingOrder.TRANSPARENT);" was always there.
Is it possible to auto-shrink the background as far as possible without cutting off any of the text, plus the other way around (auto-increase the size to fully show more text)?

This does works:
    textviewobj.setBackgroundColor(Color.WHITE);
but it doesn't really solve my problem.

I've also been having troubles with positioning the TextViewSceneObjects:
getTransform().setPosition(...)
moves the center of the object, which is okay but I can't seem to find a way to get the actual width and height to position the object properly with its left edge right next to one of my other objects.
"textviewobj.getBackground()" returns a null Drawable object, so I can't even work with that.

**Comment by NolaDonato** [comment]
This is what worked for me with the latest GearVRF:

        GVRTextViewSceneObject textViewSceneObject = new GVRTextViewSceneObject(gvrContext, "Hello World!");
        textViewSceneObject.setGravity(Gravity.CENTER);
        textViewSceneObject.setTextSize(12);
        
        GVRRenderData textRD = textViewSceneObject.getRenderData();
        GVRMaterial textMtl = textRD.getMaterial();
        textMtl.setColor(1, 0, 0);
        textMtl.setOpacity(0.7f);
        textRD.setAlphaBlend(true);
        textRD.setRenderingOrder(GVRRenderingOrder.TRANSPARENT);

**Comment by NolaDonato** [comment]
I also documented how to do transparency (just now):
http://gearvrf.org/bin/view/GearVRfDeveloperGuide/RenderData

**Comment by Nathipha** [comment]
Thank you and also thanks for the documentation (I noticed that a couple of brackets and semicolons are missing ;) ), I got it to work with the standard shader!
But - yes, sadly there's a "but" - there's a weird bug now:
I used pretty much your code, so:

```
GVRTextViewSceneObject t = new GVRTextViewSceneObject(gvrc,"very very long test text");
t.setGravity(Gravity.TOP | Gravity.LEFT);
t.setTextSize(4);
t.getTransform().setPosition(y-4,z-1,x-12);
GVRRenderData rd = t.getRenderData();
GVRMaterial m = rd.getMaterial();
m.setColor(1, 0, 0);
rd.setAlphaBlend(true);
rd.setRenderingOrder(GVRRenderingOrder.TRANSPARENT);
```

This is what it looks like:
http://i.imgur.com/Pp1KPuC.png

As you can see, the first two TextViewSceneObjects show some kind of transparency for the polylines and the plane but there's still some kind of background behind them that covers the other TextViewObjects.
In the beginning, so right after starting the app and enabling the text, all of them have the same weird background but if I simply look away for a second, it fixes itself for almost all of them and usually only the first two objects - plus maybe 1 or 2 others - show that weird behavior.
I ran my app a couple of times and used sometimes more, sometimes less polylines and TextViewObjects but the first two ones always had the same weird background and, if you think that's weird, look at this screenshot:
http://i.imgur.com/zSTEkwl.png
The first text almost completely covers the second but the others objects behind it still shine through.


Regarding my other two questions (auto-shrinking/inflating the background and getting the size of the background), does anyone know how to do it or if it's even possible?

**Comment by NolaDonato** [comment]
I am looking into the transparency issue. It could have something to do with how we are sorting transparent objects.

I think the background border is because of the text font we use. I will look into whether we allow you to supply your own font.

I have been really swamped this week so my response might be slow.

**Comment by NolaDonato** [comment]
I have not forgotten about your issue. I have managed to reproduce the problem here and am looking into why the text view is not completely transparent.

**Comment by NolaDonato** [comment]
Roshan is working on fixing the transparency problem.

**Comment by NolaDonato** [comment]
More updates on this issue: enabling alphaToCoverage in the GVRRenderData does NOT solve the problem. I tried replacing a call to GVRRenderData.setAlphaBlend(true) with GVRRenderData.setAlphaToCoverage(true) for the transparent items in my test application and it still exhibits the problem. This has something to do with Z buffering because it appears the transparent stuff in the background that should be drawn is not being drawn.

**Comment by Nathipha** [comment]
Thanks for the update!
I just found a related bug with transparency:
If I readd an already existing polygon object (in my case it's either made with GL_TRIANGLES or GL_TRIANGLE_FAN) to a scene with more than one polyline (GL_LINE_STRIP), the transparency for the polygon also doesn't work properly. I have to build the scene object for the polygon from scratch to get the transparency back. This time looking away doesn't even partially fix it.

**Comment by NolaDonato** [comment]
I figured out what is wrong with the transparency on GVRTextViewSceneObject. Our renderer should be disabling the depth test on transparent objects and it is not. We are fixing this but in the meantime you can call GVRRenderData.setDepthTest(false) on your transparent objects and your app should work correctly.

**Comment by Nathipha** [comment]
Thank you, that fixed it for the TextViewSceneObjects. :)
I also tested it with my polygon but unfortunately it didn't work for it too.
Regarding the fix in the new version: Are we talking about GVRf 2 or version 3 that won't work with Eclipse anymore?

**Comment by thomasflynn** [comment]
GVRf 2 and 3 currently support eclipse.  So does 3.0.1.  There will be a future version (probably 3.1) that will no longer support building from Eclipse.

**Comment by NolaDonato** [comment]
Did you disable the depth test in your polygons too?
I also have a question about what you want it to look like. Do you want all the text to be on top of all the polygons? Or do you want some polygons to cover the text? If you want the former you can set the rendering order to GVRRenderData.OVERLAY and it will render all the text after it renders the polygons. Right now it is intermixing them because they both have GVRRenderData.TRANSPARENT

**Comment by Nathipha** [comment]
@thomasflynn Ah, thanks for clarifying

@NolaDonato Yes but I had to enable it again because the transparency almost stopped working completely for the polygons with it enabled and it also had a weird side effect.

I uploaded a few pictures. This is how I want it to look: 
http://i.imgur.com/sAv9mmO.png
http://i.imgur.com/sXsU2B4.png
You can see the polylines (set as Background, so default) through the polygon and the text (both set as transparent, polygon: alpha of 0.5), plus you can see the text through the polygon and the other way around.

If I reload the polygon's object (clear the scene, add new polylines, then readd the object, so my app doesn't have to create it again) it looks like the object didn't remember its transparency correctly:
http://i.imgur.com/lMFaQKK.png
The text gets covered in a weird way too but it still shows the polylines if I look at them from the bottom:
http://i.imgur.com/HN0Dn6I.png

This is with the depth test disabled for the polygon: 
http://i.imgur.com/H8elYAZ.png
You can barely see the polylines anymore, even if they're "in front" of the polygon.
http://i.imgur.com/ajsZbjh.png
http://i.imgur.com/5mj6MJb.png

**Comment by liaxim** [comment]
@Nathipha Regarding this issue - is the framework working well enough for you or do you still have problems? If you have problems, can we summarize what exactly they are since this is such a long thread.

**Comment by Nathipha** [comment]
Sorry for my late answer!

The wrong visability for TextViewSceneObjects is still there in 3.0.1 unfortunately. If there's an easy fix, I'd be happy to try it but if there isn't, I can as well keep it the way it is - it's not the prettiest but you have to pay close attention to actually notice it.

To summarize the problem:

With ...
```
GVRTextViewSceneObject t = new GVRTextViewSceneObject(gvrc,"very very long test text");
t.setTextSize(4);
t.setGravity(Gravity.TOP | Gravity.LEFT);
t.getTransform().setPosition(y-4,z-1,x-12);
GVRRenderData rd = t.getRenderData();
GVRMaterial m = rd.getMaterial();
m.setColor(1, 0, 0);
rd.setAlphaBlend(true);
rd.setRenderingOrder(GVRRenderingOrder.TRANSPARENT);
rd.setCullFace(GVRCullFaceEnum.None);
rd.setDepthTest(false);
```
... it looks like this:
http://i.imgur.com/wicCIVG.png - this is okay because the polygon actually has a smaller y value than the text, so when you look up through it, it partially covers the TextViewSceneObjects.
http://i.imgur.com/eAnal3O.png - this doesn't look right on the other hand. I snapped this screenshot from above the polygon, so the TextViewSceneObjects should be in front of it.

If I change the RenderingOrder to "OVERLAY", the TextViewSceneObjects are always in front of every other object, even in the same situation as in screenshot 1.
I can't change the DepthTest to "true" because that makes the bounding boxes of the TextViewSceneObjects show up but I guess that option's exactly what I need, right?

Polygon:
```
rd.setDrawMode(GLES20.GL_TRIANGLE_FAN);		
rd.setShaderTemplate(GVRPhongShader.class);
rd.setAlphaBlend(true);
rd.setRenderingOrder(GVRRenderingOrder.TRANSPARENT);
rd.setCullFace(GVRCullFaceEnum.None);
```
Polylines:
```
rd.setDrawMode(GLES20.GL_LINE_STRIP);
rd.setRenderingOrder(GVRRenderingOrder.GEOMETRY);
rd.setMaterial(material);
rd.setShaderTemplate(GVRPhongShader.class);
```

**Comment by thomasflynn** [comment]
@NolaDonato could you look into this?  @Nathipha another thing to try is using alpha-to-coverage.
1) make sure AA is turned on by checking your gvr.xml and looking the number of 'multiSamples' specified.  it should be either 2 or 4.  if it is '1', change it to '2'.
2) get the RenderData for the TextViewSceneObject and call setAlphaToCoverage(true) for that renderdata.

**Comment by NolaDonato** [comment]
I am looking at it now.

**Comment by Nathipha** [comment]
Oh, I didn't know there was AA. That's nice!

Your suggestion works if I re-enable the depth test (with it disabled it looks like in my screenshots, so nothing changes) and, what I'm really surprised about, it also doesn't make the bounding boxes come back. Thank you, @thomasflynn  and @NolaDonato !

I'll close the issue on Friday if no new problems come up while doing some more more testing.

**Comment by Nathipha** [comment]
Everything has been working fine so far, so thanks for your help again!
