### ISSUE TITLE
Back Button doesn't work

### ISSUE THREAD

**Issue by mohan6feet** [Samsung/GearVRf#661]
In Gear VR when i press back button it doesn't work or go back, Is there any specific code for that?

**Comment by rahul27** [comment]
When you say " it doesn't work or go back" - what is it that you expect to happen when you hit back?

The gvr-events sample for example intercepts the back button, leaving it to the developer to handle the action on button press.

For most of the other samples hitting back should take you to the oculus home screen.

**Comment by rahul27** [comment]
If you want you own custom action on back button press, you could look at the dispatchKeyEvent call on the activity:

[dispatchKeyEvent](https://developer.android.com/reference/android/app/Activity.html#dispatchKeyEvent(android.view.KeyEvent))

You must also make sure that you call super() for all unhandled events.

**Comment by mohan6feet** [comment]
I followed the gvr-events example to go for back, Is there any predefined way to record our flow of process or we need to give the way of the process.

**Comment by liaxim** [comment]
Usually on pressing back the exit-to-Oculus-Home prompt is brought up but you could change that in GVRActivity.
