### ISSUE TITLE
How to switch between multiple GVRSceneobjects

### ISSUE THREAD

**Issue by mohan6feet** [Samsung/GearVRf#664]
I create one GVRScene and multiple GVRSceneobjects, Now i want to interact with Sceneobjects like when click one GVRSceneobject some GVRSceneobjects hide on the screen, when i click another one the hide objects are shown. How?

**Comment by NolaDonato** [comment]
The gvr-pickandmove sample shows how to move the currently picked object. The gvr-switch sample shows how to selectively enable a single scene object among many. I think you could combine the logic from these two to accomplish what you want.
