### ISSUE TITLE
App crashes when changing GVRBitmapTexture/GVRSceneObject multiple times

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#665]
I try to update my main scene by adding a new GVRBitmapTexture as an GVRSceneObject for the left and right screen, the GVRBitmapTexture uses a Android.Bitmap. 

`final GVRBitmapTexture textureLeft = bitmapLeft == null ? null : new GVRBitmapTexture(this.gvrContext,
                    bitmapLeft);
            final GVRBitmapTexture textureRight = bitmapRight == null ? null : new GVRBitmapTexture(this.gvrContext,
                    bitmapRight);`

I am adding the texture to the object as followd:

` final GVRSceneObject leftScreen = new GVRSceneObject(this.gvrContext, this.mesh, textureLeft);
            leftScreen.getRenderData().setRenderMask(GVRRenderMaskBit.Left);

            final GVRSceneObject rightScreen = new GVRSceneObject(this.gvrContext, this.mesh, textureRight);
            rightScreen.getRenderData().setRenderMask(GVRRenderMaskBit.Right);`

I also removing the old scene objects before adding new objects.

`
this.mainScene.removeSceneObject(this.leftScreenObject);
this.mainScene.removeSceneObject(this.rightScreenObject);

this.leftScreenObject = leftScreen;
this.rightScreenObject = rightScreen;`

This works for nearly 30 images, and then the app crashes. The RAM usage seems to be ok, but the GC must work a lot:

`I/art: Background partial concurrent mark sweep GC freed 139(4KB) AllocSpace objects, 2(43MB) LOS objects, 14% free, 92MB/108MB, paused 2.068ms total 397.845ms`

I can not find an exception or error in the log, just an information shortly before my app crashes:

` I/ActivityManager: Process com.oculus.horizon (pid 15848)(adj 0) has died(87,92)`

And then I get the following log:

` D/ActivityManager: isAutoRunBlockedApp:: com.oculus.horizon, Auto Run ON
07-04 11:15:31.841 3474-4605/? D/GraphicsStats: Buffer count: 2
07-04 11:15:31.851 3474-4485/? I/WindowState: WIN DEATH: Window{461bef2 u0 d0 com.myapp/com.myapp.TestActivity}
07-04 11:15:31.861 3474-4474/? E/Sensors: Mag old sensor_state 4, new sensor_state : 0 en : 0
07-04 11:15:31.861 3474-5021/? W/ActivityManager: Scheduling restart of crashed service com.oculus.horizon/.service.SDKLoggingService in 272458ms`

Does anyone have an idea how to find out what forces the app to crash?
Do I miss something, to avoid that? Like cleaning the scene?

**Comment by liaxim** [comment]
Hi, would you mind sharing a complete logcat output? Is there an option you could share a sample app that exhibits this behavior with us? How big are your bitmaps?

**Comment by QKnows** [comment]
Hi, after many hours of debugging I am pretty sure that the problem occurs due to a memory leak - I  guess that removing the GVRSceneObject is not enough, and that there is still memory allocated. 

The bitmaps are about 2-3MB. 

Is there a better way to remove GVRSceneObject's then just invoking mainScene.removeSceneObject ? Will the GVRBitmapTexture be deleted, too?

I will try to develop a minimal-sample app in the next days and let you know when I finished it, or if I could solve the bug by myself...

**Comment by liaxim** [comment]
removeSceneObject should be enough. Any chance you might be holding references to sceneObjects someplace else?

**Comment by QKnows** [comment]
ok, I use the same memeber (leftScreenObject, rightScreenObject) again, and that is the only reference to this object...

**Comment by liaxim** [comment]
Ok, we will look into it. Thank you.

**Comment by QKnows** [comment]
Thank you for looking into it... I let you know when i finished the minimal-sample

**Comment by QKnows** [comment]
Hello @liaxim - 
I finally fnished a sample app which demonstrates the behaviour. I edited the gvr-360photo example and added 3D support, using Bitmap(Texture) for left and right screen. 

If you have any questions or problems, please contact me.

Thanky you for looking into the problem.

[gvr-360photo.edited.zip](https://github.com/Samsung/GearVRf/files/349365/gvr-360photo.edited.zip)

**Comment by liaxim** [comment]
Ok, I see it. In GVREventManager change the mHanderMethodCache to use a WeakHashMap. I have limited network access at the moment so I can't upload a pull request immediately.

**Comment by liaxim** [comment]
The fix has been merged. Please get the latest and let us know how it works.

**Comment by QKnows** [comment]
Thank you @liaxim - first tests shows that it works perfectly now! 

Thank you very, very much for the fast fix...
