### ISSUE TITLE
Is it possible to view own app in Gear VR without publishing Occulus store?

### ISSUE THREAD

**Issue by mohan6feet** [Samsung/GearVRf#666]
I'm trying to create own app i want to test my app, but when i connect to gear it directly goes to occulus store. what i do?

**Comment by QKnows** [comment]
Did you start your app befre you connect it to the Gear? 
When you start the app a message should pop up which informs you to connect to the GearVR...

**Comment by liaxim** [comment]
@mohan6feet See https://developer.oculus.com/documentation/mobilesdk/latest/concepts/mobile-troublesh-device-run-app-outside/

**Comment by thomasflynn** [comment]
do you have the vr_only tag in your AndroidManifest.xml?

**Comment by mohan6feet** [comment]
Wow, It works thanks @thomasflynn
