### ISSUE TITLE
Possible bug in gvr-simplegallery 

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#670]
The gvr-simplegallery crashes on startup.

Logcat:

`07-06 13:36:49.811 23889-23938/com.samsung.android.gvr.sample D/ResourceCacheBase: put resource CLOSED{filePath=null; resourceId=7f02000b; assetPath=null, url=null, inputStreamName=null} to cache
07-06 13:36:49.831 23889-23938/com.samsung.android.gvr.sample I/MediaPlayer: Need to enable context aware info
07-06 13:36:49.831 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer-JNI: native_setup
07-06 13:36:49.831 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: constructor
07-06 13:36:49.831 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: setListener
07-06 13:36:49.831 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer-JNI: setParameter: key 1400
07-06 13:36:49.831 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: MediaPlayer::setParameter(1400)
07-06 13:36:49.831 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer-JNI: setAudioStreamType: 3
07-06 13:36:49.831 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: MediaPlayer::setAudioStreamType
07-06 13:36:49.831 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer-JNI: set_session_id(): 49
07-06 13:36:49.831 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: MediaPlayer::setAudioSessionId(49)
07-06 13:36:49.841 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer-JNI: setDataSourceFD: fd 30
07-06 13:36:49.841 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: setDataSource(30, 4819716, 73840816)
07-06 13:36:49.841 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: setVideoSurfaceTexture
07-06 13:36:49.851 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: prepare
07-06 13:36:49.851 23889-23965/com.samsung.android.gvr.sample I/OVR: DeviceManagerThread - event 50 (0Hz) (Tid=23965)
07-06 13:36:49.901 23889-23980/com.samsung.android.gvr.sample V/MediaPlayer: message received msg=5, ext1=1280, ext2=720
07-06 13:36:49.901 23889-23980/com.samsung.android.gvr.sample V/MediaPlayer: New video size 1280 x 720
07-06 13:36:49.901 23889-23980/com.samsung.android.gvr.sample V/MediaPlayer: callback application
07-06 13:36:49.901 23889-23980/com.samsung.android.gvr.sample V/MediaPlayer: back from callback
07-06 13:36:49.901 23889-23980/com.samsung.android.gvr.sample V/MediaPlayer: message received msg=1, ext1=0, ext2=0
07-06 13:36:49.901 23889-23980/com.samsung.android.gvr.sample V/MediaPlayer: prepared
07-06 13:36:49.901 23889-23980/com.samsung.android.gvr.sample V/MediaPlayer: signal application thread
07-06 13:36:49.901 23889-23980/com.samsung.android.gvr.sample V/MediaPlayer: callback application
07-06 13:36:49.901 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: prepare complete - status=0
07-06 13:36:49.901 23889-23938/com.samsung.android.gvr.sample D/MediaPlayer: setSubtitleAnchor in MediaPlayer
07-06 13:36:49.901 23889-23980/com.samsung.android.gvr.sample V/MediaPlayer: back from callback
07-06 13:36:49.921 23889-23889/com.samsung.android.gvr.sample I/Vsync: Choreographer doFrame callback delayed by 3.8 milliseconds
07-06 13:36:49.921 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: invoke 68
07-06 13:36:49.931 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer-JNI: start
07-06 13:36:49.931 23889-23938/com.samsung.android.gvr.sample V/MediaPlayer: start
07-06 13:36:49.971 23889-23938/com.samsung.android.gvr.sample D/gvrf:   # 0: 0xee7f11c4  _Z15printStackTracej
                                                                        # 1: 0xee7eb758  
                                                                        # 2: 0xee7eca54  _ZN3gvr22CustomPostEffectShaderC1ESsSs
                                                                        # 3: 0xee7d3588  Java_org_gearvrf_NativePostEffectShaderManager_addCustomPostEffectShader
07-06 13:36:49.971 23889-23938/com.samsung.android.gvr.sample E/gvrf: fatal error: no deleter associated with this thread!
07-06 13:36:49.981 23889-23938/com.samsung.android.gvr.sample A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 23938 (gvrf-main)
07-06 13:36:49.981 23889-23939/com.samsung.android.gvr.sample V/MediaPlayer: setVideoSurfaceTexture
07-06 13:36:49.991 23889-23995/com.samsung.android.gvr.sample W/TimeWarp: VSync 2722476: Eye=1,late=0.0ms,over=0.2ms,CPU=0.6ms,GPU=9.2ms,Tot=9.9ms
07-06 13:36:50.011 23889-23995/com.samsung.android.gvr.sample W/TimeWarp: VSync 2722477: Eye=0,late=1.6ms,over=0.0ms,CPU=0.7ms,GPU=17.5ms,Tot=19.9ms
07-06 13:36:50.011 23889-23900/com.samsung.android.gvr.sample V/MediaPlayer: message received msg=6, ext1=0, ext2=0
07-06 13:36:50.011 23889-23900/com.samsung.android.gvr.sample V/MediaPlayer: Received MEDIA_STARTED
07-06 13:36:50.011 23889-23900/com.samsung.android.gvr.sample V/MediaPlayer: callback application
07-06 13:36:50.011 23889-23900/com.samsung.android.gvr.sample V/MediaPlayer: back from callback`

**Comment by liaxim** [comment]
Please get the latest from github. This issue should have been resolved yesterday. See https://github.com/gearvrf/GearVRf-Demos/pull/222.

**Comment by QKnows** [comment]
Thanks for the fast answer and sorry for the report, it works with the newest version...

**Comment by liaxim** [comment]
No worries. Thank you for letting us know.
