### ISSUE TITLE
Release builds

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#676]
I think the current static lib release scheme has some issues with all the new raw resources we have in the framework. We can easily upload an .aar file which is probably the only foolproof way of producing a static lib but Eclipse support becomes challenging. I am still working on making the existing scheme work hence the delay. I also have to come up with an automated way of doing this.

I'd really like us not to have to support Eclipse when it comes to prebuilt binaries since anyway there is no good way of doing it for an Android library.

**Comment by liaxim** [comment]
AAR is the best option since it is completely self-contained. If we have to take out the Oculus .jars and .so then the user needs to manually deal with re-adding those back.

**Comment by liaxim** [comment]
The only viable way of supporting Eclipse I see is creating and Android Library project with all the prebuilt binaries and letting people use that. I don't think the toolchain can handle the framework resource otherwise.

**Comment by liaxim** [comment]
Published the release: https://github.com/Samsung/GearVRf/releases/tag/v3.0.1

If we stick to this model, and I believe we have to, bunch of instructions will have to be updated. Issues I had:

- we need to support Android Studio somehow; there is no better way to do that than .aar
- for the .aar we have to exclude the Oculus binaries which leads to extra steps for end users; inevitable
- Eclipse support impossible unless an Android Library project is distributed; we have a bunch of raw resources added since April that can't be accessed without code changes

Next:
- script that prepares the .aar distributable
- script that creates the source code zip archive
- script that updates an Android Library project template with all the binaries and produces the zip for eclipse
- specifically for nightly builds: script that uses GitHub's REST interface to update the nightly build release

**Comment by jason2kim** [comment]
I am seeing the release 3.0.1. Overall it looks good to me. Just quick questions,
1)	So, we are releasing two different prebuilt files for each IDE. For the future homework, is there no way to use one file and/or automation for the big community of Eclipse users? 
2)	The source code snapshot of  gvrf-3.0.1-src.zip seems redundant, as there is Source code (zip)  already?

**Comment by liaxim** [comment]
1) You can't just use an .aar with Eclipse. There are some plugins but "out-of-the-box" it does not work. As long as we use raw resources I have no other solution for Eclipse other than the Android Library project.
2) Removed the snapshot. Didn't realize it gets created automatically.

**Comment by anandlalvb** [comment]
It seems, there is a typo in the release note, https://github.com/Samsung/GearVRf/releases/tag/v3.0.1

"This binary release works with the **Oculus Mobile SDK 3.0.1.**"

I think, It should be **1.0.3** (https://developer.oculus.com/downloads/)

**Comment by liaxim** [comment]
@anandlalvb Thank you for the catch. Fixed.
