### ISSUE TITLE
missing texture gets thread assertion

### ISSUE THREAD

**Issue by NolaDonato** [Samsung/GearVRf#679]
This assertion occurs whenever it cannot find a texture on the SD card. It does not occur when the texture is found. We are not handling these errors gracefully. 

07-07 18:12:39.199: D/GVRAssetLoader(16692): ASSET: loading sd:GearVRF/jassimp/cube/cube_wrongtex.fbx ...
07-07 18:12:39.209: D/ResourceCacheBase(16692): put resource CLOSED{filePath=/storage/emulated/0/GearVRF/jassimp/cube/cube_wrongtex.fbx; resourceId=0; assetPath=null, url=null, inputStreamName=null} to cache
07-07 18:12:39.229: D/GVRAssetLoader(16692): ASSET: successfully loaded model cube_wrongtex.fbx
07-07 18:12:39.239: D/GVRAndroidResource(16692): Looking for compressed header
07-07 18:12:39.239: W/System.err(16692): java.io.FileNotFoundException: /storage/emulated/0/GearVRF/jassimp/cube/missing_texture.png: open failed: ENOENT (No such file or directory)
07-07 18:12:39.259: W/System.err(16692):    at libcore.io.IoBridge.open(IoBridge.java:409)
07-07 18:12:39.259: W/System.err(16692):    at java.io.FileInputStream.<init>(FileInputStream.java:78)
07-07 18:12:39.259: W/System.err(16692):    at java.io.FileInputStream.<init>(FileInputStream.java:105)
07-07 18:12:39.259: W/System.err(16692):    at org.gearvrf.utility.MarkingFileInputStream.<init>(MarkingFileInputStream.java:34)
07-07 18:12:39.259: W/System.err(16692):    at org.gearvrf.GVRAndroidResource.openStream(GVRAndroidResource.java:348)
07-07 18:12:39.259: W/System.err(16692):    at org.gearvrf.GVRAndroidResource.getCompressedLoader(GVRAndroidResource.java:649)
07-07 18:12:39.259: W/System.err(16692):    at org.gearvrf.asynchronous.GVRAsynchronousResourceLoader$4.run(GVRAsynchronousResourceLoader.java:288)
07-07 18:12:39.259: W/System.err(16692):    at org.gearvrf.utility.Threads$1.run(Threads.java:108)
07-07 18:12:39.259: W/System.err(16692):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-07 18:12:39.259: W/System.err(16692):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-07 18:12:39.259: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-07 18:12:39.269: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-07 18:12:39.269: W/System.err(16692):    at java.lang.Thread.run(Thread.java:841)
07-07 18:12:39.269: W/System.err(16692): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
07-07 18:12:39.269: W/System.err(16692):    at libcore.io.Posix.open(Native Method)
07-07 18:12:39.269: W/System.err(16692):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
07-07 18:12:39.269: W/System.err(16692):    at libcore.io.IoBridge.open(IoBridge.java:393)
07-07 18:12:39.269: W/System.err(16692):    ... 12 more
07-07 18:12:39.279: W/System.err(16692): java.io.FileNotFoundException: /storage/emulated/0/GearVRF/jassimp/cube/missing_texture.png: open failed: ENOENT (No such file or directory)
07-07 18:12:39.279: W/System.err(16692):    at libcore.io.IoBridge.open(IoBridge.java:409)
07-07 18:12:39.279: W/System.err(16692):    at java.io.FileInputStream.<init>(FileInputStream.java:78)
07-07 18:12:39.279: W/System.err(16692):    at java.io.FileInputStream.<init>(FileInputStream.java:105)
07-07 18:12:39.279: W/System.err(16692):    at org.gearvrf.utility.MarkingFileInputStream.<init>(MarkingFileInputStream.java:34)
07-07 18:12:39.279: W/System.err(16692):    at org.gearvrf.GVRAndroidResource.openStream(GVRAndroidResource.java:348)
07-07 18:12:39.279: W/System.err(16692):    at org.gearvrf.GVRAndroidResource.getStream(GVRAndroidResource.java:298)
07-07 18:12:39.279: W/System.err(16692):    at org.gearvrf.GVRAndroidResource.getCompressedLoader(GVRAndroidResource.java:652)
07-07 18:12:39.279: W/System.err(16692):    at org.gearvrf.asynchronous.GVRAsynchronousResourceLoader$4.run(GVRAsynchronousResourceLoader.java:288)
07-07 18:12:39.279: W/System.err(16692):    at org.gearvrf.utility.Threads$1.run(Threads.java:108)
07-07 18:12:39.279: W/System.err(16692):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-07 18:12:39.279: W/System.err(16692):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-07 18:12:39.289: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-07 18:12:39.289: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-07 18:12:39.289: W/System.err(16692):    at java.lang.Thread.run(Thread.java:841)
07-07 18:12:39.289: W/System.err(16692): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
07-07 18:12:39.299: W/System.err(16692):    at libcore.io.Posix.open(Native Method)
07-07 18:12:39.299: W/System.err(16692):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
07-07 18:12:39.299: W/System.err(16692):    at libcore.io.IoBridge.open(IoBridge.java:393)
07-07 18:12:39.299: W/System.err(16692):    ... 13 more
07-07 18:12:39.299: W/System.err(16692): java.lang.NullPointerException
07-07 18:12:39.299: W/System.err(16692):    at org.gearvrf.asynchronous.CompressedTexture.readBytes(CompressedTexture.java:235)
07-07 18:12:39.299: W/System.err(16692):    at org.gearvrf.asynchronous.CompressedTexture.sniff(CompressedTexture.java:192)
07-07 18:12:39.299: W/System.err(16692):    at org.gearvrf.GVRAndroidResource.getCompressedLoader(GVRAndroidResource.java:652)
07-07 18:12:39.299: W/System.err(16692):    at org.gearvrf.asynchronous.GVRAsynchronousResourceLoader$4.run(GVRAsynchronousResourceLoader.java:288)
07-07 18:12:39.309: W/System.err(16692):    at org.gearvrf.utility.Threads$1.run(Threads.java:108)
07-07 18:12:39.309: W/System.err(16692):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-07 18:12:39.309: W/System.err(16692):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-07 18:12:39.309: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-07 18:12:39.309: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-07 18:12:39.309: W/System.err(16692):    at java.lang.Thread.run(Thread.java:841)
07-07 18:12:39.309: W/System.err(16692): java.io.FileNotFoundException: /storage/emulated/0/GearVRF/jassimp/cube/missing_texture.png: open failed: ENOENT (No such file or directory)
07-07 18:12:39.309: W/System.err(16692):    at libcore.io.IoBridge.open(IoBridge.java:409)
07-07 18:12:39.309: W/System.err(16692):    at java.io.FileInputStream.<init>(FileInputStream.java:78)
07-07 18:12:39.309: W/System.err(16692):    at java.io.FileInputStream.<init>(FileInputStream.java:105)
07-07 18:12:39.319: W/System.err(16692):    at org.gearvrf.utility.MarkingFileInputStream.<init>(MarkingFileInputStream.java:34)
07-07 18:12:39.319: W/System.err(16692):    at org.gearvrf.GVRAndroidResource.openStream(GVRAndroidResource.java:348)
07-07 18:12:39.319: W/System.err(16692):    at org.gearvrf.asynchronous.Throttler$PendingRequests.registerCallback(Throttler.java:325)
07-07 18:12:39.319: W/System.err(16692):    at org.gearvrf.asynchronous.Throttler.registerCallback(Throttler.java:60)
07-07 18:12:39.319: W/System.err(16692):    at org.gearvrf.asynchronous.AsyncBitmapTexture.loadTexture(AsyncBitmapTexture.java:77)
07-07 18:12:39.319: W/System.err(16692):    at org.gearvrf.asynchronous.GVRAsynchronousResourceLoader$4.run(GVRAsynchronousResourceLoader.java:306)
07-07 18:12:39.319: W/System.err(16692):    at org.gearvrf.utility.Threads$1.run(Threads.java:108)
07-07 18:12:39.319: W/System.err(16692):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-07 18:12:39.319: W/System.err(16692):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-07 18:12:39.319: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-07 18:12:39.319: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-07 18:12:39.319: W/System.err(16692):    at java.lang.Thread.run(Thread.java:841)
07-07 18:12:39.319: W/System.err(16692): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
07-07 18:12:39.329: W/System.err(16692):    at libcore.io.Posix.open(Native Method)
07-07 18:12:39.329: W/System.err(16692):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
07-07 18:12:39.329: W/System.err(16692):    at libcore.io.IoBridge.open(IoBridge.java:393)
07-07 18:12:39.329: W/System.err(16692):    ... 14 more
07-07 18:12:39.339: W/System.err(16692): java.io.FileNotFoundException: /storage/emulated/0/GearVRF/jassimp/cube/missing_texture.png: open failed: ENOENT (No such file or directory)
07-07 18:12:39.339: W/System.err(16692):    at libcore.io.IoBridge.open(IoBridge.java:409)
07-07 18:12:39.339: W/System.err(16692):    at java.io.FileInputStream.<init>(FileInputStream.java:78)
07-07 18:12:39.339: W/System.err(16692):    at java.io.FileInputStream.<init>(FileInputStream.java:105)
07-07 18:12:39.339: W/System.err(16692):    at org.gearvrf.utility.MarkingFileInputStream.<init>(MarkingFileInputStream.java:34)
07-07 18:12:39.349: W/System.err(16692):    at org.gearvrf.GVRAndroidResource.openStream(GVRAndroidResource.java:348)
07-07 18:12:39.349: W/System.err(16692):    at org.gearvrf.GVRAndroidResource.getStream(GVRAndroidResource.java:298)
07-07 18:12:39.349: W/System.err(16692):    at org.gearvrf.asynchronous.AsyncBitmapTexture$AsyncLoadTextureResource.loadResource(AsyncBitmapTexture.java:340)
07-07 18:12:39.349: W/System.err(16692):    at org.gearvrf.asynchronous.AsyncBitmapTexture$AsyncLoadTextureResource.loadResource(AsyncBitmapTexture.java:1)
07-07 18:12:39.349: W/System.err(16692):    at org.gearvrf.asynchronous.Throttler$AsyncLoader.run(Throttler.java:183)
07-07 18:12:39.349: W/System.err(16692):    at org.gearvrf.asynchronous.Throttler$PendingRequests$PendingRequest.run(Throttler.java:469)
07-07 18:12:39.349: W/System.err(16692):    at org.gearvrf.utility.Threads$ThreadLimiter$ThreadManager.run(Threads.java:521)
07-07 18:12:39.349: W/System.err(16692):    at org.gearvrf.utility.Threads$1.run(Threads.java:108)
07-07 18:12:39.349: W/System.err(16692):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-07 18:12:39.349: W/System.err(16692):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-07 18:12:39.349: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-07 18:12:39.349: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-07 18:12:39.349: W/System.err(16692):    at java.lang.Thread.run(Thread.java:841)
07-07 18:12:39.349: W/System.err(16692): Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
07-07 18:12:39.359: W/System.err(16692):    at libcore.io.Posix.open(Native Method)
07-07 18:12:39.359: W/System.err(16692):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
07-07 18:12:39.359: W/System.err(16692):    at libcore.io.IoBridge.open(IoBridge.java:393)
07-07 18:12:39.359: W/System.err(16692):    ... 16 more
07-07 18:12:39.359: W/System.err(16692): java.lang.NullPointerException
07-07 18:12:39.359: W/System.err(16692):    at org.gearvrf.asynchronous.AsyncBitmapTexture$DecodeStreamHelper.<init>(AsyncBitmapTexture.java:733)
07-07 18:12:39.359: W/System.err(16692):    at org.gearvrf.asynchronous.AsyncBitmapTexture.decodeStream(AsyncBitmapTexture.java:399)
07-07 18:12:39.359: W/System.err(16692):    at org.gearvrf.asynchronous.AsyncBitmapTexture$AsyncLoadTextureResource.loadResource(AsyncBitmapTexture.java:340)
07-07 18:12:39.359: W/System.err(16692):    at org.gearvrf.asynchronous.AsyncBitmapTexture$AsyncLoadTextureResource.loadResource(AsyncBitmapTexture.java:1)
07-07 18:12:39.359: W/System.err(16692):    at org.gearvrf.asynchronous.Throttler$AsyncLoader.run(Throttler.java:183)
07-07 18:12:39.359: W/System.err(16692):    at org.gearvrf.asynchronous.Throttler$PendingRequests$PendingRequest.run(Throttler.java:469)
07-07 18:12:39.369: W/System.err(16692):    at org.gearvrf.utility.Threads$ThreadLimiter$ThreadManager.run(Threads.java:521)
07-07 18:12:39.369: W/System.err(16692):    at org.gearvrf.utility.Threads$1.run(Threads.java:108)
07-07 18:12:39.369: W/System.err(16692):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-07 18:12:39.369: W/System.err(16692):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-07 18:12:39.369: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-07 18:12:39.369: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-07 18:12:39.369: W/System.err(16692):    at java.lang.Thread.run(Thread.java:841)
07-07 18:12:39.379: E/Threads.ThreadLimiter.ThreadManager(16692): org.gearvrf.utility.RuntimeAssertion: Not expecting this to be called in thread 29003
07-07 18:12:39.379: W/System.err(16692): org.gearvrf.utility.RuntimeAssertion: Not expecting this to be called
07-07 18:12:39.379: W/System.err(16692):    at org.gearvrf.asynchronous.Throttler$PendingRequests$PendingRequest.failed(Throttler.java:450)
07-07 18:12:39.379: W/System.err(16692):    at org.gearvrf.asynchronous.Throttler$AsyncLoader.run(Throttler.java:201)
07-07 18:12:39.379: W/System.err(16692):    at org.gearvrf.asynchronous.Throttler$PendingRequests$PendingRequest.run(Throttler.java:469)
07-07 18:12:39.379: W/System.err(16692):    at org.gearvrf.utility.Threads$ThreadLimiter$ThreadManager.run(Threads.java:521)
07-07 18:12:39.379: W/System.err(16692):    at org.gearvrf.utility.Threads$1.run(Threads.java:108)
07-07 18:12:39.379: W/System.err(16692):    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
07-07 18:12:39.379: W/System.err(16692):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-07 18:12:39.379: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-07 18:12:39.379: W/System.err(16692):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-07 18:12:39.379: W/System.err(16692):    at java.lang.Thread.run(Thread.java:841)

**Comment by danke-sra** [comment]
Maybe I/O exceptions should be handled at the application level? We used a Java error reporting model and throw I/O errors as exceptions. Does the app catch IOException thrown from loadModel()?

**Comment by NolaDonato** [comment]
Yes the application will catch I/O errors for the main model. The textures are loaded asynchronously in other threads. I have been slowly working on getting load errors from these threads to populate up to the application. I think I have a fix for this issue already in the works.

**Comment by danke-sra** [comment]
Yeah, I realized this is a new issue. We normally tested out a few cases like this, including SD card and network.

**Comment by NolaDonato** [comment]
I made a lot of modifications to the asset loader last year to handle cases like these. I tested by loading cube_notexture.fbx from gvr-modelviewer2 (which loads from the SD card). The cube appears without a texture (because the asset loader replaces missing textures with white). I think this one is fixed.
