### ISSUE TITLE
Possible missing textures with the asset loader?

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#681]
I had opened a similar issue with the model loader a while back:

https://github.com/Samsung/GearVRf/issues/461

It seems to be happening again but this time with the asset loader. I've updated the sample test program to use the asset loader:

https://github.com/rahul27/GearVRf-Demos/commit/2292a96e0dbf5edb17e8e6acf1ea65c783e9021c

**Comment by NolaDonato** [comment]
Does this still happen with the x3d pull request? I fixed an error in the asset loader there that could cause this to happen.

**Comment by rahul27** [comment]
Happens with the x3d pull request as well.

**Comment by NolaDonato** [comment]
After all of the work I did last year on the asset loader, it appears to have fixed this bug. All of the little guys appear to be textured.
