### ISSUE TITLE
In-App Purchases support

### ISSUE THREAD

**Issue by andrejsinigoj** [Samsung/GearVRf#683]
Is the integration of the oculus in-app purchases planned for the future? If it is not, what would be the best way to integrate them?

**Comment by liaxim** [comment]
Are you referring to https://developer.oculus.com/documentation/platform/latest/concepts/dg-iap/? I don't see those APIs in the Mobile SDK (as of 1.0.3).

**Comment by andrejsinigoj** [comment]
Yes, I was referring to that. Sorry, I didn't notice it was in the platform SDK.. so we need to wait for it to be in the mobile SDK first and then it can be implemented in the framework?

**Comment by liaxim** [comment]
I thinks so.

**Comment by liaxim** [comment]
@andrejsinigoj If you don't have any other questions can we close this issue?

**Comment by andrejsinigoj** [comment]
Yes, we can close.
