### ISSUE TITLE
Getting errors when trying to clean framework

### ISSUE THREAD

**Issue by limpkin** [Samsung/GearVRf#686]
With a freshly cloned repository, oculus sdk 1.0.3 and ndk r12b, with the exact same configuration as #643 

Error:error: 'struct ovrModeParms' has no member named 'Flags'
         parms.Flags |=AllowPowerSave;
               ^
Error:error: 'struct ovrModeParms' has no member named 'Flags'
         parms.Flags |=ResetWindowFullscreen;
               ^
make: *** [obj/local/armeabi-v7a/objs/gvrf/oculus/activity.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by liaxim** [comment]
Do you happen to have older Oculus Mobile SDK's installed somewhere? These errors imply that you might be using the wrong version. Please double check your environment. You can always use this https://github.com/Samsung/GearVRf/wiki/Build%20Tips to set up the path to your Mobile SDK. The environment variables could be harder to track..

**Comment by limpkin** [comment]
Hello,

This is a completely fresh install with oculus sdk 1.0.3 placed in the same folder as the android-ndk-r12b folder, named ovr_sdk_mobile.
I haven't modified anything on the gearvrf demos, I just manually set this in build.gradle:
def ndkbuild = "C:\\dev\\android-ndk-r12b\\"

**Comment by liaxim** [comment]
Hi,
Could you please examine the definition of ovrModeParms from <your_oculus_dir>/VrApi/Include/VrApi_Types.h? For example mine (on line 288) has a Flags field.

**Comment by limpkin** [comment]
Not mine:

`typedef struct
{
	ovrStructureType	Type;

	// If true, warn and allow the app to continue at 30fps when
	// throttling occurs.
	// If false, display the level 2 error message which requires
	// the user to undock.
	bool				AllowPowerSave;

	// When an application with multiple activities moves backwards on
	// the activity stack, the activity window it returns to is no longer
	// flagged as fullscreen. As a result, Android will also render
	// the decor view, which wastes a significant amount of bandwidth.
	// By setting this flag, the fullscreen flag is reset on the window.
	// Unfortunately, this causes Android life cycle events that mess up
	// several NativeActivity codebases like Stratum and UE4, so this
	// flag should only be set for select applications with multiple
	// activities. Use "adb shell dumpsys SurfaceFlinger" to verify
	// that there is only one HWC next to the FB_TARGET.
	bool				ResetWindowFullscreen;

	// The Java VM is needed for the time warp thread to create a Java environment.
	// A Java environment is needed to access various system services. The thread
	// that enters VR mode is responsible for attaching and detaching the Java
	// environment. The Java Activity object is needed to get the windowManager,
	// packageName, systemService, etc.
	ovrJava				Java;

	// If not zero, then use this display for asynchronous time warp rendering.
	// Using EGL this is an EGLDisplay.
	unsigned long long	Display;

	// If not zero, then use this window surface for asynchronous time warp rendering
	// This is expected to be the front buffer.
	// Using EGL this is an EGLSurface.
	unsigned long long	WindowSurface;

	// If not zero, then resources from this context will be shared
	// with the asynchronous time warp.
	// Using EGL this is an EGLContext.
	unsigned long long	ShareContext;
} ovrModeParms;`

**Comment by liaxim** [comment]
Your looks like pre-1.0.3; this is how mine looks:
```
typedef struct
{
        ovrStructureType        Type;

        // Combination of ovrModeFlags flags.
        unsigned int            Flags;

        // The Java VM is needed for the time warp thread to create a Java environment.
        // A Java environment is needed to access various system services. The thread
        // that enters VR mode is responsible for attaching and detaching the Java
        // environment. The Java Activity object is needed to get the windowManager,
        // packageName, systemService, etc.
        ovrJava                         Java;

        OVR_VRAPI_PADDING_32_BIT( 4 );

        // If not zero, then use this display for asynchronous time warp rendering.
        // Using EGL this is an EGLDisplay.
        unsigned long long      Display;

        // If not zero, then use this window surface for asynchronous time warp rendering.
        // Using EGL this can be the EGLSurface created by the application for the ANativeWindow.
        // Preferrably this is the ANativeWIndow itself (requires VRAPI_MODE_FLAG_NATIVE_WINDOW).
        unsigned long long      WindowSurface;

        // If not zero, then resources from this context will be shared with the asynchronous time warp.
        // Using EGL this is an EGLContext.
        unsigned long long      ShareContext;
} ovrModeParms;
```

Would you mind re-downloading 1.0.3 and making sure you are using that?

**Comment by limpkin** [comment]
Just downloaded from https://developer.oculus.com/downloads/mobile/1.0.3/Oculus_Mobile_SDK/ and it seems you're right! that's very odd... thank you!
