### ISSUE TITLE
Possible bug in gvr-accessibility

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#687]
Hi,
I tried to start the gvr-accessibility and it crashes with the following error:

` 07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVRSceneObject.addChildObject(GVRSceneObject.java:754)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVRScene.addSceneObject(GVRScene.java:111)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at com.samsung.accessibility.main.Main.createPedestalObject(Main.java:95)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at com.samsung.accessibility.main.Main.onInit(Main.java:60)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVREventManager.invokeMethod(GVREventManager.java:307)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMaskParamArray(GVREventManager.java:126)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVREventManager.sendEventWithMask(GVREventManager.java:113)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVREventManager.sendEvent(GVREventManager.java:108)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at org.gearvrf.GVRViewManager$3$1.run(GVRViewManager.java:678)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at android.os.Looper.loop(Looper.java:158)
07-11 16:59:37.681 6792-7020/com.samsung.android.gvr.sample W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
07-11 16:59:37.731 6792-6792/com.samsung.android.gvr.sample I/GVRActivity: onPause e78e9c6`

**Comment by liaxim** [comment]
@QKnows Thanks for the catch. Fixed by https://github.com/gearvrf/GearVRf-Demos/pull/251. You need to update your Demos repository.
