### ISSUE TITLE
Orientation Tracking

### ISSUE THREAD

**Issue by arianaa30** [Samsung/GearVRf#689]
What is the methodology GearVRf (or oculus mobile sdk) uses to compute orientation tracking for 3D movement? (when using `scene.getMainCameraRig().getLookAt()`)
So basically Euler angles introduces a phenomenon called gimbal lock. For instance there are ways to model a device’s 3D movement without introducing gimbal lock such as rotation matrices and quaternions. Is it using rotation matrix?

**Comment by liaxim** [comment]
Hi, rotations are represented as quaternions in Oculus and GVRF; I see that getLookAt uses matrices but the rotation is still coming from a quaternion. HTH.

**Comment by liaxim** [comment]
Hi, is that what you were looking for?

**Comment by arianaa30** [comment]
Yes, thanks!
