### ISSUE TITLE
About using prebuilt .aar from the samples

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#694]
Given an aar, say, framework-debug.aar, this is what it takes to modify a sample to use it:

- copy the .aar to ./app/libs/
- remove the references to "framework" from settings.gradle
- modify ./app/build.gradle like this:
```
apply plugin: 'com.android.application'

allprojects {
   repositories {
      jcenter()
      flatDir {
        dirs 'libs'
      }   
   }   
}

android {
   ...
}

dependencies {
    compile(name:'framework-debug', ext:'aar')
}
```

--

- verified that ./gradlew assemble works
- verified that importing the sample in AS and building works

**Comment by liaxim** [comment]
@NolaDonato I believe this does what you've asked for.

**Comment by liaxim** [comment]
You could also share the .aar across all the samples. For example it could be copied to the root of the Demos repo. Then the ``dirs`` in ./app/build.gradle should be changed to ``../../``.

**Comment by liaxim** [comment]
Using the prebuilt .aar will greatly speed up the automated build for the demos which currently takes about 8 hours.. Mostly because of building the framework again and again. @NolaDonato I am all for the switch to a prebuilt aar for the demos.

**Comment by NolaDonato** [comment]
I will start modifying the samples as soon as you merge. I will test first myself with a few and then I will enlist helpers so we can get this done soon.

**Comment by rahul27** [comment]
./app/build.gradle **should** be more like this:

**Comment by thomasflynn** [comment]
your comment said, "should be more like this:", but then nothing afterwards.

**Comment by rahul27** [comment]
:smile: ... fixed it ... hit enter too soon.

**Comment by liaxim** [comment]
Well, we need some generic name otherwise we will have to modify the samples after each release. There might be a way to just pick all the .aar's from a certain directory.

**Comment by rahul27** [comment]
Also you might need to correct the android studio instructions on the releases page:

libvrapi.so needs to go into 
```
app/src/main/jniLibs/armeabi-v7a/
```

**Comment by liaxim** [comment]
Not finding a way to pick .aar-s by using a wildcard. Seems to be intentionally not supported. .jar-s work but .aar-s are rejected. Settle on a name without version numbers if you ask me. We might have the build produce generically named artifacts too..

**Comment by liaxim** [comment]
Regarding extension libraries: if we have the 3DCursorLibrary refer to the framework's aar then the framework classes and resources are not included in the 3DCursorLibrary's aar.

**Comment by liaxim** [comment]
Also the automated build will have to produce the .aars for the 3dcursor and the widgetplugin extensions.

**Comment by liaxim** [comment]
The demos use the prebuilt aar now. Will track additional work in new tickets.
