### ISSUE TITLE
Any Clicklisteners for scene objects

### ISSUE THREAD

**Issue by mohanvthink** [Samsung/GearVRf#702]
I need to add some actions when click on some scene objects, but there is no Onclicklisteners for scene objects. Is there is any other way to add actions to scene objects?

**Comment by liaxim** [comment]
You might find the gvr-events sample helpful.

**Comment by mohanvthink** [comment]
It has only for buttons, I need for scene objects

**Comment by rahul27** [comment]
You could look at https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-3dcursor-simple as an example of implementing clicks on scene objects.

**Comment by mohanvthink** [comment]
you mean setStateChangedListener is the function to implementing clicks on scene objects

**Comment by liaxim** [comment]
@mohanvthink Yes, this is what we currently have. You need an extra library first - https://github.com/Samsung/GearVRf/tree/master/GVRf/Extensions/3DCursor.

Then you follow the sample:

```
CursorManager cursorManager = new CursorManager(gvrContext, mainScene);
SelectableBehavior selectable = new SelectableBehavior(cursorManager);
selectable.setStateChangedListener(new StateChangedListener() {
            @Override
            public void onStateChanged(ObjectState prev, ObjectState current) {
                if(current == ObjectState.CLICKED) {
                    //do something
                }
            }
        });
sceneObject.attachComponent(selectable);
mainScene.addSceneObject(sceneObject);
```

The 3DCursor library is about much more than this hence the complexity. We will work on streamlining handling of the case you describe and provide simpler APIs; we will try to make these APIs part the framework itself so there is no need for an extra library.

**Comment by mohanvthink** [comment]
I tried this, i gave some action inside the if condition but it doesn't  change any thing on the Screen when i click the objects

**Comment by rahul27** [comment]
Do you get the click event callbacks? 

It is the apps responsibility to handle the event and change the asset to react to the click event.
