### ISSUE TITLE
Is it possible to switch between the GVRVideoType 

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#703]
Hi,
is it possible to switch the GVRVideoType of a GVRVideoSceneObject dynamically without creating a new GVRVideoSceneObject everytime I want to switch the format (i.e. switch from HORIZONTAL_STEREO to VERTICAL_STEREO?

**Comment by QKnows** [comment]
Hi @liaxim - thank you for your fastreply - it seem to work! Thank you very, very much!

**Comment by liaxim** [comment]
@QKnows Great. Can we close the issue then?

**Comment by QKnows** [comment]
Yes, sure - I closed the issue already...
