### ISSUE TITLE
GVRSceneObject cannot have multiple parents

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#704]

**Comment by rahul27** [comment]
Here are the sample apps:

https://github.com/gearvrf/GearVRf-Demos/issues/249
https://github.com/gearvrf/GearVRf-Demos/issues/246
https://github.com/gearvrf/GearVRf-Demos/issues/245
https://github.com/gearvrf/GearVRf-Demos/issues/237

**Comment by rahul27** [comment]
@NolaDonato I thought https://github.com/Samsung/GearVRf/pull/699 was supposed to fix this.

**Comment by liaxim** [comment]
The applications have to be updated to behave correctly.

**Comment by rahul27** [comment]
What is the fix? 

Call parent.remove() before the add?

**Comment by liaxim** [comment]
Making sure you don't add the same scene object to more than one parent.

**Comment by rahul27** [comment]
Looks like the simpler fix is  child.getParent().removeChildObject(child);

**Comment by rahul27** [comment]
Used here https://github.com/Samsung/GearVRf/pull/700 and here https://github.com/Samsung/GearVRf/pull/705

**Comment by rahul27** [comment]
Here is the fix for the remaining samples:

https://github.com/gearvrf/GearVRf-Demos/pull/251

**Comment by liaxim** [comment]
Fixes merged in
