### ISSUE TITLE
Wavely lines on GVRSphereSceneObject

### ISSUE THREAD

**Issue by dlockh3ll** [Samsung/GearVRf#710]
I got a 360 picture of an internal of a house but all the window lines are not straight, are wavely, did anyone had this problem for just putting an image on a sphere (360 photo)? Looks like it doesen't make the texture right. Are there some parameters should i try with? Like scaling or other stuff? Sorry but I cant post the image.
My code:

```
        GVRSphereSceneObject sphereObject = null;
        Future<GVRTexture> texture = gvrContext.loadFutureTexture(new GVRAndroidResource(gvrContext, R.raw.low));
        sphereObject = new GVRSphereSceneObject(gvrContext, false, texture);
        sphereObject.getTransform().setScale(10, 10, 10);
        sphereObject.getRenderData().setRenderingOrder(1);
        scene.addSceneObject(sphereObject);
```

**Comment by liaxim** [comment]
Is this an equirectangular image? Like [these](https://www.flickr.com/groups/equirectangular/)

**Comment by dlockh3ll** [comment]
Yes, the image is 7000 x 3500, aspect ratio 2:1

**Comment by thomasflynn** [comment]
I know you can't share the original image, but can you re-create or share something else that shows the problem?  Maybe an image with grid lines or something?

**Comment by dlockh3ll** [comment]
Tried also with this image (from the website @liaxim mentioned) and lines were not straight.
Then i found a constructor for the GVRSphereSceneObject:
`        sphereObject = new GVRSphereSceneObject(gvrContext, 72, 144, false, material);
`
which set the number of stacks and slices and the image was correctly shown on the VR.
Is this a good way to solve the problem?
![28076135200_e61fbfc955_k](https://cloud.githubusercontent.com/assets/20435741/16916551/a8947af2-4cfd-11e6-83f9-7977570a43c9.jpg)

**Comment by thomasflynn** [comment]
Thanks, that's a perfect test image.  Looks, off-hand, to be a problem with interpolating texture coordinates for the sphere.  We'll look into it.  In the meantime, your work-around for increasing the number of slices and stacks seems to be fine.  If that's working out for you, i'd say stick with it for now.

**Comment by thomasflynn** [comment]
@m-blix showed me a similar situation in webgl.  so, it's not something specific to the texcoord generation in our framework.  it really does seem to be just number of triangles.  more triangles, less area to interpolate over, more accuracy.  in that case, maybe just bumping up the default number of stacks and slices would be sufficient.

**Comment by dlockh3ll** [comment]
Ok, got it :)

**Comment by liaxim** [comment]
@thomasflynn @dlockh3ll In that case can we close this issue?

**Comment by dlockh3ll** [comment]
I think we can close it, @thomasflynn ?

**Comment by thomasflynn** [comment]
Sure.  Though I may later make a pull request to increase the number of stacks/slices and make a convenience method to specify that along with a texture (rather than having to create a material and passing that in).  not sure why i didn't do that originally.
