### ISSUE TITLE
Scaling Scene objects

### ISSUE THREAD

**Issue by mohanvthink** [Samsung/GearVRf#711]
I want to scale scene object's left and right edges like occulus home screen menus, how to do it?

**Comment by liaxim** [comment]
Is this what you are referring to? [screenshot](https://i.ytimg.com/vi/Qmkf-u2WmaM/maxresdefault.jpg)

**Comment by mohanvthink** [comment]
Yes, Exactly this one

**Comment by mohanvthink** [comment]
You have any examples for that?

**Comment by liaxim** [comment]
No, we don't have samples which do that.
