### ISSUE TITLE
what is the difference between onSensorEvent and onTouchEvent

### ISSUE THREAD

**Issue by mohanvthink** [Samsung/GearVRf#716]
Is it possible to use the GVRPicker for both events

**Comment by rahul27** [comment]
- onTouchEvent is a call made by the Android framework: [onTouchEvent](https://developer.android.com/reference/android/app/Activity.html#onTouchEvent(android.view.MotionEvent))

- onSensorEvent is a call made the GVRf IO framework when it responds to user input. The gvr-events is an example of the same. You could also look at [gvr-inputsample](https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-inputsample)

- GVRPicker is a module that helps applications perform ray picking on scene objects in the scene graph. Here is some additional info: [Picking](http://gearvrf.org/bin/view/GearVRfDeveloperGuide/Picking)

**Comment by liaxim** [comment]
@mohanvthink Do you need further assistance?
