### ISSUE TITLE
How to add loader in app

### ISSUE THREAD

**Issue by mohanvthink** [Samsung/GearVRf#730]
when open a app it should show the loader

**Comment by liaxim** [comment]
Hi, are you referring to the so called splash screen?

**Comment by mohanvthink** [comment]
yes exactly

**Comment by liaxim** [comment]
@mohanvthink Are you referring to some of our samples or are you talking about your app? In case of your app, do you implement the getSplashMode() method in the class you derive from GVRScript or GVRMain?

**Comment by mohanvthink** [comment]
I'm talking about my app and i didn't get u. can you give code for that

**Comment by liaxim** [comment]
You can start with implementing GVRScript.getSplashMode; returning SplashMode.AUTOMATIC is the easiest thing to do. You might find useful examining all of the GVRScript.getSplash* methods to see what is available.

If you use a splash screen, please get familiar with the GVRContext.getNextMainScene APIs and their javadoc. Pretty much all of our samples utilize the splash screen and the getNextMainScene call.

**Comment by mohanvthink** [comment]
How can i add my own image in splash screen and how to rotate that image?

**Comment by thomasflynn** [comment]
(answering from my phone)...look at the splash relates methods in GVRScript.java.  just override those in your GVRScript or GVRMain.

**Comment by mohanvthink** [comment]
![loading](https://cloud.githubusercontent.com/assets/13622163/17100291/1db4711a-528b-11e6-86b0-1b170b7e6545.gif)
how can i add this loader  between switching the scene objects?

**Comment by rahul27** [comment]
Think I know what you are talking about. I'll have a sample for you in sometime.

**Comment by rahul27** [comment]
Here is a sample application that implements the loader you want:

https://github.com/rahul27/GearVRf-Demos/commit/56755c4a94070ad4c071a5588b4ad321e2b31922

The code loads a series of bitmaps using the ZipLoader (look at `gvr-simplesample/app/src/main/assets/loading.zip`). Feel free to modify it to show the custom animation that you want.

**Comment by mohanvthink** [comment]
It's working, Thank you.

**Comment by liaxim** [comment]
@rahul27 How about trying to generalize this a bit and adding it to the framework as an utility class?

**Comment by rahul27** [comment]
Yup. Was thinking about adding it.
