### ISSUE TITLE
How to add dispatchTouchEvent to multiple frameLayout

### ISSUE THREAD

**Issue by mohanvthink** [Samsung/GearVRf#731]
I followed gvr-events and I create two frameLayout scene. I add dispatchTouchEvent to both frameLayouts but the problem is when i click any frameLayout buttons both frameLayout Events are executed at the same time. Is there is any solution for that?

**Comment by rahul27** [comment]
You should be able to filter events based on the scene object, here is one way you could do it:

https://github.com/rahul27/GearVRf-Demos/commit/2f9e138ae6121b6f9da2a22dd30c1dd37f3b34a0

**Comment by mohanvthink** [comment]
Thanks, you're Genius man.
