### ISSUE TITLE
gvrContext.loadModel does not work in subdirectories

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#735]
Hello,
I tried to import the 
`home_theater.fbx` scene into my main scene and I might have found some bug. If I place the file and the textures in the asset folder, it works without problems 
`gvrContext.loadModel("home_theater.fbx")`
 If I place the fbx and file and all textures into a subfolder (theater) and I load it this.gvrContext.loadModel("theater/home_theater.fbx"), 
I get the following error:

`D/GVRAssetLoader:  ASSET: loading theater/home_theater.fbx ...
W/TimeWarp: VSync 17406696: Eye=0,late=0.0ms,over=0.1ms,CPU=12.8ms,GPU=3.6ms,Tot=16.5ms
W/TimeWarp: VSync 17406696: Eye=1,late=8.1ms,over=0.0ms,CPU=0.4ms,GPU=3.2ms,Tot=11.8ms
W/System.err: java.io.FileNotFoundException: home_theater.fbx
W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:363)
W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:337)
W/System.err:     at org.gearvrf.GVRAndroidResource.openStream(GVRAndroidResource.java:338)
W/System.err:     at org.gearvrf.GVRAndroidResource.getStream(GVRAndroidResource.java:298)
W/System.err:     at org.gearvrf.GVRAssetLoader$ResourceVolumeIO.read(GVRAssetLoader.java:437)
W/System.err:     at org.gearvrf.GVRAssetLoader$CachedVolumeIO.read(GVRAssetLoader.java:473)
W/System.err:     at org.gearvrf.jassimp2.Jassimp.aiImportFileEx(Native Method)
W/System.err:     at org.gearvrf.jassimp2.Jassimp.importFileEx(Jassimp.java:125)
W/System.err:     at org.gearvrf.GVRAssetLoader.loadJassimpModel(GVRAssetLoader.java:641)
W/System.err:     at org.gearvrf.GVRAssetLoader.loadModel(GVRAssetLoader.java:611)
W/System.err:     at org.gearvrf.GVRContext.loadModel(GVRContext.java:690)
W/System.err:     at org.gearvrf.GVRContext.loadModel(GVRContext.java:640)`

**Comment by liaxim** [comment]
@QKnows Are you building the framework yourself or are you using one of the binary releases?

I tried this with the latest code and it worked so we will need some help from you to get to the bottom of it.

I doubt this could help but would you mind cleaning and rebuilding your project? In case you are using Eclipse manually removing the ./bin and ./gen folders might be helpful too. Can you also attach full logcat output?

**Comment by NolaDonato** [comment]
Yes, you might be using something old because I just fixed this bug last week.

**Comment by QKnows** [comment]
@NolaDonato absolutly right, I can confirm that I works now, sorry for the inconvenience and thank you for the fast reply...
