### ISSUE TITLE
Input samples

### ISSUE THREAD

**Issue by mkeblx** [Samsung/GearVRf#74]
It would be useful to have some samples that demonstrate usage of external input like a gamepad and keyboard. A lot of applications beyond gaming could use good text entry support.

**Comment by tflynnt** [comment]
I tried replying to the email notification of then when i got this earlier today.  Apparently it wasn't enough.  Here was my reply:

Fair enough.  We can create some samples that include various input.  Here are some references in the meantime:

for keyboard input, override onKeyDown in your activity:  http://developer.android.com/reference/android/app/Activity.html

Gamepad:  https://developer.android.com/training/game-controllers/controller-input.html

**Comment by mkeblx** [comment]
Hmm, I couldn't get onKeyDown/onKeyUp to invoke. Had to resort to shimming with dispatchKeyEvent:

```java
    @Override
	public boolean dispatchKeyEvent(KeyEvent event) {
		int keyCode = event.getKeyCode();

		if (event.getAction() == KeyEvent.ACTION_DOWN ) {
			mScript.onKeyDown(keyCode, event);
		} else if (event.getAction() == KeyEvent.ACTION_UP) {
			mScript.onKeyUp(keyCode, event);
		}

		return true;
	}
```

**Comment by thomasflynn** [comment]
interesting.  we'll have to take a closer look into that.  we had problems earlier with the oculus sdk intercepting touch events and not passing them to the activity.  we had to work-around it in a similar way.  maybe something similar is happening with the keyboard.

**Comment by mkeblx** [comment]
That's likely it. The physical back button near the headset touchpad is using that code path.

**Comment by thomasflynn** [comment]
hi jason, can you take care of the keyboard dispatching?  should probably be a quick change.

**Comment by jason2kim** [comment]
sure, i am in the middle of something, let me get to this shortly.

**Comment by chenchao1407** [comment]
Hi @mkeblx 

I think your issue with key event dispatching is resolved by pull request #116 

I think you can try it now. I think the sample app will be added later.

**Comment by dknaan** [comment]
I created a new sample application (#147) to demonstrate how to use a gamepad to control the scene. Fire keys change background color. Left motion key translates the scene.

**Comment by thomasflynn** [comment]
Input samples Have been merged
