### ISSUE TITLE
Can splashscreen be 3d?

### ISSUE THREAD

**Issue by afuse** [Samsung/GearVRf#740]
Is there a documentation of api?

**Comment by thomasflynn** [comment]
I don't see why i can't be 3d.  You can override the splash related methods in your GVRScript / GVRMain.  Take a look at GVRScript.java in framework/org/gearvrf/.  You can override what mesh to use, what texture to use, etc.

**Comment by liaxim** [comment]
@afuse Do you need further assistance?

**Comment by liaxim** [comment]
@afuse I assume it is all good now. Let us know if you have more questions.
