### ISSUE TITLE
attachEyePointeeHolder() for a mesh

### ISSUE THREAD

**Issue by arianaa30** [Samsung/GearVRf#743]
Hi,
Is there any ways to assign a `attachEyePointeeHolder()` on a `GVRMesh` mesh, instead of an object? I have a single mesh that is assigned multiple objects that are enabled/disabled depending on situation. So assigning an eyepick on the mesh would save resources instead of all of its objects. Is it true?

And btw, `attachEyePointeeHolder()` seems deprecated on my eyepick example. Any updated version for that?

**Comment by apjagdale** [comment]
Hi,
I did not get your question but we generally pass Mesh to EyePointeeHolder.

Example:
GVREyePointeeHolder playPauseHolder = new GVREyePointeeHolder(context);
playPauseHolder.addPointee(new GVRMeshEyePointee(context, GVRMesh));
model.attachEyePointeeHolder(playPauseHolder);

**Comment by arianaa30** [comment]
So basically I need to apply it on every mesh, right? 
`The method attachEyePointeeHolder(GVREyePointeeHolder) is undefined for the type GVRMesh`
Assuming GVRMesh on the second line is the mesh variable? same for model on third line?!

**Comment by NolaDonato** [comment]
It really depends on the mesh. In general a scene object can only have one component of a given type. If your mesh will fit nicely into a ball, you can use a sphere collided. These are really cheap. The mesh collider with the bounding box option is also cheap. If you need the full precision of the mesh collider you can always attach it to one object and set the render mask to not draw it.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by arianaa30** [comment]
Thanks. Actually I'm a bit confused here; apparently there are two ways to implement the eyepicking approach. 
1- based on the eyePick demo example on the bunnies, simply assign  a `sceneObject.attachEyePointeeHolder();` on each object, and in the onStep, find what object is hit and do something:
```
        for (GVRPickedObject pickedObject : GVRPicker.findObjects(mGVRContext.getMainScene())) {
            for (GVRSceneObject object : objects) {
                if (pickedObject.getHitObject().equals(object)) {
                	pickedObject.get
                    object.setEnable(false);
                    break;
                }
            }
        }
```

2- based on your instruction at http://gearvrf.org/bin/view/GearVRfDeveloperGuide/Picking ... So implement a PickHandler class, and use collider, and set what happens when I enter or exit an object and whatnot. The exit works for me (setEnable(false)), but enter doesn't (setenable(true) doesn't show the object back):
```

public class PickHandler implements IPickEvents
{
	@Override
    public void onEnter(GVRSceneObject sceneObj, GVRPicker.GVRPickedObject pickInfo)
    {		sceneObj.setEnable(true);
    }

	@Override
	public void onExit(GVRSceneObject sceneObj) {
		sceneObj.setEnable(false);
	}
	@Override
	public void onNoPick(GVRPicker sceneObj) {
		// TODO Auto-generated method stub
	}
	@Override
	public void onPick(GVRPicker sceneObj) {
		// TODO Auto-generated method stub

	}

	@Override
	public void onInside(GVRSceneObject arg0, GVRPickedObject arg1) {
		// TODO Auto-generated method stub
		
	}
}
```

What are exactly the differences?! What I need to do is whenever I look at an object (enter?), I give it one texture, and when I'm not, I give it another texture.

**Comment by liaxim** [comment]
@arianaa30 You should be using method 2. The updated eyepicking sample uses it too.

Are you using a binary release? Which one?

I tried these with the latest code:
- setEnable(true/false) from onEnter/onExit works but your object would end up flickering; probably not what you'd want
- changing the texture works too

For example if you create a sceneObject like this and have textures texture1 and texture2:

```
        GVRMaterial material = new GVRMaterial(mGVRContext);
        GVRSceneObject so = new GVRSceneObject(mGVRContext, width, height);
        so.setTexture("diffuseTexture", texture1);
        so.getRenderData().setMaterial(material);
        so.getRenderData().setShaderTemplate(GVRPhongShader.class);
```

Then in onEnter/onLeave you can:

```
        public void onEnter(GVRSceneObject sceneObj, GVRPicker.GVRPickedObject pickInfo)
        {
            sceneObj.getRenderData().getMaterial().setTexture("diffuseTexture", texture2);
        }
        public void onExit(GVRSceneObject sceneObj)
        {
            sceneObj.getRenderData().getMaterial().setTexture("diffuseTexture", texture1);
        }
```

--

You can consider setMainTexture deprecated. At some point we will clean that up.

**Comment by arianaa30** [comment]
Yeah, that makes sense. My objects are in fact videos, but it doesn't work on it.

**Comment by NolaDonato** [comment]
Setting the diffuse texture for a video won't work. You would need to set the main texture. I think video scene objects use a different shader.

**Comment by arianaa30** [comment]
I see. Maybe that's why it didn't work.

**Comment by NolaDonato** [comment]
Did you get this working? Is it still an issue?

**Comment by arianaa30** [comment]
I didnt get this working, but found other says to do it.
You can close it. Tnx!
