### ISSUE TITLE
Adding GVRImageViewSceneObject??

### ISSUE THREAD

**Issue by arianaa30** [Samsung/GearVRf#750]
I was just thinking how to add an image inside my VR app. I looked into, and noticed ImageView is missing from the API. We have `GVRTextViewSceneObject` which is useful, but nothing for images. So maybe as a feature request, any plans on adding a class called `GVRImageViewSceneObject`?

**Comment by NolaDonato** [comment]
What is different about image view scene object from mapping a texture onto a quad?


Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by liaxim** [comment]
@arianaa30 Please look at this GVRSceneObject constructor:
```
    /**
     * Constructs a 2D, rectangular scene object that uses the standard
     * {@linkplain Texture 'texture shader'} to display a {@linkplain GVRTexture
     * texture.}
     * 
     * @param gvrContext
     *            current {@link GVRContext}
     * @param width
     *            the rectangle's width
     * @param height
     *            the rectangle's height
     * @param texture
     *            a {@link GVRTexture}
     */
    public GVRSceneObject(GVRContext gvrContext, float width, float height, GVRTexture texture) {
```

**Comment by arianaa30** [comment]
Great!

**Comment by NolaDonato** [comment]
Gvrsceneviewobject has a constructor that makes a quad



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by arianaa30** [comment]
Thanks. You can close it.
