### ISSUE TITLE
Hybrid app

### ISSUE THREAD

**Issue by knnnrd** [Samsung/GearVRf#763]
Hello,

The app I'm trying to build should start in non-VR mode. Then when the user presses a button, a VR activity must start and the dialog to put the phone in the Gear VR must be shown.
I have been searching around if this is possible but I can't seem to find a clear answer, although I think it sadly isn't possible?

Thanks

**Comment by liaxim** [comment]
Hi. Unfortunately not possible. You will get the prompt when you try to launch your first, launcher, activity instead.

**Comment by knnnrd** [comment]
Alright, thanks for the information.
It's because of the way the oculus sdk is implemented that this isn't possible, right?

**Comment by liaxim** [comment]
Yes, you could put it this way.
