### ISSUE TITLE
API Version compatibility crash sample

### ISSUE THREAD

**Issue by joaobiriba** [Samsung/GearVRf#770]
Running the sample in GearVRf-samples after building Gear VRf with 1.0.3 ovr sdk, my app crash with this  error:
#
The requested API version in ovrInitParms (1.0.3.1) is not compatible with this version of VrApi Loader (1.0.0.1)!

Any solutions?

**Comment by liaxim** [comment]
Hi. Can you please double-check that according to the instructions you copied the VrApi.jar and SystemUtils.jar from the 1.0.3 ovr sdk?

**Comment by joaobiriba** [comment]
Hi, 
double checked. They are the same files. I'm using the last ovr sdk 1.0.3 $OVR_MOBILE_SDK/VrAppFramework/Libs/Android/AppFramework.jar has now different name 

 VrAppFramework.jar

**Comment by liaxim** [comment]
Ok, lets try this. Download the SystemActivities.apk referenced from https://developer.oculus.com/downloads/mobile/1.0.0.0/Oculus_Mobile_SDK/; the url is https://s3.amazonaws.com/o.oculuscdn.com/staging/SystemActivities-P4-119024-FB-16656924.apk. Install it on your phone and let us know the results. Please if possible share with us the complete logcat output. Thanks.

You can ignore VrAppFramework. We no longer use it.

**Comment by liaxim** [comment]
I am pretty sure you are including libvrapi.so from the 1.0.0.1 Oculus SDK in your apk. How do you build (Eclipse, AS, have you customized something in the build)?

Can you please let me know the file size of your libvrapi.so? The one in 1.0.0.1 is 111988 and the one in 1.0.3 is 136584.

**Comment by joaobiriba** [comment]
Thanks,
checking the size I think you are right, I'm using command line to build ( gradle ). I'll double check again
```


(VR) • find . -name libvrapi.so -exec ls -l {} \;
-rw-r--r--  1 joaobiriba  staff  111988  4 Aug 21:55 ./GearVRf/GVRf/Framework/framework/build/intermediates/bundles/debug/jni/armeabi-v7a/libvrapi.so
-rw-r--r--  1 joaobiriba  staff  111988 22 Jul 16:28 ./GearVRf/GVRf/Framework/framework/build/intermediates/jniLibs/debug/armeabi-v7a/libvrapi.so
-rw-r--r--  1 joaobiriba  staff  111988  4 Aug 21:55 ./GearVRf/GVRf/Framework/framework/build/intermediates/transforms/mergeJniLibs/debug/folders/2000/3/main/lib/armeabi-v7a/libvrapi.so
-rwxr-xr-x  1 joaobiriba  staff  111988  4 Aug 21:54 ./GearVRf/GVRf/Framework/framework/src/main/libs/armeabi-v7a/libvrapi.so
-rw-r--r--@ 1 joaobiriba  staff  111988 22 Jul 14:08 ./GearVRf/GVRf/Framework/framework/src/main/obj/local/armeabi-v7a/libvrapi.so
-rw-r--r--  1 joaobiriba  staff  111988  4 Aug 21:32 ./GearVRf-Demos/gvr-cubemap/app/build/intermediates/exploded-aar/framework-debug/jni/armeabi-v7a/libvrapi.so
-rw-r--r--  1 joaobiriba  staff  111988  4 Aug 21:32 ./GearVRf-Demos/gvr-cubemap/app/build/intermediates/transforms/mergeJniLibs/debug/folders/2000/1f/main/lib/armeabi-v7a/libvrapi.so
-rw-r--r--  1 joaobiriba  staff  111988  4 Aug 22:15 ./GearVRf-Demos/gvr-sample/app/build/intermediates/exploded-aar/framework-debug/jni/armeabi-v7a/libvrapi.so
-rw-r--r--  1 joaobiriba  staff  111988  4 Aug 22:15 ./GearVRf-Demos/gvr-sample/app/build/intermediates/transforms/mergeJniLibs/debug/folders/2000/1f/main/lib/armeabi-v7a/libvrapi.so
-rw-r--r--@ 1 joaobiriba  staff  136584 16 Jun 09:46 ./ovr_sdk_mobile_1.0.3/VrApi/Libs/Android/armeabi-v7a/libvrapi.so
```

**Comment by liaxim** [comment]
You shouldn't have to but you may manually copy the correct libvrapi.so. I am confused how this could happen. Double-check whether it gets overwritten though.

**Comment by liaxim** [comment]
@joaobiriba Hi, if your problem is resolved, can we close this issue?

**Comment by joaobiriba** [comment]
Yes, everything is ok right now. I rebuilt all the GVRf from scratch using 1.0.3 Oculus SDK. Thanks

**Comment by Juniiorf** [comment]
@liaxim 
how can I manually copy the libvrapi.so?

I'm having this problem:
09-12 00:47:49.981 1901-1901/com.samsung.android.gvr.sample E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.samsung.android.gvr.sample, PID: 1901
 java.lang.UnsatisfiedLinkError: dlopen failed: library "libvrapi.so" not found
 at java.lang.Runtime.loadLibrary(Runtime.java:372)

**Comment by liaxim** [comment]
Do you build the framework yourself? If you do so, "libvrapi.so" gets copied automatically. You can always copy it from the Oculus Mobile SDK - ./VrApi/Libs/Android/armeabi-v7a/libvrapi.so.
