### ISSUE TITLE
Cannot add a scene object in X3D

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#781]
scene.addSceneObject() does not work after PL https://github.com/Samsung/GearVRf/pull/774

**Comment by rahul27** [comment]
@NolaDonato @mwitchwilliams any idea about what might be going wrong?

**Comment by mwitchwilliams** [comment]
I’m up and running so I’ll be happy to look at it Monday.

Mitch

**Comment by NolaDonato** [comment]
I will look at it. I am going to change jassimp to add a scene object after I read in an X3D file. Will that be a sufficient test?

**Comment by rahul27** [comment]
That should recreate it. I noticed the issue with the X3D demo.

**Comment by NolaDonato** [comment]
I replaced astro_boy.dae with astro.x3d in the gvr-jassimp sample. It correctly displays the astronaut, the bench and the trees. I know that GVRAssetLoader calls GVRScene.addSceneObject to add each model to the scene. So adding a scene object after importing X3D seems to work.

Can you tell me a bit more about exactly when after importing the X3D model that you added the scene object? Are you absolutely sure that this new scene object is not already a child of another parent?

Thanks,

Nola

**Comment by rahul27** [comment]
Here is the modified sample that does not work:

https://github.com/rahul27/GearVRf-Demos/commit/62129540745aee6d83510eee82655aa66236ccee

Make sure you sync to master so that the changes form PL 774 are included when you build the framework.

**Comment by mwitchwilliams** [comment]
X3D (and I believe this is true of all Jassimp model loaders) never adds objects directly to GVRSceneObject 'scene' and thus never uses _scene.addSceneObject()_ .  The model loader passes a GVRModelSceneObject '_root_' in the X3Dobject constructor.  When the X3D parser adds GVRSceneObjects, it calls "root.addChildObject(_myNewObject_); or to currentSceneObject.addChildObject( _myNewObject_ ) when we are not at the root.  I'll look at the demo and suggest a fix soon but I believe that is the source of the issue 
My sense is the renderer parses the Scene Heirarchy at this _root_ object.

**Comment by rahul27** [comment]
Found the bug. It is an NPE on the following line:

https://github.com/gearvrf/GearVRf-Demos/blob/master/gvr-x3d-demo/app/src/main/java/org/gearvrf/x3ddemo/X3DparserScript.java#L119

@NolaDonato seems to have fixed it in PL https://github.com/gearvrf/GearVRf-Demos/pull/288
