### ISSUE TITLE
How can I open android phone default apps in a VR app

### ISSUE THREAD

**Issue by freshindee** [Samsung/GearVRf#783]
I wanted to see videos in android phone videos inside  a VR app screen. (I created a screen as Netflix).
I want to see my phone videos inside that screen, I opened some other android apps in a VR screen, but it come to full screen when I testing with phone debug mode. But when I wearing a Gear VR device that opened apps can not see.

Please advice me how to achieve this and where I went wrong. 

Regards

**Comment by thomasflynn** [comment]
I see you closed this, so perhaps you already answered your own question, but I would still like to better understand what that question was :).  For a Netflix type app, you can look at our gvr-video sample.  (actually, there's an updated, refactored version that may be easier to follow as a pull-request that will probably be merged soon: https://github.com/gearvrf/GearVRf-Demos/pull/287).

But, I did not understand what your second sentence.

**Comment by freshindee** [comment]
Thanks very much.

Actually I got one part fixed and I got your updated sample.

Still Im getting same type issue. please guide me.  How I can show a normal android apps( like mobile version of word application) inside a VR app screen , not in whole screen, it must be like a front screen like in Netflix. (I can open word app from VR app , but I cannot put it in the front screen, it comes to whole screen). Please any idea.

**Comment by freshindee** [comment]
Thanks very much.

Actually I got one part fixed and I got your updated sample.

Still Im getting same type issue. please guide me. How I can show a normal android apps( like mobile version of word application) inside a VR app screen , not in whole screen, it must be like a front screen like in Netflix. (I can open word app from VR app , but I cannot put it in the front screen, it comes to whole screen). Please any idea.

**Comment by thomasflynn** [comment]
If you want to display android ui that you inflate, you can take a look at gvr-events.  

If you're talking about trying to display a different activity / process within your vr app, it's going to be a lot more difficult.  You would need to find a way to get a handle to the surface that the application renders to and use that as a texture in your vr app.  I don't think you'll be able to do that without modifying android itself.

**Comment by freshindee** [comment]
Thank you very much.

Actually what I want  is as you explain here   'You would need to find a way to get a handle to the surface that the application renders to and use that as a texture in your vr app'

Im finding a way to how to modify android .....

If any idea related, please advice.

**Comment by thomasflynn** [comment]
That's all I've got.  I'm not too sure I can really help any further than that.  Good luck.  I'm sure it will be challenging.

**Comment by liaxim** [comment]
@freshindee Do you have other questions or can we close the issue?

**Comment by freshindee** [comment]
I want to run android normal app(not VR app, other apps like mobile version of word, excel) inside a VR app as a response to click event of any control. SO please guide me how I can achieve this, can you provide a container,popup window, something like this.

**Comment by liaxim** [comment]
@freshindee I am afraid we don't have anything more than what @thomasflynn already explained. This is not something that the platform supports out of the box and there is nothing gvrf can do to remedy that.

**Comment by freshindee** [comment]
Ok..Thanks.

**Comment by liaxim** [comment]
@freshindee Would you mind if we close this issue?
