### ISSUE TITLE
VR volume UI

### ISSUE THREAD

**Issue by cikus** [Samsung/GearVRf#785]
I got the test result from Oculus: "Your volume buttons must adjust the volume using the VR volume UI provided by the Oculus Mobile SDK." 
How can I manage to display the default volume UI with the GearVRf SDK?

**Comment by rahul27** [comment]
Overriding the dispatchKeyEvent in your activity might help:

````
    @Override
    public boolean dispatchKeyEvent(KeyEvent event) {
        AudioManager audioManager = (AudioManager) getSystemService(AUDIO_SERVICE);
        int keyCode = event.getKeyCode();
        int keyAction = event.getAction();
        switch (keyCode) {
            case KeyEvent.KEYCODE_VOLUME_UP:
                if(keyAction == KeyEvent.ACTION_UP) {
                    audioManager.adjustStreamVolume(AudioManager.STREAM_MUSIC,
                            AudioManager.ADJUST_RAISE, AudioManager.FLAG_SHOW_UI);
                }
                break;
            case KeyEvent.KEYCODE_VOLUME_DOWN:
                if(keyAction == KeyEvent.ACTION_UP) {
                    audioManager.adjustStreamVolume(AudioManager.STREAM_MUSIC,
                            AudioManager.ADJUST_LOWER, AudioManager.FLAG_SHOW_UI);
                }
                break;
            default:
                return super.dispatchKeyEvent(event);
        }
        return true;
    }
````

**Comment by liaxim** [comment]
We also have change in the framework so this stuff can happen automatically - see https://github.com/Samsung/GearVRf/pull/788.

**Comment by thomasflynn** [comment]
@cikus, also, if you get your app approved and into the store, let us know.

**Comment by cikus** [comment]
@rahul27 Thanks for your comment, but I guess we misunderstood each other. If we handle the event so the Android system volume UI shows up, but that is what should be avoided. Gear VR applications must use the Oculus default VR volume UI (see attached). 
It has to be implemented natively like the global menu for a long back press, or the quit confirmation for the back press. 
![volume_ui](https://cloud.githubusercontent.com/assets/1011601/17510136/ebaa20ae-5e1d-11e6-931c-ed5feae6df49.png)

**Comment by rahul27** [comment]
@cikus yes, that is what I see when using the volume keys with the changes in PL  https://github.com/Samsung/GearVRf/pull/788 

This is a screenshot of the simple sample with the changes included. Let me know if you are looking for something different or in case it does not work with your application.

![screenshot_20160810-014432](https://cloud.githubusercontent.com/assets/609380/17525098/29080e64-5e16-11e6-9201-d497a4d3d156.png)

**Comment by cikus** [comment]
@rahul27 Oh, was my mistake. Working as expected. Thanks.

**Comment by rahul27** [comment]
@cikus awesome. Can we close this?

**Comment by cikus** [comment]
@rahul27 yes.
