### ISSUE TITLE
Build issue google-vr-*

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#786]
Hello,
I can not build the framework since the last update, it seems that something with google-vr went wrong.

Would be really great if you could fix that problem or let me know if it's a local problem.

Thank you...

The log:

`Error:A problem occurred configuring project ':framework'.
> Could not resolve all dependencies for configuration ':framework:_debugCompile'.
   > Could not find :google-vr-base:.
     Searched in the following locations:
         file:/C:/tools/devTools/Android/studio/gradle/m2repository//google-vr-base//google-vr-base-.pom
         file:/C:/tools/devTools/Android/studio/gradle/m2repository//google-vr-base//google-vr-base-.aar
         https://jcenter.bintray.com//google-vr-base//google-vr-base-.pom
         https://jcenter.bintray.com//google-vr-base//google-vr-base-.aar
         file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository//google-vr-base//google-vr-base-.pom
         file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository//google-vr-base//google-vr-base-.aar
     Required by:
         trunk:framework:unspecified
   > Could not find :google-vr-common:.
     Searched in the following locations:
         file:/C:/tools/devTools/Android/studio/gradle/m2repository//google-vr-common//google-vr-common-.pom
         file:/C:/tools/devTools/Android/studio/gradle/m2repository//google-vr-common//google-vr-common-.aar
         https://jcenter.bintray.com//google-vr-common//google-vr-common-.pom
         https://jcenter.bintray.com//google-vr-common//google-vr-common-.aar
         file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository//google-vr-common//google-vr-common-.pom
         file:/C:/Users/user/AppData/Local/Android/Sdk/extras/google/m2repository//google-vr-common//google-vr-common-.aar
     Required by:
         trunk:framework:unspecified`

**Comment by liaxim** [comment]
Hi,
Could you please let us know what files do you have under your GVRf/Framework/framework/src/main/libs folder? Please ensure you have the very latest versions of the gradle files.

**Comment by QKnows** [comment]
Hi,
I have the following files in the libs folder

drwxrwxr-x+ 1 user Kein        0  8. Aug 13:21 armeabi-v7a
-rw-rw-r--+ 1 user Kein   604140  6. Aug 16:23 google-vr-base.aar
-rw-rw-r--+ 1 user Kein   341690  6. Aug 16:23 google-vr-common.aar
-rw-rw-r--+ 1 user Kein   190432 12. Mai 09:45 gson-2.2.4.jar
-rw-rw-r--+ 1 user Kein   175292 12. Mai 09:45 jline-android.jar
-rw-rw-r--+ 1 user Kein   126805 12. Mai 09:45 jnlua-android.jar
-rw-rw-r--+ 1 user Kein   729759 19. Mai 13:44 js.jar
-rw-rw-r--+ 1 user Kein    42131 12. Mai 09:45 jsr223.jar
-rwxrwxr-x+ 1 user Kein 10894256 12. Mai 09:45 libassimp.so
-rwxrwxr-x+ 1 user Kein   133064 12. Mai 09:45 libjnlua.so
-rwxrwxr-x+ 1 user Kein     6351 16. Jun 18:46 SystemUtils.jar
-rwxrwxr-x+ 1 user Kein     4107 16. Jun 18:46 VrApi.jar
-rwxrwxr-x+ 1 user Kein    17918 16. Jun 18:46 VrAppFramework.jar

**Comment by liaxim** [comment]
Ok, looks like you've got the files. The build is fine as far as I know. Are you building just the framework project or a project where you have your app and the framework is included as a module? If it is the latter could you try adding the flatDir section to your project's build.gradle file:
```
allprojects {
    repositories {
        jcenter()
        flatDir {
            dirs 'src/main/libs'
        }
    }
}
```

**Comment by Nathipha** [comment]
Does the latest build (from 3 days ago) still support Eclipse?
I had to download it to get the changes for eyepicking but it now also won't build properly:

```
**** Build of configuration Default for project Framework ****

G:\Dev\AndroidNDK\ndk-build.cmd -j16 OVR_DEBUG=0 NDK_DEBUG=0 
Android NDK: There is no Android.mk under ./jni    
Android NDK: If this is intentional  please define APP_BUILD_SCRIPT to point   
G:/Dev/AndroidNDK/build/core/add-application.mk:214: *** Android NDK: Aborting...    .  Stop.
Android NDK: to a valid NDK build script.    

**** Build Finished ****
```

I didn't change anything since the last version (June 23rd) and I did copy the 3 jar files into the "lib" folder again.

**Comment by liaxim** [comment]
I will look into fixing the Eclipse build temporarily but eventually Eclipse will not be supported.

You can copy the ``./GVRf/Framework/backend_oculus/src/main/jni/Android.mk`` file to ``./GVRf/Framework/framework/src/main/jni/Android.mk`` and try again.

**Comment by Nathipha** [comment]
@liaxim Thanks but unforunately it didn't work:
http://pastebin.com/8QUuLDat

I remember getting similar errors before a few months ago when I first tried to get it to run. I didn't manage to make it work back then but a new version a few days later fixed it.

I already tried importing my project into Android Studio but got really annoyed with all the errors nobody knows anything about that I gave up after an hour. So I'm really thankful for every version that still works with Eclipse!

**Comment by liaxim** [comment]
The Android Studio builds works pretty well. I do recommend you start using it instead. I can help with any issues you may encounter.

Back to the Eclipse build: it is pretty complicated to get it to work since we have a dependency to Google VR now and Google VR uses .aar files. Google doesn't produce libraries Eclipse can use. So we can't build with Eclipse anymore.

If you do insist on using Eclipse I can give you instructions how to manually configure Eclipse but you will also have to comment out the fallback to Google VR. Which means your framework build would break on phones without Oculus.

--

I can't promise anything but we can explore applying selectively some changes to the 3.0.1 release.

**Comment by Nathipha** [comment]
I already opened a new thread on StackExchange, so hopefully someone can help me with importing my project in Android Studio there.

The GVRf version I've been using for almost the last two months has been working fine so far. I only downloaded the new version to get the new samples for eyepicking (eyepicking, pickandmove) to work like it's recommended in the developer guide.
I'll try the old way first and open a new issue if it shouldn't work.

Is it possible to download the last version that is still fully compatible with Eclipse (including the samples)?

**Comment by QKnows** [comment]
Thank you again @liaxim  - you hint with including the `allprojects` code worked. 

Sorry, for the inconvenience - it was a mistake in my gradle configuration.

The issue can me closed if @Nathipha's issue is solved, too...

**Comment by liaxim** [comment]
@Nathipha https://github.com/Samsung/GearVRf/releases/tag/v3.0.1 is the last release with official Eclipse support. You can either download it from that link or execute "git checkout v3.0.1" in your framework repo directory.

I created a 3.0.1 release for the samples. You can either download it or execute "git checkout v3.0.1" in your demos repo directory.

Bear in mind that these releases are from the start of June.

**Comment by Nathipha** [comment]
@liaxim Thank you.

@QKnows Yes, sorry, you can close it.
