### ISSUE TITLE
GVRSceneObject with children

### ISSUE THREAD

**Issue by QKnows** [Samsung/GearVRf#787]
Hello,

I am trying to add two GVRSceneObjects to a parent object. All GVRSceneObjects have one texture and a mesh. The texture of the parent object gets invisible if the second child (child2) is not on in the field of view - but the parent object is still in the field of view. It works fine if I just add child1 in the center of the parent object.

Is it possible to group GVRSceneObjects like this? 

Looking ath the center

![ok](https://cloud.githubusercontent.com/assets/19469900/17493597/5bc743ac-5db1-11e6-8cbb-7a26a012c1c5.png)

Looking above parent, the texture is not visible

![parent_object_invisible](https://cloud.githubusercontent.com/assets/19469900/17493598/5bd54114-5db1-11e6-9182-cd493eb64f69.png)

Expected behavior

![expected_behavior](https://cloud.githubusercontent.com/assets/19469900/17493828/4737aade-5db2-11e6-8a08-88d8bfb676f0.png)

Example code:

       // Create the textures		
       final GVRTexture parentTexture = this.getGVRContext().loadTexture(
			new GVRAndroidResource(this.getGVRContext(), "parentTexture.png"));
        final GVRTexture child1Texture = this.getGVRContext().loadTexture(
			new GVRAndroidResource(this.getGVRContext(), "child1Texture.png"));
        final GVRTexture child2Texture = this.getGVRContext().loadTexture(
			new GVRAndroidResource(this.getGVRContext(), "child2Texture.png"));

        // Create the meshes...
        final GVRMesh parentMesh = this.getGVRContext().createQuad(50.0f, 30.0f);
        final GVRMesh child1Mesh = this.getGVRContext().createQuad(30.0f, 15.0f);
        final GVRMesh child2Mesh = this.getGVRContext().createQuad(120.0f, 25.0f);

        // Create the objects...
        final GVRSceneObject parent = new GVRSceneObject(this.getGVRContext(), parentMesh,   
			parentTexture);
        final GVRSceneObject child1 = new GVRSceneObject(this.getGVRContext(), child1Mesh, 
			child1Texture);
        final GVRSceneObject child2 = new GVRSceneObject(this.getGVRContext(), child2Mesh, 
			child2Texture);

        // Set the render mask
        parent.getRenderData().setRenderMask(GVRRenderMaskBit.Left | GVRRenderMaskBit.Right);
        child1.getRenderData().setRenderMask(GVRRenderMaskBit.Left | GVRRenderMaskBit.Right);
        child2.getRenderData().setRenderMask(GVRRenderMaskBit.Left | GVRRenderMaskBit.Right);

        // Add the children to the parent object...
        parent.addChildObject(child1);
        parent.addChildObject(child2);

        // Translate the objects...
        parent.getTransform().translate(0.0f, 0.0f, -50.0f);
        child1.getTransform().translate(0.0f, 0.0f, 0.1f);
        child2.getTransform().translate(0.0f, -30.0f, 0.1f);

        // Add the parent to the main scene.
        this.mainScene.addSceneObject(parent);``

**Comment by rahul27** [comment]
Looks like a bug with Frustum Culling. The quad does not disappear when you disable culling:
````
scene.setFrustumCulling(false);
````

**Comment by QKnows** [comment]
@rahul27 thanks you - when I am disabling the FrustumCulling it works like expected.

**Comment by rahul27** [comment]
@QKnows keep in mind that setting frustum culling to false is not a fix. There is still a bug with culling. You could disable it to continue testing your application.

**Comment by roshanch** [comment]
I will look into it.

**Comment by roshanch** [comment]
#791 this will fix the issue.

**Comment by QKnows** [comment]
I still have the issue if I don't disable frustum culling like @rahul27 explained.

**Comment by liaxim** [comment]
@QKnows Hi. We are still testing the fix. If you'd like to try it out too do this on top of master:

```
git checkout -b roshanch-culling_issue master
git pull https://github.com/roshanch/GearVRf.git culling_issue
```

**Comment by roshanch** [comment]
@QKnows: the fix is merged. You can get it from master
