### ISSUE TITLE
How to response more events with more controls

### ISSUE THREAD

**Issue by freshindee** [Samsung/GearVRf#792]
I have 5 buttons for display different screens.
But i have only onTouchEvent method to code it..Please give me a example how I can handle this.
and give me a example how I show these 5 different screen in a one place. Means in front middle screen.

**Comment by deepakrawat22** [comment]
A good example to implement buttons is from the sample app immersivepedia video component

https://github.com/gearvrf/GearVRf-Demos/blob/master/gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/videoComponent/ButtonBoard.java

the sub package focus "https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-immersivepedia/app/src/main/java/org/gearvrf/immersivepedia/focus" deals with focus, tap and gestures.

**Comment by deepakrawat22** [comment]
A simplified version of focus, just for using button can be found in the pull request

https://github.com/gearvrf/GearVRf-Demos/pull/287

**Comment by liaxim** [comment]
@freshindee Do you need further assistance? Let us know!

**Comment by freshindee** [comment]
Thank you. I got it success.

**Comment by liaxim** [comment]
Closing then
