### ISSUE TITLE
Entitlement Check

### ISSUE THREAD

**Issue by oliverRandom42** [Samsung/GearVRf#808]
Hi all,

Has anybody had any luck with creating an entitlement check as required by the oculus store submission guidelines?

And how did they go about it?

There is instruction on how to do it with the native ovr sdk but not sure how to approach with gearvrf:
https://developer.oculus.com/documentation/platform/latest/concepts/pgsg-3-pw-platform-walkthrough/#pgsg-pw-g-native-gear-vr-ent

Cheers,

O.

**Comment by thomasflynn** [comment]
FYI, we're double-checking the process on our side.  off-hand it looks like the relevant initialization code would go in the backend_oculus/src/main/jni/activity.cpp in initilaizeVrApi() and the per frame code in onDrawFrame().

**Comment by liaxim** [comment]
@oliverRandom42 Have you used the entitlement check in a native app? It seem it will be easier to make the changes to the framework than to actually test them.

I am getting odd errors like 
```
08-16 09:14:35.217 18677-18677/? W/System.err: android.content.pm.PackageManager$NameNotFoundException: com.oculus.shimwow
08-16 09:14:35.217 18677-18677/? W/System.err:     at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:199)
```
and
```
08-16 09:14:35.247 18677-18677/? W/System.err: java.lang.RuntimeException: Requested PlatformSDK version (api=1.1.7.0, driver=0) is incompatible with the currently installed version.
08-16 09:14:35.247 18677-18677/? W/System.err:     at com.oculus.platform.loader.EntryPoint.load(EntryPoint.java:54)
08-16 09:14:35.247 18677-18677/? W/System.err:     at com.oculus.platform.loader.EntryPoint.load32(EntryPoint.java:76)
```

**Comment by liaxim** [comment]
Never mind. Apparently we should use Platform SDK 1.6.0 instead of 1.7.0. Have no idea how to determine that other than trial and error.

**Comment by liaxim** [comment]
@oliverRandom42 Hi. We have something but it requires building the framework yourself. See #818.

1. Download and install Platform SDK 1.6.0. This and only this version works for me.
2. In gradle.properties define OVR_PLATFORM_SDK so it points to the location where the Platform SDK was installed.
3. Get the latest framework code.
4. Apply the changes on top of it by doing

   ```
   git checkout -b liaxim-oculus_entitlement_check master
   git pull https://github.com/liaxim/GearVRf.git oculus_entitlement_check
   ```
5. Build the framework.
6. Have your onCreate look something like this:
```
 protected void onCreate(Bundle icicle) {
      setOculusAppId("123456789012345");
      getEventReceiver().addListener(new IPlatformSDKEvents() {
          public void onPlatformInitializeError(int errorCode) {
          }

          public void onUserIsNotEntitled() {
          }
      };

      super.onCreate(icicle);
      setScript(new SampleMain(this), "gvr.xml");
 }
```


Looking forward to hearing your feedback.

**Comment by oliverRandom42** [comment]
HI guys,

apologies for not getting back to you sooner - have been off sick from work the past few days...

Will go over all of your suggestions and provide feedback

Cheers,

O.

**Comment by thomasflynn** [comment]
@oliverRandom42 have you gotten a chance to look over things?  Also, we generated https://github.com/Samsung/GearVRf/pull/818

**Comment by oliverRandom42** [comment]
Hi all,

I have also responded in the other thread - have been on holiday for the past 2 and a half weeks - will be getting up to speed with all of this today and will provide any feedback.

Regards,

Oliver

**Comment by liaxim** [comment]
https://github.com/Samsung/GearVRf/pull/818 verified as working. Merged.

**Comment by rahul27** [comment]
Here is a link to the wiki:

https://github.com/Samsung/GearVRf/wiki/Entitlement-Check-using-GVRF
