### ISSUE TITLE
Lesson 2 ppt in Tutourial is broken

### ISSUE THREAD

**Issue by s910503486f** [Samsung/GearVRf#811]
Hi,I'm trying to open "GearVRFTutorial-Lesson2"  in GearVRf/Installer/Tutorials/
but the file is broken.
I use another computer to clone the project and open the file,
and the problem is not solved.

**Comment by thomasflynn** [comment]
@NolaDonato , this is the issue i was mentioning.  check it out?

**Comment by liaxim** [comment]
The file is encrypted

**Comment by NolaDonato** [comment]
Pull request #817 fixes this
