### ISSUE TITLE
gvr-widgetviewer will not build

### ISSUE THREAD

**Issue by NolaDonato** [Samsung/GearVRf#830]
I built the Framework and the WidgetPlugin but I still get this when I try to build the gvr-widgetviewer sample.

Information:Gradle tasks [:app:assembleDebug]
Observed package id 'build-tools;20.0.0' in inconsistent location '/home/nola.donato/android-sdks/build-tools/android-4.4W' (Expected '/home/nola.donato/android-sdks/build-tools/20.0.0')
:app:copyOculusSignature UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareFrameworkDebugLibrary UP-TO-DATE
:app:prepareGoogleVrBaseLibrary UP-TO-DATE
:app:prepareGoogleVrCommonLibrary UP-TO-DATE
:app:prepareWidgetpluginDebugLibrary UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:prePackageMarkerForDebug
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/vr/cardboard/R$color;
Information:BUILD FAILED

**Comment by liaxim** [comment]
https://github.com/Samsung/GearVRf/pull/831 should fix this but considering gradle's complexity I can't be ever too confident.

Even without the fix a ./gradlew clean assembleDebug in the modelviewer directory might get you through (it does for me with the old version; it shouldn't but it does).

**Comment by NolaDonato** [comment]
It builds now
