### ISSUE TITLE
PNG transparancy

### ISSUE THREAD

**Issue by knnnrd** [Samsung/GearVRf#833]
Hello,

I am trying to to use a PNG image as a texture for a simple GVRSceneObject. The png image has transparency in it.

Every part of the image that should be transparant is showing a black color. Is this normal behaviour?
This is the code I am using:

`GVRTexture texBack = gvrContext.loadTexture(new GVRAndroidResource(gvrContext, R.drawable.btn));
        btnBack = new GVRSceneObject(gvrContext, 0.7f, 0.7f, texBack);`

**Comment by liaxim** [comment]
You need to set the rendering order:
```
btnBack.getRenderData().setRenderingOrder(GVRRenderingOrder.TRANSPARENT)
```
