### ISSUE TITLE
Error:Failed to resolve: :framework-debug:

### ISSUE THREAD

**Issue by pecabum** [Samsung/GearVRf#838]
i've pushed both repos in one folder, but still when i open studio with some of the demos and try to sync it gives me "Error:Failed to resolve: :framework-debug:".

Also when i try to make project :

```
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find :framework-debug:.
     Searched in the following locations:
         file:/Applications/Android Studio.app/Contents/gradle/m2repository//framework-debug//framework-debug-.pom
         file:/Applications/Android Studio.app/Contents/gradle/m2repository//framework-debug//framework-debug-.aar
         https://jcenter.bintray.com//framework-debug//framework-debug-.pom
         https://jcenter.bintray.com//framework-debug//framework-debug-.aar
         file:/Users/user/Documents/Projects/GearVRf-Demos/gearvrf-libs/framework-debug-.aar
         file:/Users/user/Documents/Projects/GearVRf-Demos/gearvrf-libs/framework-debug.aar
         file:/Users/user/Documents/Projects/GearVRf/GVRf/Framework/framework/build/outputs/aar/framework-debug-.aar
file:/Users/user/Documents/Projects/GearVRf/GVRf/Framework/framework/build/outputs/aar/framework-debug.aar
file:/Users/user/Library/Android/sdk/extras/android/m2repository//framework-debug//framework-debug-.pom
file:/Users/user/Library/Android/sdk/extras/android/m2repository//framework-debug//framework-debug-.aar
file:/Users/user/Library/Android/sdk/extras/google/m2repository//framework-debug//framework-debug-.pom
file:/Users/user/Library/Android/sdk/extras/google/m2repository//framework-debug//framework-debug-.aar
Required by:
         gvr-360video:app:unspecified
```

**Comment by liaxim** [comment]
Did the framework build successfully for you? Can you find any .aar files under GearVRf/GVRf/Framework/framework/build/outputs/aar/?

**Comment by pecabum** [comment]
when i try to build framework as a project it gives me :

`Information:Gradle tasks [:framework:generateDebugSources, :framework:generateDebugAndroidTestSources, :framework:prepareDebugUnitTestDependencies, :framework:mockableAndroidJar, :framework:compileDebugSources, :framework:compileDebugAndroidTestSources, :framework:compileDebugUnitTestSources]
Warning:not copying Oculus files; OVR_MOBILE_SDK not found
Warning:relying on hard-coded paths and environment variables; OVR_MOBILE_SDK not found
:framework:preBuild UP-TO-DATE
:framework:preDebugBuild UP-TO-DATE
:framework:checkDebugManifest
:framework:preDebugAndroidTestBuild UP-TO-DATE
:framework:preDebugUnitTestBuild UP-TO-DATE
:framework:preReleaseBuild UP-TO-DATE
:framework:preReleaseUnitTestBuild UP-TO-DATE
:framework:prepareGoogleVrBaseLibrary UP-TO-DATE
:framework:prepareGoogleVrCommonLibrary UP-TO-DATE
:framework:prepareDebugDependencies
:framework:compileDebugAidl UP-TO-DATE
:framework:compileDebugRenderscript UP-TO-DATE
:framework:generateDebugBuildConfig UP-TO-DATE
:framework:mergeDebugShaders UP-TO-DATE
:framework:compileDebugShaders UP-TO-DATE
:framework:generateDebugAssets UP-TO-DATE
:framework:mergeDebugAssets UP-TO-DATE
:framework:generateDebugResValues UP-TO-DATE
:framework:generateDebugResources UP-TO-DATE
:framework:mergeDebugResources UP-TO-DATE
:framework:processDebugManifest UP-TO-DATE
:framework:processDebugResources UP-TO-DATE
:framework:generateDebugSources UP-TO-DATE
:framework:prepareDebugAndroidTestDependencies
:framework:compileDebugAndroidTestAidl UP-TO-DATE
:framework:compileDebugNdk UP-TO-DATE
:framework:compileLint
:framework:copyDebugLint UP-TO-DATE
:framework:mergeDebugProguardFiles UP-TO-DATE
:framework:packageDebugRenderscript UP-TO-DATE
:framework:packageDebugResources UP-TO-DATE
:framework:buildNative FAILED
Error:Execution failed for task ':framework:buildNative'.
> A problem occurred starting process 'command 'ndk-build''`

**Comment by liaxim** [comment]
In project's gradle.properties please set ANDROID_NDK_HOME to your NDK's path. We have few other things documented in https://github.com/Samsung/GearVRf/wiki/Build%20Tips.

**Comment by pecabum** [comment]
yes , i have them 
`android.useDeprecatedNdk=true
org.gradle.jvmargs=-Xmx2048M
#GVRF_BACKEND=backend_oculus
# Un-comment and add the path to ndk directory
#ANDROID_NDK_HOME=/Users/user/Downloads/android-ndk
# Un-comment and add the path to ovr directory
#OVR_MOBILE_SDK=/Users/user/Downloads/ovr_sdk_mobile_1.0.3
# Variable defines the path to the GearVRf-Demos/gearvrf-libs directory relative to the git root
# of this project. The .aar files generated by building this project will be copied to
# GearVRf-Demos/gearvrf-libs. The .aar files will not be copied if the directory does not exist
LIBS_DIRECTORY=/Users/user/Documents/Projects/GearVRf-Demos/gearvrf-libs`

Still the same error

**Comment by pecabum** [comment]
thanks!
