### ISSUE TITLE
Google-vr-common and Google-vr-base failed to resolve

### ISSUE THREAD

**Issue by revinfopawan** [Samsung/GearVRf#849]
I am trying to import **gvr-camera2renderscript** Project in android studio, i import framework and backend-oculus as a module and when i am building the project i am getting following error:-

`Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find :google-vr-base:.
     Searched in the following locations:
         https://jcenter.bintray.com//google-vr-base//google-vr-base-.pom
         https://jcenter.bintray.com//google-vr-base//google-vr-base-.aar
     Required by:
         gvr-camera2renderscript:app:unspecified > gvr-camera2renderscript:backend_oculus:unspecified
   > Could not find :google-vr-common:.
     Searched in the following locations:
         https://jcenter.bintray.com//google-vr-common//google-vr-common-.pom
         https://jcenter.bintray.com//google-vr-common//google-vr-common-.aar
     Required by:
         gvr-camera2renderscript:app:unspecified > gvr-camera2renderscript:backend_oculus:unspecified`

everytime **google-vr-common** and **google-vr-base** failed to resolve. How i can resolve this issue ??
Thanks in advance!

**Comment by liaxim** [comment]
These aars are included in the repository under GearVRf-Demos/gearvrf-libs/. If you open GearVRf-Demos/gvr-camera2renderscript in Android Studio they will be found.

It seems like you have a different project structure. You can always manually add the dependency to the aars.

--
If you just want to build the sample, make sure you have GearVRf and GearVRf-Demos in the same directory. Then build the framework - the framework build will update GearVRf-Demos/gearvrf-libs/ with the latest aars. Then the sample build will pick them up from there including daydream's aars.

**Comment by revinfopawan** [comment]
I am not able to build that project also, i successfully import and build the framework but when trying to import the demo then error occur. Is there any video or proper documentation for importing project step by step.

**Comment by liaxim** [comment]
Hi, could you describe what do you do? We do have this - http://gearvrf.org/bin/view/GearVRfDeveloperGuide/GearVRfDevGuide200Start#BuildInstruct but it is somewhat outdated.

Let's focus first on the framework build. Does it build successfully for you? Do you see the framework-debug.aar and backend-debug.aar files under GearVRf-Demos/gearvrf-libs/? What other files do you find in that folder?

**Comment by revinfopawan** [comment]
yes, now i am able to build and run the demo in android studio,
Thanks!

**Comment by revinfopawan** [comment]
i want to open camera in gearvr app is there any demo for that?????

**Comment by revinfopawan** [comment]
thanks! @rahul27 but this camera is not clear means camera quality/clarity is not good.

**Comment by liaxim** [comment]
You could also try the gvr-vuforia sample. Is the quality good enough in that sample?

**Comment by revinfopawan** [comment]
yes, that is working much better 
Thanks!
