### ISSUE TITLE
GVRViewManager.getMainCameraRig() throws NullPointerException

### ISSUE THREAD

**Issue by Lordpeara** [Samsung/GearVRf#864]
Hi all,

I made project with your sample code (https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-360video/app) and run it on my Galaxy S6. And it works well.

But after I tried to dock my S6 onto Gear VR, app crashes with NullpointerException.

I thought when phone is plugged onto headset, GVRConfigurationManager.configureForHeadset() will be invoked.

here is the stack trace.

```
FATAL EXCEPTION: main
Process: x.y.z, PID: 8088
java.lang.NullPointerException: Attempt to invoke virtual method 'org.gearvrf.GVRCameraRig org.gearvrf.GVRScene.getMainCameraRig()' on a null object reference
    at org.gearvrf.GVRConfigurationManager.configureForHeadset(GVRConfigurationManager.java:113)
    at org.gearvrf.GVRConfigurationManager$2$1.run(GVRConfigurationManager.java:80)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7229)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

How can I fix it?

FYI, I built gvrf over this project/master (b2503e20dd719fdab9a046cdad721bb228aa5866)
with Oculus mobile sdk v1.0.3 and android NDK 12.1.2977051 (through android studio)

Thanks in advance.

**Comment by liaxim** [comment]
Hi, is it consistently reproduced? The phone was at the screen where it was asking you to dock into the headset, you docked and then it crashed? Thanks.

**Comment by liaxim** [comment]
Here is a patch: https://github.com/liaxim/GearVRf/commits/wait_for_viewmgr
You can pull it to your tree with ``git pull https://github.com/liaxim/GearVRf.git wait_for_viewmgr``

**Comment by Lordpeara** [comment]
Phone does not ask to dock into headset. It screen shows the app like this.

![image](https://cloud.githubusercontent.com/assets/6825249/18733920/22a415fc-80aa-11e6-8e80-ef88c3d8b8df.png)

And before running application I set developer mode in Gear VR Service application.
However, neither setting dev mode nor not I saw the same result.

I will pull & rebuild your patch now. Thank for fast reviewing!

**Comment by liaxim** [comment]
You need to add ``<meta-data android:name="com.samsung.android.vr.application.mode" android:value="vr_only"/>`` to the ``application`` section in your AndroidManifest.xml. Then you would get the prompt and the app would run ok in developer mode without being docked.

I am really curious to find out did the patch help you with the crash you mentioned. Thank you.

**Comment by Lordpeara** [comment]
Both patch and previous master work fine. Thanks!
