### ISSUE TITLE
Using LOD disables optimizations

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#874]
To get lod-test back to a working state optimizations in SceneObject::frustumCull are turned off if any scene object uses lod. This eventually needs to be addressed properly.

**Comment by NolaDonato** [comment]
We should get rid of the hard-coded LOD on SceneObject and replace it with an LOD component. I will look at making such a component – I think it is possible now that we have GVRBehavior.

**Comment by liaxim** [comment]
Addressed by https://github.com/Samsung/GearVRf/pull/901
