### ISSUE TITLE
OpenGL Calls

### ISSUE THREAD

**Issue by vladdonets** [Samsung/GearVRf#883]
Hello! 

I have a question related to the internal calls of OpenGL in GearVRF. Is there any way I can directly use OpenGL ES API in the GearVRF (except overwriting predefined functions) ?

**Comment by thomasflynn** [comment]
It is possible.  You'll need to set up a drawFrameListener.  You'll need to also save and restore any opengl state that you set, including framebuffer binding.  Keep in mind that you may be modifying any opengl state we may be using as well.

**Comment by vladdonets** [comment]
Thank you for your prompt response!
