### ISSUE TITLE
Some objects are not drawn

### ISSUE THREAD

**Issue by lassehe** [Samsung/GearVRf#886]
My application stopped drawing some objects (or their textures) after commit d02474726d39cef500310006ebe36540389ef210 "Fix the matrix transformation of the bounding volume" was merged. Depending on the direction looked at all or none of the objects are missing. Later commits 979bf2df9f13fae870146d461c5a01d2c06d90ed and 8513f039e9f2a814fde3ba09bdb0d4cb8f933cf5 related to this do not fix the issue.

Any ideas what is causing this? I am not sure if there is a problem in this change, or had I been doing something wrong before.

**Comment by rahul27** [comment]
The fix corrects the bounds of the bounding volume for a given object. Could you share an example of what you are seeing?

**Comment by lassehe** [comment]
Here are screenshots made using GVRf version 3de46c46aa0cb43e71dae5b2aae9ee50f2d5ae80  where Mihail's patches related to this were also merged. A complete sphere surface, assembled from smaller tiles, should be present here, but now some GVRSceneObjects are not drawn, based on the exact direction which is being looked at. For example, when looking directly towards top or bottom this looks just fine.

I came to conclusion my issue has something to do with that bounding volume fix by using git bisect. Of course it is possible that the problem is in my code, but earlier this worked fine.

![screenshot1](https://cloud.githubusercontent.com/assets/15195342/19300317/511a498e-9062-11e6-8d4a-f22f9384a78b.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/15195342/19300319/51201eea-9062-11e6-871e-d1da758c548c.jpg)

**Comment by rahul27** [comment]
@lassehe Are you using the GVRPicker to determine picked objects? 

Could you let me know the exact GVRf calls that fail? Also could you share a sample code (if possible) so that I can recreate and track down the issue faster?

Finally, when you say it could be a problem with your code are you doing something different than the Picker?

**Comment by rahul27** [comment]
Hi @lassehe, just following up on my question above.

**Comment by lassehe** [comment]
Thanks for your help! Perhaps I'm missing something here, but why would GVRPicker affect rendering? All these GVRSceneObjects should be visible. In screenshots the camera is in the center of the sphere. The app used GVRPicker for certain purposes, but removing it didn't fix this drawing issue.

However, I probably did ran into that GVRPicker bug earlier. Now I tested editing head model params in the configuration XML, but didn't notice any difference with this rendering.

I'm not so familiar with GVRf internals that I could point faulty calls. I guess it must have something to do with deciding which objects to draw and which not. :) Unfortunately I'm unable to provide sample code for this now. The only "unusual" thing I'm doing here is that meshes of these occasionally missing objects are generated during initialization.

**Comment by liaxim** [comment]
@lassehe Does GVRScene.setFrustumCulling(false) have any effect? 
```
getGVRContext().getMainScene().setFrustumCulling(false);
getGVRContext().getNextMainScene().setFrustumCulling(false);
```

**Comment by thomasflynn** [comment]
from the screenshots, it looks like maybe you create some GVRSphereSceneObjects?  what arguments did you give to the constructor?

**Comment by lassehe** [comment]
@liaxim Yes! Objects become and stay visible after setting frustum culling false. The scene looks like it was before this change.
@thomasflynn Thanks for the idea, but these are just regular GVRSceneObjects I have generated.

**Comment by rahul27** [comment]
@lassehe I assumed that you were picking objects to be drawn based on the GVRPicker, which does not seem to be the case. So we can ignore that for now. You are right, the Picker should not affect the rendering.

It seems to be an issue with the culling. I tried to quickly whip up a similar sample at my end but it seems to render okay.

![screenshot_20161015-020340](https://cloud.githubusercontent.com/assets/609380/19396119/41fe6d14-91f6-11e6-9a03-076c4169bed0.png)

Are you creating a hierarchical scene graph or all you objects added to the scene root? Also are you loading a separate texture for each tile? 

You mentioned `The only "unusual" thing I'm doing here is that meshes of these occasionally missing objects are generated during initialization.` 

Are your textures being loaded on demand?

**Comment by liaxim** [comment]
@rahul27 If you have trouble reproducing and have no other leads, you could check out gvr-immersivepedia. It exhibits what looks like a culling issue - start the video and rotate left/right so it is about to get out of the view. It disappears much earlier that it should. There is other geometry in the museum scene that gets culled too early too.

**Comment by rahul27** [comment]
@liaxim yeah, I see the issue with immersivepedia. It goes away when I revert my change. Will look into it.

**Comment by lassehe** [comment]
My scene graph is hierarchical with asynchronously loaded textures. But this happens during initialization, so not really on demand. Hopefully immersivepedia helps debugging there. Looks like same issue.

**Comment by rahul27** [comment]
@lassehe could you let me know if the following pull request fixes your issue?

https://github.com/Samsung/GearVRf/pull/898

**Comment by lassehe** [comment]
@rahul27 yes, it looks fine now. Thanks!
