### ISSUE TITLE
Decrease the number of samples

### ISSUE THREAD

**Issue by dknaan** [Samsung/GearVRf#9]
Hi,

There are currently 12 samples. Some of them don't demonstrate any special feature and some have duplicated code. 
I consider dcreasing the number of samples and adding new samples that demonstrate specific features or abilities of the GVRF library.
In general, I would prefer to have simple samples that are demonstrate well a specific feature and easy to understand. 

Having too many samples, make it more difficult to maintain the code, so at the first stage I consider to remove some samples:
* Cockpit
* Panorama
* Gvr-sample
* Simplegallery or Opacityanigallery (because they are almost identical).

If anyone has any objection or ideas (for samples to add or samples to remove), please share here.

Thanks

**Comment by thomasflynn** [comment]
Agreed.  It would be a good idea to focus our samples a bit better:  Remove redundant ones and make new ones to highlight how to use features that aren’t already covered in the existing samples.  Removing Cockpit, Panorama, Gvr-sample sound like good candidates.  Simplegallery and Opacityanigallery seem like they could be perhaps merged into one with some option to select which animation to use.

Any other thoughts on this?
-tom

**Comment by chenchao1407** [comment]
I would rather keep gvrsample since it is a very basic and clear example for people to get into GVRF.

**Comment by dknaan** [comment]
Don’t you think that the simple-sample enough to demonstrate the basics?

**Comment by ragner** [comment]
Maybe we could create a new repository like GearVRf-Demos and put there the more complex demos
and decrease the size of GearVRf repository that currently is more than ~1.5G!?

**Comment by liaxim** [comment]
This sounds like a very good idea for so many reasons. I second that.

**Comment by liaxim** [comment]
Repo https://github.com/gearvrf/GearVRf-Demos created and the samples have been copied there. Will wait a few days before removing the samples from the main repo.

There is more to it as the history will be maintained so there will not be immediate benefit. Using some scary commands the history can be rewritten and the samples really purged; have to practice the procedure first.

**Comment by ragner** [comment]
+1: Nice

**Comment by liaxim** [comment]
Status: if we truly remove the samples from the history log it means the git reflog will be rewritten (commit ids will change). The forks will have to be manually updated as there will be no common history. Existing pull requests will have to be re-created. There is potential of other side-effects which I can't predict based on running tests just on my test fork.

The repo does become much smaller and fetches are waay faster..

**Comment by liaxim** [comment]
I think we are going in the exact opposite direction. @dknaan Should we close this?

**Comment by dknaan** [comment]
My idea was to have a simple and specific sample for each technique (for example, a sample to show how to display video, a sample to show how to use animation, etc). This could help a new developer to learn how to use GVRF and help us as a test units.
I opened this issue when we had 12 samples. Now we have much more and even less control of our samples.

I still think that we need a limited set of simple examples, but agree with you that we go to the other directions...
If  you want you can close it, and maybe we will re-open it when we decide to invest in documentation for developers.

**Comment by liaxim** [comment]
In a way that is all the new samples do. It is just that this issue doesn't seem likely to be addressed, ever. To close it or not - your call then.

**Comment by dknaan** [comment]
You can close it.
