### ISSUE TITLE
Error:Failed to resolve: :backend_daydream-debug: Error:Failed to resolve: :framework-debug: Error:Failed to resolve: :backend_oculus-debug:

### ISSUE THREAD

**Issue by JacobLawtonClaro** [Samsung/GearVRf#922]
Open a demo project and it can not resolve the dependencies, here is the output.

> Error:A problem occurred configuring project ':app'.
> > Could not resolve all dependencies for configuration ':app:_debugCompile'.
>    > Could not find :framework-debug:.
>      Searched in the following locations:
>          file:/C:/Program Files/Android/Android Studio/gradle/m2repository//framework-debug//framework-debug-.pom
>          file:/C:/Program Files/Android/Android Studio/gradle/m2repository//framework-debug//framework-debug-.aar
>          https://jcenter.bintray.com//framework-debug//framework-debug-.pom
>          https://jcenter.bintray.com//framework-debug//framework-debug-.aar
>          file:/C:/dev/GearVRf-Demos/gearvrf-libs/framework-debug-.aar
>          file:/C:/dev/GearVRf-Demos/gearvrf-libs/framework-debug.aar
>          file:/C:/dev/GearVRf/GVRf/Framework/framework/build/outputs/aar/framework-debug-.aar
>          file:/C:/dev/GearVRf/GVRf/Framework/framework/build/outputs/aar/framework-debug.aar
>          file:/C:/Android/sdk/extras/android/m2repository//framework-debug//framework-debug-.pom
>          file:/C:/Android/sdk/extras/android/m2repository//framework-debug//framework-debug-.aar
>          file:/C:/Android/sdk/extras/google/m2repository//framework-debug//framework-debug-.pom
>          file:/C:/Android/sdk/extras/google/m2repository//framework-debug//framework-debug-.aar
>          file:/C:/Android/sdk/extras/m2repository//framework-debug//framework-debug-.pom
>          file:/C:/Android/sdk/extras/m2repository//framework-debug//framework-debug-.aar
>      Required by:
>          gvr-tutorial-lesson2:app:unspecified
>    > Could not find :backend_oculus-debug:.
>      Searched in the following locations:
>          file:/C:/Program Files/Android/Android Studio/gradle/m2repository//backend_oculus-debug//backend_oculus-debug-.pom
>          file:/C:/Program Files/Android/Android Studio/gradle/m2repository//backend_oculus-debug//backend_oculus-debug-.aar
>          https://jcenter.bintray.com//backend_oculus-debug//backend_oculus-debug-.pom
>          https://jcenter.bintray.com//backend_oculus-debug//backend_oculus-debug-.aar
>          file:/C:/dev/GearVRf-Demos/gearvrf-libs/backend_oculus-debug-.aar
>          file:/C:/dev/GearVRf-Demos/gearvrf-libs/backend_oculus-debug.aar
>          file:/C:/dev/GearVRf/GVRf/Framework/framework/build/outputs/aar/backend_oculus-debug-.aar
>          file:/C:/dev/GearVRf/GVRf/Framework/framework/build/outputs/aar/backend_oculus-debug.aar
>          file:/C:/Android/sdk/extras/android/m2repository//backend_oculus-debug//backend_oculus-debug-.pom
>          file:/C:/Android/sdk/extras/android/m2repository//backend_oculus-debug//backend_oculus-debug-.aar
>          file:/C:/Android/sdk/extras/google/m2repository//backend_oculus-debug//backend_oculus-debug-.pom
>          file:/C:/Android/sdk/extras/google/m2repository//backend_oculus-debug//backend_oculus-debug-.aar
>          file:/C:/Android/sdk/extras/m2repository//backend_oculus-debug//backend_oculus-debug-.pom
>          file:/C:/Android/sdk/extras/m2repository//backend_oculus-debug//backend_oculus-debug-.aar
>      Required by:
>          gvr-tutorial-lesson2:app:unspecified
>    > Could not find :backend_daydream-debug:.
>      Searched in the following locations:
>          file:/C:/Program Files/Android/Android Studio/gradle/m2repository//backend_daydream-debug//backend_daydream-debug-.pom
>          file:/C:/Program Files/Android/Android Studio/gradle/m2repository//backend_daydream-debug//backend_daydream-debug-.aar
>          https://jcenter.bintray.com//backend_daydream-debug//backend_daydream-debug-.pom
>          https://jcenter.bintray.com//backend_daydream-debug//backend_daydream-debug-.aar
>          file:/C:/dev/GearVRf-Demos/gearvrf-libs/backend_daydream-debug-.aar
>          file:/C:/dev/GearVRf-Demos/gearvrf-libs/backend_daydream-debug.aar
>          file:/C:/dev/GearVRf/GVRf/Framework/framework/build/outputs/aar/backend_daydream-debug-.aar
>          file:/C:/dev/GearVRf/GVRf/Framework/framework/build/outputs/aar/backend_daydream-debug.aar
>          file:/C:/Android/sdk/extras/android/m2repository//backend_daydream-debug//backend_daydream-debug-.pom
>          file:/C:/Android/sdk/extras/android/m2repository//backend_daydream-debug//backend_daydream-debug-.aar
>          file:/C:/Android/sdk/extras/google/m2repository//backend_daydream-debug//backend_daydream-debug-.pom
>          file:/C:/Android/sdk/extras/google/m2repository//backend_daydream-debug//backend_daydream-debug-.aar
>          file:/C:/Android/sdk/extras/m2repository//backend_daydream-debug//backend_daydream-debug-.pom
>          file:/C:/Android/sdk/extras/m2repository//backend_daydream-debug//backend_daydream-debug-.aar
>      Required by:
>          gvr-tutorial-lesson2:app:unspecified

it is next to the gearvrf file, do I need to add some dependencies to the project and which ones?

**Comment by liaxim** [comment]
Hi,

Two options:

**Build the framework yourself first**
- clone this and the framework repo in the same directory
- follow the instructions how to build the framework at https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/060_Gear_VRf_Developer_Guide/110_Build_Instructions
- you should have all the framework artifacts under GearVRf-Demos/gearvrf-libs (like framework-debug.aar)
- now you can open a demo app, build and run it

**Use prebuilt framework**
- since the demos use the latest framework you can use our nightly build from https://github.com/Samsung/GearVRf/releases/tag/nightly_build
- download backend_oculus-debug-11-07-2016.aar to GearVRf-Demos/gearvrf-libs and rename it to backend_oculus.aar
- download framework-debug-11-07-2016.aar to GearVRf-Demos/gearvrf-libs and rename it to framework-debug.aar
- you need to manually add the oculus libraries to the demos per the "Android Studio instructions" section from https://github.com/Samsung/GearVRf/releases/tag/v3.0.1


Few demos utilize framework extensions and if you are interested in one of these I can provide further assistance.

**Comment by liaxim** [comment]
@JacobLawtonClaro Still having problems?

**Comment by JacobLawtonClaro** [comment]
Sorry, it ended up in spam and I only saw the response yesterday.But yes that has got the demos working thank you.On 09 November 2016 at 17:33 Mihail <notifications@github.com> wrote:@JacobLawtonClaro Still having problems?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by JacobLawtonClaro** [comment]
Sorry about this, just another question, the "eye picking" app uses a custom open gl es fragment and vertex shader to color the models. I have some open gl shaders i would like to use with gearVRf, but they are more complex than just outputting a single colour and a single uniform input. Do you have examples of more complex open gl shaders being used with gearVRf? The API for GVRMaterial is missing some key information e.g. it does not have the .setTextCoord method and there does not seem to be away to pass in a varying? An example would be appreciated to help me work my though. On 09 November 2016 at 17:33 Mihail <notifications@github.com> wrote:@JacobLawtonClaro Still having problems?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by liaxim** [comment]
@JacobLawtonClaro You should take a look at the shaders in the gvr-video sample. They should be more helpful; there is an attribute being passed there to the vertex shader which in turn sets a varying for the fragment shader.

setTexcoord has been added recently to GVRMaterial. Prior to that, depending on your specific GVRF version, you can use setVec4("a_tex_coord", ..) or setVec2("a_texcoord", ..) to set the texture coordinates.

**Comment by thomasflynn** [comment]
also, gvr-modelviewer has a bunch of custom shaders you may want to look at.  they do a bunch of reflection and lighting and stuff.

**Comment by JacobLawtonClaro** [comment]
I found some good ones in the dinosaur viewer gvr-immersivepida, got my shaders linked in now.

**Comment by mayank1111** [comment]
When i run gvrtextviewsample app from GVRF-Demos i got the following error-

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "vrapi_ShowSystemUI" referenced by "/data/app/org.gearvrf.gvrtextviewsample-1/lib/arm/libgvrf-oculus.so".

Anybody knows how to resolve it?

**Comment by liaxim** [comment]
@mayank1111 Did "git clean -fdx" and rebuilding fixed your problem?

**Comment by liaxim** [comment]
Assuming it is all good by now.
