### ISSUE TITLE
GearVR volume change dialog is not rendered.

### ISSUE THREAD

**Issue by kpilyugin** [Samsung/GearVRf#923]
When changing volume on GearVR, special Volume Notifier should be rendered (due to https://developer3.oculus.com/documentation/mobilesdk/latest/concepts/release/, this is done since version 1.0.3 automatically by Oculus SDK). 

But when running app made with framework (e.g. gvr-sample from https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-sample), it is not rendered at all.

**Comment by kpilyugin** [comment]
Actually this can be fixed by overriding dispatchKeyEvent in activity and calling AudioManager.adjustStreamVolume, Oculus samples do exactly this.

**Comment by liaxim** [comment]
Actually this is exactly what we do. See GVRActivity.dispatchKeyEvent. I checked it out on Note5 and it works as expected. What kind of phone are you using?

**Comment by kpilyugin** [comment]
@liaxim thanks for reply! I am using Galaxy S6. This is not reproduced anymore, probably was caused by outdated version of Oculus SDK (however I was pretty sure I used the latest).
