### ISSUE TITLE
Render to texture

### ISSUE THREAD

**Issue by rsisaleh** [Samsung/GearVRf#926]
Hi guys, 

I want to create something like dynamic waves and need to generate the height map in a shader and store it in a render texture to be used later. I would rather not hack apart the framework to make this happen, if possible.
I have a terrifying feeling that the solution is really obvious and I'm just missing it.

Cheers

**Comment by liaxim** [comment]
Hi. Is GVRRenderTexture what you are looking for? The gvr-vuforia sample app uses it.

**Comment by thomasflynn** [comment]
I believe @roshanch was going to give a more specific answer.  We helped someone with this in a hackathon a couple months back.  If you just want to execute a bunch of opengl calls on your own rendertarget, then the flow would go something like this:

create a drawframelistener
in your drawframelistener
  if this is your first frame, create your GVRRenderTexture (let's call that 'renderTexture')
  query and save the currently bound FBO (let's call that 'oldFBO')
  renderTexture->bind();
  make opengl calls
  glBindFramebuffer(oldFBO);
  
when doing 'make opengl calls', when changing any opengl state, you will probably want to query the current opengl state first, then restore it before exiting your drawframelistener

if you're looking to render a scene with a bunch of sceneobjects (as opposed to making your own gl calls) to a renderTexture, then we would need to expose a variant of renderCamera() up to the java level.

**Comment by rsisaleh** [comment]
Thanks for that, I ended up using unity as time was a bit of a factor for the prototype.

**Comment by liaxim** [comment]
@rsisaleh We made the whole thing more user-friendly. Also added a new demo app - gvr-rendertotexture, that shows how to do it.
