### ISSUE TITLE
sRGB support

### ISSUE THREAD

**Issue by thomasflynn** [Samsung/GearVRf#93]
Add support for sRGB render targets and textures.

**Comment by thomasflynn** [comment]
this is related to the initial configuration issue.

**Comment by chenchao1407** [comment]
Ok. Working on it now.

**Comment by thomasflynn** [comment]
the check-in for initial configuration was merged.  You can now enable an sRGB framebuffer.  Is there anything else needed for this?

**Comment by thomasflynn** [comment]
if there is anything else needed for this, please open a new issue.  thanks.
