### ISSUE TITLE
Consider upgrading to JOML 1.9.1 for Android

### ISSUE THREAD

**Issue by httpdigest** [Samsung/GearVRf#930]
Hi,

the latest development version 1.9.1-SNAPSHOT of JOML is now built and deployed as an Android Library (.aar file) with sources and Javadoc jars, currently available through oss.sonatype.org with the coordinates `org.joml:joml-android:1.9.1-SNAPSHOT`.
See the [android](https://github.com/JOML-CI/JOML/tree/android) branch.
Also see the [Gradle Setup for Android](https://github.com/JOML-CI/JOML/wiki#gradle-setup-for-android) Wiki section.

Between the version 1.6.6 of JOML, which GearVRf is using, and the latest 1.9.1-SNAPSHOT, there are significant performance and feature improvements that also apply to Android, including special-case methods to multiply and invert matrices.
Additionally, there are new affine-only matrix types, Matrix4x3f and Matrix4x3d, which reduce computation and storage cost even further.

**API breaks**
It has always been a high priority to do as few API breaks as possible with new JOML versions. So, between 1.6.6 and 1.9.1 there are just a few:

Since version 1.8.1, direct field accesses to the m* fields of 4x4 and 4x3 matrices are disallowed, in order to optimize many matrix methods (certain properties of a matrix are assumed in order to use faster mul/invert/... code paths). If write access to individual matrix elements is needed, it must be done through the setter methods m*() now.

As far as I saw, there is [just one case](https://github.com/Samsung/GearVRf/blob/master/GVRf/Framework/framework/src/main/java/org/gearvrf/animation/keyframe/GVRAnimationChannel.java#L321-L332) in the framework, where direct field access is performed. This should be refactored to:
```Java
mat.scale(scale).setTranslation(pos);
```

Renamings that affect GearVRf:
- class FrustumCuller has been renamed to FrustumIntersection -> (used in GVRFrustumPicker.java and GVRObjectPicker.java)
- Matrix4f.mulPoint() has been renamed to Matrix4f.mulPosition() -> (used in [GVRGazeCursorController.java](https://github.com/Samsung/GearVRf/blob/master/GVRf/Framework/framework/src/main/java/org/gearvrf/io/GVRGazeCursorController.java#L198))
- Vector3f.set(int, ...) has been renamed to Vector3f.setComponent(int, ...) -> (used in [X3Dobject.java](https://github.com/Samsung/GearVRf/blob/master/GVRf/Framework/framework/src/main/java/org/gearvrf/x3d/X3Dobject.java#L3827-L3828))

Kind regards,
Kai

**Comment by liaxim** [comment]
Thanks for letting us know. We will definitely upgrade.

**Comment by httpdigest** [comment]
fyi: extensive performance optimizations in JOML for Android Marshmallow and Nougat devices are currently being done. No API changes and no semantic changes in any operations. Just performance optimizations.
The first release 1.9.1 of JOML for Android will be ready soon. Minimum API level 4, but optimized for API levels 23 and 24.

**Comment by thomasflynn** [comment]
Hi Kai, we finished our 3.1 release and are now allowing check-ins into master.  I've done a pull-request for the joml upgrade.  Please check:  https://github.com/Samsung/GearVRf/pull/964

**Comment by httpdigest** [comment]
Hi Thomas, thanks for noting. Please tell, if you need any further information/help on this or have any questions.

**Comment by liaxim** [comment]
Addressed by https://github.com/Samsung/GearVRf/pull/964 and https://github.com/Samsung/GearVRf/pull/966
