### ISSUE TITLE
The shadows in gvr-shadows "jump"

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#940]
I haven't seen this before but today I am. The shadows kind of "jump" every once in a while. Maybe I am just doing something wrong. I picked up the binaries from the 3.1 prerelease and build with those. Tested on Note5. @NolaDonato Could you please double-check?

[video.zip](https://github.com/Samsung/GearVRf/files/595381/video.zip)

**Comment by liaxim** [comment]
Confirmed as a bug. @NolaDonato and @deepakrawat22 are looking into it.

**Comment by NolaDonato** [comment]
What I am seeing is that the entire scene appears to flicker to black periodically as the light moves around.

**Comment by thomasflynn** [comment]
this can be closed now, right?

**Comment by liaxim** [comment]
Yes. Fixed.
