### ISSUE TITLE
GVRSpotLight.InnerCone > GVRSpotLight.OuterCone not clampled at OuterCone dimension

### ISSUE THREAD

**Issue by mwitchwilliams** [Samsung/GearVRf#941]
In X3D, a SpotLight's BeamWidth (which sets GVRSpotLight.InnerCone) is larger than X3D SpotLight's CutOffAngle (which sets GVRSpotLight.OuterCone).  According to the X3D spec., the CutOffAngle should be clamped at the BeamWidth's values.  There is no fall-off of light around the cone - it acts like a laser.
In GearVR, it appears that the BeamWidth  'shines' and the area represented the cutOffAngle is blanked out.

In the image, the beamWidth is 0.50265485 radians, and the cutOffAngle is 0.32941985
The middle Sphere is at (0, -.5, -6); the Cylinder is at (-2.5, -.5, -6); and the Cone is at (2.5, -.5, -6).  The SpotLight is at (0, 0, -1).

![image](https://cloud.githubusercontent.com/assets/18128830/20358057/3a51f466-abdf-11e6-9d09-3221fea4b15d.png)

_[ will be posting demo file to the GVR-Tests repo soon]._

**Comment by NolaDonato** [comment]
In GearVRf the inner cone angle must be <= to the outer cone angle. It uses the OpenGL spotlight model where the spotlight is at full intensity up to the inner angle and falls off to zero between the inner and outer angle.

Perhaps you need to use the X3D beam width for the outer angle and theX3D  cutoff for the inner angle?

**Comment by mwitchwilliams** [comment]
OK, thanks for the explanation.   I'm wondering if OpenGL figures if the innerCone is larger than the outerCone, then make the center area dark.  Could be part of the design, or just something not implemented.
X3D spec does say the innerCone should be capped by the outerCone.  I may try to implement this or just let it go figuring the designer made a conscience choice here.  And if we mimic OpenGL's implementation, then that's not so bad either.
While I ponder this, I suggest removing this as a bug and closing the issue.
