### ISSUE TITLE
gvr-multilight and ovr_multiview enabled; light moves much slower

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#942]
The light moves from right to left 3x slower compared to the default case. Tested on Note5 and used the prerelease binaries from https://github.com/Samsung/GearVRf/releases/tag/3.1.

@roshanch please check it out.

**Comment by roshanch** [comment]
with multiview FPS drops from 60 to 38. I am looking at it.

**Comment by liaxim** [comment]
Fixed
