### ISSUE TITLE
GRVMaterial emissive_color doesn't appear to have an effect

### ISSUE THREAD

**Issue by mwitchwilliams** [Samsung/GearVRf#943]
Emissive Color doesn't appear to have an effect

Setting **gvrMaterail.setVec4("emissive_color", red, green, blue, 1.0f)** but not seeing any effect.  I set diffuse and specular colors to dark gray and black respectively so I should see the emissive effect.
I believe the value was set correctly because immediately after that code, I tested with the statement: 
**float[] emissive = gvrMaterial().getVec4("emissive_color");**
and that returns the value I set emissive color..

I'm using similar code to set diffuse and specular colors and that works fine.
**gvrMaterial().setVec4("diffuse_color", red, green, blue, 1.0f);
gvrMaterial().setVec4("specular_color", red, green, blue, , 1.0f);**

**Comment by liaxim** [comment]
@mwitchwilliams Is this issue related to the https://github.com/Samsung/GearVRf/pull/1192 pull request?

**Comment by mwitchwilliams** [comment]
My tests indicate this is fixed.
