### ISSUE TITLE
Failed to build physics extension

### ISSUE THREAD

**Issue by ragner** [Samsung/GearVRf#947]
Does anybody could help me to fix this issue after ovr_sdk_mobile_1.0.4 update ?

arm-linux-androideabi-g++: error: jni/../../../build/intermediates/exploded-aar/framework-debug/jni/armeabi-v7a/libgvrf.so: No such file or directory

make: Leaving directory `/Users/ragner/Workspace/SIDIA/GearVRf/GearVRf/GVRf/Extensions/gvrf-physics/src/main'

make: *** [obj/local/armeabi-v7a/libgvrf-physics.so] Error 1

:gvrf-physics:buildNative FAILED

FAILURE: Build failed with an exception.

**Comment by rahul27** [comment]
Could you confirm that the following line is commented in all your gradle.properties files:

`org.gradle.parallel=true`

**Comment by ragner** [comment]
yes, it is

**Comment by liaxim** [comment]
@ragner Where do you find libgvrf.so if you search for it? It is all set up to work if the framework and backends are built from GearVRf/GVRf/Framework and the extensions from GearVRf/GVRf/Extensions. If you have custom project structure where you include selected modules then it is likely you may experience problems.

I couldn't figure a good reliable way of referencing libgvrf.so from Android.mk of modules that need it. So it is something that easily can get broken.

**Comment by ragner** [comment]
@liaxim 

$ find . -name libgvrf.so

./Extensions/3DCursor/3DCursorLibrary/build/intermediates/exploded-aar/framework-debug/jni/armeabi-v7a/libgvrf.so
./Extensions/3DCursor/IODevices/gearwear/GearWearIoDevice/build/intermediates/exploded-aar/framework-debug/jni/armeabi-v7a/libgvrf.so
./Extensions/DebugWebServer/debugwebserver/build/intermediates/exploded-aar/framework-debug/jni/armeabi-v7a/libgvrf.so
./Extensions/SceneSerializer/sceneserializer/build/intermediates/exploded-aar/framework-debug/jni/armeabi-v7a/libgvrf.so
./Extensions/WidgetPlugin/widgetplugin/build/intermediates/exploded-aar/framework-debug/jni/armeabi-v7a/libgvrf.so
./Framework/backend_daydream/build/intermediates/exploded-aar/Framework/framework/unspecified/jni/armeabi-v7a/libgvrf.so
./Framework/backend_oculus/build/intermediates/exploded-aar/Framework/framework/unspecified/jni/armeabi-v7a/libgvrf.so
./Framework/framework/build/intermediates/bundles/debug/jni/armeabi-v7a/libgvrf.so
./Framework/framework/build/intermediates/bundles/release/jni/armeabi-v7a/libgvrf.so
./Framework/framework/build/intermediates/jniLibs/debug/armeabi-v7a/libgvrf.so
./Framework/framework/build/intermediates/jniLibs/release/armeabi-v7a/libgvrf.so
./Framework/framework/build/intermediates/transforms/mergeJniLibs/debug/folders/2000/3/main/lib/armeabi-v7a/libgvrf.so
./Framework/framework/build/intermediates/transforms/mergeJniLibs/release/folders/2000/3/main/lib/armeabi-v7a/libgvrf.so
./Framework/framework/src/main/libs/armeabi-v7a/libgvrf.so
./Framework/framework/src/main/obj/local/armeabi-v7a/libgvrf.so

**Comment by liaxim** [comment]
libgvrf.so is conspicuously missing under gvrf-physics. The dependency is there in the gradle file. The aar should have been "exploded".

Could you please try to complete clean your tree (git clean -fdx) and then build the Framework and the Extensions project?

**Comment by ragner** [comment]
@liaxim  Yes, I already try it ... 
I have made the git clean -fdx and imported the project again
I have got the same message error.

This is my git diff

$ git diff
diff --git a/GVRf/Extensions/gradle.properties b/GVRf/Extensions/gradle.properties
index 25b9254..c19b9a5 100644
--- a/GVRf/Extensions/gradle.properties
+++ b/GVRf/Extensions/gradle.properties
@@ -1,9 +1,11 @@
 android.useDeprecatedNdk=true
 org.gradle.daemon=true
 org.gradle.jvmargs=-Xmx2048M
-LIBS_DIRECTORY=\.\.\/GearVRf-Demos\/gearvrf-libs
+LIBS_DIRECTORY=../GearVRf-Demos/gearvrf-libs
+
+ANDROID_NDK_HOME=/Users/ragner/Workspace/Devtools/android/ndk
 
 #to build the platformsdk-support extension uncomment this property and
 #supply the correct path to the platform sdk. Then run
 #./gradlew -Pplatformsdk_support=true platformsdk_support:assembleDebug
-#OVR_PLATFORM_SDK=<path-to-the-oculus-platform-sdk>
+OVR_MOBILE_SDK=/Users/ragner/Workspace/SIDIA/GearVRf/ovr_sdk_mobile
diff --git a/GVRf/Framework/gradle.properties b/GVRf/Framework/gradle.properties
index 828199a..787d138 100644
--- a/GVRf/Framework/gradle.properties
+++ b/GVRf/Framework/gradle.properties
@@ -14,13 +14,13 @@
 # org.gradle.parallel=true
 #Thu May 05 12:55:40 PDT 2016
 android.useDeprecatedNdk=true
-org.gradle.jvmargs=-Xmx2048M
+org.gradle.jvmargs=-Xmx204M
 #GVRF_BACKEND=backend_oculus
 # Un-comment and add the path to ndk directory
-#ANDROID_NDK_HOME=
+ANDROID_NDK_HOME=/Users/ragner/Workspace/Devtools/android/ndk
 # Un-comment and add the path to ovr directory
-#OVR_MOBILE_SDK=
+OVR_MOBILE_SDK=/Users/ragner/Workspace/SIDIA/GearVRf/ovr_sdk_mobile
 # Variable defines the path to the GearVRf-Demos/gearvrf-libs directory relative to the git root
 # of this project. The .aar files generated by building this project will be copied to
 # GearVRf-Demos/gearvrf-libs. The .aar files will not be copied if the directory does not exist
-LIBS_DIRECTORY=\.\.\/GearVRf-Demos\/gearvrf-libs
\ No newline at end of file
+LIBS_DIRECTORY=../GearVRf-Demos/gearvrf-libs
\ No newline at end of file

**Comment by rahul27** [comment]
Does it only fail while building the physics extension?

Are you able to build only the framework and run the other samples?

**Comment by liaxim** [comment]
@ragner What is your build procedure? What we expect to work is
- go to GVRf/Framework - run "./gradlew assembleDebug"
- go to GVRf/Extensions - run "./gradlew assembleDebug"

If you still have problems please go to GVRf/Extensions and run "./gradlew -d -i gvrf-physics:assembleDebug" and send me the output of this command. Thanks.

**Comment by ragner** [comment]
Ok,
@liaxim I am trying it.
My internet is very slow today and it is taking a long time to download gradle-2.14.1-all.zip

Framework$./gradlew assembleDebug 
Downloading https://services.gradle.org/distributions/gradle-2.14.1-all.zip .....

**Comment by ragner** [comment]
@rahul27 Only the build of physics extension is failing.
Framework is building ok

**Comment by ragner** [comment]
@liaxim the command line worked for me! 
I need check the configurations of my AndroidStudio.

Thank you @all.
