### ISSUE TITLE
Total Vertices (indices) for a Mesh limited to 64K - limits X3D files

### ISSUE THREAD

**Issue by mwitchwilliams** [Samsung/GearVRf#962]
We only accept total number of vertices to 64K.
GVRMesh _indices_ is an array of type char[] which is 2 bytes.

Some X3D files, particularly those sent to 3D printers, will have > 64K vertices.  These include meshes generated by scanners and catscans.

Enabling meshes with > 64K vertices opens up new markets for GearVR, sharing the same X3D files sent to 3d printers.

Note that GVRMesh also has texture coordinates and normals which are arrays of float[], a 4 byte value.

**Comment by NolaDonato** [comment]
If you find a mesh in the X3D file that has more than 64K vertices, why don’t we create multiple scene objects with multiple meshes for now.

**Comment by thomasflynn** [comment]
we could also add a method that takes 'int[]' for indices.  ES3.0 supports that, so we should be able to as well.

**Comment by showats** [comment]
ردیاب

**Comment by mwitchwilliams** [comment]
Fixed in v4.0, new GVRMesh allowing > 64K vertices.
