### ISSUE TITLE
Texture goes missing if a new material is created and assigned to RenderData

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#967]
Quite easy to reproduce; last known instance is the new physics sample app. There is this section there

```
        GVRMaterial material = new GVRMaterial(context);

        GVRSceneObject groundObject = new GVRCubeSceneObject(context, true, texture);

        groundObject.getRenderData().setMaterial(material);
        groundObject.getRenderData().getMaterial().setTexture("diffuseTexture", texture);
        groundObject.getRenderData().getMaterial().setMainTexture(texture);
        groundObject.getTransform().setScale(15.0f, 0.5f, 15.0f);
        groundObject.getTransform().setPosition(x, y, z);
```

If the setMainTexture call is removed the texture is not going to be applied. If the existing material associated with the scene object is used the texture is applied correctly. We have to look at this sooner rather than later.

**Comment by NolaDonato** [comment]
We are already working on this but it will take a bit more time. I am rewriting all the old built-in shaders in terms of the custom shader. When this is complete, the new texture shader will let you omit the texture and it will use only the color like the phong shader does. You also will never have to call bindShaders again - the system will do it automatically.

**Comment by NolaDonato** [comment]
This is not a bug. It is a "feature" of the texture shader (which is the default shader if you don't specify anything). If you remove the setMainTexture call, you have to create the cube with the Phong shader (which uses "diffuseTexture" instead of "mainTexture"). Right now the way to do this is via GVRRenderData.setShaderTemplate. Replace the setMainTexture call with this:

groundObject.getRenderData().setShaderTemplate(GVRPhongShader.class);
groundObject.getRenderData().bindShaders(scene);

This will force that render data to use the Phong shader. As a update: the bindShaders removal has been coded in the Vulkan branch and is working.

**Comment by liaxim** [comment]
This is more complete excerpt from the simplephysics sample (MainHelper.java):

```
        Future<GVRTexture> texture = context.loadFutureTexture(new GVRAndroidResource(context, R.drawable.orange));
        GVRMaterial material = new GVRMaterial(context);

        GVRSceneObject groundObject = new GVRCubeSceneObject(context, true, texture);

        groundObject.getRenderData().setMaterial(material);
        groundObject.getRenderData().getMaterial().setTexture("diffuseTexture", texture);
        groundObject.getRenderData().getMaterial().setMainTexture(texture);
        groundObject.getTransform().setScale(15.0f, 0.5f, 15.0f);
        groundObject.getTransform().setPosition(x, y, z);

        //set phong Shader
        groundObject.getRenderData().setShaderTemplate(GVRPhongShader.class);
```

It is using the phong shader so that is why the use of the main texture is surprising.

Also it works without having to resort to the main texture if no new material is created but the existing is used instead.

**Comment by liaxim** [comment]
I also sprinkled a bunch of bindShaders calls but it had no effect.

**Comment by NolaDonato** [comment]
This works for me on the S7 Edge, what phone are you using?

    public void onInit(GVRContext context) {
        GVRScene scene = context.getMainScene();
        Future<GVRTexture> texture = context.loadFutureTexture(new GVRAndroidResource(context, R.drawable.checker));
        GVRMaterial material = new GVRMaterial(context);
        GVRSceneObject groundObject = new GVRCubeSceneObject(context, **false**, texture);
        GVRRenderData rdata = groundObject.getRenderData();

        rdata.setMaterial(material);
        material.setTexture("diffuseTexture", texture);
        groundObject.getTransform().setScale(10.0f, 10.0f, 10.0f);
        rdata.setShaderTemplate(GVRPhongShader.class);
        rdata.bindShader(scene);
        scene.addSceneObject(groundObject);
    }

Also notice that to see anything you have to make the normals point in (the "false" argument to GVRCubeSceneObject) or the entire thing is culled.

**Comment by NolaDonato** [comment]
I guess if you position the cube not at the center you don't have to use "false", you can use "true" in that case. I didn't know what x,y,z were in your example.

**Comment by liaxim** [comment]
I am seeing it on Note5 and S7. It was originally encountered by @ragner - this is how I know about it. He has the normals facing out since he uses the cube to create the platform for his physics game. The platform we are looking at from some distance.

Comment out gvr-simplephysics:MainHelper.java:94 to reproduce.

**Comment by liaxim** [comment]
It is caused by the use of Future textures. As a side note I think it is time to consider removing these Futures.

**Comment by liaxim** [comment]
Addressed by https://github.com/Samsung/GearVRf/pull/1081
