### ISSUE TITLE
Loading fails if showLoadingIcon set to false

### ISSUE THREAD

**Issue by TimecodePete** [Samsung/GearVRf#968]
Using gvr360video sample as an example.

Could be I'm doing something wrong, but in the assets/gvr.xml file on the vr-app-settings node, if I set showLoadingIcon attribute to false, screen remains black. As soon as I set it back to true, video loads and is displayed correctly. No other changes made to the code, just this one flag.
Any ideas :) ?

**Comment by liaxim** [comment]
It is a long standing issue with our apis. If you use the splash screen you obtain the main scene via GVRContext.getNextMainScene but if you are not using a splash screen you need to use GVRContext.getMainScene. So change getNextMainScene to getMainScene.

**Comment by TimecodePete** [comment]
That solved the issue! Thanks for your time!
