### ISSUE TITLE
Simplify picking

### ISSUE THREAD

**Issue by thomasflynn** [Samsung/GearVRf#98]
picking currently requires setting up a bounding Mesh for a object, creating an EyePointee, add the EyePointee to an EyePointeeHolder and then adding the EyePointeeHolder to the SceneObject.  While flexible, it is a lot for a developer to go through to have the ability to pick.  We saw this sort of trouble during the recent hackathon.  We can provide a simple enablePicking() api that will construct a default bounding box for the mesh, and add the appropriate EyePointee and EyePointeeHolders.

**Comment by DanielNogueiraAndroid** [comment]
Excellent improvement !!!
