### ISSUE TITLE
Correctly handling back button for release

### ISSUE THREAD

**Issue by JacobLawtonClaro** [Samsung/GearVRf#986]
To publish your app you need to be able to press the back button for 0.75 to activate the Universal Menu and less than 0.75 "must back out one level in your UI. If already at the top level of your UI, prompt the user to return to Oculus Home." 

I have been using immersivepedia demo as the base for my code which handles opening the Universal menu correctly but when I want to swap back to the menu by just pressing the back button it always triggers the "Oculus Home" prompt instead of backing out to the last scene. 

Is there a demo which handles the back button correctly, e.g. pick up when it has been short pressed and then call the correct logic either stating the "Oculus Home" or showing the main sence?

**Comment by liaxim** [comment]
Hi. This is not something that could be handled entirely on the app side. I drafted a framework change that adds a onBackPress method to GVRScript/GVRMain for this very purpose. The change will need some additional testing but should let you proceed as-is. Will create a patch for whichever version of the framework you use.

Framework change: https://github.com/Samsung/GearVRf/pull/987
Change to gvr-immersivepdia: https://github.com/gearvrf/GearVRf-Demos/pull/388

**Comment by JacobLawtonClaro** [comment]
This is really cool, thanks for the patch.

**Comment by liaxim** [comment]
https://github.com/Samsung/GearVRf/pull/987 has been merged.
